/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_ideal_auto_electrique_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812694/tapavis_tenant_ideal_auto_electrique_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812694/tapavis_tenant_ideal_auto_electrique_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812708/tapavis_tenant_ideal_auto_electrique_inc/hero_0ed45a80-2afc-4f94-93fe-2b167c16731b.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812709/tapavis_tenant_ideal_auto_electrique_inc/freins_d2d3846b-4b5d-40b9-bc61-d0559b71bb00.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812710/tapavis_tenant_ideal_auto_electrique_inc/systeme-electrique_16e0e4ed-402f-417c-8331-5e07533220df.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812716/tapavis_tenant_ideal_auto_electrique_inc/mecanique-generale_6d5a2d2c-0427-49d9-b3ad-fb089b31240c.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812724/tapavis_tenant_ideal_auto_electrique_inc/vidange-huile_060eadea-4403-4fa8-8929-30bfa37ae62d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812725/tapavis_tenant_ideal_auto_electrique_inc/equilibrage-rotation-pneus_9ca5f421-2320-4a0a-a183-22b75251fa72.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812728/tapavis_tenant_ideal_auto_electrique_inc/suspension_bd105dd2-750e-4495-8356-47e2492f892f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812728/tapavis_tenant_ideal_auto_electrique_inc/silencieux_55578982-b550-4f68-b50d-1f267978d846.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812738/tapavis_tenant_ideal_auto_electrique_inc/systeme-de-refroidissement_0227d8c1-52c4-473b-831b-d1dad188260c.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812738/tapavis_tenant_ideal_auto_electrique_inc/climatisation_0e9cb523-03ea-4442-bdfa-a3a24b164c63.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812740/tapavis_tenant_ideal_auto_electrique_inc/mise-au-point_d7840aab-7f48-43f5-bd5f-8ddc3e1d0af5.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812743/tapavis_tenant_ideal_auto_electrique_inc/transmission_f904345e-156f-4bd9-a390-a5b4bb74fb16.png"
  }
};
