module.exports = async function(db,services) {
const defaults={hero_title:'Les plus gros spéciaux sur l’électroménager.',hero_subtitle:'Liquidations à Saint-Jérôme. Venez voir les appareils disponibles en magasin.',tagline:'Électroménagers · Saint-Jérôme',about_text:'Les articles présentés sont à découvrir en magasin. Un appel avant votre visite permet de confirmer les renseignements de l’appareil qui vous intéresse.',text_hero_title_en:'Big deals on major appliances.',text_hero_subtitle_en:'Clearance in Saint-Jérôme. Come see the appliances available in store.',text_tagline_en:'Major appliances · Saint-Jérôme',text_about_text_en:'The featured appliances are available to explore in store. Calling before your visit lets you confirm the details of the appliance that interests you.',contact_verified:'false',hero_real:'false',store_real:'false'};
for(const [key,value] of Object.entries(defaults))await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[key,value]);
if(services&&services.config){const c=services.config;for(const [key,value] of Object.entries({business_name:c.businessName||c.displayName,contact_email:c.contactEmail,contact_phone:c.contactPhone,business_address:c.businessAddress}))if(value)await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[key,String(value)]);}
await db.run("INSERT INTO admin_settings (key,value) VALUES ('_p_hero_image_url',$1) ON CONFLICT (key) DO NOTHING",['https://res.cloudinary.com/duhp69meg/image/upload/v1789491016/tapavis_tenant_econo-plus/build_econo-plus_6c6df0e4-ceff-4379-99eb-dc34f8de38af.png']);
const seeded=await db.get("SELECT value FROM admin_settings WHERE key='_seed_catalogue_v1'");
if(seeded)return;
const products=[
['Réfrigérateur à congélateur supérieur','Top-freezer refrigerator','refrigerator','Gabarit de fiche pour un réfrigérateur. Ajoutez la marque, le modèle, les mesures et les photos de l’appareil réellement présenté avant publication.','Listing template for a refrigerator. Add the brand, model, measurements and actual appliance photographs before publishing.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491014/tapavis_tenant_econo-plus/build_econo-plus_dcbb6174-ced9-47e5-8609-752feac6d0f0.png'],
['Cuisinière électrique à surface lisse','Smooth-top electric range','range','Gabarit de fiche pour une cuisinière. Confirmez le type de cuisson, les dimensions et les défauts observés sur l’appareil réel.','Listing template for a range. Confirm the cooking type, dimensions and observed defects of the actual appliance.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491018/tapavis_tenant_econo-plus/build_econo-plus_f6206cb9-37ca-446b-a00a-733ceadc5485.png'],
['Laveuse à chargement frontal','Front-load washer','washer','Gabarit de fiche pour une laveuse. Indiquez les caractéristiques vérifiées, les dimensions et les accessoires inclus seulement après inspection.','Listing template for a washer. Enter verified features, dimensions and included accessories only after inspection.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491019/tapavis_tenant_econo-plus/build_econo-plus_19fa5845-4c34-40a1-af09-97c9683095cd.png'],
['Sécheuse électrique','Electric dryer','dryer','Gabarit de fiche pour une sécheuse. Remplacez cette description par les renseignements de l’appareil en magasin.','Listing template for a dryer. Replace this description with details of the appliance in store.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491017/tapavis_tenant_econo-plus/build_econo-plus_ef2204ce-bbf3-4530-850d-b348fdfa2ac8.png'],
['Lave-vaisselle encastrable','Built-in dishwasher','dishwasher','Gabarit de fiche pour un lave-vaisselle. Vérifiez la largeur, l’état des paniers et les défauts connus avant publication.','Listing template for a dishwasher. Verify the width, rack condition and known defects before publishing.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491013/tapavis_tenant_econo-plus/build_econo-plus_bb174485-2b08-46aa-a498-9b8bccdcbb7d.png'],
['Congélateur vertical','Upright freezer','freezer','Gabarit de fiche pour un congélateur. Ajoutez uniquement les mesures et les caractéristiques confirmées de l’appareil réel.','Listing template for a freezer. Add only confirmed measurements and features of the actual appliance.','https://res.cloudinary.com/duhp69meg/image/upload/v1789491016/tapavis_tenant_econo-plus/build_econo-plus_65208795-4e5b-45e8-8f43-ebde7956dc58.png']
];
for(const p of products)await db.run('INSERT INTO products (title,title_en,category,description,description_en,image_url,published,photos_verified,facts_verified) SELECT $1,$2,$3,$4,$5,$6,0,FALSE,FALSE WHERE NOT EXISTS (SELECT 1 FROM products WHERE title=$1)',p);
const posts=[
['Avant de venir au magasin','Before visiting the store','Repérez la référence de l’appareil qui vous intéresse et appelez pour confirmer sa disponibilité avant votre déplacement.','Find the reference of the appliance that interests you and call to confirm availability before making the trip.','Préparer sa visite'],
['Les mesures à avoir sous la main','Measurements to bring','Notez la largeur, la hauteur et la profondeur de l’espace prévu. Apportez ces mesures pour discuter du format de l’appareil en magasin.','Write down the width, height and depth of the intended space. Bring these measurements to discuss appliance size in store.','Préparer sa visite'],
['Regarder l’état de l’appareil','Inspecting the appliance','Les renseignements d’une fiche peuvent inclure l’état et les défauts connus. Posez vos questions au magasin pour obtenir les précisions nécessaires.','A listing may include condition details and known defects. Ask the store for any clarification you need.','Renseignements'],
['Une fiche utile pour votre appel','A useful listing for your call','Gardez le nom du modèle et sa référence à portée de main. Ils permettent d’identifier l’appareil dont vous souhaitez discuter.','Keep the model name and reference handy. They help identify the appliance you would like to discuss.','Renseignements']
];
for(const p of posts)await db.run('INSERT INTO posts (title,title_en,content,content_en,category,published) SELECT $1,$2,$3,$4,$5,0 WHERE NOT EXISTS (SELECT 1 FROM posts WHERE title=$1)',p);
await db.run("INSERT INTO admin_settings (key,value) VALUES ('_seed_catalogue_v1','true') ON CONFLICT (key) DO NOTHING");
};