ALTER TABLE services ADD COLUMN IF NOT EXISTS price_type TEXT DEFAULT 'flat';
ALTER TABLE services ADD COLUMN IF NOT EXISTS duration_min INTEGER;
ALTER TABLE services ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS bay_number TEXT;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS equipment TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS vehicle TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_name TEXT;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';
