/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_pierre_begin).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962772/tapavis_tenant_garage_pierre_begin/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962772/tapavis_tenant_garage_pierre_begin/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790962790/tapavis_tenant_garage_pierre_begin/hero_0402c537-77ed-4c92-a03f-3ab6497d55bf.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790962788/tapavis_tenant_garage_pierre_begin/vidange-huile_23c25bd5-a235-484b-90e9-bb31f8024bd1.webp",
    "freins": "https://media.liasse.tech/upload/v1790962790/tapavis_tenant_garage_pierre_begin/freins_52faa99d-3f88-400b-ac65-737385bb30dd.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962791/tapavis_tenant_garage_pierre_begin/mecanique-generale_b4e03ed2-86d9-4939-80d1-f23c0dc4bc80.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962799/tapavis_tenant_garage_pierre_begin/equilibrage-rotation-pneus_7bf24105-638c-41b4-aea5-5939af5c2c25.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962800/tapavis_tenant_garage_pierre_begin/suspension_943d28c8-fabb-4699-bf36-6da042521a8c.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962800/tapavis_tenant_garage_pierre_begin/silencieux_ce2ea7ce-a017-453c-9fb8-a74425eba466.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962802/tapavis_tenant_garage_pierre_begin/systeme-de-refroidissement_579a2821-c11f-40c7-9ea4-dc0380d9ee7b.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790962810/tapavis_tenant_garage_pierre_begin/climatisation_a01d16e7-fce1-4511-a477-180b61b580fd.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790962810/tapavis_tenant_garage_pierre_begin/mise-au-point_10eb1bbf-eeb9-4717-9f07-955b6002cf64.webp",
    "transmission": "https://media.liasse.tech/upload/v1790962811/tapavis_tenant_garage_pierre_begin/transmission_d704dbe7-02ec-472e-bea0-c9be6c8404c5.webp"
  }
};
