/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_ikm_garage_sorel_tracy).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538262/tapavis_tenant_ikm_garage_sorel_tracy/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538262/tapavis_tenant_ikm_garage_sorel_tracy/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538274/tapavis_tenant_ikm_garage_sorel_tracy/hero_87b7e790-f998-49e9-893d-9045e744a9c3.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538273/tapavis_tenant_ikm_garage_sorel_tracy/vidange-huile_8e5da727-2bda-49ae-9fad-d1803d19e6ec.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538274/tapavis_tenant_ikm_garage_sorel_tracy/mecanique-generale_69867325-6461-4087-9600-7dd200eafc20.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538274/tapavis_tenant_ikm_garage_sorel_tracy/freins_a3970b81-7eda-44bc-9375-2cb1bb792bf1.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538284/tapavis_tenant_ikm_garage_sorel_tracy/silencieux_802b6c97-3bc4-4dfe-93f6-8db2a365ffc2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538285/tapavis_tenant_ikm_garage_sorel_tracy/suspension_a77626c5-b5cb-4792-ac4f-a12d724e7111.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538285/tapavis_tenant_ikm_garage_sorel_tracy/equilibrage-rotation-pneus_705d2b7f-316d-42a6-9e51-20a81c55c672.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538287/tapavis_tenant_ikm_garage_sorel_tracy/systeme-de-refroidissement_64b37a6a-a86b-496d-a9f7-ec5e097bfe81.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538295/tapavis_tenant_ikm_garage_sorel_tracy/climatisation_c3b019a4-2f12-40fd-9bc6-7054b6330aea.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538296/tapavis_tenant_ikm_garage_sorel_tracy/mise-au-point_8632eef0-01c7-4659-a57d-b433778549b4.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538297/tapavis_tenant_ikm_garage_sorel_tracy/transmission_ab54bae8-5327-4c3b-a62c-2c69187c5a30.png"
  }
};
