/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_centre_de_l_auto_carignan).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740404/tapavis_tenant_centre_de_l_auto_carignan/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740404/tapavis_tenant_centre_de_l_auto_carignan/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740416/tapavis_tenant_centre_de_l_auto_carignan/hero_321af8d0-9706-4b56-b6c0-efc66c94c4c2.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740416/tapavis_tenant_centre_de_l_auto_carignan/freins_cd877ab4-805a-4d27-b38a-3e7d9df2ab93.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740416/tapavis_tenant_centre_de_l_auto_carignan/vidange-huile_cbb0ebad-8ef6-42c9-ad99-0ff2b9d6e011.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740421/tapavis_tenant_centre_de_l_auto_carignan/mecanique-generale_ae77a58d-ba59-468a-81ba-5a5ff88af856.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740427/tapavis_tenant_centre_de_l_auto_carignan/silencieux_8516566c-ff6b-47c9-8e53-e4a35cbe6fb7.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740428/tapavis_tenant_centre_de_l_auto_carignan/suspension_2d20d5ce-063b-4aa5-84d9-4a55edd20745.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740428/tapavis_tenant_centre_de_l_auto_carignan/equilibrage-rotation-pneus_918e1f6d-ccdf-48e2-8268-8f2e85d99a4d.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740434/tapavis_tenant_centre_de_l_auto_carignan/systeme-de-refroidissement_7d643a71-7c0a-4ac9-8d0f-f44cf04621d0.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740438/tapavis_tenant_centre_de_l_auto_carignan/climatisation_4c771f14-2d20-4949-9ae0-25f494cdd616.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740440/tapavis_tenant_centre_de_l_auto_carignan/transmission_6697e880-f462-4e68-849a-9372fbba4ed2.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740441/tapavis_tenant_centre_de_l_auto_carignan/mise-au-point_c6a2f6f6-c36a-456e-94a7-772c2e402956.png"
  }
};
