/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_gc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332153/tapavis_tenant_mecanique_gc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332153/tapavis_tenant_mecanique_gc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332163/tapavis_tenant_mecanique_gc/hero_0ad9cd53-19f2-4158-8ffe-cfb42f9e594a.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332165/tapavis_tenant_mecanique_gc/freins_78282df9-da54-4673-a71f-f6a77892579d.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332165/tapavis_tenant_mecanique_gc/vidange-huile_e58152fb-5dac-4793-a893-de6ad0d3b4a0.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332702/tapavis_tenant_mecanique_gc/mecanique-generale_94d5c005-01f9-4750-b884-c75680ee424a.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332176/tapavis_tenant_mecanique_gc/suspension_76618106-98c6-4957-abbf-ecb46d2ce7b7.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332177/tapavis_tenant_mecanique_gc/silencieux_9761b1ae-e99c-488d-a0e4-00f6bdfafde7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332176/tapavis_tenant_mecanique_gc/equilibrage-rotation-pneus_f233d62e-39c6-42ce-8aad-2998f0044f57.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332182/tapavis_tenant_mecanique_gc/systeme-de-refroidissement_4cc6e57d-2979-44fe-a1e0-b20e1608a621.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332190/tapavis_tenant_mecanique_gc/climatisation_46c15ef9-2fa8-4d2c-af33-476f2c051c09.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332191/tapavis_tenant_mecanique_gc/mise-au-point_457f79a3-c106-4de6-825f-9a0dbdfb9ec8.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790332192/tapavis_tenant_mecanique_gc/transmission_861247c7-fdfd-4b97-a6cd-e8b08fbe4621.png"
  }
};
