/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_silencieux_select).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048765/tapavis_tenant_silencieux_select/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048765/tapavis_tenant_silencieux_select/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791048781/tapavis_tenant_silencieux_select/hero_ccfba795-1673-45b8-b9d5-de334d950cdf.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791048781/tapavis_tenant_silencieux_select/freins_27ed373b-eaa7-4b9f-a377-f27c57d2266b.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048782/tapavis_tenant_silencieux_select/vidange-huile_5f890ae6-6330-4bf4-aa20-6f045ed5c634.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048784/tapavis_tenant_silencieux_select/mecanique-generale_036b9f10-9586-48e4-acd6-f9546e59212f.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048791/tapavis_tenant_silencieux_select/silencieux_caa49fa8-1f43-419c-9277-e62211cfe6b4.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048792/tapavis_tenant_silencieux_select/equilibrage-rotation-pneus_0b0fd317-679a-4093-bc9a-d513d6df52ec.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048792/tapavis_tenant_silencieux_select/suspension_0bcbabae-276f-4955-b681-ba511a415078.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048795/tapavis_tenant_silencieux_select/systeme-de-refroidissement_71c1075f-7f9c-4e3e-8c09-559fd944fcb9.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048802/tapavis_tenant_silencieux_select/mise-au-point_1d2d6983-d080-4adb-8722-a9bd0c92cf25.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048802/tapavis_tenant_silencieux_select/climatisation_9a698291-ed1f-423a-af6a-a4fbdab53a88.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048803/tapavis_tenant_silencieux_select/transmission_f1bc5fc3-8512-4eaf-85f6-e31f05c601ad.webp"
  }
};
