/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_auto_electrique_lavaltrie_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667316/tapavis_tenant_auto_electrique_lavaltrie_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667316/tapavis_tenant_auto_electrique_lavaltrie_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667328/tapavis_tenant_auto_electrique_lavaltrie_inc/hero_1e1267b0-2c8f-449a-89ba-8b1d6af90d9d.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667328/tapavis_tenant_auto_electrique_lavaltrie_inc/freins_7cdf5e03-dd62-4975-9a71-3086889d34e7.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667328/tapavis_tenant_auto_electrique_lavaltrie_inc/mecanique-generale_b6901b81-fb95-4267-b90e-c34e520889f9.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667330/tapavis_tenant_auto_electrique_lavaltrie_inc/systeme-electrique_45156584-4bc6-4404-90d9-65c1edc734b8.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667340/tapavis_tenant_auto_electrique_lavaltrie_inc/silencieux_d4f71c1d-e0b8-44e7-931d-c76a884f8626.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667341/tapavis_tenant_auto_electrique_lavaltrie_inc/vidange-huile_5c9eaa7e-6b0c-4454-b8ce-a0dc45a804ea.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667341/tapavis_tenant_auto_electrique_lavaltrie_inc/equilibrage-rotation-pneus_3d4ef64c-073a-4b45-9a0a-fa2ae2392a84.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667341/tapavis_tenant_auto_electrique_lavaltrie_inc/suspension_5bd973d8-c440-4ac9-936d-b8df002ee392.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667351/tapavis_tenant_auto_electrique_lavaltrie_inc/systeme-de-refroidissement_9a66d5d9-acdb-4a38-86d0-16ede6aad3fa.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667352/tapavis_tenant_auto_electrique_lavaltrie_inc/mise-au-point_d21af0fe-d7fc-4576-8994-7b8a0e9bcaea.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667354/tapavis_tenant_auto_electrique_lavaltrie_inc/transmission_ae8429cc-aa4e-49d3-a013-a85d6bdc7cf3.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667355/tapavis_tenant_auto_electrique_lavaltrie_inc/climatisation_f872daa3-ce88-4b12-af59-85cce2f384eb.png"
  }
};
