/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_s_d_m).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736227/tapavis_tenant_mecanique_s_d_m/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736227/tapavis_tenant_mecanique_s_d_m/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736239/tapavis_tenant_mecanique_s_d_m/hero_973e519b-c9d7-4ad6-a09c-1d9064c7918c.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736239/tapavis_tenant_mecanique_s_d_m/freins_7af85fbd-762b-43da-b9e6-29e6688629c2.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736240/tapavis_tenant_mecanique_s_d_m/mecanique-generale_687cac20-29d4-4691-bb6c-ce1e8e487e17.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736241/tapavis_tenant_mecanique_s_d_m/vidange-huile_7368a871-0e25-42e0-892b-5e3612ca611c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736250/tapavis_tenant_mecanique_s_d_m/silencieux_0895d4d8-42cc-48c2-b48b-8342b5d2770b.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736251/tapavis_tenant_mecanique_s_d_m/suspension_c2f3267f-f739-4166-9595-716ba18df01d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736252/tapavis_tenant_mecanique_s_d_m/equilibrage-rotation-pneus_6e7075e5-6648-4050-a59b-a405e2d77051.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736255/tapavis_tenant_mecanique_s_d_m/systeme-de-refroidissement_54fbb5ff-d914-4e73-af81-09c0f0451322.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736264/tapavis_tenant_mecanique_s_d_m/climatisation_058866c4-3dba-447d-a136-2ff903913472.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736265/tapavis_tenant_mecanique_s_d_m/transmission_11a4485a-44b8-40e3-96f5-46340edc07c7.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736265/tapavis_tenant_mecanique_s_d_m/mise-au-point_1d7b3fa7-55d9-4719-9a2d-fc2f4b899e64.png"
  }
};
