/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_principale_mi).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668404/tapavis_tenant_garage_principale_mi/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668404/tapavis_tenant_garage_principale_mi/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668415/tapavis_tenant_garage_principale_mi/hero_cd479573-d0d8-4325-86d2-8377ea653e9b.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668414/tapavis_tenant_garage_principale_mi/vidange-huile_c9b947cc-56ec-4519-98f4-3e8c7ed03547.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668415/tapavis_tenant_garage_principale_mi/mecanique-generale_f0f806dd-8fec-483f-abc3-e8e67d94cf4a.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668417/tapavis_tenant_garage_principale_mi/freins_f208333c-ebaf-4d94-b4fe-4df9f143647c.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668426/tapavis_tenant_garage_principale_mi/equilibrage-rotation-pneus_e66ca3e6-ab38-41d1-91c5-d4b6cb84f26a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668426/tapavis_tenant_garage_principale_mi/silencieux_1202948b-1571-4e5c-9bb8-096208fb92c2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668427/tapavis_tenant_garage_principale_mi/suspension_145ab0bc-2622-457e-bedf-3e7d92f4adc5.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668428/tapavis_tenant_garage_principale_mi/systeme-de-refroidissement_95a328db-dbc5-4bb0-99c4-3536bfb7a322.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668438/tapavis_tenant_garage_principale_mi/climatisation_7ab2a714-a4ad-4cc5-bc5d-159394185d8b.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668438/tapavis_tenant_garage_principale_mi/mise-au-point_cecf078e-6196-4d98-9fb6-37b560672efa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668439/tapavis_tenant_garage_principale_mi/transmission_b1e2cbcb-f0e8-41fa-9341-bd76cc67632a.png"
  }
};
