/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_jacques_cyr).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790964989/tapavis_tenant_garage_jacques_cyr/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790964989/tapavis_tenant_garage_jacques_cyr/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790965005/tapavis_tenant_garage_jacques_cyr/hero_2dfff648-2b02-4e21-95f3-2d2e1a1be90b.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790965005/tapavis_tenant_garage_jacques_cyr/vidange-huile_43fa7b9e-0261-4b98-9ade-61210778ce87.webp",
    "freins": "https://media.liasse.tech/upload/v1790965005/tapavis_tenant_garage_jacques_cyr/freins_952980eb-579b-42bb-a1db-bf54017b4a80.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790965007/tapavis_tenant_garage_jacques_cyr/mecanique-generale_3ffaf574-d0e4-4c94-91b3-7a2cf9098388.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790965015/tapavis_tenant_garage_jacques_cyr/silencieux_73b9c1c2-e252-4e3a-89cf-737a4ba2d5b6.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790965015/tapavis_tenant_garage_jacques_cyr/equilibrage-rotation-pneus_23032293-6aae-403e-8d39-e58fc431c125.webp",
    "suspension": "https://media.liasse.tech/upload/v1790965017/tapavis_tenant_garage_jacques_cyr/suspension_c2a8e5bb-eb61-482b-b392-756566acee8d.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790965019/tapavis_tenant_garage_jacques_cyr/systeme-de-refroidissement_06b6443d-761a-4e18-a5f2-a8e94fa7addb.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790965025/tapavis_tenant_garage_jacques_cyr/mise-au-point_b5f6c9cd-267f-499f-942e-a517bba558bc.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790965026/tapavis_tenant_garage_jacques_cyr/climatisation_23b4c28a-68f3-47a0-9a47-374b27e5de3c.webp",
    "transmission": "https://media.liasse.tech/upload/v1790965027/tapavis_tenant_garage_jacques_cyr/transmission_d8ce2289-a3a0-4cdd-8a37-6d974751607e.webp"
  }
};
