/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_hg_autoport_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791054831/tapavis_tenant_hg_autoport_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791054831/tapavis_tenant_hg_autoport_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791054845/tapavis_tenant_hg_autoport_inc/hero_d878859c-39c5-4de1-9d63-c4a0a9ebe6c2.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791054846/tapavis_tenant_hg_autoport_inc/vidange-huile_20fe514f-5b3c-4bf3-80f2-964c7a46571b.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791054847/tapavis_tenant_hg_autoport_inc/mecanique-generale_08541e47-0a55-41b7-9111-2f8eb32234ed.webp",
    "freins": "https://media.liasse.tech/upload/v1791054848/tapavis_tenant_hg_autoport_inc/freins_91835da4-c129-4852-8054-938b4ce4be04.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791054855/tapavis_tenant_hg_autoport_inc/equilibrage-rotation-pneus_476d4030-6e9e-4bf7-a409-314b81830b18.webp",
    "suspension": "https://media.liasse.tech/upload/v1791054856/tapavis_tenant_hg_autoport_inc/suspension_25352066-120e-44e1-83ea-eff8a242d239.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791054856/tapavis_tenant_hg_autoport_inc/silencieux_9d7319fa-d0b6-4d6b-8497-44a018ea50d8.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791054858/tapavis_tenant_hg_autoport_inc/systeme-de-refroidissement_db5fdfe3-c98c-4d96-93db-3f513f71cab0.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791054866/tapavis_tenant_hg_autoport_inc/mise-au-point_e3695de5-23a5-4927-bef1-9400ab4e3ca7.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791054866/tapavis_tenant_hg_autoport_inc/climatisation_5d421dae-3863-4167-9c61-135966fe8ee6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791054867/tapavis_tenant_hg_autoport_inc/transmission_f2dff6ef-911e-4b30-a0a8-bb4905fa0438.webp"
  }
};
