/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_rej_stars_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048478/tapavis_tenant_rej_stars_auto/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048478/tapavis_tenant_rej_stars_auto/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050344/tapavis_tenant_rej_stars_auto/hero_5c8076af-b522-44f6-8769-6b77a32d888c.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048493/tapavis_tenant_rej_stars_auto/mecanique-generale_7fd270b2-4373-42c0-9a32-7847f10bb38d.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048493/tapavis_tenant_rej_stars_auto/vidange-huile_4229206d-8618-442b-a09b-913214a69ae5.webp",
    "freins": "https://media.liasse.tech/upload/v1791048494/tapavis_tenant_rej_stars_auto/freins_04a00b71-e66a-441d-b0fc-49d1ffc6605f.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048502/tapavis_tenant_rej_stars_auto/silencieux_723f2028-257b-47d5-8c16-260df40ff894.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048503/tapavis_tenant_rej_stars_auto/suspension_416caf1d-b02d-45ac-9ac3-bca06e0a5739.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048503/tapavis_tenant_rej_stars_auto/equilibrage-rotation-pneus_5ae4936e-1ba8-4a2e-8128-611b1ef3325c.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048505/tapavis_tenant_rej_stars_auto/systeme-de-refroidissement_c0fab043-8aa5-4f5c-9580-2f0f13698a8b.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048513/tapavis_tenant_rej_stars_auto/climatisation_6d884086-4d4b-4326-8560-032a072534f9.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048513/tapavis_tenant_rej_stars_auto/transmission_5cbf5ce2-57e6-4cc1-822e-277189fc88a8.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048522/tapavis_tenant_rej_stars_auto/mise-au-point_9587974f-2c2e-4ab0-924c-2c706268cca0.webp"
  }
};
