/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_service_mini_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732399/tapavis_tenant_service_mini_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732399/tapavis_tenant_service_mini_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732409/tapavis_tenant_service_mini_mecanique/hero_732221f6-44cc-46b1-8e20-6988ed585b37.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732411/tapavis_tenant_service_mini_mecanique/freins_019b457a-e05e-41aa-999e-25e9ef7d760d.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732411/tapavis_tenant_service_mini_mecanique/vidange-huile_82620414-c61c-4a19-b3b1-1606317aa04c.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732412/tapavis_tenant_service_mini_mecanique/mecanique-generale_114c0e2e-3ca7-493f-9600-26926290f907.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732422/tapavis_tenant_service_mini_mecanique/equilibrage-rotation-pneus_8542ff49-2186-4f38-be87-540045228f7a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732423/tapavis_tenant_service_mini_mecanique/silencieux_f9fda98d-c01f-4de5-b774-ad0e7076fb6c.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732424/tapavis_tenant_service_mini_mecanique/systeme-de-refroidissement_4ff23c48-acc5-47ed-8032-1f671e1751b8.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732424/tapavis_tenant_service_mini_mecanique/suspension_e43a7e9e-edf4-48e5-b6bf-36abc54e31b6.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732435/tapavis_tenant_service_mini_mecanique/mise-au-point_f41ffe3d-9927-4118-ae3f-8c4a754ad3f8.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732435/tapavis_tenant_service_mini_mecanique/climatisation_51031114-2a7a-46cc-bcdd-0f3988f5f992.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732436/tapavis_tenant_service_mini_mecanique/transmission_00a69b0c-99d2-4a78-b35f-b8b611b8be4c.png"
  }
};
