/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_mario_gough).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813273/tapavis_tenant_garage_mario_gough/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813273/tapavis_tenant_garage_mario_gough/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814735/tapavis_tenant_garage_mario_gough/hero_066c53e4-1b74-472b-b556-d109b8241626.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813292/tapavis_tenant_garage_mario_gough/vidange-huile_da0cff9f-0fb2-4e5f-91f7-22eed3e8e4d6.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813295/tapavis_tenant_garage_mario_gough/equilibrage-rotation-pneus_7226fc34-6bcf-45f6-a956-2abf4fbe17b0.png",
    "carrosserie": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813312/tapavis_tenant_garage_mario_gough/carrosserie_1676e61b-ed25-45c4-aa8a-996c685123b7.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813313/tapavis_tenant_garage_mario_gough/freins_f4483ca2-db85-4b1d-809f-1d3e0bec1dc5.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813314/tapavis_tenant_garage_mario_gough/mecanique-generale_7b566425-5530-4071-b28c-100facc7252c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813328/tapavis_tenant_garage_mario_gough/silencieux_a604349a-fdbd-4735-a340-73e013093beb.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813332/tapavis_tenant_garage_mario_gough/suspension_49e65043-85e1-49b9-9417-724e1079d6fd.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813335/tapavis_tenant_garage_mario_gough/climatisation_5e87b931-1c59-45a4-9f1e-f98dac4840bb.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813335/tapavis_tenant_garage_mario_gough/systeme-de-refroidissement_c7dae7c5-fbfa-44ca-ade9-9908f42463ca.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813341/tapavis_tenant_garage_mario_gough/mise-au-point_7965fd26-54c3-4692-94a3-812b109c7b1b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813345/tapavis_tenant_garage_mario_gough/transmission_0a702db3-c9dc-434e-b6d2-fe26f3a2edb4.png"
  }
};
