/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_entreprise_georges_lepage).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963181/tapavis_tenant_entreprise_georges_lepage/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963181/tapavis_tenant_entreprise_georges_lepage/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963197/tapavis_tenant_entreprise_georges_lepage/hero_5e6370dc-e65f-4495-b10f-961dbd0f4edb.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790963198/tapavis_tenant_entreprise_georges_lepage/freins_9e367b61-fce7-4dd8-a675-617bd7d80adc.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963198/tapavis_tenant_entreprise_georges_lepage/mecanique-generale_34d0793f-6b06-4f97-ab81-29262210afc3.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790963198/tapavis_tenant_entreprise_georges_lepage/vidange-huile_05f9091b-ebed-470d-bfbc-9bcce35ce82d.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963207/tapavis_tenant_entreprise_georges_lepage/equilibrage-rotation-pneus_bd8f6963-d7cb-4c8b-b48d-044a0ed5a2cf.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963208/tapavis_tenant_entreprise_georges_lepage/silencieux_09088a47-4713-4077-8cc6-fdfada017e3d.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963209/tapavis_tenant_entreprise_georges_lepage/suspension_04336a2a-94f2-45bc-948b-b967eb5a94ad.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963210/tapavis_tenant_entreprise_georges_lepage/systeme-de-refroidissement_e176c5d2-3c65-41e0-93c2-afaa63bf0328.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963217/tapavis_tenant_entreprise_georges_lepage/climatisation_f41e4283-be94-4056-84b6-f89e49e96b30.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963218/tapavis_tenant_entreprise_georges_lepage/mise-au-point_6d572d12-5589-452e-967a-f22dde8cf0de.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963221/tapavis_tenant_entreprise_georges_lepage/transmission_b7305a0d-5995-44a6-99b0-ae31d019cfde.webp"
  }
};
