/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_service_auto_jc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668835/tapavis_tenant_service_auto_jc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668835/tapavis_tenant_service_auto_jc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668845/tapavis_tenant_service_auto_jc/hero_1f33feb6-2521-4d67-83ed-69c25ee73b3a.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668846/tapavis_tenant_service_auto_jc/vidange-huile_02740501-cc1c-4b91-93bd-09fe7a9b2520.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668846/tapavis_tenant_service_auto_jc/freins_93dfd52f-5d16-4381-ad9c-d02f92f7874d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668846/tapavis_tenant_service_auto_jc/mecanique-generale_9210bea1-4f67-4159-b8b7-95164e5a256e.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668855/tapavis_tenant_service_auto_jc/silencieux_49213afb-927c-49f6-a38e-3fbb5b7237ad.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668856/tapavis_tenant_service_auto_jc/suspension_8ad35207-2b52-42eb-b12d-8c7aa204a940.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668857/tapavis_tenant_service_auto_jc/equilibrage-rotation-pneus_91c70f96-3f13-4322-b359-fe5928a06d12.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668859/tapavis_tenant_service_auto_jc/systeme-de-refroidissement_6c87e42f-fa7b-4b8f-8c93-7ad9e201e109.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668867/tapavis_tenant_service_auto_jc/climatisation_512663c9-eeac-4681-9483-24686c3e7dc8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668867/tapavis_tenant_service_auto_jc/mise-au-point_a762160a-4870-4f6b-8b4b-abf73de5f5e4.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668870/tapavis_tenant_service_auto_jc/transmission_7b851feb-4276-45b1-b0e2-28b3e791e72d.png"
  }
};
