/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_bertony_automotive).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790972138/tapavis_tenant_bertony_automotive/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790972138/tapavis_tenant_bertony_automotive/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790972155/tapavis_tenant_bertony_automotive/hero_db894ff0-5ab0-465d-b754-ccf2a4a33f50.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790972154/tapavis_tenant_bertony_automotive/mecanique-generale_15a993df-d7f5-4f2a-9689-a28b69eb67f5.webp",
    "freins": "https://media.liasse.tech/upload/v1790972155/tapavis_tenant_bertony_automotive/freins_d59c6045-6d5c-48ae-9cd2-0950de050bfb.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790972156/tapavis_tenant_bertony_automotive/vidange-huile_45b2b4fb-baaf-4df1-afa1-4dd736ba7446.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790972164/tapavis_tenant_bertony_automotive/silencieux_8af78fc1-1fe1-4e45-afe6-bf8d72175b78.webp",
    "suspension": "https://media.liasse.tech/upload/v1790972165/tapavis_tenant_bertony_automotive/suspension_491f0cdc-58a8-41a2-91bd-8e1b3503f89d.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790972166/tapavis_tenant_bertony_automotive/equilibrage-rotation-pneus_0dd851ae-253e-4582-abaf-2553eaa706bf.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790972168/tapavis_tenant_bertony_automotive/systeme-de-refroidissement_c6753fa9-223a-45c7-9f7b-ad663675860c.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790972175/tapavis_tenant_bertony_automotive/mise-au-point_b6270057-1916-4705-93d2-a7c691e661b3.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790972175/tapavis_tenant_bertony_automotive/climatisation_16f55ee6-e4eb-48f5-b2d3-877fcf756995.webp",
    "transmission": "https://media.liasse.tech/upload/v1790972177/tapavis_tenant_bertony_automotive/transmission_2f7e2afc-adaa-4c0d-a939-cde2f237ba2e.webp"
  }
};
