ALTER TABLE posts ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE member_posts ADD COLUMN IF NOT EXISTS hidden INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_minor INTEGER DEFAULT 0;