/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_atelier_mfg).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812704/tapavis_tenant_atelier_mfg/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812704/tapavis_tenant_atelier_mfg/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812719/tapavis_tenant_atelier_mfg/hero_7c6560aa-b102-453b-b765-660806d900ce.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812719/tapavis_tenant_atelier_mfg/freins_6129a5b9-5e5c-4d37-bb87-7d5f93ae0cbf.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812720/tapavis_tenant_atelier_mfg/vidange-huile_7c78799c-4220-4bcf-a100-3547dfb46664.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812723/tapavis_tenant_atelier_mfg/mecanique-generale_a56becd1-5428-451b-9f18-7791778c5b12.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812733/tapavis_tenant_atelier_mfg/silencieux_451fe798-5b17-4d94-8104-0718cc7c6473.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812733/tapavis_tenant_atelier_mfg/equilibrage-rotation-pneus_08e3bae7-6bf0-43e0-a193-fc351c701734.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812733/tapavis_tenant_atelier_mfg/suspension_c7898d1a-04ae-4e64-93ab-589681b17f62.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812736/tapavis_tenant_atelier_mfg/systeme-de-refroidissement_91336526-ceeb-4263-99c2-6a448f23ec07.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812745/tapavis_tenant_atelier_mfg/transmission_a8bfbbca-5a8f-4683-a033-f62c4be03a4c.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812745/tapavis_tenant_atelier_mfg/climatisation_beb841b1-c374-49e9-863e-88babd69f836.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812746/tapavis_tenant_atelier_mfg/mise-au-point_9fa08f43-7ca7-4fbf-b9c6-ac688626241a.png"
  }
};
