/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_d_s).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735090/tapavis_tenant_mecanique_d_s/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735090/tapavis_tenant_mecanique_d_s/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736453/tapavis_tenant_mecanique_d_s/hero_ad04298b-7800-4a9f-b4f3-bbffd3a3b36b.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735100/tapavis_tenant_mecanique_d_s/vidange-huile_491e6d60-60c4-40e5-8afe-dd8084ac6754.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735102/tapavis_tenant_mecanique_d_s/mecanique-generale_299ba340-c887-4456-af4d-9e5a49a62f3e.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735103/tapavis_tenant_mecanique_d_s/freins_412dbb2e-3bf7-4eca-9a92-18c3bcc63de2.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735112/tapavis_tenant_mecanique_d_s/silencieux_57c2cb30-30b6-4744-b5e0-9a532734f31c.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735113/tapavis_tenant_mecanique_d_s/equilibrage-rotation-pneus_d263e7c5-a5aa-4651-874e-8cc5b3230b87.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735114/tapavis_tenant_mecanique_d_s/suspension_1c841e82-807a-4133-8b74-bd2e40ba8994.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735115/tapavis_tenant_mecanique_d_s/systeme-de-refroidissement_4d6fc982-3e01-49c9-a55e-a8bdb8dc1c57.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735125/tapavis_tenant_mecanique_d_s/mise-au-point_605e6eac-c7dd-49ab-8f17-0bc9817faf64.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735125/tapavis_tenant_mecanique_d_s/climatisation_3e2c0538-66fc-4913-bc44-8e44a9b769cc.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735127/tapavis_tenant_mecanique_d_s/transmission_b4eb532b-4f54-48c9-b610-556e0caceda0.png"
  }
};
