/**
 * Rivard Mecanic — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "mecanique-generale",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Réparation mécanique",
    "name_en": "Mechanical repair",
    "tagline": "Diagnostic, freins, courroies, direction : on trouve la cause, on répare.",
    "tagline_en": "Diagnostics, brakes, belts, steering: we find the cause and fix it.",
    "body": "Un bruit nouveau, un voyant qui s’allume, une conduite qui a changé : la mécanique générale commence par un diagnostic. Le véhicule est inspecté, les codes d’erreur sont lus, et vous recevez une explication claire de ce qui se passe avant toute réparation.\nFreins, courroies, direction, démarreur, alternateur, batterie : la plupart des réparations courantes se font dans la même visite.",
    "body_en": "A new noise, a warning light, a car that drives differently: general repair starts with a diagnosis. The vehicle is inspected, fault codes are read, and you get a clear explanation of what is going on before any repair.\nBrakes, belts, steering, starter, alternator, battery: most everyday repairs are handled in the same visit.",
    "signs": "[\"Un voyant « Check engine » allumé\",\"Grincement ou vibration au freinage\",\"Difficulté à démarrer\",\"Odeur de brûlé ou fuite sous le véhicule\"]",
    "signs_en": "[\"A \\\"Check engine\\\" light\",\"Squealing or vibration when braking\",\"Hard starts\",\"A burning smell or a leak under the car\"]",
    "confirmed": 1
  },
  {
    "slug": "inspection-mecanique",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Inspection de véhicule",
    "name_en": "Vehicle inspection",
    "tagline": "Avant un achat, un voyage ou pour l’assurance.",
    "tagline_en": "Before buying, a trip, or for insurance.",
    "body": "L’inspection passe en revue les points essentiels du véhicule : freins, pneus, suspension, direction, éclairage, fuites, échappement et état général, avec un rapport des travaux à prévoir. Utile avant d’acheter un véhicule d’occasion, avant un long voyage ou lorsqu’un assureur la demande.",
    "body_en": "An inspection reviews the vehicle’s key points: brakes, tires, suspension, steering, lights, leaks, exhaust and general condition, with a report of the work to plan. Useful before buying a used vehicle, before a long trip, or when an insurer asks for one.",
    "signs": "[\"Achat d’un véhicule d’occasion\", \"Long voyage à venir\", \"Demande de l’assureur\", \"Bruits ou fuites inexpliqués\"]",
    "signs_en": "[\"Buying a used vehicle\", \"A long trip ahead\", \"Insurer request\", \"Unexplained noises or leaks\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-asiatiques",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures asiatiques",
    "name_en": "Asian cars",
    "tagline": "Japonaises et coréennes.",
    "tagline_en": "Japanese and Korean cars.",
    "body": "Voitures japonaises et coréennes : entretien prévu au carnet, freins, suspension, courroies et diagnostic. Indiquez la marque, le modèle et l’année en réservant.",
    "body_en": "Japanese and Korean cars: scheduled maintenance, brakes, suspension, belts and diagnostics. Give the make, model and year when you book.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant allumé\", \"Bruit ou vibration\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"A warning light\", \"A noise or vibration\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-americaines",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures américaines",
    "name_en": "American cars",
    "tagline": "Autos, VUS et camionnettes américains.",
    "tagline_en": "American cars, SUVs and pickups.",
    "body": "Autos, VUS et camionnettes de constructeurs américains : entretien prévu au carnet, freins, suspension, direction et diagnostic. Indiquez le modèle, l’année et le moteur en réservant.",
    "body_en": "Cars, SUVs and pickups from American makers: scheduled maintenance, brakes, suspension, steering and diagnostics. Give the model, year and engine when you book.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant moteur allumé\", \"Bruit sous le véhicule\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"Check-engine light on\", \"A noise under the vehicle\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-anciennes",
    "icon": "car",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures anciennes",
    "name_en": "Older and classic cars",
    "tagline": "Les véhicules d’un autre temps ont besoin d’attention.",
    "tagline_en": "Older vehicles need special care.",
    "body": "Les voitures anciennes demandent de la patience : pièces à trouver, carburateurs, allumage, freins et rouille. Décrivez le véhicule en réservant ; le garage évalue le travail avant de commencer.",
    "body_en": "Older cars take patience: parts to source, carburetors, ignition, brakes and rust. Describe the vehicle when you book; the garage assesses the work before starting.",
    "signs": "[\"Remise en route après l’hiver\", \"Pièce difficile à trouver\", \"Freins ou allumage à revoir\"]",
    "signs_en": "[\"Getting it running after winter\", \"A hard-to-find part\", \"Brakes or ignition to go over\"]",
    "confirmed": 1
  },
  {
    "slug": "climatisation",
    "icon": "snow",
    "duration_min": 90,
    "bookable": 1,
    "featured": 0,
    "name": "Service complet d’air climatisé",
    "name_en": "Full air-conditioning service",
    "tagline": "De l’air froid l’été, un pare-brise qui désembue l’hiver.",
    "tagline_en": "Cold air in summer, a windshield that clears in winter.",
    "body": "La climatisation ne sert pas qu’en juillet : elle assèche l’air et aide le pare-brise à désembuer par temps froid et humide. L’entretien vérifie la charge de réfrigérant, cherche les fuites et contrôle le compresseur et le filtre d’habitacle.",
    "body_en": "Air conditioning is not only for July: it dries the air and helps clear the windshield in cold, damp weather. The service checks the refrigerant charge, looks for leaks and checks the compressor and cabin filter.",
    "signs": "[\"L’air ne refroidit plus comme avant\",\"Odeur d’humidité à la mise en marche\",\"Le pare-brise désembue mal\",\"Bruit quand la climatisation démarre\"]",
    "signs_en": "[\"The air is not as cold as it used to be\",\"A musty smell when it starts\",\"The windshield clears poorly\",\"A noise when the A/C kicks in\"]",
    "confirmed": 1
  },
  {
    "slug": "entretien-moteur-flotte",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Sous-traitance de flotte",
    "name_en": "Fleet subcontracting",
    "tagline": "Entretien et réparation de véhicules d’entreprise.",
    "tagline_en": "Maintenance and repair of company vehicles.",
    "body": "Le garage indique la sous-traitance de flotte de véhicules : entretien et réparations des véhicules d’une entreprise, avec un suivi par véhicule. Appelez pour organiser le service.",
    "body_en": "The garage lists vehicle fleet subcontracting: maintenance and repairs of a company’s vehicles, with per-vehicle follow-up. Call to set up the service.",
    "signs": "[\"Plusieurs véhicules d’entreprise\", \"Suivi par véhicule\", \"Réparations à planifier\"]",
    "signs_en": "[\"Several company vehicles\", \"Per-vehicle follow-up\", \"Repairs to plan\"]",
    "confirmed": 1
  }
];
