/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_pro_one).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791055333/tapavis_tenant_garage_pro_one/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791055333/tapavis_tenant_garage_pro_one/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791055347/tapavis_tenant_garage_pro_one/hero_539658a2-dfef-4d0b-ad07-93cf6e844c73.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791055348/tapavis_tenant_garage_pro_one/freins_d6a21f3c-40bb-46f1-a9dc-298cac525716.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791055348/tapavis_tenant_garage_pro_one/vidange-huile_483113d1-2b2a-486a-873d-07391da005c5.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791055350/tapavis_tenant_garage_pro_one/mecanique-generale_aa4ad487-414d-416f-985d-c76d5bd55031.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791055358/tapavis_tenant_garage_pro_one/silencieux_6007ccd2-0b8a-4439-a348-c2f0b58d92bf.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791055358/tapavis_tenant_garage_pro_one/equilibrage-rotation-pneus_f6b27f43-cd23-495b-a6b9-d45bb60b3317.webp",
    "suspension": "https://media.liasse.tech/upload/v1791055360/tapavis_tenant_garage_pro_one/suspension_2ca25939-4421-42b3-87be-11fb7f7cfef6.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791055361/tapavis_tenant_garage_pro_one/systeme-de-refroidissement_81e6c3c7-7bfc-4cb7-aca6-28607396c1f4.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791055368/tapavis_tenant_garage_pro_one/climatisation_18675e96-95f6-4c59-9f79-2bf05f755db7.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791055368/tapavis_tenant_garage_pro_one/mise-au-point_9c1ff7f1-3c47-41e0-8ad1-955eae0c388f.webp",
    "transmission": "https://media.liasse.tech/upload/v1791055370/tapavis_tenant_garage_pro_one/transmission_f6a0b33b-4c78-43cd-accd-21ad7bea6215.webp"
  }
};
