/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_kl_coaticook).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556425/tapavis_tenant_mecanique_kl_coaticook/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556425/tapavis_tenant_mecanique_kl_coaticook/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556435/tapavis_tenant_mecanique_kl_coaticook/hero_f64bdc68-1b54-478b-aeda-fef0a39dc572.png",
  "services": {
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556435/tapavis_tenant_mecanique_kl_coaticook/mecanique-generale_171921b9-bdbb-4fa0-93e1-f9b874573992.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556436/tapavis_tenant_mecanique_kl_coaticook/vidange-huile_6e7c57d8-0d13-43c0-8d5a-db4055718e2b.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556437/tapavis_tenant_mecanique_kl_coaticook/freins_e4aa136c-b3ac-4237-a009-2cd577240d7a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556445/tapavis_tenant_mecanique_kl_coaticook/silencieux_ca5db93e-4b42-44b0-9db9-a8e3f4d6ccec.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556446/tapavis_tenant_mecanique_kl_coaticook/suspension_6820bba3-afa7-4203-af28-674345cf3d06.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556448/tapavis_tenant_mecanique_kl_coaticook/equilibrage-rotation-pneus_ab23309f-7ba4-49e5-a259-0e0850e6f681.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556452/tapavis_tenant_mecanique_kl_coaticook/systeme-de-refroidissement_169cd5f4-6e87-4c25-803e-78dbd294c165.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556457/tapavis_tenant_mecanique_kl_coaticook/mise-au-point_b2eabc79-228b-4f75-a21c-eac17fe6387d.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556458/tapavis_tenant_mecanique_kl_coaticook/climatisation_dfc02fbb-ee28-4ace-b49e-f52e3c5623a3.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556461/tapavis_tenant_mecanique_kl_coaticook/transmission_2f4ebeb6-4651-4bb6-8a33-26e7345e8294.png"
  }
};
