/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_pinard_fils_senc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442949/tapavis_tenant_garage_pinard_fils_senc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442949/tapavis_tenant_garage_pinard_fils_senc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442961/tapavis_tenant_garage_pinard_fils_senc/hero_e6bfda95-2d53-4c47-930b-848f8db05126.png",
  "services": {
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442959/tapavis_tenant_garage_pinard_fils_senc/silencieux_f8999eb2-83a1-434f-abec-cbb58ac5a679.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442962/tapavis_tenant_garage_pinard_fils_senc/systeme-de-refroidissement_115ed6f9-19bf-457e-bfb4-8bdea9838a58.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442962/tapavis_tenant_garage_pinard_fils_senc/systeme-electrique_a3081542-a219-47fc-8d88-1d1bf6627ba6.png",
    "injection": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442969/tapavis_tenant_garage_pinard_fils_senc/injection_fec29f85-5cfc-4ccc-960e-40e5d1f7eee1.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442973/tapavis_tenant_garage_pinard_fils_senc/suspension_635fdf36-e53f-4c39-ba11-80c599efc512.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442973/tapavis_tenant_garage_pinard_fils_senc/mise-au-point_49d384ba-a6b3-4a72-9401-e318c59be518.png",
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442974/tapavis_tenant_garage_pinard_fils_senc/batterie-demarreur-alternateur_fb300a2c-dee4-45b1-8f32-6a40b5a8446e.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442981/tapavis_tenant_garage_pinard_fils_senc/inspection-mecanique_f4a08eeb-6169-4814-a00c-52214d28cdd0.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442983/tapavis_tenant_garage_pinard_fils_senc/entretien-preventif_ed9bcd61-40c7-47e3-bed1-3dac04d76d4e.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790442984/tapavis_tenant_garage_pinard_fils_senc/vidange-huile_f22c87e7-9f62-4849-a487-cf66adafe3a9.png"
  }
};
