/**
 * Garage Melkon C. — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "freins",
    "icon": "brake",
    "duration_min": 90,
    "bookable": 1,
    "featured": 1,
    "name": "Freins",
    "name_en": "Brakes",
    "tagline": "Plaquettes, disques, étriers et liquide : des freins qui répondent.",
    "tagline_en": "Pads, rotors, calipers and fluid: brakes that answer.",
    "body": "Les freins s’usent un peu à chaque arrêt. L’inspection mesure les plaquettes et les disques, vérifie les étriers, les conduites et le liquide de frein, puis vous dit ce qui est usé, ce qui peut attendre et ce qui presse.\nLe sel et les hivers québécois sont durs pour les étriers et les conduites : un bruit ou une vibration au freinage mérite d’être vérifié rapidement.",
    "body_en": "Brakes wear a little at every stop. The inspection measures the pads and rotors, checks the calipers, lines and brake fluid, then tells you what is worn, what can wait and what is urgent.\nSalt and Québec winters are hard on calipers and lines: a noise or vibration when braking deserves a quick check.",
    "signs": "[\"Grincement ou sifflement au freinage\",\"Vibration dans la pédale ou le volant\",\"La pédale est molle ou descend plus bas\",\"Le véhicule tire d’un côté au freinage\"]",
    "signs_en": "[\"Squealing or grinding when braking\",\"Vibration in the pedal or steering wheel\",\"The pedal feels soft or sinks lower\",\"The vehicle pulls to one side when braking\"]",
    "confirmed": 1
  },
  {
    "slug": "pneus",
    "icon": "wheel",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Vente et pose de pneus",
    "name_en": "Tire sales and mounting",
    "tagline": "Pneus neufs, pose et balancement.",
    "tagline_en": "New tires, mounting and balancing.",
    "body": "Au changement de saison ou quand l’usure l’exige, les pneus sont montés sur les jantes, balancés et installés, puis la pression est ajustée. Demandez conseil pour choisir des pneus adaptés à votre véhicule et à votre conduite.",
    "body_en": "At the seasonal change or when wear calls for it, tires are mounted on the rims, balanced and installed, and the pressure is set. Ask for advice to choose tires suited to your vehicle and driving.",
    "signs": "[\"Changement de saison\", \"Témoin d’usure atteint\", \"Vibration à haute vitesse\", \"Flanc fissuré ou bosselé\"]",
    "signs_en": "[\"Change of season\", \"Tread-wear bar reached\", \"Vibration at highway speed\", \"Cracked or bulging sidewall\"]",
    "confirmed": 1
  },
  {
    "slug": "silencieux",
    "icon": "exhaust",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Silencieux et échappement",
    "name_en": "Muffler & exhaust",
    "tagline": "Un échappement étanche, silencieux et conforme.",
    "tagline_en": "An exhaust that is sealed, quiet and compliant.",
    "body": "Le sel de nos hivers est dur pour l’échappement. Un silencieux percé ou un tuyau rouillé rend la voiture bruyante et peut laisser entrer des gaz dans l’habitacle. L’inspection couvre le silencieux, les tuyaux, les supports et les joints.",
    "body_en": "Winter road salt is hard on an exhaust. A holed muffler or a rusted pipe makes the car loud and can let fumes into the cabin. The inspection covers the muffler, pipes, hangers and gaskets.",
    "signs": "[\"Grondement plus fort qu’avant\",\"Cliquetis sous le véhicule\",\"Odeur de gaz d’échappement dans l’habitacle\"]",
    "signs_en": "[\"A louder rumble than before\",\"Rattling under the car\",\"Exhaust smell inside the cabin\"]",
    "confirmed": 1
  },
  {
    "slug": "alignement",
    "icon": "wheel",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Alignement des roues",
    "name_en": "Wheel alignment",
    "tagline": "Une auto qui roule droit et des pneus qui durent.",
    "tagline_en": "A car that tracks straight and tires that last.",
    "body": "L’alignement règle l’angle des roues selon les données du fabricant. Un nid-de-poule, un choc contre une bordure ou des pièces de suspension usées suffisent à le dérégler : le véhicule tire d’un côté et les pneus s’usent de façon inégale. On le vérifie aussi après le remplacement de pièces de direction ou de suspension.",
    "body_en": "An alignment sets the wheel angles to the maker’s specifications. A pothole, a hit against a curb or worn suspension parts are enough to throw it off: the car pulls to one side and the tires wear unevenly. It is also checked after steering or suspension parts are replaced.",
    "signs": "[\"Le véhicule tire d’un côté\", \"Volant décentré en ligne droite\", \"Usure inégale des pneus\", \"Après un choc contre une bordure\"]",
    "signs_en": "[\"The car pulls to one side\", \"Steering wheel off-centre when driving straight\", \"Uneven tire wear\", \"After hitting a curb\"]",
    "confirmed": 1
  },
  {
    "slug": "suspension",
    "icon": "spring",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Suspension",
    "name_en": "Suspension",
    "tagline": "Amortisseurs, ressorts, rotules : stabilité et confort.",
    "tagline_en": "Shocks, springs, ball joints: stability and comfort.",
    "body": "Nids-de-poule et routes bosselées usent vite la suspension. Des amortisseurs fatigués allongent les distances de freinage et usent les pneus. L’inspection vérifie amortisseurs, ressorts, rotules, biellettes et bras de suspension.",
    "body_en": "Potholes and rough roads wear a suspension quickly. Tired shocks lengthen braking distances and wear tires. The inspection covers shocks, springs, ball joints, links and control arms.",
    "signs": "[\"Cognements dans les bosses\",\"Le véhicule tire d’un côté\",\"Le nez plonge au freinage\",\"Rebonds après une bosse\"]",
    "signs_en": "[\"Clunks over bumps\",\"The car pulls to one side\",\"The nose dives when braking\",\"Bouncing after a bump\"]",
    "confirmed": 1
  },
  {
    "slug": "diagnostic-electronique",
    "icon": "spark",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Diagnostic électronique",
    "name_en": "Electronic diagnostics",
    "tagline": "Voyants, codes d’erreur, capteurs.",
    "tagline_en": "Warning lights, fault codes, sensors.",
    "body": "Un voyant allumé enregistre un code d’erreur dans l’ordinateur du véhicule. Le diagnostic lit ces codes avec un lecteur adapté, puis vérifie les capteurs, le câblage et les composants en cause, pour réparer la bonne pièce plutôt que de deviner.",
    "body_en": "A warning light stores a fault code in the vehicle’s computer. Diagnostics read those codes with a proper scan tool, then check the sensors, wiring and parts involved, so the right part gets fixed instead of guessing.",
    "signs": "[\"Voyant moteur ou ABS allumé\", \"Perte de puissance\", \"Démarrage difficile\", \"Consommation qui augmente\"]",
    "signs_en": "[\"Check-engine or ABS light on\", \"Loss of power\", \"Hard starting\", \"Rising fuel use\"]",
    "confirmed": 1
  },
  {
    "slug": "climatisation",
    "icon": "snow",
    "duration_min": 90,
    "bookable": 1,
    "featured": 0,
    "name": "Entretien de la climatisation",
    "name_en": "Air conditioning service",
    "tagline": "De l’air froid l’été, un pare-brise qui désembue l’hiver.",
    "tagline_en": "Cold air in summer, a windshield that clears in winter.",
    "body": "La climatisation ne sert pas qu’en juillet : elle assèche l’air et aide le pare-brise à désembuer par temps froid et humide. L’entretien vérifie la charge de réfrigérant, cherche les fuites et contrôle le compresseur et le filtre d’habitacle.",
    "body_en": "Air conditioning is not only for July: it dries the air and helps clear the windshield in cold, damp weather. The service checks the refrigerant charge, looks for leaks and checks the compressor and cabin filter.",
    "signs": "[\"L’air ne refroidit plus comme avant\",\"Odeur d’humidité à la mise en marche\",\"Le pare-brise désembue mal\",\"Bruit quand la climatisation démarre\"]",
    "signs_en": "[\"The air is not as cold as it used to be\",\"A musty smell when it starts\",\"The windshield clears poorly\",\"A noise when the A/C kicks in\"]",
    "confirmed": 1
  },
  {
    "slug": "remorquage",
    "icon": "tow",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "option": "towing",
    "name": "Remorquage",
    "name_en": "Towing",
    "tagline": "Le véhicule ne roule plus? Appelez le garage.",
    "tagline_en": "Car won’t move? Call the garage.",
    "body": "En panne à Saint-Hubert ou dans les environs? Appelez directement le garage. Au moment de réserver, vous pouvez aussi indiquer que le véhicule doit être remorqué et l’adresse où il se trouve : le garage vous rappelle pour organiser la prise en charge.",
    "body_en": "Broken down in Saint-Hubert or nearby? Call the garage directly. When booking, you can also say the vehicle needs a tow and where it is: the garage calls you back to arrange the pickup.",
    "signs": "[\"Le véhicule ne démarre plus\", \"Voyant rouge ou surchauffe sur la route\", \"Accident ou crevaison sans roue de secours\"]",
    "signs_en": "[\"The car will not start\", \"A red warning light or overheating on the road\", \"An accident or a flat without a spare\"]",
    "confirmed": 1
  },
  {
    "slug": "antirouille",
    "icon": "oil",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Traitement antirouille",
    "name_en": "Rustproofing",
    "tagline": "Protéger le dessous du véhicule contre le sel.",
    "tagline_en": "Protect the underbody from road salt.",
    "body": "Le sel et le calcium de nos routes attaquent le dessous des véhicules. Un traitement antirouille appliqué chaque année, idéalement à l’automne, protège le châssis, les bas de caisse et les conduites.",
    "body_en": "Salt and calcium on our roads attack the underside of vehicles. A rustproofing treatment applied every year, ideally in the fall, protects the frame, rocker panels and lines.",
    "signs": "[\"Avant l’hiver\", \"Taches de rouille sur le châssis\", \"Véhicule neuf ou récent\", \"Bas de caisse qui bullent\"]",
    "signs_en": "[\"Before winter\", \"Rust spots on the frame\", \"A new or recent vehicle\", \"Bubbling rocker panels\"]",
    "confirmed": 1
  }
];
