/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_laurier_leclerc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961743/tapavis_tenant_garage_laurier_leclerc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961743/tapavis_tenant_garage_laurier_leclerc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961761/tapavis_tenant_garage_laurier_leclerc/hero_67bc54c5-e05f-4956-af38-f4894c277f79.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961759/tapavis_tenant_garage_laurier_leclerc/mecanique-generale_764a3606-3d67-47cb-9d2e-49e341ec41d9.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790961759/tapavis_tenant_garage_laurier_leclerc/vidange-huile_b7700c68-dbab-4e3b-83ca-58f36d52a8b9.webp",
    "freins": "https://media.liasse.tech/upload/v1790961763/tapavis_tenant_garage_laurier_leclerc/freins_0e734150-56ca-4845-8f6a-3b924f5ec8eb.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961769/tapavis_tenant_garage_laurier_leclerc/equilibrage-rotation-pneus_2419e788-24bf-4b4a-9f90-35c42966087a.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961769/tapavis_tenant_garage_laurier_leclerc/suspension_d791cd44-ce95-494f-97f9-07807c12c9ec.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961770/tapavis_tenant_garage_laurier_leclerc/silencieux_cf35370f-92a5-40b8-9a42-9f7558788655.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961775/tapavis_tenant_garage_laurier_leclerc/systeme-de-refroidissement_2eecdb3b-983d-434e-9478-86b59e15f1d0.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961779/tapavis_tenant_garage_laurier_leclerc/mise-au-point_866c86c7-c0c8-4fdb-a433-9700cc9b9562.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961781/tapavis_tenant_garage_laurier_leclerc/climatisation_d571ca85-caf7-4e82-abf0-7b4d80835c98.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961782/tapavis_tenant_garage_laurier_leclerc/transmission_fd30c888-d604-416d-b565-1ab7c360c875.webp"
  }
};
