/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_luc_cote_et_fils_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732187/tapavis_tenant_garage_luc_cote_et_fils_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732187/tapavis_tenant_garage_luc_cote_et_fils_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732200/tapavis_tenant_garage_luc_cote_et_fils_inc/hero_45184c1e-e985-4653-a321-c08e4d956b0e.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732200/tapavis_tenant_garage_luc_cote_et_fils_inc/freins_da2e2e3b-0f4b-46d1-90ce-818aa32b4375.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732200/tapavis_tenant_garage_luc_cote_et_fils_inc/vidange-huile_07577e0d-a42c-4f7d-8715-4f0f7a54a317.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732203/tapavis_tenant_garage_luc_cote_et_fils_inc/mecanique-generale_9ecf73dc-d6c8-4750-87a1-588914697069.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732211/tapavis_tenant_garage_luc_cote_et_fils_inc/silencieux_236bd134-1bdc-4183-8c0b-c21c831475c8.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732212/tapavis_tenant_garage_luc_cote_et_fils_inc/equilibrage-rotation-pneus_f0ae4498-35d5-4094-8420-93d0c6488980.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732212/tapavis_tenant_garage_luc_cote_et_fils_inc/suspension_d74b7ef9-579a-4dde-aab0-6a1e518ecb58.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732216/tapavis_tenant_garage_luc_cote_et_fils_inc/systeme-de-refroidissement_a43a9946-f965-420e-a704-54de08824bbd.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732222/tapavis_tenant_garage_luc_cote_et_fils_inc/climatisation_fb195761-7bb5-40d7-9795-d0a82af10f96.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732224/tapavis_tenant_garage_luc_cote_et_fils_inc/mise-au-point_5613cf76-fba9-4905-bf69-aa5b7f049f2e.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732224/tapavis_tenant_garage_luc_cote_et_fils_inc/transmission_36f1da33-9115-4d9b-ab9c-6978a4131ffd.png"
  }
};
