/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_la_perseverance).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624126/tapavis_tenant_garage_la_perseverance/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624126/tapavis_tenant_garage_la_perseverance/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624138/tapavis_tenant_garage_la_perseverance/hero_40e0432a-d85d-456e-ba7c-ea0a8673b1ef.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624136/tapavis_tenant_garage_la_perseverance/freins_6da8cba6-2fca-4815-82cd-d63ba30e6696.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624136/tapavis_tenant_garage_la_perseverance/vidange-huile_a369b114-c232-4c34-9573-62106046c75d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624138/tapavis_tenant_garage_la_perseverance/mecanique-generale_d33b4074-0b12-41ae-ba98-b9685e5eade9.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624147/tapavis_tenant_garage_la_perseverance/silencieux_2004c1f3-be2f-4fb1-a963-bbe4a43cd8e1.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624148/tapavis_tenant_garage_la_perseverance/suspension_ffac31a1-846b-48cf-8549-49670e44e2b7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624150/tapavis_tenant_garage_la_perseverance/equilibrage-rotation-pneus_7af5ea45-061c-4302-b2e7-836f77fad20e.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624151/tapavis_tenant_garage_la_perseverance/systeme-de-refroidissement_aa68bce5-6f9f-4499-8c50-7d0071437db4.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624157/tapavis_tenant_garage_la_perseverance/climatisation_2db57d50-1b69-4e08-a63d-23a97f80c239.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624160/tapavis_tenant_garage_la_perseverance/mise-au-point_81a1fa1e-fa2a-40c9-a242-d7f19442864b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624162/tapavis_tenant_garage_la_perseverance/transmission_d97f3203-75b5-4078-816e-257d2f4b6c52.png"
  }
};
