module.exports = async function(db) {
const settings={tagline:'Démonstration interne',hero_title:'Laboratoire de validation',hero_subtitle:'Un site interne pour éprouver notre constructeur de sites.',about_text:'Ce site est un support de démonstration interne de Liasse. Il sert à essayer notre constructeur de sites.'};
for(const [key,value] of Object.entries(settings))await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[key,value]);
await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',['_p_hero_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1789508413/tapavis_tenant_liasse-pipeline-validation-20260915/build_liasse-pipeline-validation-20260915_6bd5bf0c-1bf2-4f0f-8b37-dd238dedab4f.png']);
const rows=[
['home-intro','home','intro','Laboratoire de validation','Validation Lab','Un site interne pour éprouver notre constructeur de sites.','An internal site for testing our website builder.','none',10],
['home-scope','home','scope','Périmètre','Scope','Deux pages publiques, deux langues et un éditeur de contenu.','Two public pages, two languages and a content editor.','none',20],
['initial-build','home','card','Création initiale','Initial build','Examiner la structure, les titres et les contenus produits au premier passage.','Review the structure, headings and content produced in the first build.','document',30],
['mobile-check','home','card','Vérification mobile','Mobile check','Observer la navigation et la lisibilité sur un écran étroit.','Check navigation and readability on a narrow screen.','phone',40],
['accessibility','home','card','Accessibilité','Accessibility','Vérifier les contrastes, le parcours clavier et la hiérarchie des titres.','Check contrast, keyboard navigation and heading hierarchy.','focus',50],
['home-limit','home','note','','','Ces rubriques décrivent des essais à effectuer, pas des résultats de validation.','These topics describe checks to perform, not validation results.','none',60],
['about-intro','about','intro','À propos du laboratoire','About the lab','Ce site est un support de démonstration interne de Liasse. Il sert à essayer notre constructeur de sites.','This site is an internal Liasse demonstration. It is used to test our website builder.','none',10],
['about-examine','about','card','Ce que nous examinons','What we examine','Nous examinons la création initiale, l’affichage sur mobile et les contrôles d’accessibilité. Ces rubriques indiquent des essais à effectuer, sans annoncer de résultat.','We examine the initial build, the mobile display and accessibility checks. These topics describe checks to perform without reporting a result.','document',20],
['about-edit','about','card','Ce que nous modifions','What we edit','Les titres et les paragraphes sont éditables en français et en anglais. L’éditeur local permet d’essayer des textes dans ce navigateur ; les modules d’administration modifient les contenus partagés.','Headings and paragraphs can be edited in French and English. The local editor lets you try text in this browser; administration modules change shared content.','phone',30],
['about-not','about','card','Ce que ce site n’est pas','What this site is not','Ce site n’est ni une offre commerciale ni un rapport de certification. Il ne présente aucun client, témoignage, prix ou résultat de validation.','This site is neither a commercial offer nor a certification report. It presents no clients, testimonials, prices or validation results.','focus',40],
['about-scope','about','scope','Hors périmètre','Outside the scope','Aucun formulaire de contact, envoi de courriel, paiement ou service externe.','No contact forms, email sending, payments or external services.','none',50]
];
for(const row of rows)await db.run('INSERT INTO lab_content (content_key,page,area,title,title_en,content,content_en,icon,sort_order) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (content_key) DO NOTHING',row);
const posts=[
['Préparer une création initiale','Décrire les deux pages attendues, les langues et les contenus à rendre éditables. Conserver le périmètre de démonstration dans la description.','https://res.cloudinary.com/duhp69meg/image/upload/v1789508412/tapavis_tenant_liasse-pipeline-validation-20260915/build_liasse-pipeline-validation-20260915_cb60a464-f40d-47f3-a56e-80e630f29254.png','Construction'],
['Observer une navigation mobile','Ouvrir les deux pages sur un écran étroit. Examiner le menu, les liens de langue et la lisibilité. Cette note ne contient aucun résultat de test.','https://res.cloudinary.com/duhp69meg/image/upload/v1789508411/tapavis_tenant_liasse-pipeline-validation-20260915/build_liasse-pipeline-validation-20260915_c552f271-723c-490d-b247-82dfa2402afb.png','Navigation'],
['Examiner le parcours clavier','Parcourir les liens et les boutons au clavier. Observer le focus et la hiérarchie des titres sans transformer ces observations en certification.','https://res.cloudinary.com/duhp69meg/image/upload/v1789508415/tapavis_tenant_liasse-pipeline-validation-20260915/build_liasse-pipeline-validation-20260915_a3396114-ad21-49d4-aa31-4a01e152e018.png','Accessibilité'],
['Maintenir une identité interne','Conserver les mentions de démonstration interne et distinguer clairement les essais locaux des modifications partagées.','https://res.cloudinary.com/duhp69meg/image/upload/v1789508414/tapavis_tenant_liasse-pipeline-validation-20260915/build_liasse-pipeline-validation-20260915_46648c09-5a00-4465-b8dd-f9c764354bcd.png','Périmètre']
];
for(const row of posts)await db.run('INSERT INTO posts (title,content,image_url,category,published) SELECT $1,$2,$3,$4,0 WHERE NOT EXISTS (SELECT 1 FROM posts WHERE title=$1)',row);
};