/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_p_mansourati).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624677/tapavis_tenant_garage_p_mansourati/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624677/tapavis_tenant_garage_p_mansourati/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624688/tapavis_tenant_garage_p_mansourati/hero_37a3c1fd-2bb1-4cc2-841e-a151647eda6c.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624687/tapavis_tenant_garage_p_mansourati/vidange-huile_6151ee46-0720-49c6-a931-31b81d3997f6.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624688/tapavis_tenant_garage_p_mansourati/freins_06239c20-13c6-4e62-bbff-2f8904a319c5.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624689/tapavis_tenant_garage_p_mansourati/mecanique-generale_a7da268e-aff2-4611-a38b-48e6169826d6.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624698/tapavis_tenant_garage_p_mansourati/silencieux_945ae16f-0083-4ec8-a9e0-77b796912197.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624698/tapavis_tenant_garage_p_mansourati/suspension_42631665-cad3-430e-87a3-7bd19f3199a4.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624700/tapavis_tenant_garage_p_mansourati/equilibrage-rotation-pneus_c0ceb569-d07a-4e41-8eb0-9c30d274b417.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624702/tapavis_tenant_garage_p_mansourati/systeme-de-refroidissement_6c986696-738e-465c-855e-f28cd758c131.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624709/tapavis_tenant_garage_p_mansourati/climatisation_197a861b-f75f-414e-a680-71a4adef7bfe.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624712/tapavis_tenant_garage_p_mansourati/mise-au-point_2cdd9d0f-286b-410a-a1c1-f586fb3f35bb.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624714/tapavis_tenant_garage_p_mansourati/transmission_e511da14-4054-433e-9975-1326487cc7bc.png"
  }
};
