/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_alain_plante_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554114/tapavis_tenant_garage_alain_plante_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554114/tapavis_tenant_garage_alain_plante_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554128/tapavis_tenant_garage_alain_plante_inc/hero_fd6c25b3-9056-471e-9684-465b9a47313b.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554125/tapavis_tenant_garage_alain_plante_inc/vidange-huile_1fb6e046-7104-4eba-957b-3a0960c12f46.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554126/tapavis_tenant_garage_alain_plante_inc/freins_7f9bc814-bf9c-479f-b46a-bce04877849d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554129/tapavis_tenant_garage_alain_plante_inc/mecanique-generale_90b7aaf2-f400-40bc-aaab-ca749ccf39b2.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554136/tapavis_tenant_garage_alain_plante_inc/equilibrage-rotation-pneus_f7eccc1b-3aed-4569-b9aa-95ff894cf8cc.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554137/tapavis_tenant_garage_alain_plante_inc/silencieux_57a9a232-15ba-459d-a992-fc977253ec08.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554139/tapavis_tenant_garage_alain_plante_inc/suspension_d8e7e864-4430-4e43-9fba-f5c12ddfc9c0.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554143/tapavis_tenant_garage_alain_plante_inc/systeme-de-refroidissement_79c144ee-7e05-4638-99ba-c40fc00937b4.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554148/tapavis_tenant_garage_alain_plante_inc/mise-au-point_f172dfbc-b9af-4695-bfe9-f3c7c65f85f6.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554149/tapavis_tenant_garage_alain_plante_inc/climatisation_f18557f5-1b50-43fd-8117-ae6787efe9c4.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554151/tapavis_tenant_garage_alain_plante_inc/transmission_ea05d565-30d7-445b-b4ad-b25a30c5fd5a.png"
  }
};
