/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_f_et_f_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666817/tapavis_tenant_garage_f_et_f_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666817/tapavis_tenant_garage_f_et_f_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666829/tapavis_tenant_garage_f_et_f_inc/hero_0672aee5-d926-4f4f-9366-cfe43e1e026f.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666829/tapavis_tenant_garage_f_et_f_inc/freins_13c0eb6f-c159-422c-afbc-56804d45d133.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666829/tapavis_tenant_garage_f_et_f_inc/mecanique-generale_b8648414-3366-4ae4-a3fd-7b84cc2c1d51.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666829/tapavis_tenant_garage_f_et_f_inc/vidange-huile_3cc5b8e7-f2ca-4091-8039-9fc287438a89.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666839/tapavis_tenant_garage_f_et_f_inc/silencieux_c55dbfb1-f81b-4dda-9314-e21721dd8061.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666840/tapavis_tenant_garage_f_et_f_inc/suspension_e598de3e-df99-4882-99fe-5ee5d0c85897.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666841/tapavis_tenant_garage_f_et_f_inc/equilibrage-rotation-pneus_572dffde-610b-4b36-a0a9-fbcdb12c73df.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666842/tapavis_tenant_garage_f_et_f_inc/systeme-de-refroidissement_a2b1b47d-b43e-4347-b849-ec407aef5506.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666852/tapavis_tenant_garage_f_et_f_inc/mise-au-point_8eed1f02-538e-4e13-84f3-e4a3d36d89ce.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666852/tapavis_tenant_garage_f_et_f_inc/climatisation_26a00710-af43-444b-bb0f-76d94efb18fb.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666852/tapavis_tenant_garage_f_et_f_inc/transmission_fcf63ac3-ae69-4f71-9b6e-da9356f0df2f.png"
  }
};
