/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_rpm_charles_mercier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961236/tapavis_tenant_rpm_charles_mercier/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961236/tapavis_tenant_rpm_charles_mercier/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961252/tapavis_tenant_rpm_charles_mercier/hero_55419a7d-cf19-4e00-ae3f-bebfde7edf55.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790961253/tapavis_tenant_rpm_charles_mercier/freins_d6e4892c-a73b-48b8-9382-2b09bb3c47db.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790961253/tapavis_tenant_rpm_charles_mercier/vidange-huile_1f2316a7-e942-4b90-851f-d24a2d4aaeff.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961255/tapavis_tenant_rpm_charles_mercier/mecanique-generale_7e5368b4-af62-4f7d-b75a-1051c069af1b.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961264/tapavis_tenant_rpm_charles_mercier/silencieux_36f9e3e3-6642-4677-8ced-942581e1fbd4.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961264/tapavis_tenant_rpm_charles_mercier/equilibrage-rotation-pneus_03afc641-fe7f-445c-b32a-0b50b65dd6f6.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961265/tapavis_tenant_rpm_charles_mercier/suspension_6f21c576-40e7-406c-a987-922d211be059.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961267/tapavis_tenant_rpm_charles_mercier/systeme-de-refroidissement_62440266-af25-4e2d-9c0e-c24a0a3862ee.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961276/tapavis_tenant_rpm_charles_mercier/climatisation_3cfabc0d-2dbb-468d-ac23-9a5d63078332.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961276/tapavis_tenant_rpm_charles_mercier/mise-au-point_127c769e-5f75-4c99-9648-32acf0fb173c.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961276/tapavis_tenant_rpm_charles_mercier/transmission_05dff856-76a8-48e5-8913-369e290b608b.webp"
  }
};
