const S=require('./settings');
function cents(value){if(!/^\d+\.\d{2}$/.test(String(value)))return NaN;return Number(String(value).replace('.',''));}
function verifyOrder(order,b,merchant){const units=order.purchase_units||[],u=units[0];if(order.id!==b.paypal_order_id||order.intent!=='CAPTURE'||units.length!==1||!u||u.custom_id!=='appointment:'+b.id||u.invoice_id!==b.order_key||!u.amount||u.amount.currency_code!=='CAD'||cents(u.amount.value)!==Number(b.amount_cents)||!u.payee||u.payee.merchant_id!==merchant)throw S.error('paypal_mismatch',409);return u;}
function base64(s){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';let out='';for(let i=0;i<s.length;i+=3){const x=s.charCodeAt(i),y=s.charCodeAt(i+1),z=s.charCodeAt(i+2);out+=a[x>>2]+a[((x&3)<<4)|(Number.isNaN(y)?0:y>>4)]+(Number.isNaN(y)?'=':a[((y&15)<<2)|(Number.isNaN(z)?0:z>>6)])+(Number.isNaN(z)?'=':a[z&63]);}return out;}
module.exports=function(services){const db=services.db;const busy=new Set();
function config(){const client=services.externalVars.PAYPAL_CLIENT_ID;const secret=services.externalVars.PAYPAL_CLIENT_SECRET;const mode=services.externalVars.PAYPAL_MODE;const merchant=services.externalVars.PAYPAL_MERCHANT_ID;if(!client||!secret||!mode||!merchant)throw S.error('paypal_setup',503);if(!['sandbox','live'].includes(mode))throw S.error('invalid',503);return {client,secret,mode,merchant,base:mode==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com'};}
function ready(){try{config();return true;}catch(e){return false;}}
function enabled(raw,preview){return !preview&&S.flag(raw,'payments_enabled')&&S.flag(raw,'payment_terms_approved')&&S.flag(raw,'live_actions_enabled')&&S.both(raw.payment_terms)&&ready();}
function eligible(b,raw,preview){return enabled(raw,preview)&&b.status==='confirmed'&&!b.cancel_requested&&!!b.billing_verified&&Number(b.amount_cents)>0&&!['paid','pending','refunded','partially_refunded','denied'].includes(b.payment_status);}
async function transport(url,options){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await services.fetch(url,Object.assign({},options,{signal:controller.signal}));let data={};try{data=await response.json();}catch(e){}if(!response.ok){const issue=(data.details&&data.details[0]&&data.details[0].issue)||data.name||data.error||'UPSTREAM_ERROR';throw S.error(response.status===429?'rate_limit':'paypal_provider',response.status===429?429:502,/^[A-Z0-9_]+$/i.test(issue)?String(issue).toUpperCase():'UPSTREAM_ERROR');}return data;}catch(e){if(e.name==='AbortError')throw S.error('paypal_timeout',504);if(e.code&&e.status)throw e;throw S.error('paypal_timeout',502);}finally{clearTimeout(timer);}}
async function call(c,path,method='GET',body,key){const auth=await transport(c.base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+base64(c.client+':'+c.secret),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials'});if(!auth.access_token)throw S.error('paypal_provider',502,'TOKEN_MISSING');const headers={Authorization:'Bearer '+auth.access_token,'Content-Type':'application/json',Prefer:'return=representation'};if(key)headers['PayPal-Request-Id']=key;return await transport(c.base+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})});}
function checkConfig(b,c){if(b.paypal_mode!==c.mode||b.paypal_client_hash!==services.crypto.sha256(c.client))throw S.error('manual_reconcile',409);}
async function sync(b){if(!b.paypal_order_id)return b;const c=config();checkConfig(b,c);const order=await call(c,'/v2/checkout/orders/'+encodeURIComponent(b.paypal_order_id));const unit=verifyOrder(order,b,c.merchant);const captures=(unit.payments&&unit.payments.captures)||[];let status='initiated',capture=null;if(captures.length>1)throw S.error('paypal_mismatch',409);if(captures.length){capture=await call(c,'/v2/payments/captures/'+encodeURIComponent(captures[0].id));if(capture.id!==captures[0].id||!capture.amount||capture.amount.currency_code!=='CAD'||cents(capture.amount.value)!==Number(b.amount_cents)||capture.final_capture!==true)throw S.error('paypal_mismatch',409);const related=capture.supplementary_data&&capture.supplementary_data.related_ids;if(related&&related.order_id&&related.order_id!==b.paypal_order_id)throw S.error('paypal_mismatch',409);const map={COMPLETED:'paid',PENDING:'pending',DECLINED:'denied',DENIED:'denied',FAILED:'denied',REFUNDED:'refunded',PARTIALLY_REFUNDED:'partially_refunded'};status=map[capture.status]||'pending';if(status==='paid'&&order.status!=='COMPLETED')status='pending';}else if(order.status==='VOIDED')status='denied';return await db.get('UPDATE appointments SET payment_status=$1,paypal_capture_id=COALESCE($2,paypal_capture_id),paid_at=CASE WHEN $1 IN (\'paid\',\'refunded\',\'partially_refunded\') THEN COALESCE(paid_at,NOW()) ELSE paid_at END,checked_at=NOW(),updated_at=NOW() WHERE id=$3 RETURNING *',[status,capture?capture.id:null,b.id]);}
async function exclusive(id,fn){if(busy.has(String(id)))throw S.error('conflict',409);busy.add(String(id));try{return await fn();}finally{busy.delete(String(id));}}
async function create(b,raw,preview,body){return await exclusive(b.id,async()=>{b=await db.get('SELECT * FROM appointments WHERE id=$1',[b.id]);if(!eligible(b,raw,preview))throw S.error('pay_unavailable',409);if(body.accept_terms!==true)throw S.error('required');const c=config();if(b.paypal_order_id){checkConfig(b,c);const order=await call(c,'/v2/checkout/orders/'+encodeURIComponent(b.paypal_order_id));verifyOrder(order,b,c.merchant);if(!['CREATED','SAVED','APPROVED','PAYER_ACTION_REQUIRED'].includes(order.status)){await sync(b);throw S.error('conflict',409);}return {orderId:b.paypal_order_id};}if(!b.order_key){if(String(body.version)!==new Date(b.updated_at).toISOString())throw S.error('conflict',409);const locked=await db.get("UPDATE appointments SET order_key=$1,capture_key=$2,paypal_mode=$3,paypal_client_hash=$4,order_started_at=NOW(),payment_status='initiated',updated_at=NOW() WHERE id=$5 AND order_key IS NULL AND updated_at=$6 AND status='confirmed' AND cancel_requested=0 RETURNING *",[services.crypto.randomUUID(),services.crypto.randomUUID(),c.mode,services.crypto.sha256(c.client),b.id,b.updated_at]);if(!locked)throw S.error('conflict',409);b=locked;}checkConfig(b,c);if(Date.now()-new Date(b.order_started_at).getTime()>5*3600000)throw S.error('manual_reconcile',409);const value=(Number(b.amount_cents)/100).toFixed(2),tax=(Number(b.tax_cents)/100).toFixed(2),net=((Number(b.amount_cents)-Number(b.tax_cents))/100).toFixed(2);const order=await call(c,'/v2/checkout/orders','POST',{intent:'CAPTURE',purchase_units:[{reference_id:String(b.id),custom_id:'appointment:'+b.id,invoice_id:b.order_key,description:'Sens-O-Reel appointment '+b.id,payee:{merchant_id:c.merchant},amount:{currency_code:'CAD',value,breakdown:{item_total:{currency_code:'CAD',value:net},tax_total:{currency_code:'CAD',value:tax}}}}],payment_source:{paypal:{experience_context:{shipping_preference:'NO_SHIPPING',user_action:'PAY_NOW'}}}},b.order_key);if(!order.id||!/^[A-Z0-9]+$/.test(order.id))throw S.error('paypal_provider',502,'ORDER_ID_MISSING');await db.run('UPDATE appointments SET paypal_order_id=$1,updated_at=NOW() WHERE id=$2 AND order_key=$3',[order.id,b.id,b.order_key]);return {orderId:order.id};});}
async function capture(b,raw,preview,body){return await exclusive(b.id,async()=>{b=await db.get('SELECT * FROM appointments WHERE id=$1',[b.id]);if(!enabled(raw,preview))throw S.error('pay_unavailable',503);if(!b.paypal_order_id||body.orderId!==b.paypal_order_id)throw S.error('paypal_mismatch',409);const c=config();checkConfig(b,c);const order=await call(c,'/v2/checkout/orders/'+encodeURIComponent(b.paypal_order_id));const unit=verifyOrder(order,b,c.merchant);if(unit.payments&&unit.payments.captures&&unit.payments.captures.length)return await sync(b);if(b.status!=='confirmed'||b.cancel_requested)throw S.error('pay_unavailable',409);if(order.status!=='APPROVED')throw S.error('pay_pending',409);try{await call(c,'/v2/checkout/orders/'+encodeURIComponent(b.paypal_order_id)+'/capture','POST',{},b.capture_key);}catch(e){try{const recovered=await sync(b);if(['paid','pending','refunded','partially_refunded'].includes(recovered.payment_status))return recovered;}catch(ignored){}throw e;}return await sync(b);});}
function publicConfig(b,raw,preview){if(!eligible(b,raw,preview))return {available:false};const c=config();return {available:true,clientId:c.client,mode:c.mode};}
return {ready,enabled,eligible,create,capture,sync,publicConfig};};
module.exports.verifyOrder=verifyOrder;