/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_transmission_st_anselme).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669057/tapavis_tenant_transmission_st_anselme/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669057/tapavis_tenant_transmission_st_anselme/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669069/tapavis_tenant_transmission_st_anselme/hero_8467c26c-6f9e-47b6-9cf4-40ae31e685ad.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669069/tapavis_tenant_transmission_st_anselme/freins_716a383f-d8f3-4c19-a8d6-9703d4d813d3.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669070/tapavis_tenant_transmission_st_anselme/vidange-huile_7ae5a9f2-3731-4a14-a880-a0c12fe111eb.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669072/tapavis_tenant_transmission_st_anselme/mecanique-generale_f02d638b-5339-44d7-beaf-fd2756c687b5.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669080/tapavis_tenant_transmission_st_anselme/equilibrage-rotation-pneus_08fbbe37-3393-4fda-b788-6085cdaf3c2c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669081/tapavis_tenant_transmission_st_anselme/silencieux_1cf3058a-b099-4aea-a1b7-0e2949891c61.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669082/tapavis_tenant_transmission_st_anselme/suspension_cce0568a-9d80-445a-bdb3-73e1cb547867.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669084/tapavis_tenant_transmission_st_anselme/systeme-de-refroidissement_b608f1ab-0e82-44e2-bb6b-6cfd50b784ae.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669092/tapavis_tenant_transmission_st_anselme/climatisation_e32d5060-4a02-455b-91e2-9da315c4b92d.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669092/tapavis_tenant_transmission_st_anselme/mise-au-point_d4234d71-9f3f-40f0-8f9e-28d98bd5f8fa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669094/tapavis_tenant_transmission_st_anselme/transmission_2999064d-ca72-4b11-8084-f62effb8bb1d.png"
  }
};
