/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_station_service_ouimet_fils).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554045/tapavis_tenant_station_service_ouimet_fils/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554045/tapavis_tenant_station_service_ouimet_fils/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554056/tapavis_tenant_station_service_ouimet_fils/hero_ac9f21a5-db11-410b-9f30-6f58d2e23007.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554057/tapavis_tenant_station_service_ouimet_fils/vidange-huile_c8d9a635-85c4-4bd8-8f36-9004c796e9b6.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554057/tapavis_tenant_station_service_ouimet_fils/freins_4dd0196b-4e98-4c26-9996-235e7fa6c4c0.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554058/tapavis_tenant_station_service_ouimet_fils/mecanique-generale_f867178a-ab3a-4835-8485-a00712dcc020.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554067/tapavis_tenant_station_service_ouimet_fils/equilibrage-rotation-pneus_ae01d28f-8201-480b-ab89-99dfaf86c64a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554068/tapavis_tenant_station_service_ouimet_fils/silencieux_3825c4fc-5723-4a21-9a8e-72ad428c9856.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554068/tapavis_tenant_station_service_ouimet_fils/suspension_bccdebb9-c97a-4989-91c5-b20e0b7679fb.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554071/tapavis_tenant_station_service_ouimet_fils/systeme-de-refroidissement_306a05ed-f242-4751-a9f1-958537a492a2.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554078/tapavis_tenant_station_service_ouimet_fils/mise-au-point_b9c5595a-7240-4f5d-9bc9-380c351f48a2.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554078/tapavis_tenant_station_service_ouimet_fils/climatisation_8098ead4-4114-4ca0-bacc-0fe8b838353c.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790554079/tapavis_tenant_station_service_ouimet_fils/transmission_65a9116c-7e7f-45de-90b1-2b35d4444aca.png"
  }
};
