/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_atelier_mecanique_daaquam).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790972612/tapavis_tenant_atelier_mecanique_daaquam/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790972612/tapavis_tenant_atelier_mecanique_daaquam/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790973921/tapavis_tenant_atelier_mecanique_daaquam/hero_92ad55ca-b13e-432a-bf9a-b1bf6c3954cd.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790972628/tapavis_tenant_atelier_mecanique_daaquam/mecanique-generale_a597dd3a-fd01-4b7e-838b-f0c654e67e09.webp",
    "freins": "https://media.liasse.tech/upload/v1790972628/tapavis_tenant_atelier_mecanique_daaquam/freins_8e2e0999-9278-4b7f-ae0f-ddae5e1200c7.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790972628/tapavis_tenant_atelier_mecanique_daaquam/vidange-huile_b2fe6c40-89df-49ee-99be-38ce384f2b3f.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790972638/tapavis_tenant_atelier_mecanique_daaquam/silencieux_30c066c7-37f3-449a-91d3-0d23173be7b3.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790972638/tapavis_tenant_atelier_mecanique_daaquam/equilibrage-rotation-pneus_c8e22c29-98d7-409b-93e6-3f7deb25f11d.webp",
    "suspension": "https://media.liasse.tech/upload/v1790972638/tapavis_tenant_atelier_mecanique_daaquam/suspension_8d938859-1e2e-4abc-9e8e-ca3452b17f51.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790972639/tapavis_tenant_atelier_mecanique_daaquam/systeme-de-refroidissement_6e7081b1-cd41-4621-991b-7d18819ea97f.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790972648/tapavis_tenant_atelier_mecanique_daaquam/climatisation_783fb938-853b-4835-9620-421a1df8e1b9.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790972649/tapavis_tenant_atelier_mecanique_daaquam/mise-au-point_73b5126f-cd1a-4cef-8c2b-35c09a991135.webp",
    "transmission": "https://media.liasse.tech/upload/v1790972649/tapavis_tenant_atelier_mecanique_daaquam/transmission_c29c6e22-62d2-4183-ac63-865653772919.webp"
  }
};
