/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_mathieu_bourassa_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962158/tapavis_tenant_mathieu_bourassa_mecanique/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962158/tapavis_tenant_mathieu_bourassa_mecanique/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790962173/tapavis_tenant_mathieu_bourassa_mecanique/hero_b70cc43d-bccb-4356-939f-03116d306ad8.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962174/tapavis_tenant_mathieu_bourassa_mecanique/mecanique-generale_e6b06198-a326-4a9b-9641-2af692a9c523.webp",
    "freins": "https://media.liasse.tech/upload/v1790962175/tapavis_tenant_mathieu_bourassa_mecanique/freins_9adca2c4-da44-4387-8bd7-3c4effce891c.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790962176/tapavis_tenant_mathieu_bourassa_mecanique/vidange-huile_28df1d29-b8f3-468a-be69-38548f13a046.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962184/tapavis_tenant_mathieu_bourassa_mecanique/equilibrage-rotation-pneus_d61e89cb-675d-4d44-9c16-7df7d227a69c.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962185/tapavis_tenant_mathieu_bourassa_mecanique/silencieux_09e70e04-2fd9-480e-a4b5-451e8b87abf4.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962185/tapavis_tenant_mathieu_bourassa_mecanique/suspension_eff5ebe9-fb61-40bf-8d60-6bc3b8cd0c11.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962186/tapavis_tenant_mathieu_bourassa_mecanique/systeme-de-refroidissement_15310d7c-b66f-4b39-89b7-0b91e0df9190.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790962195/tapavis_tenant_mathieu_bourassa_mecanique/climatisation_4e79bde9-a30e-45c2-9c4e-515d6b2e9198.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790962195/tapavis_tenant_mathieu_bourassa_mecanique/mise-au-point_45c0b181-49db-43b0-9597-5460f1acdeaf.webp",
    "transmission": "https://media.liasse.tech/upload/v1790962196/tapavis_tenant_mathieu_bourassa_mecanique/transmission_9a80f973-0809-40f2-8437-a2d25fcc5b01.webp"
  }
};
