/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_service_mecanique_bobby_gelinas).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668724/tapavis_tenant_service_mecanique_bobby_gelinas/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668724/tapavis_tenant_service_mecanique_bobby_gelinas/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668734/tapavis_tenant_service_mecanique_bobby_gelinas/hero_e4527e31-0c62-4c6a-b47d-2a354fd2236b.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668733/tapavis_tenant_service_mecanique_bobby_gelinas/freins_7cfd052b-7b73-460a-8157-a8b16bca672e.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668735/tapavis_tenant_service_mecanique_bobby_gelinas/vidange-huile_73f24aaf-9741-476f-9495-749fb0d718b8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668736/tapavis_tenant_service_mecanique_bobby_gelinas/mecanique-generale_55a107bc-a2cc-4503-9010-2bfe934d3874.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668745/tapavis_tenant_service_mecanique_bobby_gelinas/silencieux_34550430-79cb-4dbb-bfd7-6da8f6ebb4fa.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668745/tapavis_tenant_service_mecanique_bobby_gelinas/equilibrage-rotation-pneus_ffb57308-2930-4888-8a98-f1b11fb35af2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668746/tapavis_tenant_service_mecanique_bobby_gelinas/suspension_fe2fc5f1-e27a-4b77-9625-83655545ad89.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668748/tapavis_tenant_service_mecanique_bobby_gelinas/systeme-de-refroidissement_d07f6261-df59-42d3-b13e-3d5cfe45680d.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668757/tapavis_tenant_service_mecanique_bobby_gelinas/mise-au-point_ab14ff19-f9f1-490a-b9d9-1bbbda03b6dd.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668758/tapavis_tenant_service_mecanique_bobby_gelinas/transmission_083d3c1a-7397-4a14-a454-77aff5e7cb2a.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668759/tapavis_tenant_service_mecanique_bobby_gelinas/climatisation_446fc7f4-1dfa-4db9-a61d-f57e6583f561.png"
  }
};
