/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_des_laurentides).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302325/tapavis_tenant_mecanique_des_laurentides/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302325/tapavis_tenant_mecanique_des_laurentides/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302411/tapavis_tenant_mecanique_des_laurentides/hero_b115b015-c9b0-4971-be35-593ffb2ef9b5.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302338/tapavis_tenant_mecanique_des_laurentides/freins_3118a20c-6a8a-465a-b3e1-74933807f355.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302338/tapavis_tenant_mecanique_des_laurentides/vidange-huile_0d2812b6-4413-491e-92c5-1d7b554ca243.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302338/tapavis_tenant_mecanique_des_laurentides/mecanique-generale_c83eee73-c7f8-48c0-b81d-af200727223f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302349/tapavis_tenant_mecanique_des_laurentides/silencieux_00e13015-41b6-4028-a003-3c0161254c66.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302351/tapavis_tenant_mecanique_des_laurentides/systeme-de-refroidissement_60a9ff40-7420-47d2-850f-d1b90170b607.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302351/tapavis_tenant_mecanique_des_laurentides/equilibrage-rotation-pneus_0b70d132-f43d-42e8-af4f-219b25fd279b.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302351/tapavis_tenant_mecanique_des_laurentides/suspension_9a09640c-d131-4f69-8ee9-1ccd8f6dfb90.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302362/tapavis_tenant_mecanique_des_laurentides/climatisation_ad7bdda1-705f-4b14-8d23-1552030d087a.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302362/tapavis_tenant_mecanique_des_laurentides/mise-au-point_bf326b99-0a55-47d3-ada9-680b45f9d516.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790302365/tapavis_tenant_mecanique_des_laurentides/transmission_f5872f8c-2714-4b3a-b5d7-a993afeffb3a.png"
  }
};
