/**
 * Centre Mécanique RDP — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "freins",
    "icon": "brake",
    "duration_min": 90,
    "bookable": 1,
    "featured": 1,
    "name": "Installation de freins",
    "name_en": "Brake installation",
    "tagline": "Plaquettes, disques, étriers et liquide : des freins qui répondent.",
    "tagline_en": "Pads, rotors, calipers and fluid: brakes that answer.",
    "body": "Les freins s’usent un peu à chaque arrêt. L’inspection mesure les plaquettes et les disques, vérifie les étriers, les conduites et le liquide de frein, puis vous dit ce qui est usé, ce qui peut attendre et ce qui presse.\nLe sel et les hivers québécois sont durs pour les étriers et les conduites : un bruit ou une vibration au freinage mérite d’être vérifié rapidement.",
    "body_en": "Brakes wear a little at every stop. The inspection measures the pads and rotors, checks the calipers, lines and brake fluid, then tells you what is worn, what can wait and what is urgent.\nSalt and Québec winters are hard on calipers and lines: a noise or vibration when braking deserves a quick check.",
    "signs": "[\"Grincement ou sifflement au freinage\",\"Vibration dans la pédale ou le volant\",\"La pédale est molle ou descend plus bas\",\"Le véhicule tire d’un côté au freinage\"]",
    "signs_en": "[\"Squealing or grinding when braking\",\"Vibration in the pedal or steering wheel\",\"The pedal feels soft or sinks lower\",\"The vehicle pulls to one side when braking\"]",
    "confirmed": 1
  },
  {
    "slug": "pneus-neufs-usages",
    "icon": "wheel",
    "duration_min": 45,
    "bookable": 1,
    "featured": 1,
    "name": "Pneus neufs et usagés",
    "name_en": "New and used tires",
    "tagline": "Vente et installation de pneus.",
    "tagline_en": "Tire sales and installation.",
    "body": "Le garage vend des pneus neufs et usagés et les installe. Au Québec, les pneus d’hiver sont obligatoires du 1er décembre au 15 mars ; à chaque pose, la pression, l’usure et l’équilibrage sont vérifiés.",
    "body_en": "The garage sells new and used tires and installs them. In Québec, winter tires are mandatory from December 1 to March 15; at each install, pressure, tread wear and balance are checked.",
    "signs": "[\"Le changement de saison approche\", \"Usure proche du témoin\", \"Crevaison ou hernie\", \"Vibration au volant\"]",
    "signs_en": "[\"The seasonal change is coming\", \"Tread close to the wear bar\", \"A puncture or a bulge\", \"Steering-wheel vibration\"]",
    "confirmed": 1
  },
  {
    "slug": "installation-mags",
    "icon": "wheel",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Installation de mags",
    "name_en": "Alloy wheel installation",
    "tagline": "Jusqu’à 26 pouces.",
    "tagline_en": "Up to 26 inches.",
    "body": "Le garage installe les mags (jantes en alliage) jusqu’à 26 pouces, selon sa fiche. La pose comprend le montage des pneus, l’équilibrage et le serrage au couple prescrit ; précisez la taille et le véhicule en réservant.",
    "body_en": "The garage installs alloy wheels up to 26 inches, according to its listing. Installation includes mounting the tires, balancing and torquing to spec; give the size and the vehicle when you book.",
    "signs": "[\"Nouvelles jantes à poser\", \"Changement de taille de roue\", \"Jante abîmée à remplacer\"]",
    "signs_en": "[\"New wheels to fit\", \"A change of wheel size\", \"A damaged rim to replace\"]",
    "confirmed": 1
  },
  {
    "slug": "entreposage-pneus",
    "icon": "wheel",
    "duration_min": 30,
    "bookable": 1,
    "featured": 0,
    "name": "Entreposage de pneus",
    "name_en": "Tire storage",
    "tagline": "Vos pneus de l’autre saison, gardés au garage.",
    "tagline_en": "Your off-season tires, kept at the garage.",
    "body": "Entre deux saisons, les pneus prennent de la place et craignent le soleil, l’humidité et les écarts de température. L’entreposage au garage les garde dans de bonnes conditions jusqu’au prochain changement : ils sont prêts à être posés au moment de la permutation saisonnière.",
    "body_en": "Between seasons, tires take up room and do not like sun, damp or temperature swings. Storing them at the garage keeps them in good condition until the next change, ready to go on at the seasonal swap.",
    "signs": "[\"Pas de place pour les pneus à la maison\", \"Pneus rangés dehors ou au soleil\", \"Le changement de saison approche\"]",
    "signs_en": "[\"No room for the tires at home\", \"Tires stored outside or in the sun\", \"The seasonal change is coming\"]",
    "confirmed": 1
  },
  {
    "slug": "diagnostic-electronique",
    "icon": "spark",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Scanner et diagnostic",
    "name_en": "Scan and diagnostics",
    "tagline": "Voyants, codes d’erreur, capteurs.",
    "tagline_en": "Warning lights, fault codes, sensors.",
    "body": "Un voyant allumé enregistre un code d’erreur dans l’ordinateur du véhicule. Le diagnostic lit ces codes avec un lecteur adapté, puis vérifie les capteurs, le câblage et les composants en cause, pour réparer la bonne pièce plutôt que de deviner.",
    "body_en": "A warning light stores a fault code in the vehicle’s computer. Diagnostics read those codes with a proper scan tool, then check the sensors, wiring and parts involved, so the right part gets fixed instead of guessing.",
    "signs": "[\"Voyant moteur ou ABS allumé\", \"Perte de puissance\", \"Démarrage difficile\", \"Consommation qui augmente\"]",
    "signs_en": "[\"Check-engine or ABS light on\", \"Loss of power\", \"Hard starting\", \"Rising fuel use\"]",
    "confirmed": 1
  },
  {
    "slug": "electricite-auto",
    "icon": "spark",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Réparation de système électrique",
    "name_en": "Electrical system repair",
    "tagline": "Démarrage, charge, éclairage, câblage.",
    "tagline_en": "Starting, charging, lights, wiring.",
    "body": "Le système électrique alimente le démarrage, la recharge de la batterie, l’éclairage, les accessoires et les nombreux capteurs du véhicule. Un diagnostic électrique mesure la batterie, l’alternateur et le démarreur, puis suit le câblage et les fusibles pour trouver la cause d’une panne plutôt que de remplacer des pièces au hasard.",
    "body_en": "The electrical system powers starting, battery charging, lights, accessories and the vehicle’s many sensors. An electrical diagnosis measures the battery, alternator and starter, then follows the wiring and fuses to find the cause of a fault instead of replacing parts at random.",
    "signs": "[\"Démarrage lent ou clic sans démarrage\", \"Voyant de batterie allumé\", \"Phares ou accessoires qui faiblissent\", \"Fusible qui saute encore\"]",
    "signs_en": "[\"Slow cranking or a click but no start\", \"Battery light on\", \"Dimming lights or accessories\", \"A fuse that keeps blowing\"]",
    "confirmed": 1
  },
  {
    "slug": "vidange-huile",
    "icon": "oil",
    "duration_min": 30,
    "bookable": 1,
    "featured": 1,
    "name": "Changement d’huile",
    "name_en": "Oil change",
    "tagline": "Huile, filtre et inspection des points essentiels.",
    "tagline_en": "Oil, filter and a check of the essentials.",
    "body": "La vidange est l’entretien le plus simple et le plus important pour la vie du moteur. Elle comprend l’huile appropriée à votre moteur, un filtre neuf et un coup d’œil aux niveaux, aux pneus et aux fuites. Réservez en ligne, déposez la voiture ou attendez sur place.",
    "body_en": "An oil change is the simplest and most important service for engine life. It includes the right oil for your engine, a new filter and a quick look at fluid levels, tires and leaks. Book online, drop the car off or wait on site.",
    "signs": "[\"Le rappel d’entretien s’affiche\",\"Kilométrage atteint depuis la dernière vidange\",\"Huile foncée ou niveau bas\"]",
    "signs_en": "[\"The service reminder appears\",\"Mileage reached since the last change\",\"Dark oil or a low level\"]",
    "confirmed": 1
  },
  {
    "slug": "antirouille",
    "icon": "oil",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Traitement antirouille",
    "name_en": "Rustproofing",
    "tagline": "Protéger le dessous du véhicule contre le sel.",
    "tagline_en": "Protect the underbody from road salt.",
    "body": "Le sel et le calcium de nos routes attaquent le dessous des véhicules. Un traitement antirouille appliqué chaque année, idéalement à l’automne, protège le châssis, les bas de caisse et les conduites.",
    "body_en": "Salt and calcium on our roads attack the underside of vehicles. A rustproofing treatment applied every year, ideally in the fall, protects the frame, rocker panels and lines.",
    "signs": "[\"Avant l’hiver\", \"Taches de rouille sur le châssis\", \"Véhicule neuf ou récent\", \"Bas de caisse qui bullent\"]",
    "signs_en": "[\"Before winter\", \"Rust spots on the frame\", \"A new or recent vehicle\", \"Bubbling rocker panels\"]",
    "confirmed": 1
  },
  {
    "slug": "suspension",
    "icon": "spring",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Suspension",
    "name_en": "Suspension",
    "tagline": "Amortisseurs, ressorts, rotules : stabilité et confort.",
    "tagline_en": "Shocks, springs, ball joints: stability and comfort.",
    "body": "Nids-de-poule et routes bosselées usent vite la suspension. Des amortisseurs fatigués allongent les distances de freinage et usent les pneus. L’inspection vérifie amortisseurs, ressorts, rotules, biellettes et bras de suspension.",
    "body_en": "Potholes and rough roads wear a suspension quickly. Tired shocks lengthen braking distances and wear tires. The inspection covers shocks, springs, ball joints, links and control arms.",
    "signs": "[\"Cognements dans les bosses\",\"Le véhicule tire d’un côté\",\"Le nez plonge au freinage\",\"Rebonds après une bosse\"]",
    "signs_en": "[\"Clunks over bumps\",\"The car pulls to one side\",\"The nose dives when braking\",\"Bouncing after a bump\"]",
    "confirmed": 1
  },
  {
    "slug": "embrayage",
    "icon": "gear",
    "duration_min": 180,
    "bookable": 1,
    "featured": 0,
    "name": "Réparation d’embrayage",
    "name_en": "Clutch repair",
    "tagline": "Pédale qui patine, passages difficiles.",
    "tagline_en": "Slipping pedal, hard shifts.",
    "body": "Sur une boîte manuelle, l’embrayage relie le moteur à la transmission. Avec l’usure, il patine, broute ou rend les passages de vitesses difficiles. Le remplacement comprend généralement le disque, le plateau de pression et la butée, avec une vérification du volant moteur.",
    "body_en": "On a manual gearbox, the clutch connects the engine to the transmission. As it wears, it slips, judders or makes shifting hard. Replacement usually covers the disc, pressure plate and release bearing, with a check of the flywheel.",
    "signs": "[\"Le régime monte sans que la voiture accélère\", \"Pédale dure ou qui reste enfoncée\", \"Vitesses difficiles à passer\", \"Odeur de brûlé en côte\"]",
    "signs_en": "[\"Revs rise but the car does not speed up\", \"A stiff or sticking pedal\", \"Hard-to-select gears\", \"A burning smell on hills\"]",
    "confirmed": 1
  },
  {
    "slug": "mise-au-point",
    "icon": "spark",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Mise au point du moteur",
    "name_en": "Engine tune-up",
    "tagline": "Bougies, filtres, allumage : retrouver la puissance et l’économie.",
    "tagline_en": "Plugs, filters, ignition: get the power and the mileage back.",
    "body": "Une mise au point remplace les pièces d’usure qui font perdre de la puissance et augmenter la consommation : bougies, filtres à air et à carburant, et vérification de l’allumage. Les intervalles varient selon le véhicule; le manuel du fabricant fait foi.",
    "body_en": "A tune-up replaces the wear parts that cost power and raise fuel use: spark plugs, air and fuel filters, and an ignition check. Intervals vary by vehicle; the manufacturer’s manual is the reference.",
    "signs": "[\"Consommation d’essence en hausse\",\"Ralenti irrégulier ou ratés\",\"Accélération paresseuse\"]",
    "signs_en": "[\"Rising fuel consumption\",\"Rough idle or misfires\",\"Sluggish acceleration\"]",
    "confirmed": 1
  },
  {
    "slug": "remorquage",
    "icon": "tow",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "option": "towing",
    "name": "Remorquage",
    "name_en": "Towing",
    "tagline": "Le véhicule ne roule plus? Appelez le garage.",
    "tagline_en": "Car won’t move? Call the garage.",
    "body": "En panne à Rivière-des-Prairies ou dans les environs? Appelez directement le garage. Au moment de réserver, vous pouvez aussi indiquer que le véhicule doit être remorqué et l’adresse où il se trouve : le garage vous rappelle pour organiser la prise en charge.",
    "body_en": "Broken down in Rivière-des-Prairies or nearby? Call the garage directly. When booking, you can also say the vehicle needs a tow and where it is: the garage calls you back to arrange the pickup.",
    "signs": "[\"Le véhicule ne démarre plus\", \"Voyant rouge ou surchauffe sur la route\", \"Accident ou crevaison sans roue de secours\"]",
    "signs_en": "[\"The car will not start\", \"A red warning light or overheating on the road\", \"An accident or a flat without a spare\"]",
    "confirmed": 1
  },
  {
    "slug": "pre-inspection-saaq",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Inspection pré-SAAQ",
    "name_en": "SAAQ pre-inspection",
    "tagline": "Arriver prêt à la vérification mécanique.",
    "tagline_en": "Arrive ready for the mechanical inspection.",
    "body": "Avant une vérification mécanique exigée par la SAAQ, une pré-inspection passe en revue les points qui seront contrôlés — freins, direction, suspension, éclairage, pneus, pare-brise, échappement — pour corriger les défauts avant le rendez-vous officiel.",
    "body_en": "Before a mechanical inspection required by the SAAQ, a pre-inspection reviews the points that will be checked — brakes, steering, suspension, lights, tires, windshield, exhaust — so defects are fixed before the official appointment.",
    "signs": "[\"Avis de vérification mécanique reçu\", \"Achat ou immatriculation d’un véhicule\", \"Échéance d’inspection d’un véhicule lourd\"]",
    "signs_en": "[\"A mechanical inspection notice received\", \"Buying or registering a vehicle\", \"A heavy-vehicle inspection due\"]",
    "confirmed": 1
  },
  {
    "slug": "service-valet",
    "icon": "car",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "name": "Service de valet",
    "name_en": "Valet service",
    "tagline": "Offert selon la fiche du garage — appelez pour les détails.",
    "tagline_en": "Listed by the garage — call for details.",
    "body": "La fiche du garage indique un service de valet. Appelez le garage pour savoir comment il fonctionne et s’il convient à votre rendez-vous.",
    "body_en": "The garage’s listing mentions a valet service. Call the garage to find out how it works and whether it suits your appointment.",
    "signs": "[\"Pas le temps d’apporter le véhicule\", \"Question sur le service\"]",
    "signs_en": "[\"No time to bring the car in\", \"A question about the service\"]",
    "confirmed": 1
  },
  {
    "slug": "voiture-courtoisie",
    "icon": "car",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "option": "courtesy",
    "name": "Voiture de courtoisie",
    "name_en": "Courtesy car",
    "tagline": "Disponible selon la fiche du garage.",
    "tagline_en": "Available according to the garage’s listing.",
    "body": "La fiche du garage indique qu’une voiture de courtoisie est disponible. Demandez-la au moment de réserver ; le garage confirme sa disponibilité.",
    "body_en": "The garage’s listing says a courtesy car is available. Ask for it when you book; the garage confirms availability.",
    "signs": "[\"Réparation de plus d’une journée\", \"Besoin de rester mobile\"]",
    "signs_en": "[\"A repair taking more than a day\", \"Need to stay mobile\"]",
    "confirmed": 1
  },
  {
    "slug": "transmission",
    "icon": "gear",
    "duration_min": 90,
    "bookable": 1,
    "featured": 0,
    "name": "Transmission",
    "name_en": "Transmission",
    "tagline": "Entretien, diagnostic et réparation, automatique ou manuelle.",
    "tagline_en": "Service, diagnosis and repair, automatic or manual.",
    "body": "L’huile de transmission s’use comme l’huile moteur. Un entretien régulier prévient bien des réparations coûteuses. Au premier signe inhabituel, un diagnostic permet de distinguer un simple entretien d’une réparation.",
    "body_en": "Transmission fluid wears out just like engine oil. Regular service prevents many costly repairs. At the first unusual sign, a diagnosis tells a simple service apart from a repair.",
    "signs": "[\"Passages de vitesse brusques ou retardés\",\"Bruit en prise\",\"Fuite de liquide rouge\",\"Voyant de transmission\"]",
    "signs_en": "[\"Harsh or delayed shifts\",\"Noise in gear\",\"A red fluid leak\",\"A transmission warning light\"]",
    "confirmed": 1
  }
];
