/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_jean_proulx).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669965/tapavis_tenant_mecanique_jean_proulx/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669965/tapavis_tenant_mecanique_jean_proulx/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669978/tapavis_tenant_mecanique_jean_proulx/hero_c92560e2-40a3-4b55-9530-fe53caf88565.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669979/tapavis_tenant_mecanique_jean_proulx/freins_4237e06c-527b-4d33-a9e2-e5f8f9af5c6b.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669980/tapavis_tenant_mecanique_jean_proulx/vidange-huile_d29c0142-67a4-43e1-a88e-26feaefe86d6.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669980/tapavis_tenant_mecanique_jean_proulx/mecanique-generale_c42ac55f-7c89-4f17-99cb-95203a4f8a0d.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669990/tapavis_tenant_mecanique_jean_proulx/suspension_00b2f345-1b15-40ea-943a-38ecf64c1405.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669991/tapavis_tenant_mecanique_jean_proulx/equilibrage-rotation-pneus_4ee8332d-7ca6-4d3f-b7e1-71fd939cba14.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669991/tapavis_tenant_mecanique_jean_proulx/silencieux_21cdd720-95ca-4f1b-862b-7466a2b8c396.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669991/tapavis_tenant_mecanique_jean_proulx/systeme-de-refroidissement_36fa2fdd-d4bc-442d-92e0-0aa4a220f027.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670002/tapavis_tenant_mecanique_jean_proulx/climatisation_32faa519-1983-4772-b7ce-3565b6dd0757.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670003/tapavis_tenant_mecanique_jean_proulx/mise-au-point_edf1bf68-f995-499a-a414-b364da26a3d8.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670009/tapavis_tenant_mecanique_jean_proulx/transmission_23012e41-0161-4a6e-8e9c-08202edfcdc7.png"
  }
};
