/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_rg_garage).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669628/tapavis_tenant_rg_garage/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669628/tapavis_tenant_rg_garage/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669639/tapavis_tenant_rg_garage/hero_d429fc78-3a51-4f54-8c5b-a4374823ad81.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669639/tapavis_tenant_rg_garage/vidange-huile_f044f68e-6143-4a92-9664-ee5e8245c03b.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669640/tapavis_tenant_rg_garage/freins_5a38c80c-ddc7-4db6-a4e3-a48099a9344d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669640/tapavis_tenant_rg_garage/mecanique-generale_6846fb60-c773-47d2-8c12-4730f020de15.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669650/tapavis_tenant_rg_garage/equilibrage-rotation-pneus_c4a945f5-3fe2-4fbc-a110-a718fec7e03a.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669650/tapavis_tenant_rg_garage/suspension_aa429782-14b2-43c6-93c4-85e3708655fe.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669651/tapavis_tenant_rg_garage/systeme-de-refroidissement_9e779594-8c89-4ac2-9959-fced86f1cb5c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669652/tapavis_tenant_rg_garage/silencieux_f8675bbe-2607-4e8c-a274-226307d9f9d8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669660/tapavis_tenant_rg_garage/mise-au-point_c6a49002-9d9b-477b-82bd-61707ef2af16.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669662/tapavis_tenant_rg_garage/climatisation_409c6c81-cc77-4d08-afa0-bce598159df7.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669664/tapavis_tenant_rg_garage/transmission_d2a76353-223d-4774-8943-3429fc5b3027.png"
  }
};
