-- Ali Baba Grillades — tenant image settings.
-- Slug: ali-baba-boucherie
--
-- IMPORTANT: ON CONFLICT DO NOTHING (not DO UPDATE) on the _p_*_image_url
-- rows so tenant-side customizations (e.g. operator's dashboard icon upload,
-- which writes _p_nav_logo_url via setPwaIconAndMirror) survive the next
-- cache-invalidation cycle. runTenantSchemaIfNeeded re-applies this whole
-- file every time the tenant dir is re-materialized, so an upsert would
-- silently clobber operator overrides on every re-render.
--
-- _p_*_image_url values are stored BARE (the f_auto,q_auto,w_1280,c_limit
-- transform segment is injected at render time by subscriberPwaRouter, never
-- stored). Hero + about reuse the business's own charcoal-grill photos from
-- the Liasse Restaurants ordering menu (business 296).

INSERT INTO admin_settings (key, value) VALUES ('_p_nav_logo_url', 'https://res.cloudinary.com/duhp69meg/image/upload/v1771379528/tapavis_logos/ali-baba-boucherie/o2n6ufhn1givosddjvgc.png')
  ON CONFLICT (key) DO NOTHING;
INSERT INTO admin_settings (key, value) VALUES ('_p_hero_image_url', 'https://res.cloudinary.com/duhp69meg/image/upload/v1781898959/tapavis_menu/296/l6qrlo9ykavj0wszyh2c.jpg')
  ON CONFLICT (key) DO NOTHING;
INSERT INTO admin_settings (key, value) VALUES ('_p_about_image_url', 'https://res.cloudinary.com/duhp69meg/image/upload/v1781898961/tapavis_menu/296/zkpkruhfiq2vqdzvisx0.jpg')
  ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Real business facts from Google Places (place_id ChIJF4-Q7NnXyEwRTorFpzfVkmc),
-- fetched 2026-06-20 via place-id-fetcher. Populate-if-blank: fills missing or
-- empty values on the LIVE tenant (seed.js is first-install only) WITHOUT
-- clobbering later operator edits in Admin (DO UPDATE guarded on blank/NULL).
-- hours_json drives the footer hours table; the `hours` string is the
-- human-readable fallback. Hours: Wed-Sun 09:00-19:00, Mon-Tue closed.
-- ---------------------------------------------------------------------------
INSERT INTO admin_settings (key, value) VALUES ('contact_phone', '(450) 420-0003')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';
INSERT INTO admin_settings (key, value) VALUES ('business_address', '1185 Bd Curé-Labelle, Local 3, Blainville, QC J7C 4K6')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';
INSERT INTO admin_settings (key, value) VALUES ('hours', E'Mer-Dim : 9h - 19h\nLun-Mar : Fermé')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';
INSERT INTO admin_settings (key, value) VALUES ('hours_json', '[{"day":"mon","open":"","close":"","closed":true},{"day":"tue","open":"","close":"","closed":true},{"day":"wed","open":"09:00","close":"19:00","closed":false},{"day":"thu","open":"09:00","close":"19:00","closed":false},{"day":"fri","open":"09:00","close":"19:00","closed":false},{"day":"sat","open":"09:00","close":"19:00","closed":false},{"day":"sun","open":"09:00","close":"19:00","closed":false}]')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';
INSERT INTO admin_settings (key, value) VALUES ('google_place_id', 'ChIJF4-Q7NnXyEwRTorFpzfVkmc')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';
INSERT INTO admin_settings (key, value) VALUES ('map_embed_url', 'https://www.google.com/maps?q=1185%20Bd%20Cur%C3%A9-Labelle%20Local%203%2C%20Blainville%2C%20QC%20J7C%204K6%2C%20Canada&output=embed')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value WHERE admin_settings.value IS NULL OR admin_settings.value = '';

-- ---------------------------------------------------------------------------
-- Menu rebuild v2 (latest menu export, 43 items). ONE-TIME + re-run-safe
-- via the _menu_rebuild_v2 sentinel: first Push-to-Live wipes + reinserts; later
-- re-materializations no-op (sentinel present) so operator CRUD edits survive.
-- ---------------------------------------------------------------------------
DELETE FROM menu_items WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Babaghanouge', 'Baba Ghanoush', 'Caviar d''aubergine grillée au tahini, citron et ail.', 'Smoky grilled-eggplant dip with tahini, lemon and garlic.', 7.5, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061795/tapavis_menu/296/babaghanouge_1782061794032.png', 1, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":7.5},{"label_fr":"Grand","label_en":"Large","price":13.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Patates à l''ail', 'Garlic Potatoes', 'Pommes de terre sautées à l''ail et coriandre. Format petit ou grand.', 'Potatoes sautéed in garlic and coriander. Small or large.', 4.99, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061795/tapavis_menu/296/patates_a_l_ail_1782061793656.png', 2, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":4.99},{"label_fr":"Grand","label_en":"Large","price":8.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Riz', 'Rice', 'Riz libanais parfumé. Format petit ou grand.', 'Fragrant Lebanese rice. Small or large.', 3.99, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061828/tapavis_menu/296/riz_1782061826840.png', 3, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":3.99},{"label_fr":"Grand","label_en":"Large","price":8.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Hommous', 'Hummus', 'Purée de pois chiches au tahini, citron et huile d''olive. Format petit ou grand.', 'Chickpea purée with tahini, lemon and olive oil. Small or large.', 7.5, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061793/tapavis_menu/296/hommous_1782061791979.png', 4, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":7.5},{"label_fr":"Grand","label_en":"Large","price":13.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Fattouche', 'Fattoush', 'Salade de légumes croquants et pain pita grillé, vinaigrette au sumac.', 'Crisp vegetable salad with toasted pita and a sumac dressing.', 4.99, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782062416/tapavis_menu/296/fattouche_1782062414159.png', 5, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":4.99},{"label_fr":"Grand","label_en":"Large","price":11.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Taboulé', 'Tabbouleh', 'Salade de persil, boulgour, tomate et menthe, citron et huile d''olive.', 'Parsley, bulgur, tomato and mint salad with lemon and olive oil.', 4.99, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782062428/tapavis_menu/296/taboule_1782062426682.png', 6, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":4.99},{"label_fr":"Grand","label_en":"Large","price":9.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sauce à l''ail', 'Garlic Sauce', 'Notre sauce à l''ail maison, crémeuse et généreuse.', 'Our creamy house-made garlic sauce.', 7.5, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061795/tapavis_menu/296/sauce_a_l_ail_1782061794060.png', 7, 0, 1, '[{"label_fr":"Petit","label_en":"Small","price":7.5},{"label_fr":"Grand","label_en":"Large","price":13.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Pain pita épicé', 'Spiced Pita Bread', 'Pain pita moyen assaisonné de sauce piquante et d''oignons, le tout grillé.', 'Medium pita seasoned with hot sauce and onions, then grilled.', 3.57, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782062440/tapavis_menu/296/pain_pita_epice_1782062438515.png', 8, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sac de 5 pitas moyennes', 'Bag of 5 Medium Pitas', 'Sac de 5 pains pita moyens.', 'Bag of 5 medium pita breads.', 2.5, 'entrees', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782062655/tapavis_menu/296/dgjoct5idueftu4qfxxs.jpg', 9, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Shish taouk', 'Shish Taouk Sandwich', 'Poitrine de poulet marinée, grillée sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Marinated chicken breast charcoal-grilled. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898972/tapavis_menu/296/zxacvy75nmtgrcl0jd1t.jpg', 1, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Filet mignon', 'Filet Mignon Sandwich', 'Filet mignon grillé sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled filet mignon. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898973/tapavis_menu/296/okka7eig9hv5cczktkff.jpg', 2, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Steak', 'Steak Sandwich', 'Steak grillé sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled steak. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898975/tapavis_menu/296/un8hwnr3asdhm68gpxho.jpg', 3, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Kafta', 'Kafta Sandwich', 'Brochette de bœuf haché, persil, oignon et épices, grillée sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled ground-beef kafta with parsley, onion and spices. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898974/tapavis_menu/296/ac30uszwyjejexi27bhr.jpg', 4, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Makaneek', 'Makanek Sandwich', 'Saucisses libanaises non piquantes, grillées sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled mild Lebanese sausages. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898977/tapavis_menu/296/suycuncj0ylxjb5qo3x4.jpg', 5, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Soujouk', 'Soujouk Sandwich', 'Saucisses arméniennes piquantes, grillées sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled spicy Armenian sausages. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898977/tapavis_menu/296/klmcglqmwktai6dbdm1d.jpg', 6, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Arayes', 'Arayes Sandwich', 'Pain pita farci de kafta et grillé sur charbon, croustillant. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Pita stuffed with kafta and charcoal-grilled until crisp. Topped with tomato, pickle, onion, hummus or garlic sauce.', 12.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898978/tapavis_menu/296/eqcby2c0p8avm0lmxdde.jpg', 7, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":12.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":18.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Foie', 'Liver Sandwich', 'Foie grillé sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled liver. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061807/tapavis_menu/296/sandwich_foie_1782061805486.png', 8, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Crevettes', 'Shrimp Sandwich', 'Crevettes grillées sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled shrimp. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061806/tapavis_menu/296/sandwich_crevettes_1782061804583.png', 9, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Hamburger', 'Hamburger', 'Galette de bœuf grillée sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled beef patty. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061808/tapavis_menu/296/hamburger_1782061806892.png', 10, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Agneau', 'Lamb Sandwich', 'Agneau grillé sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled lamb. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061808/tapavis_menu/296/sandwich_agneau_1782061806619.png', 11, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio ou combo","label_en":"Trio or combo","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Sandwich Merguez', 'Merguez Sandwich', 'Saucisses marocaines non piquantes, grillées sur charbon. Garni de tomate, cornichon, oignon, houmous ou sauce à l''ail.', 'Charcoal-grilled mild Moroccan sausages. Topped with tomato, pickle, onion, hummus or garlic sauce.', 9.99, 'sandwichs', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061818/tapavis_menu/296/sandwich_merguez_1782061815915.png', 12, 0, 1, '[{"label_fr":"seul","label_en":"Single","price":9.99},{"label_fr":"trio","label_en":"Trio","price":16.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Boeuf (tartare)', 'Beef Tartare', 'Tartare de bœuf libanais. Styles tablé, kebbeh, kafta ou malsé. Sandwich ou au kilo.', 'Lebanese-style beef tartare. Tablé, kebbeh, kafta or malsé. Sandwich or by the kilo.', 9.5, 'tartares', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781899013/tapavis_menu/296/yyhhj3jhqznnjyqmujre.jpg', 1, 0, 1, '[{"label_fr":"sandwich","label_en":"Sandwich","price":9.5},{"label_fr":"au kilo","label_en":"By the kilo","price":27.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Agneau (tartare)', 'Lamb Tartare', 'Tartare d''agneau libanais. Styles tablé, kebbeh, kafta ou malsé. Sandwich ou au kilo.', 'Lebanese-style lamb tartare. Tablé, kebbeh, kafta or malsé. Sandwich or by the kilo.', 9.99, 'tartares', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781899015/tapavis_menu/296/i86zl9dfmhfnf1widnya.jpg', 2, 0, 1, '[{"label_fr":"sandwich","label_en":"Sandwich","price":9.99},{"label_fr":"au kilo","label_en":"By the kilo","price":42.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Veau (tartare)', 'Veal Tartare', 'Tartare de veau libanais. Styles tablé, kebbeh, kafta ou malsé. Sandwich ou au kilo.', 'Lebanese-style veal tartare. Tablé, kebbeh, kafta or malsé. Sandwich or by the kilo.', 9.5, 'tartares', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781899014/tapavis_menu/296/f4zigtnpkzxgxttfvngu.jpg', 3, 0, 1, '[{"label_fr":"sandwich","label_en":"Sandwich","price":9.5},{"label_fr":"au kilo","label_en":"By the kilo","price":33.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Poulet sur charbon en crapaudine', 'Charcoal Crapaudine Chicken', 'Poulet entier en crapaudine, grillé sur charbon de bois.', 'Whole spatchcock chicken charcoal-grilled.', 25.99, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898961/tapavis_menu/296/zkpkruhfiq2vqdzvisx0.jpg', 1, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Mix', 'Mixed Grill', 'Taouk, kafta et filet mignon grillés sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Charcoal-grilled taouk, kafta and filet mignon. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 32, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898959/tapavis_menu/296/l6qrlo9ykavj0wszyh2c.jpg', 2, 0, 1, '[{"label_fr":"½kg","label_en":"½ kg","price":32},{"label_fr":"1kg","label_en":"1 kg","price":52}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Filet mignon', 'Filet Mignon', 'Bœuf tendre grillé sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Tender charcoal-grilled beef. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 39, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898960/tapavis_menu/296/w9hcgfmjapohgaglmm4a.jpg', 3, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":39},{"label_fr":"1 kg","label_en":"1 kg","price":75.99}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Kafta', 'Kafta', 'Bœuf haché, persil, oignon et épices, grillé sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Ground beef with parsley, onion and spices, charcoal-grilled. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 30, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898962/tapavis_menu/296/pwmlbzi4kkrjrn6aazi0.jpg', 4, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":30},{"label_fr":"1 kg","label_en":"1 kg","price":48}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Taouk', 'Taouk', 'Poitrine de poulet marinée, grillée sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Marinated chicken breast charcoal-grilled. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 32, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898962/tapavis_menu/296/iruy1v5h35zxwriqzabi.jpg', 5, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":32},{"label_fr":"1 kg","label_en":"1 kg","price":52}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Makanek', 'Makanek', 'Saucisses libanaises non piquantes, grillées sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Mild Lebanese sausages charcoal-grilled. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 32, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898963/tapavis_menu/296/qoo2efrlejjtvlbodfzh.jpg', 6, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":32},{"label_fr":"1 kg","label_en":"1 kg","price":52}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Côtelettes d''agneau', 'Lamb Chops', 'Côtelettes d''agneau grillées sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Charcoal-grilled lamb chops. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 40, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898966/tapavis_menu/296/yt9pwpwp02y7vnrcxkm3.jpg', 7, 0, 1, '[{"label_fr":"½kg","label_en":"½ kg","price":40},{"label_fr":"1kg","label_en":"1 kg","price":77}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Soujouk', 'Soujouk', 'Saucisses arméniennes piquantes, grillées sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Spicy Armenian sausages charcoal-grilled. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 32, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898965/tapavis_menu/296/fpruetusiyssanepfoea.jpg', 8, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":32},{"label_fr":"1 kg","label_en":"1 kg","price":52}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Merguez', 'Merguez', 'Saucisses marocaines non piquantes, grillées sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Mild Moroccan sausages charcoal-grilled. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 32, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898964/tapavis_menu/296/rxbuefnkkkmleg7prcjl.jpg', 9, 0, 1, '[{"label_fr":"½ kg","label_en":"½ kg","price":32},{"label_fr":"1 kg","label_en":"1 kg","price":52}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Foie de veau de grain', 'Grain-fed Veal Liver', 'Foie de veau de grain grillé sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Charcoal-grilled grain-fed veal liver. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 35, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061818/tapavis_menu/296/foie_de_veau_de_grain_1782061816066.png', 10, 0, 1, '[{"label_fr":"½kg","label_en":"½ kg","price":35},{"label_fr":"1kg","label_en":"1 kg","price":55}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Agneau qc. en cubes', 'Quebec Lamb Cubes', 'Agneau du Québec en cubes, grillé sur charbon. Servi avec légumes grillés, pain pita épicé, houmous et sauce à l''ail. ½ kg ou 1 kg.', 'Charcoal-grilled Quebec lamb cubes. Served with grilled vegetables, spiced pita bread, hummus and garlic sauce. ½ kg or 1 kg.', 40, 'assiettes', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782061816/tapavis_menu/296/agneau_qc_en_cubes_1782061814979.png', 11, 0, 1, '[{"label_fr":"½kg","label_en":"½ kg","price":40},{"label_fr":"1kg","label_en":"1 kg","price":77}]' WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Pepsi', 'Pepsi', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063139/tapavis_menu/296/x7whccqlumhpcdenctur.jpg', 1, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Pepsi Diète', 'Diet Pepsi', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063175/tapavis_menu/296/jtqhze789mplbs2etd5f.jpg', 2, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Coca-Cola', 'Coca-Cola', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063303/tapavis_menu/296/gs2kjjq1k8le6dvuu4rh.jpg', 3, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT '7 UP', '7 UP', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063329/tapavis_menu/296/nie5drrrzijmhovts7ha.jpg', 4, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Crush', 'Crush', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063354/tapavis_menu/296/pfdafxggjox2pculd1ui.jpg', 5, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Bouteille d''Eau', 'Bottled Water', NULL, NULL, 3.25, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063406/tapavis_menu/296/pf1xgiqhcdqgxmlbgabv.jpg', 6, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Ayrane', 'Ayran', 'Boisson lactée rafraîchissante à base de yogourt.', 'Refreshing yogurt-based drink.', 4.5, 'breuvages', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1782063412/tapavis_menu/296/py7om9aueqptdelwfyom.jpg', 7, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO menu_items (name_fr,name_en,description_fr,description_en,price,category,image_url,position,featured,available,sizes_json)
  SELECT 'Mélange de Baklava', 'Baklava Assortment', '10 morceaux de baklavas frais.', '10 pieces of fresh baklava.', 9.86, 'dessert', 'https://res.cloudinary.com/duhp69meg/image/upload/w_640,h_480,c_fill,g_auto,q_auto,f_auto/v1781898981/tapavis_menu/296/bor0dhsbt3tdtyx1xzpk.jpg', 1, 0, 1, NULL WHERE NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
-- category display order: Assiettes first, then Entrées, Sandwichs, Tartares, Breuvages, Dessert
UPDATE menu_categories SET position = 1, updated_at = NOW() WHERE slug = 'assiettes' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
UPDATE menu_categories SET position = 2, updated_at = NOW() WHERE slug = 'entrees' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
UPDATE menu_categories SET position = 3, updated_at = NOW() WHERE slug = 'sandwichs' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
UPDATE menu_categories SET position = 4, updated_at = NOW() WHERE slug = 'tartares' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
UPDATE menu_categories SET position = 5, updated_at = NOW() WHERE slug = 'breuvages' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
UPDATE menu_categories SET position = 6, updated_at = NOW() WHERE slug = 'dessert' AND NOT EXISTS (SELECT 1 FROM admin_settings WHERE key='_menu_rebuild_v2');
INSERT INTO admin_settings (key, value) VALUES ('_menu_rebuild_v2', '1') ON CONFLICT (key) DO NOTHING;
