/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_generale_martin_tremblay_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626088/tapavis_tenant_mecanique_generale_martin_tremblay_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626088/tapavis_tenant_mecanique_generale_martin_tremblay_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626098/tapavis_tenant_mecanique_generale_martin_tremblay_inc/hero_3c7315ea-be73-4a3c-a3e5-fdc773693d25.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626098/tapavis_tenant_mecanique_generale_martin_tremblay_inc/freins_fb7f8d15-cc03-4539-ab2b-155dbf8d9d40.png",
    "reparation-camions": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626100/tapavis_tenant_mecanique_generale_martin_tremblay_inc/reparation-camions_8cdd6b19-8279-478a-8db1-fc5ac05bbad7.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626100/tapavis_tenant_mecanique_generale_martin_tremblay_inc/mecanique-generale_183bcfd4-bc7f-4ce7-90fa-6318687661fe.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626109/tapavis_tenant_mecanique_generale_martin_tremblay_inc/equilibrage-rotation-pneus_5d04b387-1c8e-427c-985e-551ff75ea8d8.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626109/tapavis_tenant_mecanique_generale_martin_tremblay_inc/vidange-huile_7cfa37be-27eb-47ad-b553-1bebdf6bb728.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626109/tapavis_tenant_mecanique_generale_martin_tremblay_inc/silencieux_192314fe-b710-4afb-b81f-a512ff52e29f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626112/tapavis_tenant_mecanique_generale_martin_tremblay_inc/suspension_9958ddbb-6745-44af-88da-476e816a6e38.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626120/tapavis_tenant_mecanique_generale_martin_tremblay_inc/mise-au-point_2db706ff-369a-4032-aefe-e8db6283c4c6.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626121/tapavis_tenant_mecanique_generale_martin_tremblay_inc/climatisation_a71dd939-c67b-465d-a873-5dca01ff5e43.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626121/tapavis_tenant_mecanique_generale_martin_tremblay_inc/systeme-de-refroidissement_d982472c-6060-44a4-9b02-63ed1ca55f58.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626124/tapavis_tenant_mecanique_generale_martin_tremblay_inc/transmission_9734e4a1-db08-42fb-bb0f-34c56f5f5ef4.png"
  }
};
