/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mr_mecanicien).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624684/tapavis_tenant_mr_mecanicien/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624684/tapavis_tenant_mr_mecanicien/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624694/tapavis_tenant_mr_mecanicien/hero_911c4d8e-5626-4801-906a-f6a16c6c3f9b.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624695/tapavis_tenant_mr_mecanicien/vidange-huile_2238daf1-1c53-4de7-8e00-80ac17190a51.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624695/tapavis_tenant_mr_mecanicien/mecanique-generale_166c8f65-464c-4438-9f31-5a5faaa1b38d.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624695/tapavis_tenant_mr_mecanicien/freins_6badea79-5d37-47a8-b781-2e1ca343fd46.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624705/tapavis_tenant_mr_mecanicien/equilibrage-rotation-pneus_61cefb06-8307-438c-80fb-a8932fcbbe50.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624705/tapavis_tenant_mr_mecanicien/silencieux_1d58221a-2347-4328-8335-1b5631844591.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624705/tapavis_tenant_mr_mecanicien/suspension_429d48ef-2621-4cd5-926e-eef19f64ea81.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624707/tapavis_tenant_mr_mecanicien/systeme-de-refroidissement_a54a882a-da6a-4176-80f4-4896fc903164.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624716/tapavis_tenant_mr_mecanicien/climatisation_cca7b7a6-2e95-485e-8400-55b934e19504.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624717/tapavis_tenant_mr_mecanicien/mise-au-point_4d989e9e-a353-4f69-83b2-64487ee6e4f0.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624717/tapavis_tenant_mr_mecanicien/transmission_37a21b20-0149-40fd-afbd-b2c09ae0a149.png"
  }
};
