ALTER TABLE tracks ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS track_no INTEGER;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS release_date DATE;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS audio_url TEXT;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS duration TEXT;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS ticket_url TEXT;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS sold_out INTEGER DEFAULT 0;
ALTER TABLE shows ADD COLUMN IF NOT EXISTS price TEXT;
