/**
 * Atelier mécanique AFL — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "silencieux",
    "icon": "exhaust",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Spécialité : échappement",
    "name_en": "Specialty: exhaust",
    "tagline": "Silencieux, tuyaux et supports — la spécialité du garage.",
    "tagline_en": "Mufflers, pipes and hangers — the garage’s specialty.",
    "body": "Le sel de nos hivers est dur pour l’échappement. Un silencieux percé ou un tuyau rouillé rend la voiture bruyante et peut laisser entrer des gaz dans l’habitacle. L’inspection couvre le silencieux, les tuyaux, les supports et les joints.",
    "body_en": "Winter road salt is hard on an exhaust. A holed muffler or a rusted pipe makes the car loud and can let fumes into the cabin. The inspection covers the muffler, pipes, hangers and gaskets.",
    "signs": "[\"Grondement plus fort qu’avant\",\"Cliquetis sous le véhicule\",\"Odeur de gaz d’échappement dans l’habitacle\"]",
    "signs_en": "[\"A louder rumble than before\",\"Rattling under the car\",\"Exhaust smell inside the cabin\"]",
    "confirmed": 1
  },
  {
    "slug": "mecanique-generale",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Mécanique générale",
    "name_en": "General repair",
    "tagline": "Diagnostic, freins, courroies, direction : on trouve la cause, on répare.",
    "tagline_en": "Diagnostics, brakes, belts, steering: we find the cause and fix it.",
    "body": "Un bruit nouveau, un voyant qui s’allume, une conduite qui a changé : la mécanique générale commence par un diagnostic. Le véhicule est inspecté, les codes d’erreur sont lus, et vous recevez une explication claire de ce qui se passe avant toute réparation.\nFreins, courroies, direction, démarreur, alternateur, batterie : la plupart des réparations courantes se font dans la même visite.",
    "body_en": "A new noise, a warning light, a car that drives differently: general repair starts with a diagnosis. The vehicle is inspected, fault codes are read, and you get a clear explanation of what is going on before any repair.\nBrakes, belts, steering, starter, alternator, battery: most everyday repairs are handled in the same visit.",
    "signs": "[\"Un voyant « Check engine » allumé\",\"Grincement ou vibration au freinage\",\"Difficulté à démarrer\",\"Odeur de brûlé ou fuite sous le véhicule\"]",
    "signs_en": "[\"A \\\"Check engine\\\" light\",\"Squealing or vibration when braking\",\"Hard starts\",\"A burning smell or a leak under the car\"]",
    "confirmed": 1
  },
  {
    "slug": "freins",
    "icon": "brake",
    "duration_min": 90,
    "bookable": 1,
    "featured": 1,
    "name": "Changement des freins",
    "name_en": "Brake replacement",
    "tagline": "Plaquettes, disques, étriers et liquide : des freins qui répondent.",
    "tagline_en": "Pads, rotors, calipers and fluid: brakes that answer.",
    "body": "Les freins s’usent un peu à chaque arrêt. L’inspection mesure les plaquettes et les disques, vérifie les étriers, les conduites et le liquide de frein, puis vous dit ce qui est usé, ce qui peut attendre et ce qui presse.\nLe sel et les hivers québécois sont durs pour les étriers et les conduites : un bruit ou une vibration au freinage mérite d’être vérifié rapidement.",
    "body_en": "Brakes wear a little at every stop. The inspection measures the pads and rotors, checks the calipers, lines and brake fluid, then tells you what is worn, what can wait and what is urgent.\nSalt and Québec winters are hard on calipers and lines: a noise or vibration when braking deserves a quick check.",
    "signs": "[\"Grincement ou sifflement au freinage\",\"Vibration dans la pédale ou le volant\",\"La pédale est molle ou descend plus bas\",\"Le véhicule tire d’un côté au freinage\"]",
    "signs_en": "[\"Squealing or grinding when braking\",\"Vibration in the pedal or steering wheel\",\"The pedal feels soft or sinks lower\",\"The vehicle pulls to one side when braking\"]",
    "confirmed": 1
  },
  {
    "slug": "vidange-huile",
    "icon": "oil",
    "duration_min": 30,
    "bookable": 1,
    "featured": 1,
    "name": "Changement d’huile",
    "name_en": "Oil change",
    "tagline": "Huile, filtre et inspection des points essentiels.",
    "tagline_en": "Oil, filter and a check of the essentials.",
    "body": "Huile et filtre neufs selon les spécifications du fabricant, avec une inspection des points essentiels. Prix affiché par le garage sur PagesJaunes (septembre 2026) : à partir de 40,00 $.",
    "body_en": "New oil and filter to the maker’s specifications, with an inspection of the essentials. Price the garage lists on PagesJaunes (September 2026): from $40.00.",
    "signs": "[\"Le rappel d’entretien s’affiche\",\"Kilométrage atteint depuis la dernière vidange\",\"Huile foncée ou niveau bas\"]",
    "signs_en": "[\"The service reminder appears\",\"Mileage reached since the last change\",\"Dark oil or a low level\"]",
    "confirmed": 1
  },
  {
    "slug": "pose-pneus",
    "icon": "wheel",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Pneus : pose, balancement et vente",
    "name_en": "Tires: mounting, balancing and sales",
    "tagline": "Pneus neufs, pose et balancement.",
    "tagline_en": "New tires, mounting and balancing.",
    "body": "Au changement de saison, les pneus sont montés sur les jantes, balancés et installés, puis la pression est ajustée. Le garage vend aussi des pneus neufs. Prix affiché par le garage sur PagesJaunes (septembre 2026) : pose et balancement à partir de 39,95 $.",
    "body_en": "At the seasonal change, tires are mounted on the rims, balanced and installed, and the pressure is set. The garage also sells new tires. Price the garage lists on PagesJaunes (September 2026): mounting and balancing from $39.95.",
    "signs": "[\"Changement de saison\", \"Vibration à haute vitesse\", \"Pneus usés ou fissurés\"]",
    "signs_en": "[\"Change of season\", \"Vibration at highway speed\", \"Worn or cracked tires\"]",
    "confirmed": 1
  },
  {
    "slug": "entretien-hiver",
    "icon": "thermo",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Entretien avant l’hiver",
    "name_en": "Pre-winter maintenance",
    "tagline": "Prêt pour le froid, la neige et le sel.",
    "tagline_en": "Ready for cold, snow and salt.",
    "body": "Avant l’hiver, on vérifie ce que le froid met à l’épreuve : batterie, antigel, essuie-glaces et lave-glace, freins, éclairage et pneus d’hiver. Quelques vérifications à l’automne évitent la panne par le premier matin froid.",
    "body_en": "Before winter, the checks cover what the cold tests: battery, coolant, wipers and washer fluid, brakes, lights and winter tires. A few checks in the fall avoid a breakdown on the first cold morning.",
    "signs": "[\"L’automne arrive\", \"Démarrage lent par temps froid\", \"Essuie-glaces qui laissent des traces\"]",
    "signs_en": "[\"Fall is coming\", \"Slow starts in the cold\", \"Streaking wipers\"]",
    "confirmed": 1
  },
  {
    "slug": "esthetique-afl",
    "icon": "oil",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Esthétique et lavage",
    "name_en": "Detailing and washing",
    "tagline": "Lavage, cire, polissage et retouches.",
    "tagline_en": "Washing, wax, polishing and touch-ups.",
    "body": "Lavage intérieur et extérieur, nettoyage du calcium, lavage du moteur, cire, polissage, shampoing des sièges, nettoyage des jantes, polissage des phares et petites retouches de peinture. Prix affiché par le garage sur PagesJaunes (septembre 2026) : lavage intérieur 15,00 $, nettoyage du calcium 15,00 $, lavage du moteur 10,00 $, cire (voiture complète) 60,00 $, polissage complet + cire 200,00 $, shampoing des bancs 25,00 $ par banc, nettoyage des mags 5,00 $ chacun, polissage des phares avant 25,00 $, retouches de peinture : variable.",
    "body_en": "Interior and exterior washing, salt removal, engine wash, wax, polishing, seat shampoo, rim cleaning, headlight polishing and small paint touch-ups. Price the garage lists on PagesJaunes (September 2026): interior wash $15.00, salt removal $15.00, engine wash $10.00, full-car wax $60.00, full polish + wax $200.00, seat shampoo $25.00 per seat, rim cleaning $5.00 each, headlight polishing $25.00, paint touch-ups: varies.",
    "signs": "[\"Fin de l’hiver et du calcium\", \"Avant de vendre le véhicule\", \"Phares jaunis\", \"Sièges tachés\"]",
    "signs_en": "[\"End of the salt season\", \"Before selling the vehicle\", \"Yellowed headlights\", \"Stained seats\"]",
    "confirmed": 1
  }
];
