/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_station_service_ml).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538223/tapavis_tenant_station_service_ml/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538223/tapavis_tenant_station_service_ml/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538236/tapavis_tenant_station_service_ml/hero_04d76e11-42e8-4ce5-99f2-b111a8141509.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538235/tapavis_tenant_station_service_ml/vidange-huile_22d18502-fdb1-49d5-b9b3-033827358ea9.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538236/tapavis_tenant_station_service_ml/freins_852e2c68-7ac9-4a6d-8290-55265712ee3d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538237/tapavis_tenant_station_service_ml/mecanique-generale_6b78bf18-3ae6-466a-b3f2-584e6a0ff3a0.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538247/tapavis_tenant_station_service_ml/silencieux_8550f0ea-5332-4951-9339-b882c5a23334.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538247/tapavis_tenant_station_service_ml/suspension_18050018-a1d1-4895-96be-fd509b0e0b5b.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538247/tapavis_tenant_station_service_ml/equilibrage-rotation-pneus_e3f46474-37a8-4ef7-966f-046e6a4f91cc.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538250/tapavis_tenant_station_service_ml/systeme-de-refroidissement_0149b049-447d-44fe-b383-30f5aa2e9a4b.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538258/tapavis_tenant_station_service_ml/climatisation_78a2e9f2-20fd-4a1c-a51d-47d1460d9876.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538259/tapavis_tenant_station_service_ml/mise-au-point_8201d81a-13e1-4d8c-9ca7-0813ed599b5a.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790538259/tapavis_tenant_station_service_ml/transmission_84306d9a-61e7-4953-936f-a3f903ba7735.png"
  }
};
