/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_ay_daigle_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790972457/tapavis_tenant_garage_ay_daigle_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790972457/tapavis_tenant_garage_ay_daigle_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790972473/tapavis_tenant_garage_ay_daigle_inc/hero_3bada01e-5d3f-4074-9bf8-492a210800f3.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790972473/tapavis_tenant_garage_ay_daigle_inc/vidange-huile_c5bb2df9-3c9e-4778-b26e-152ff178c580.webp",
    "freins": "https://media.liasse.tech/upload/v1790972474/tapavis_tenant_garage_ay_daigle_inc/freins_27889f32-a69a-47af-9d69-04d0841ef8d3.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790972474/tapavis_tenant_garage_ay_daigle_inc/mecanique-generale_630d3d9b-0d78-4d85-bad4-c83773eb512e.webp",
    "suspension": "https://media.liasse.tech/upload/v1790972483/tapavis_tenant_garage_ay_daigle_inc/suspension_a6809f22-9098-4948-9ba5-02f6bf7ef375.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790972483/tapavis_tenant_garage_ay_daigle_inc/equilibrage-rotation-pneus_3088f046-bdf8-4223-aedd-37eb35dae512.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790972484/tapavis_tenant_garage_ay_daigle_inc/silencieux_8a3d242b-0be0-4c7f-b3fb-85b17b9333af.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790972484/tapavis_tenant_garage_ay_daigle_inc/systeme-de-refroidissement_a3eece8a-224e-4b3b-8c34-3b3c1585ed6c.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790972493/tapavis_tenant_garage_ay_daigle_inc/mise-au-point_73a78c7c-96f4-4a2a-a1d6-61b00db2a049.webp",
    "transmission": "https://media.liasse.tech/upload/v1790972495/tapavis_tenant_garage_ay_daigle_inc/transmission_2bb7e4aa-6202-4874-8a87-82783423dd94.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790972496/tapavis_tenant_garage_ay_daigle_inc/climatisation_999306da-a6c6-47e2-a5f4-fd0acb043fb3.webp"
  }
};
