/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_cloutier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812730/tapavis_tenant_garage_cloutier/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812730/tapavis_tenant_garage_cloutier/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812742/tapavis_tenant_garage_cloutier/hero_0ea8f3c2-fa42-4d2a-820b-849c46a6b6f4.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812743/tapavis_tenant_garage_cloutier/freins_cac3e9c9-b04b-4ccb-ab74-de9bb004fcce.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812743/tapavis_tenant_garage_cloutier/vidange-huile_bb3ce044-7d23-40cb-a53e-a8f12a945ac4.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812744/tapavis_tenant_garage_cloutier/mecanique-generale_4e7a0f3e-f6d9-47cd-a803-28ef956ff202.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812752/tapavis_tenant_garage_cloutier/silencieux_2fce4d96-75a5-4a78-afc3-fba24a895780.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812754/tapavis_tenant_garage_cloutier/suspension_f8269edf-6e26-45a0-abb2-445bce6241d8.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812754/tapavis_tenant_garage_cloutier/equilibrage-rotation-pneus_6ac3a5dc-29a8-497f-81ec-ced1d3385f6e.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812756/tapavis_tenant_garage_cloutier/systeme-de-refroidissement_5af7c570-3593-4457-8394-75b2f23e7f7b.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812766/tapavis_tenant_garage_cloutier/climatisation_6f8ee435-257b-4b0c-9d9c-14dc69bacab3.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812768/tapavis_tenant_garage_cloutier/mise-au-point_f1fca2d1-d6ca-42ab-805f-aac2b28c97fc.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812770/tapavis_tenant_garage_cloutier/transmission_682dfa7a-61ea-4699-8526-a1f7f437500b.png"
  }
};
