/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mcc_auto_enr).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929268/tapavis_tenant_mcc_auto_enr/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929268/tapavis_tenant_mcc_auto_enr/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929279/tapavis_tenant_mcc_auto_enr/hero_390fa0be-cd79-4b50-a66a-78bf0ef053be.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929278/tapavis_tenant_mcc_auto_enr/vidange-huile_c990b693-2401-4a9e-84c4-b8fb68276b7d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929279/tapavis_tenant_mcc_auto_enr/mecanique-generale_33b3931d-1171-4120-b3a8-054e61c0e9d8.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929280/tapavis_tenant_mcc_auto_enr/freins_ff721a69-a062-41c3-bb27-3a1992fbf892.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929290/tapavis_tenant_mcc_auto_enr/silencieux_cf37763d-0950-48d9-9c00-3af5fb393660.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929291/tapavis_tenant_mcc_auto_enr/suspension_ea6b0821-06a3-4036-b3dd-3bcb935152cb.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929292/tapavis_tenant_mcc_auto_enr/systeme-de-refroidissement_8af51736-f2c9-457e-a2a4-b35d20fbde3a.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929292/tapavis_tenant_mcc_auto_enr/equilibrage-rotation-pneus_1897261b-85b7-4fdb-ab7d-8a171ce6a40d.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929301/tapavis_tenant_mcc_auto_enr/climatisation_040a1d57-5141-48f1-831f-121a27b4c191.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929303/tapavis_tenant_mcc_auto_enr/transmission_7a11b53e-257a-4ef7-9f08-9605a5e4501f.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929303/tapavis_tenant_mcc_auto_enr/mise-au-point_e2cfa349-edcf-4f60-a075-59e47818de0a.png"
  }
};
