/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_alignement_berthier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813218/tapavis_tenant_alignement_berthier/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813218/tapavis_tenant_alignement_berthier/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815454/tapavis_tenant_alignement_berthier/hero_5d906603-c123-46d0-a063-c773406224c0.png",
  "services": {
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813235/tapavis_tenant_alignement_berthier/mise-au-point_be40e8dd-2934-4ee4-9555-5af396400dba.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815455/tapavis_tenant_alignement_berthier/freins_53c04cb0-6bf4-4811-965d-e7fe153e13c8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815455/tapavis_tenant_alignement_berthier/mecanique-generale_6e0b27fa-c5a7-4467-8abe-a3d72ce67112.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815455/tapavis_tenant_alignement_berthier/alignement_1a9db267-7aad-4c7b-acb1-d6c384a6e777.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815465/tapavis_tenant_alignement_berthier/vidange-huile_ebe93e5b-e8e4-44e7-9824-887a125f0c83.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815465/tapavis_tenant_alignement_berthier/silencieux_97b7649d-e8ea-46ec-a8cb-4f00af2d51c3.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815465/tapavis_tenant_alignement_berthier/equilibrage-rotation-pneus_700f7494-ffef-43cd-b152-51bdd661d671.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815466/tapavis_tenant_alignement_berthier/suspension_9aa35f36-52d4-4183-8140-e66f8699d3b5.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815476/tapavis_tenant_alignement_berthier/climatisation_772002aa-61dc-4cf3-b304-8be74f1203d6.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815477/tapavis_tenant_alignement_berthier/transmission_dcae8e94-efbd-43b1-89f4-66e0e9b59fc8.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815478/tapavis_tenant_alignement_berthier/systeme-de-refroidissement_f3b1f46c-4879-4ced-bd4d-97623bf5bb44.png"
  }
};
