/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_atelier_mecanique_mir_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577524/tapavis_tenant_atelier_mecanique_mir_auto/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577524/tapavis_tenant_atelier_mecanique_mir_auto/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577537/tapavis_tenant_atelier_mecanique_mir_auto/hero_1308c436-593d-43bd-9a6b-a2ddd386ec57.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577537/tapavis_tenant_atelier_mecanique_mir_auto/freins_c2232374-f7c4-40e3-b91d-64394647d6ce.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577537/tapavis_tenant_atelier_mecanique_mir_auto/vidange-huile_405a0e64-1962-4385-95f4-9a751bc2b70f.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577537/tapavis_tenant_atelier_mecanique_mir_auto/mecanique-generale_7096d578-7840-4741-a1ae-f7361fc1afde.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577547/tapavis_tenant_atelier_mecanique_mir_auto/silencieux_822e69c8-deae-4408-82c8-9ca35db16ef0.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577548/tapavis_tenant_atelier_mecanique_mir_auto/systeme-de-refroidissement_1110ddd1-1aee-495d-93d7-5180d3be96ea.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577550/tapavis_tenant_atelier_mecanique_mir_auto/suspension_da9d8cd0-dd11-47a6-ae38-951d847bbbfe.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577551/tapavis_tenant_atelier_mecanique_mir_auto/equilibrage-rotation-pneus_e6132908-03fa-4d78-9215-f147793d8f73.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577560/tapavis_tenant_atelier_mecanique_mir_auto/mise-au-point_8a928fed-eba0-48b8-a335-9e9f64cbfbc5.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577561/tapavis_tenant_atelier_mecanique_mir_auto/climatisation_f4fd67c6-2009-40a4-88ba-b37301de61dc.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577563/tapavis_tenant_atelier_mecanique_mir_auto/transmission_2c29a925-034c-498e-8a83-c597e7698e87.png"
  }
};
