/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mf_solution_mecanique_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812754/tapavis_tenant_mf_solution_mecanique_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812754/tapavis_tenant_mf_solution_mecanique_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812768/tapavis_tenant_mf_solution_mecanique_inc/hero_9f7d9404-bb76-4f1c-a731-48a5e1d7edf5.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812768/tapavis_tenant_mf_solution_mecanique_inc/freins_217ab3bc-a2d6-482e-93b0-30bbbfe1eed4.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812769/tapavis_tenant_mf_solution_mecanique_inc/mecanique-generale_ec005b7f-162b-417f-b414-b0224f259006.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812772/tapavis_tenant_mf_solution_mecanique_inc/vidange-huile_9b9f72cb-e7f4-42d7-873f-acb9f5235b40.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812787/tapavis_tenant_mf_solution_mecanique_inc/silencieux_777c78c1-5b9e-4b45-a714-324f0900f768.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812788/tapavis_tenant_mf_solution_mecanique_inc/equilibrage-rotation-pneus_8f25aaa8-accb-4cc6-b367-81109a0dfb04.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812789/tapavis_tenant_mf_solution_mecanique_inc/suspension_d2d7f121-58ef-4254-9e20-411f84e897eb.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812801/tapavis_tenant_mf_solution_mecanique_inc/systeme-de-refroidissement_c0b25834-7b95-45d8-ad47-6b93679644bf.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812805/tapavis_tenant_mf_solution_mecanique_inc/mise-au-point_a5f15719-c540-41e5-bd44-c25c79fd799d.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812805/tapavis_tenant_mf_solution_mecanique_inc/climatisation_a5b002d9-5b4d-4995-ab09-e01d7d51168c.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812806/tapavis_tenant_mf_solution_mecanique_inc/transmission_0faf08ea-af07-4f75-ac28-f2a0d9e05e7c.png"
  }
};
