/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_pneus_et_mecanique_st_augustin_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790971798/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790971798/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790971814/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/hero_2a1c425d-acbb-41db-b3a7-be3330ca4fb8.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790971814/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/freins_b17e840c-334e-40bd-80c2-1593aabf88b8.webp",
    "pneus": "https://media.liasse.tech/upload/v1790971815/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/pneus_a083bc91-4deb-42b3-a870-c9ce2c6bb904.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790971816/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/mecanique-generale_96189db1-5f08-4340-a9e5-da17c81baf20.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790971824/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/vidange-huile_1a79012f-814e-47c0-b18f-e4460d8915a5.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790971825/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/equilibrage-rotation-pneus_47f4d741-e508-477e-9ad0-8995bfeb5890.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790971825/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/silencieux_1a3af336-99a8-4f85-b557-9fd10cdb0edb.webp",
    "suspension": "https://media.liasse.tech/upload/v1790971825/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/suspension_7c64246e-3fcf-4dc6-a00f-d47e799c36cb.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790971833/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/systeme-de-refroidissement_94305dbc-5931-45bb-bcfd-4a499945d0d0.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790971835/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/climatisation_44efb8f8-5361-4b41-aa26-5ba5cf29231a.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790971835/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/mise-au-point_11a28044-bdc1-4153-afcf-a2571628513e.webp",
    "transmission": "https://media.liasse.tech/upload/v1790971836/tapavis_tenant_pneus_et_mecanique_st_augustin_inc/transmission_21f813c7-9aad-417e-b7cc-177ec46a421e.webp"
  }
};
