/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_mf_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791047972/tapavis_tenant_mf_mecanique/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791047972/tapavis_tenant_mf_mecanique/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791047989/tapavis_tenant_mf_mecanique/hero_6ce924a7-b3a4-4c34-b5de-c347ef88553b.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1791047988/tapavis_tenant_mf_mecanique/mecanique-generale_44b97903-da6d-4b52-854b-8f9525cfb07e.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791047988/tapavis_tenant_mf_mecanique/vidange-huile_02551529-35a2-4f26-97c7-699c8d8e27c5.webp",
    "freins": "https://media.liasse.tech/upload/v1791047990/tapavis_tenant_mf_mecanique/freins_e2494449-77a3-42db-a00b-cefea6aa261a.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791047997/tapavis_tenant_mf_mecanique/equilibrage-rotation-pneus_a9257abf-fc6c-4ca8-9420-0c10ffdbddda.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791047998/tapavis_tenant_mf_mecanique/silencieux_58082a2f-9ceb-4ef1-ab2e-2dbfe93a5100.webp",
    "suspension": "https://media.liasse.tech/upload/v1791047999/tapavis_tenant_mf_mecanique/suspension_e6945574-9542-4c5f-8634-4df2d2433c0b.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048003/tapavis_tenant_mf_mecanique/systeme-de-refroidissement_37b2673c-2f14-4526-9717-269fd9d42cc6.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048008/tapavis_tenant_mf_mecanique/mise-au-point_9b00611b-65c9-47d0-9e23-371825a57de6.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048008/tapavis_tenant_mf_mecanique/climatisation_a072b900-3769-400c-82a0-151edf0cad38.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048009/tapavis_tenant_mf_mecanique/transmission_31ad85fb-7488-4ba5-9552-c462e62764c4.webp"
  }
};
