/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_formule_rouge).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929378/tapavis_tenant_garage_formule_rouge/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929378/tapavis_tenant_garage_formule_rouge/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929388/tapavis_tenant_garage_formule_rouge/hero_802dbcfc-ef20-4e7a-b579-84097806f117.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929389/tapavis_tenant_garage_formule_rouge/vidange-huile_3711036f-09e6-4ebb-800d-83aba87dd74f.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929390/tapavis_tenant_garage_formule_rouge/freins_7bba978f-940c-46ae-8e46-a58b3b0a34e2.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929390/tapavis_tenant_garage_formule_rouge/mecanique-generale_6c45a795-7546-4f55-b1e9-b6c68cfe2fb5.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929399/tapavis_tenant_garage_formule_rouge/equilibrage-rotation-pneus_95a73684-3eff-4086-897b-33828adb380b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929399/tapavis_tenant_garage_formule_rouge/silencieux_72dd9097-b624-4c9c-b365-b82663676272.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929401/tapavis_tenant_garage_formule_rouge/suspension_802289df-4b4b-4365-a787-d2faae04f041.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929403/tapavis_tenant_garage_formule_rouge/systeme-de-refroidissement_2996552b-6afa-45c1-8ecb-35b224dd9e59.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929410/tapavis_tenant_garage_formule_rouge/mise-au-point_c0f1a156-6360-4c22-90ca-d5f0239a7080.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929411/tapavis_tenant_garage_formule_rouge/climatisation_7dee6e5e-eb9e-4ec3-bc09-be449a7976e3.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929415/tapavis_tenant_garage_formule_rouge/transmission_0e53d2f4-ca89-44bd-8dab-f572cc3657c2.png"
  }
};
