/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_station_service_gj_senc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961116/tapavis_tenant_station_service_gj_senc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961116/tapavis_tenant_station_service_gj_senc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961132/tapavis_tenant_station_service_gj_senc/hero_e728be83-8269-40c5-9b75-f75c12362526.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790961131/tapavis_tenant_station_service_gj_senc/freins_90465c00-d6b7-45c0-8365-f426ead78cdb.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961132/tapavis_tenant_station_service_gj_senc/mecanique-generale_e1f26532-74c0-4723-a9fd-4e4302504332.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790961136/tapavis_tenant_station_service_gj_senc/vidange-huile_d629f988-47b8-4e02-9e54-06f17d8a567d.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961142/tapavis_tenant_station_service_gj_senc/equilibrage-rotation-pneus_a8312a12-d388-4292-8a27-790f47a99516.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961142/tapavis_tenant_station_service_gj_senc/silencieux_79834f68-7eed-4e12-843a-cf9cc54adbbc.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961142/tapavis_tenant_station_service_gj_senc/suspension_6f5502cb-9957-47ff-b042-c3446aba86aa.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961147/tapavis_tenant_station_service_gj_senc/systeme-de-refroidissement_ab689b91-85d0-4a0e-9daf-92644657f992.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961152/tapavis_tenant_station_service_gj_senc/mise-au-point_0187610e-54a1-41b7-9fe9-65c999d0aea4.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961153/tapavis_tenant_station_service_gj_senc/climatisation_c74d5cf2-f2ba-4b51-a24c-9a02fe93df86.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961154/tapavis_tenant_station_service_gj_senc/transmission_36675ebd-25c2-466f-806d-73ab4a4fb8c1.webp"
  }
};
