/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_daniel_larose).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813031/tapavis_tenant_garage_daniel_larose/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813031/tapavis_tenant_garage_daniel_larose/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814657/tapavis_tenant_garage_daniel_larose/hero_6498b595-e0ca-4fe7-b6bb-a64dfbc9b81a.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813044/tapavis_tenant_garage_daniel_larose/vidange-huile_9f4ade5b-afff-49d2-9fbc-720869b0d6f8.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814076/tapavis_tenant_garage_daniel_larose/equilibrage-rotation-pneus_1109b53e-1043-4025-a597-0a8c6c2e7cba.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814077/tapavis_tenant_garage_daniel_larose/freins_0f3e614b-8415-474e-b54f-27572bf6d0a3.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814078/tapavis_tenant_garage_daniel_larose/mecanique-generale_b6ed13ea-3e7e-42ef-bfbd-05bce7a0fae0.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814086/tapavis_tenant_garage_daniel_larose/silencieux_6e83a1d2-96d9-4545-9d31-606333e6f8a2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814087/tapavis_tenant_garage_daniel_larose/suspension_fdbad86d-ced2-4fb8-bd84-28e092410af0.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814091/tapavis_tenant_garage_daniel_larose/systeme-de-refroidissement_c6cc5436-94c2-48d9-b81e-c0dd75732ea3.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814091/tapavis_tenant_garage_daniel_larose/climatisation_d274d01a-124f-4871-b504-a5b1c99d0cbe.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814097/tapavis_tenant_garage_daniel_larose/mise-au-point_925ca140-87f5-4c0f-b56e-467e50901400.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814098/tapavis_tenant_garage_daniel_larose/transmission_f54ea46b-0d03-4d6e-83d6-eff81e426be2.png"
  }
};
