ALTER TABLE routine_days ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE routine_days ADD COLUMN IF NOT EXISTS rank_label TEXT;
ALTER TABLE routine_days ADD COLUMN IF NOT EXISTS base_xp INTEGER DEFAULT 50;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS variation_label TEXT;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS xp_reward INTEGER DEFAULT 10;
ALTER TABLE exercises ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE hunter_stats ADD COLUMN IF NOT EXISTS longest_streak INTEGER DEFAULT 0;
