/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_p_poirier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048569/tapavis_tenant_garage_p_poirier/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048569/tapavis_tenant_garage_p_poirier/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791048585/tapavis_tenant_garage_p_poirier/hero_7b33af23-1b71-4284-89b2-e7f8087e8606.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791048584/tapavis_tenant_garage_p_poirier/freins_f61ca48d-5c5e-43f9-86e9-c472bd924bcd.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048585/tapavis_tenant_garage_p_poirier/vidange-huile_ea653e14-743c-43b1-bfda-35dcf55dbe40.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048585/tapavis_tenant_garage_p_poirier/mecanique-generale_10335877-00ff-4289-92be-7cbc333e8615.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048594/tapavis_tenant_garage_p_poirier/silencieux_e0715db3-8adf-42a4-be98-2c1bf0a59823.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048594/tapavis_tenant_garage_p_poirier/suspension_89c7faa9-55bb-4230-bdad-f8d94d9bd640.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048594/tapavis_tenant_garage_p_poirier/equilibrage-rotation-pneus_06b5da81-1bb4-4ffc-84b7-ba582f9fbd85.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048595/tapavis_tenant_garage_p_poirier/systeme-de-refroidissement_0252a83e-9cac-47f2-bdf2-dd117876f6b8.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048604/tapavis_tenant_garage_p_poirier/climatisation_2146b7de-b25e-4bf7-a628-a8db01f37c77.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048605/tapavis_tenant_garage_p_poirier/transmission_1bba0a40-9da4-432c-9c3b-82365521737f.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048605/tapavis_tenant_garage_p_poirier/mise-au-point_05fd39f3-c709-4a70-8626-878205b72f73.webp"
  }
};
