/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_gerard_aspirot).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556037/tapavis_tenant_garage_gerard_aspirot/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556037/tapavis_tenant_garage_gerard_aspirot/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556049/tapavis_tenant_garage_gerard_aspirot/hero_12a4c4aa-7fdd-4514-afed-286affbb8883.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556047/tapavis_tenant_garage_gerard_aspirot/vidange-huile_de898480-c5dc-4639-a726-826eafb549c6.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556049/tapavis_tenant_garage_gerard_aspirot/freins_deb31bfb-19c4-403a-be53-b8e7233a4736.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556049/tapavis_tenant_garage_gerard_aspirot/mecanique-generale_1e1711ab-0652-476d-91df-2ad685efcb6c.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556058/tapavis_tenant_garage_gerard_aspirot/equilibrage-rotation-pneus_21ec5223-b271-4bdd-851b-6b40c1463e1f.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556062/tapavis_tenant_garage_gerard_aspirot/systeme-de-refroidissement_5a503344-0086-4c34-8d53-aad5fb435f17.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556062/tapavis_tenant_garage_gerard_aspirot/silencieux_ed3b8ee9-da8a-4590-b86a-2efa1ef802c2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556062/tapavis_tenant_garage_gerard_aspirot/suspension_69f8c617-2110-4c9c-9643-49c71bd1659a.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556070/tapavis_tenant_garage_gerard_aspirot/climatisation_0f5bb197-2f4c-4760-918f-a7dc654b603e.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556073/tapavis_tenant_garage_gerard_aspirot/mise-au-point_46942f89-8f5c-49c6-9ded-8a285ee51f23.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790556074/tapavis_tenant_garage_gerard_aspirot/transmission_2ac9aa63-519a-411b-95ec-72c732c29e5e.png"
  }
};
