/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_s_f_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735143/tapavis_tenant_garage_s_f_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735143/tapavis_tenant_garage_s_f_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735155/tapavis_tenant_garage_s_f_mecanique/hero_a5842567-d9bb-4a3c-9416-19f202ed84b1.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735156/tapavis_tenant_garage_s_f_mecanique/vidange-huile_ff679403-3a5b-45ac-9f24-f1128d4f6fa8.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735155/tapavis_tenant_garage_s_f_mecanique/freins_d586fc89-b18e-4c56-81ff-4a33b2f69d69.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735156/tapavis_tenant_garage_s_f_mecanique/mecanique-generale_a6b892a6-7813-48c8-9acd-a91a373e2be4.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735166/tapavis_tenant_garage_s_f_mecanique/equilibrage-rotation-pneus_e7016be6-aabf-48a7-b09b-b8899eab75e1.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735166/tapavis_tenant_garage_s_f_mecanique/silencieux_a5e82435-99f6-4ccc-a0bd-81f15e727431.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735167/tapavis_tenant_garage_s_f_mecanique/suspension_6e197455-18b7-45c8-acb0-5b11fbbacaa1.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735169/tapavis_tenant_garage_s_f_mecanique/systeme-de-refroidissement_476283d4-3a81-4dda-b4a0-69775b37a06a.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735176/tapavis_tenant_garage_s_f_mecanique/mise-au-point_63c2fe21-6e60-4299-af2f-48f75d48c949.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735178/tapavis_tenant_garage_s_f_mecanique/climatisation_337f7c7a-188c-4cdf-aca8-5c0193279f16.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790735179/tapavis_tenant_garage_s_f_mecanique/transmission_2fa90f6b-317e-488c-aed0-296a80f2e2f0.png"
  }
};
