/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_et_pneu_1500).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310424/tapavis_tenant_mecanique_et_pneu_1500/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310424/tapavis_tenant_mecanique_et_pneu_1500/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310436/tapavis_tenant_mecanique_et_pneu_1500/hero_bc532599-3364-4708-991e-9667ec702ea8.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310435/tapavis_tenant_mecanique_et_pneu_1500/vidange-huile_bc5b8651-be15-404e-8704-97b842ca7afc.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310438/tapavis_tenant_mecanique_et_pneu_1500/freins_82bdc4b3-fc9a-48ef-a8f6-deeabbde01f8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310439/tapavis_tenant_mecanique_et_pneu_1500/mecanique-generale_8493da8d-b298-499e-a72f-f1371daf608b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310447/tapavis_tenant_mecanique_et_pneu_1500/silencieux_e474fc90-3f2b-4ae8-a6c6-05cc5c329e14.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310448/tapavis_tenant_mecanique_et_pneu_1500/equilibrage-rotation-pneus_2c34d9e6-a1ab-4f43-bc1d-94e69922918a.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310448/tapavis_tenant_mecanique_et_pneu_1500/suspension_332cbee1-2efe-4646-b787-9ea9931487fd.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310451/tapavis_tenant_mecanique_et_pneu_1500/systeme-de-refroidissement_c5e573ce-f95a-47d4-8b77-d6506703b45e.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310460/tapavis_tenant_mecanique_et_pneu_1500/mise-au-point_ede052f7-689f-4f94-868a-a56a9dd83556.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310460/tapavis_tenant_mecanique_et_pneu_1500/climatisation_da0d3915-f238-4c91-817d-5221487d73ff.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310462/tapavis_tenant_mecanique_et_pneu_1500/transmission_c30cd184-a2a2-430c-934e-ef25d4532d3b.png"
  }
};
