ALTER TABLE roasts ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE roasts ADD COLUMN IF NOT EXISTS published INTEGER DEFAULT 1;
ALTER TABLE story_moments ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE hours ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE wholesale_enquiries ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'new';
