/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_rs_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812905/tapavis_tenant_rs_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812905/tapavis_tenant_rs_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812925/tapavis_tenant_rs_mecanique/hero_05f17c5b-2f47-4318-ae7a-6c3c8e666b0e.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812929/tapavis_tenant_rs_mecanique/vidange-huile_f8f3d267-7c81-4717-bcf6-3026a78c0cbe.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812931/tapavis_tenant_rs_mecanique/freins_bfae07e2-c32d-42f6-a8a8-7a8d8175270f.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812934/tapavis_tenant_rs_mecanique/mecanique-generale_74aa3ed9-c7d7-4f66-ab36-d2ca8a58ab8b.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812940/tapavis_tenant_rs_mecanique/equilibrage-rotation-pneus_149cd041-43a6-4af5-b18f-e436fe8b88d9.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812941/tapavis_tenant_rs_mecanique/suspension_41838bd0-e5b7-49af-a209-bbbac5a0f543.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812941/tapavis_tenant_rs_mecanique/silencieux_c06e1e51-2ed4-4a25-beab-ce4e60029fc4.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812950/tapavis_tenant_rs_mecanique/systeme-de-refroidissement_7dc7db71-f88d-4ea8-91b6-4edfcce3732e.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812961/tapavis_tenant_rs_mecanique/mise-au-point_10db9fac-6145-4290-bae2-2f938a7cd5c1.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812962/tapavis_tenant_rs_mecanique/transmission_ef9f3995-8e86-4782-980f-29d1c4befc0e.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812963/tapavis_tenant_rs_mecanique/climatisation_a74c41c6-81a2-4502-af6b-79e6f5dda885.png"
  }
};
