/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_royer_sherbrooke).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670200/tapavis_tenant_garage_royer_sherbrooke/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670200/tapavis_tenant_garage_royer_sherbrooke/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670211/tapavis_tenant_garage_royer_sherbrooke/hero_344aa97b-f209-4881-8bbf-282bc8351381.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670212/tapavis_tenant_garage_royer_sherbrooke/vidange-huile_207dfed1-8276-40fb-9589-7e76a60c32b2.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670213/tapavis_tenant_garage_royer_sherbrooke/freins_94f12719-e554-453f-ad65-422e2f3f251e.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670212/tapavis_tenant_garage_royer_sherbrooke/mecanique-generale_8567c8df-1c4f-47a7-982e-8b4e43cfd223.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670222/tapavis_tenant_garage_royer_sherbrooke/equilibrage-rotation-pneus_e08bbd2c-8582-4f7c-90fb-bbed60213f39.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670223/tapavis_tenant_garage_royer_sherbrooke/silencieux_4c705cdd-247b-441c-914f-eb73cd346c4f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670223/tapavis_tenant_garage_royer_sherbrooke/suspension_f8db450d-608a-49c9-9d06-73969bbea02f.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670224/tapavis_tenant_garage_royer_sherbrooke/systeme-de-refroidissement_b84b4315-a885-4b0f-835c-098f53df677f.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670235/tapavis_tenant_garage_royer_sherbrooke/mise-au-point_c9c90c07-f02d-4d23-ae90-498f9f37333e.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670236/tapavis_tenant_garage_royer_sherbrooke/climatisation_7be89767-9d1d-47e2-ac31-571fa6ae54b5.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670236/tapavis_tenant_garage_royer_sherbrooke/transmission_d1a0f38f-e47b-4283-8bb2-7966d8fd75cf.png"
  }
};
