ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS dietary TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'nouvelle';
