/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_marc_labrie).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626008/tapavis_tenant_garage_marc_labrie/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626008/tapavis_tenant_garage_marc_labrie/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626019/tapavis_tenant_garage_marc_labrie/hero_c24c0c1b-367b-4454-b31b-5191ded07234.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626018/tapavis_tenant_garage_marc_labrie/vidange-huile_b7901119-35eb-4463-9a98-00bd8efc2731.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626019/tapavis_tenant_garage_marc_labrie/freins_97b36fdf-4bb1-41d5-85bd-042cf940acdf.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626021/tapavis_tenant_garage_marc_labrie/mecanique-generale_91caf2ba-ac9a-4950-9be1-4feb653bfbd4.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626029/tapavis_tenant_garage_marc_labrie/silencieux_5442525c-77de-440b-929c-5c4261fd37c2.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626030/tapavis_tenant_garage_marc_labrie/suspension_79621460-42e7-4b3f-89fa-29f24c806506.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626030/tapavis_tenant_garage_marc_labrie/equilibrage-rotation-pneus_bbcf619c-b28f-4f14-94b4-35df08072e73.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626032/tapavis_tenant_garage_marc_labrie/systeme-de-refroidissement_d4ea16c9-3e3b-419b-b824-0136b78d6c78.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626042/tapavis_tenant_garage_marc_labrie/climatisation_2b9d5572-bae5-4956-802a-edae199b890e.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626042/tapavis_tenant_garage_marc_labrie/mise-au-point_ed6e2a0a-7019-4dcc-a8ee-2c0feaaaca3b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626043/tapavis_tenant_garage_marc_labrie/transmission_97e94047-5ad7-4634-8e30-0c1059d13a5e.png"
  }
};
