/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_j_p_vaillancourt).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963096/tapavis_tenant_garage_j_p_vaillancourt/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963096/tapavis_tenant_garage_j_p_vaillancourt/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963113/tapavis_tenant_garage_j_p_vaillancourt/hero_c69a159d-dcf0-4a8d-8c15-ff59ef9c2789.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790963112/tapavis_tenant_garage_j_p_vaillancourt/vidange-huile_0517a299-4fe4-47ac-ad09-d5a2a8737803.webp",
    "freins": "https://media.liasse.tech/upload/v1790963112/tapavis_tenant_garage_j_p_vaillancourt/freins_911473e2-47df-48b9-9968-e0e8b835b947.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963114/tapavis_tenant_garage_j_p_vaillancourt/mecanique-generale_e30f4f92-cb1e-4a8f-98af-3e01ca7c7e53.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963123/tapavis_tenant_garage_j_p_vaillancourt/equilibrage-rotation-pneus_de47390b-75df-4763-b999-327060cf33b0.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963123/tapavis_tenant_garage_j_p_vaillancourt/suspension_0c1ec396-998a-4957-8a1f-aaff3d2863bc.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963124/tapavis_tenant_garage_j_p_vaillancourt/silencieux_8ed2a006-d489-4b69-add6-b668089deb97.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963125/tapavis_tenant_garage_j_p_vaillancourt/systeme-de-refroidissement_e558f05d-4460-4696-b770-e87cd950c4c8.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963133/tapavis_tenant_garage_j_p_vaillancourt/climatisation_24fd48c6-f877-4ed8-8e0a-4d2452f09dee.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963134/tapavis_tenant_garage_j_p_vaillancourt/mise-au-point_cc9bfc42-b92c-4cce-b779-6826dafdb2af.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963136/tapavis_tenant_garage_j_p_vaillancourt/transmission_81849510-90b7-47d7-b30c-f99ba4e9e2a8.webp"
  }
};
