/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_kesy_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961159/tapavis_tenant_kesy_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961159/tapavis_tenant_kesy_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961175/tapavis_tenant_kesy_inc/hero_c6305bf0-3d45-4b85-ae42-643fcce79f96.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790961175/tapavis_tenant_kesy_inc/freins_e66541d2-41e7-4cb4-b842-5f1367eca352.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961176/tapavis_tenant_kesy_inc/mecanique-generale_eadba8b2-af72-4137-8283-ae53b5babac2.webp",
    "reparation-camions": "https://media.liasse.tech/upload/v1790961180/tapavis_tenant_kesy_inc/reparation-camions_829bf1c3-116d-4348-ba9c-af86eddf7548.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790961186/tapavis_tenant_kesy_inc/vidange-huile_181656d9-0af3-49ef-b89a-3f0255f1b8c9.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961186/tapavis_tenant_kesy_inc/equilibrage-rotation-pneus_01bc24a6-ec25-4a4d-9343-a95559c9523a.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961186/tapavis_tenant_kesy_inc/suspension_98bfad46-4f25-4191-ae14-7d9e7c5c692f.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961189/tapavis_tenant_kesy_inc/silencieux_f1981a5c-91a3-4492-83ff-0e04fba800b4.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961196/tapavis_tenant_kesy_inc/systeme-de-refroidissement_1e2bae64-a699-4a91-adcc-d861789d824b.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961197/tapavis_tenant_kesy_inc/mise-au-point_2d87dd52-7cd5-4bfa-abd5-e56b1ab5b115.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961197/tapavis_tenant_kesy_inc/climatisation_7a97f8eb-3fb3-45d2-b273-cb18008d2573.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961201/tapavis_tenant_kesy_inc/transmission_88fbdb32-047d-49b6-8ebb-90b9818971f0.webp"
  }
};
