/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_auto_chirwan).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623773/tapavis_tenant_auto_chirwan/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623773/tapavis_tenant_auto_chirwan/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623784/tapavis_tenant_auto_chirwan/hero_53dcdab6-1417-4586-befe-aacab52192ee.png",
  "services": {
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623785/tapavis_tenant_auto_chirwan/mecanique-generale_38dcbd9d-c969-45b4-9f31-eda0dbaa552b.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623786/tapavis_tenant_auto_chirwan/freins_53a97ff0-7ee1-4392-a124-7f6b8530833b.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623786/tapavis_tenant_auto_chirwan/vidange-huile_78d55c04-93d9-417f-81b5-9e9ec32bcf84.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623794/tapavis_tenant_auto_chirwan/equilibrage-rotation-pneus_f5b6c6ac-3ca6-4aed-a430-0e8bd5d95ed1.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623795/tapavis_tenant_auto_chirwan/silencieux_7a970fc9-d922-451d-b274-36a665e52c84.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623797/tapavis_tenant_auto_chirwan/systeme-de-refroidissement_5f0cf515-4344-4483-bca2-75edbb2e1d88.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623798/tapavis_tenant_auto_chirwan/suspension_e83c8956-0145-4900-a06f-239db22f8353.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623805/tapavis_tenant_auto_chirwan/climatisation_4418dc32-64b1-4046-aad7-1e09956c5e18.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623807/tapavis_tenant_auto_chirwan/mise-au-point_e6de1dd9-0310-4ecf-be4e-3ee9cefef0da.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623809/tapavis_tenant_auto_chirwan/transmission_a9332d32-b909-4f93-8b76-0b7a89d82463.png"
  }
};
