ALTER TABLE creations ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE creations ADD COLUMN IF NOT EXISTS materials TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_url TEXT;