/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_j_r_deschenes_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963383/tapavis_tenant_garage_j_r_deschenes_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963383/tapavis_tenant_garage_j_r_deschenes_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963399/tapavis_tenant_garage_j_r_deschenes_inc/hero_6aef4425-d867-4167-acd7-a8ba8741090a.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790963399/tapavis_tenant_garage_j_r_deschenes_inc/freins_5ef0d493-1765-4fe7-84cf-69e8bf79955e.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790963401/tapavis_tenant_garage_j_r_deschenes_inc/vidange-huile_c6034ee4-7d52-426a-a258-102c4cc4eb32.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963402/tapavis_tenant_garage_j_r_deschenes_inc/mecanique-generale_b6e8d699-f8bb-4dd7-83b2-0b9d1abdb5b3.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963409/tapavis_tenant_garage_j_r_deschenes_inc/suspension_c6d4cac0-2f7c-486e-8d74-295cb02c2032.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963410/tapavis_tenant_garage_j_r_deschenes_inc/equilibrage-rotation-pneus_a07a085d-b5a6-4802-817c-3f08a04ac621.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963411/tapavis_tenant_garage_j_r_deschenes_inc/silencieux_634e5f75-893e-45e4-8b0b-de1a06f5ebb1.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963413/tapavis_tenant_garage_j_r_deschenes_inc/systeme-de-refroidissement_120bbffc-9466-4809-a9e7-5399e06be327.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963420/tapavis_tenant_garage_j_r_deschenes_inc/mise-au-point_c771e2a2-1e7e-4be6-affb-f62d3d3b6469.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963421/tapavis_tenant_garage_j_r_deschenes_inc/climatisation_d5d4869b-1d7d-4296-abb5-f2c55192c697.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963422/tapavis_tenant_garage_j_r_deschenes_inc/transmission_a37ce88c-d002-44d9-b101-e0a4334a46d5.webp"
  }
};
