/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mpb_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813001/tapavis_tenant_mpb_auto/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813001/tapavis_tenant_mpb_auto/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815802/tapavis_tenant_mpb_auto/hero_1bed5004-11ad-4e40-8d2c-92d3f5ea44f4.png",
  "services": {
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813021/tapavis_tenant_mpb_auto/equilibrage-rotation-pneus_bfa7fbf0-0543-4cc3-a2e9-1293c28e8062.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813023/tapavis_tenant_mpb_auto/climatisation_6987dc81-84bc-4f3f-96c1-80e79ced3e36.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813023/tapavis_tenant_mpb_auto/transmission_325f8fa0-74ee-4e40-85f5-ae79c25d03e1.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813037/tapavis_tenant_mpb_auto/freins_cc51fa02-f9c1-448a-9208-08f686fb56f7.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813037/tapavis_tenant_mpb_auto/mise-au-point_5a2e2160-3edc-4e9d-9167-e3e8061a158b.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813037/tapavis_tenant_mpb_auto/systeme-de-refroidissement_9fb30b00-2ad5-4669-93fb-eac32319eb0e.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815127/tapavis_tenant_mpb_auto/silencieux_929374eb-239b-4579-9ae6-12b8e0ab5e97.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815129/tapavis_tenant_mpb_auto/vidange-huile_6b60e7df-5f5a-4df2-87ab-b68ea2f51258.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815129/tapavis_tenant_mpb_auto/suspension_e8c34215-0cda-40c9-9791-bf956e130287.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815130/tapavis_tenant_mpb_auto/mecanique-generale_4e46f393-f8a9-46af-aeae-1bc2232bfcdd.png"
  }
};
