/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_top_g_garage).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310311/tapavis_tenant_top_g_garage/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310311/tapavis_tenant_top_g_garage/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310324/tapavis_tenant_top_g_garage/hero_316a57d6-d56e-4441-8bf9-872cc7f89ab4.png",
  "services": {
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310323/tapavis_tenant_top_g_garage/mecanique-generale_bc180a3a-4640-4f3d-968f-b6899cda697f.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310324/tapavis_tenant_top_g_garage/vidange-huile_32dd1e02-06a5-4864-ad2a-8723c98479be.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310325/tapavis_tenant_top_g_garage/freins_476aef7e-b4cd-4521-9816-23c20a3f2f4a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310334/tapavis_tenant_top_g_garage/silencieux_3d14e3fb-64be-4845-a3f8-4186972d7209.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310335/tapavis_tenant_top_g_garage/equilibrage-rotation-pneus_6976611e-4790-405a-891a-177505a3eda0.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310336/tapavis_tenant_top_g_garage/suspension_a9eff00f-1e5b-406b-8886-959aef5d2dc3.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310339/tapavis_tenant_top_g_garage/systeme-de-refroidissement_472d2520-2e1c-4bd8-b32f-d9bdd21bd8c6.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310347/tapavis_tenant_top_g_garage/mise-au-point_e277829e-e26b-4939-940c-c16c7cce29b6.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310347/tapavis_tenant_top_g_garage/climatisation_2eb36d9d-f952-46ad-8864-3f0614f602e7.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790310348/tapavis_tenant_top_g_garage/transmission_7f39c892-cee7-4d43-94e6-31aecd274b15.png"
  }
};
