/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_123).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732259/tapavis_tenant_mecanique_123/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732259/tapavis_tenant_mecanique_123/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732270/tapavis_tenant_mecanique_123/hero_22a45e19-ce38-4b8c-84a5-6f644d62d6d8.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732273/tapavis_tenant_mecanique_123/freins_589abdbc-7c73-4add-86b4-c38177f1e198.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732272/tapavis_tenant_mecanique_123/mecanique-generale_05495b79-0276-4766-95a0-034a427bdfe1.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732272/tapavis_tenant_mecanique_123/vidange-huile_1828f17c-1d62-42c7-b311-7848c68c3161.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732281/tapavis_tenant_mecanique_123/equilibrage-rotation-pneus_668269fc-f0d2-4d67-8f8c-92c37e460b2d.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732283/tapavis_tenant_mecanique_123/silencieux_a392e837-7ba0-4c67-a1c3-fa48f3d2ea3b.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732283/tapavis_tenant_mecanique_123/suspension_3014a0c4-dce5-49a3-8585-6558ee8b8a99.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732287/tapavis_tenant_mecanique_123/systeme-de-refroidissement_a6d32f4e-166b-40c8-a5ab-7425b3850e8a.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732293/tapavis_tenant_mecanique_123/climatisation_f0528588-8ee0-48b3-abc3-ed998822176c.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732295/tapavis_tenant_mecanique_123/transmission_6a82beeb-fbd1-4809-81c3-4462c806b35a.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732295/tapavis_tenant_mecanique_123/mise-au-point_4fe8d2e8-debe-4de2-9bb7-bf242c963618.png"
  }
};
