/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_jean_claude_grenier_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812987/tapavis_tenant_garage_jean_claude_grenier_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812987/tapavis_tenant_garage_jean_claude_grenier_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790816371/tapavis_tenant_garage_jean_claude_grenier_inc/hero_5b745a8d-b6bb-45c5-87c8-79a1ee42d960.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813000/tapavis_tenant_garage_jean_claude_grenier_inc/freins_a5ad8724-e1d5-45c6-9861-c5e5ea4abd5b.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815703/tapavis_tenant_garage_jean_claude_grenier_inc/vidange-huile_86db47ba-b4e9-4455-bf3e-64f9fcca073d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815705/tapavis_tenant_garage_jean_claude_grenier_inc/mecanique-generale_cbab48e1-8c6a-4bca-ab2d-e28e8abc061d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815705/tapavis_tenant_garage_jean_claude_grenier_inc/equilibrage-rotation-pneus_eccef9d5-23b7-4a45-9e61-2d1f335bb42f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815713/tapavis_tenant_garage_jean_claude_grenier_inc/silencieux_44831ca3-f35b-4340-bb78-f28f97e3cb77.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815714/tapavis_tenant_garage_jean_claude_grenier_inc/suspension_c5b1511b-3660-44b1-b475-c104694c5d06.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815717/tapavis_tenant_garage_jean_claude_grenier_inc/systeme-de-refroidissement_b83c9f96-57b1-4eb3-ba93-42096b8ba159.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815718/tapavis_tenant_garage_jean_claude_grenier_inc/climatisation_a955b96b-03ae-4fd0-a799-18f0db357770.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815723/tapavis_tenant_garage_jean_claude_grenier_inc/mise-au-point_8cf8e553-81fd-4165-9cea-e43e2b0a8c8e.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815725/tapavis_tenant_garage_jean_claude_grenier_inc/transmission_ba31c747-b708-4bb8-b55c-2573bb9f5abc.png"
  }
};
