/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_chez_ti_pierre).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671134/tapavis_tenant_garage_chez_ti_pierre/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671134/tapavis_tenant_garage_chez_ti_pierre/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671152/tapavis_tenant_garage_chez_ti_pierre/hero_b8fb38ae-1d4f-4885-b978-19b451e6f586.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671148/tapavis_tenant_garage_chez_ti_pierre/freins_0766ffb9-4a71-42c7-9937-698d36b7d272.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671149/tapavis_tenant_garage_chez_ti_pierre/mecanique-generale_f0e9a507-aeae-42f5-8079-8070e9ab2b5b.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671149/tapavis_tenant_garage_chez_ti_pierre/vidange-huile_244fe878-90a9-44af-bc18-408d639e7b60.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671160/tapavis_tenant_garage_chez_ti_pierre/suspension_ec7e728e-6cde-4aac-aa4c-e0ec406c87c1.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671160/tapavis_tenant_garage_chez_ti_pierre/equilibrage-rotation-pneus_6ead56b2-ea75-4dca-9a44-ce1ee7adb5ae.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671160/tapavis_tenant_garage_chez_ti_pierre/silencieux_8ddb9ed9-9829-41d3-8ab2-6ab8ccf0140d.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671164/tapavis_tenant_garage_chez_ti_pierre/systeme-de-refroidissement_c46216f7-1f62-4357-be60-338e49387872.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671171/tapavis_tenant_garage_chez_ti_pierre/climatisation_d1f3172e-6933-4527-8932-b007fd32377b.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671171/tapavis_tenant_garage_chez_ti_pierre/mise-au-point_51440928-9932-49a8-8d66-cd0574207851.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790671173/tapavis_tenant_garage_chez_ti_pierre/transmission_2771b10f-4279-4d60-aa3e-9c9cdeff6c02.png"
  }
};
