/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_122).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790972091/tapavis_tenant_garage_122/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790972091/tapavis_tenant_garage_122/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790973809/tapavis_tenant_garage_122/hero_13eac9d2-a37a-49cf-a82d-a7187f9d6e35.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790972107/tapavis_tenant_garage_122/vidange-huile_13aff84c-6f5f-4391-89b2-1a26e70c023c.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790972108/tapavis_tenant_garage_122/mecanique-generale_6e4886df-d8ab-449c-9c2d-e196a9d51947.webp",
    "freins": "https://media.liasse.tech/upload/v1790972108/tapavis_tenant_garage_122/freins_a2c686cc-7e15-45e1-8430-02746ea64fd3.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790972117/tapavis_tenant_garage_122/equilibrage-rotation-pneus_a04c2054-92a8-4fa8-a83c-04da56c1db89.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790972117/tapavis_tenant_garage_122/silencieux_f7e93337-038b-4c00-b215-3076ab103762.webp",
    "suspension": "https://media.liasse.tech/upload/v1790972117/tapavis_tenant_garage_122/suspension_1422939e-90a6-4944-911a-9c5451ffe754.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790972119/tapavis_tenant_garage_122/systeme-de-refroidissement_87afbc55-446f-44d8-a333-d6da07551528.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790972128/tapavis_tenant_garage_122/mise-au-point_0470b93d-17ba-4d7a-8161-cdafa61b1d79.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790972128/tapavis_tenant_garage_122/climatisation_ff84bdc0-0c9e-42d6-a844-bb03e81be46a.webp",
    "transmission": "https://media.liasse.tech/upload/v1790972129/tapavis_tenant_garage_122/transmission_3e634c0f-6e00-4857-9cf8-4319ce2bbd9d.webp"
  }
};
