ALTER TABLE services ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'entretien';
ALTER TABLE services ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'nouveau';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS image_url TEXT;
