/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_g_d_enr).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813115/tapavis_tenant_garage_g_d_enr/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813115/tapavis_tenant_garage_g_d_enr/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815861/tapavis_tenant_garage_g_d_enr/hero_c7a2a2ad-b812-457e-8522-22e6b8bd738f.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813127/tapavis_tenant_garage_g_d_enr/vidange-huile_1af7af84-25a1-4a6b-bbeb-81508a2172bd.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813129/tapavis_tenant_garage_g_d_enr/mecanique-generale_d987ca4e-a853-4969-b28d-d79845be2a45.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813130/tapavis_tenant_garage_g_d_enr/climatisation_d77eba09-7052-4fe6-a04d-504c9b6771e4.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815313/tapavis_tenant_garage_g_d_enr/freins_9857fd48-e452-48d7-9d2f-8837fc087af0.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815314/tapavis_tenant_garage_g_d_enr/suspension_3637cdf3-8edb-4730-879b-052690c2491f.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815314/tapavis_tenant_garage_g_d_enr/equilibrage-rotation-pneus_4669e2e3-0800-4c0c-a30d-99b672777b14.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815323/tapavis_tenant_garage_g_d_enr/silencieux_474e2611-9360-46fd-a563-00fc08919bbd.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815325/tapavis_tenant_garage_g_d_enr/mise-au-point_133ce5f3-8637-4239-b52a-79b1047e397b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815325/tapavis_tenant_garage_g_d_enr/transmission_730f3a1f-2f74-40be-ab0b-45848deba614.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815327/tapavis_tenant_garage_g_d_enr/systeme-de-refroidissement_58c74e6e-add5-412a-8c7a-4f494d953568.png"
  }
};
