/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_mecalourd_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791054360/tapavis_tenant_mecalourd_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791054360/tapavis_tenant_mecalourd_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791054375/tapavis_tenant_mecalourd_inc/hero_1459a531-e91b-4167-9158-41e5f9866229.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791054376/tapavis_tenant_mecalourd_inc/freins_7801285b-7824-454a-a9b5-304d961c51aa.webp",
    "reparation-camions": "https://media.liasse.tech/upload/v1791054378/tapavis_tenant_mecalourd_inc/reparation-camions_74f73517-ccec-4371-88b5-000f32e24077.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791054378/tapavis_tenant_mecalourd_inc/mecanique-generale_18370ed8-5e9a-4bf4-b93a-55ce784f47c7.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791054384/tapavis_tenant_mecalourd_inc/vidange-huile_5902e027-1071-4349-aa16-5034c8d5872f.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791054386/tapavis_tenant_mecalourd_inc/equilibrage-rotation-pneus_fb9ad043-4566-4a64-a043-063a8f49ab1d.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791054387/tapavis_tenant_mecalourd_inc/silencieux_74daa9f6-c752-494b-ab88-83cddcf10aa2.webp",
    "suspension": "https://media.liasse.tech/upload/v1791054388/tapavis_tenant_mecalourd_inc/suspension_04b1f485-bf76-4551-a9be-6a5e9d08c606.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791054395/tapavis_tenant_mecalourd_inc/systeme-de-refroidissement_052903e9-0114-4dd4-86c6-69e0cbf57019.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791054396/tapavis_tenant_mecalourd_inc/climatisation_995a1397-f453-4636-aa61-c26588e50fc9.webp",
    "transmission": "https://media.liasse.tech/upload/v1791054400/tapavis_tenant_mecalourd_inc/transmission_4dab33e3-1502-41f1-acf3-53d9a06307af.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791054413/tapavis_tenant_mecalourd_inc/mise-au-point_61d21d79-af7d-47c3-923a-097b4299dea1.webp"
  }
};
