/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_jean_guy_dicaire).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961927/tapavis_tenant_garage_jean_guy_dicaire/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961927/tapavis_tenant_garage_jean_guy_dicaire/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961943/tapavis_tenant_garage_jean_guy_dicaire/hero_2ea2dc0b-9d52-4180-9b83-fa4a13af984d.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790961945/tapavis_tenant_garage_jean_guy_dicaire/freins_6cb7e928-24b6-43fe-8f1b-4c3d08ab0af6.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961946/tapavis_tenant_garage_jean_guy_dicaire/mecanique-generale_6ff1ca92-c1ba-4042-9539-15b227d4e379.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790961946/tapavis_tenant_garage_jean_guy_dicaire/vidange-huile_6de11745-cb3d-48be-8992-121763846599.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961953/tapavis_tenant_garage_jean_guy_dicaire/equilibrage-rotation-pneus_7745d59f-b055-4072-997e-fe065a8f484c.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961955/tapavis_tenant_garage_jean_guy_dicaire/suspension_db7fe0df-4482-439d-b374-8b50250ebd50.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961957/tapavis_tenant_garage_jean_guy_dicaire/silencieux_3b74d091-5841-45f4-a8e3-5286c0deaead.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961957/tapavis_tenant_garage_jean_guy_dicaire/systeme-de-refroidissement_309965b6-0f78-482a-8ac1-0837df7d0abd.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961965/tapavis_tenant_garage_jean_guy_dicaire/climatisation_7c3398ac-a18a-4aaa-a42d-e6532b6ccd85.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961965/tapavis_tenant_garage_jean_guy_dicaire/mise-au-point_64572d2d-9586-4510-ac66-1dac2f7b1e52.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961968/tapavis_tenant_garage_jean_guy_dicaire/transmission_75ac51ce-c7db-426a-a772-0241a699b0e6.webp"
  }
};
