/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_atelier_mg_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739629/tapavis_tenant_atelier_mg_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739629/tapavis_tenant_atelier_mg_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739639/tapavis_tenant_atelier_mg_mecanique/hero_8bdce38f-8d8a-4f95-89d3-73b7f319d44b.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739639/tapavis_tenant_atelier_mg_mecanique/vidange-huile_e445fab3-08ec-466a-9c9a-1e896607b061.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739640/tapavis_tenant_atelier_mg_mecanique/mecanique-generale_ee15ffaf-23be-409f-a672-435a1cdc0b07.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739641/tapavis_tenant_atelier_mg_mecanique/freins_2409291b-86b9-404e-aa95-a86a6d238db9.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739650/tapavis_tenant_atelier_mg_mecanique/silencieux_8e506114-fbb2-4b58-9103-f8a07236252f.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739650/tapavis_tenant_atelier_mg_mecanique/equilibrage-rotation-pneus_94dee17c-dcb6-42ec-bf55-81888a650be1.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739653/tapavis_tenant_atelier_mg_mecanique/systeme-de-refroidissement_836c2912-9b97-47ec-92b6-9f4fb62b0177.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739660/tapavis_tenant_atelier_mg_mecanique/mise-au-point_b9d74928-e894-476e-83d2-1008687b4da4.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739661/tapavis_tenant_atelier_mg_mecanique/climatisation_5a205924-0795-4f1e-a58c-3c4749acd8bc.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739664/tapavis_tenant_atelier_mg_mecanique/transmission_bd4c3228-3d36-43a5-bb0b-fd2771ee5f3f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739694/tapavis_tenant_atelier_mg_mecanique/suspension_c2ea0ae3-9710-41ba-b84d-1563ca14fd09.png"
  }
};
