ALTER TABLE posts ADD COLUMN IF NOT EXISTS season TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS price_unit TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS season TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'Soumission';