module.exports = function(services){
  const router = require('express').Router();
  const db = services.db;

  var T = { fr: { nav_home:'Accueil', nav_services:'Services', nav_shop:'Boutique', nav_tips:'Conseils', nav_contact:'Contact', nav_booking:'Rendez-vous', nav_quote:'Soumission gratuite', nav_cart:'Panier', nav_orders:'Mes commandes', login:'Connexion', cta_quote:'Soumission gratuite', cta_book:'Prendre rendez-vous', add_cart:'Ajouter au panier', foot_rights:'Tous droits réservés.' } };

  function formatPrice(v){ if(v===null||v===undefined||v==='') return 'Sur demande'; return Number(v).toFixed(2).replace('.',',')+' $'; }
  function formatDate(d){ try{ return new Date(d).toLocaleDateString('fr-CA',{year:'numeric',month:'long',day:'numeric'}); }catch(e){ return ''; } }
  function truncate(s,n){ if(!s) return ''; s=String(s); return s.length>n ? s.slice(0,n).trim()+'…' : s; }
  function escapeHtml(s){ if(s===null||s===undefined) return ''; return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); }
  function currentSeason(){ var m=new Date().getMonth()+1; if(m>=12||m<=3) return {key:'hiver',label:'Hiver',service:'Déneigement',color:'#3E6E8E'}; if(m>=10) return {key:'automne',label:'Automne',service:'Ramassage de feuilles',color:'#E2701E'}; return {key:'ete',label:'Belle saison',service:'Entretien de pelouse',color:'#256B42'}; }

  async function getSettings(){ var o={}; try{ var rows=await db.all('SELECT key,value FROM admin_settings'); rows.forEach(function(r){ o[r.key]=r.value; }); }catch(e){} o.business_name=o.business_name||services.config.businessName||services.config.displayName||'Lamontagne Raymond'; o.contact_email=o.contact_email||services.config.contactEmail||''; o.contact_phone=o.contact_phone||services.config.contactPhone||''; o.business_address=o.business_address||services.config.businessAddress||''; return o; }

  function applyTextOverrides(t,settings,lang){ for(var k in settings){ if(k.indexOf('text_')===0 && k.lastIndexOf('_'+lang)===k.length-(lang.length+1)){ var key=k.slice(5,-(lang.length+1)); if(key) t[key]=settings[k]; } } return t; }

  async function renderPage(req,res,view,extra){ var settings=await getSettings(); var t=applyTextOverrides(Object.assign({},T.fr),settings,'fr'); res.render(view, Object.assign({ settings:settings, t:t, lang:'fr', user:(req.user||null), season:currentSeason(), formatPrice:formatPrice, formatDate:formatDate, truncate:truncate, escapeHtml:escapeHtml }, extra||{})); }

  async function count(table,where,params){ try{ var r=await db.get('SELECT COUNT(*)::int AS c FROM '+table+(where?(' WHERE '+where):''), params||[]); return r?r.c:0; }catch(e){ return 0; } }

  var MODULES = {
   services:{ table:'services', label:'Services', orderBy:'sort_order ASC, id ASC', fields:[
    {name:'name',type:'text',required:true,maxLength:120,label:'Nom du service',description:'Nom affiché sur les cartes de service.',placeholder:'ex. Tonte de pelouse'},
    {name:'description',type:'textarea',label:'Description',description:'Décrit ce que comprend le service.',placeholder:'ex. Tonte hebdomadaire, bordures incluses…'},
    {name:'price',type:'number',min:0,step:0.01,label:'Prix (à partir de)',description:'Prix de départ en dollars. Laissez vide pour afficher « Sur soumission ».',placeholder:'ex. 35'},
    {name:'price_unit',type:'text',label:'Unité de prix',description:'Texte affiché avec le prix.',placeholder:'ex. par visite'},
    {name:'season',type:'select',options:['Été','Automne','Hiver','Toutes saisons'],label:'Saison',description:'Détermine la couleur de l onglet du service.'},
    {name:'image_url',type:'image',label:'Image',description:'Photo du service. Format recommandé : 800x600px.'},
    {name:'featured',type:'boolean',default:true,label:'En vedette',description:'Affiche le service sur la page d accueil.'},
    {name:'sort_order',type:'number',min:0,step:1,label:'Ordre',description:'Plus petit = affiché en premier.',placeholder:'0'}
   ]},
   products:{ table:'products', label:'Boutique', orderBy:'featured DESC, id DESC', fields:[
    {name:'name',type:'text',required:true,label:'Nom du produit',description:'Nom affiché dans la boutique.',placeholder:'ex. Engrais à gazon 20 kg'},
    {name:'description',type:'textarea',label:'Description',description:'Détails du produit.',placeholder:'ex. Engrais à libération lente…'},
    {name:'price',type:'number',required:true,min:0,step:0.01,label:'Prix ($)',description:'Prix en dollars.',placeholder:'ex. 24.99'},
    {name:'unit',type:'text',label:'Unité',description:'Unité de vente affichée.',placeholder:'ex. le sac'},
    {name:'category',type:'select',options:['Engrais','Semences','Outils','Déneigement','Autre'],label:'Catégorie',description:'Catégorie utilisée pour le filtre de la boutique.'},
    {name:'image_url',type:'image',label:'Image',description:'Photo du produit. Format recommandé : carré 800x800px.'},
    {name:'in_stock',type:'boolean',default:true,label:'En stock',description:'Décochez pour masquer le produit de la boutique.'},
    {name:'featured',type:'boolean',label:'En vedette',description:'Met le produit en avant sur la page d accueil.'}
   ]},
   posts:{ table:'posts', label:'Conseils', orderBy:'created_at DESC', fields:[
    {name:'title',type:'text',required:true,label:'Titre',description:'Titre de l article affiché dans la liste et en haut de la page.',placeholder:'ex. Quand faire la première tonte au printemps'},
    {name:'content',type:'textarea',label:'Contenu',description:'Texte complet. Séparez vos paragraphes par une ligne vide.',placeholder:'Rédigez votre conseil ici…'},
    {name:'image_url',type:'image',label:'Image',description:'Image principale. Format recommandé : 1200x630px paysage.'},
    {name:'category',type:'text',label:'Catégorie',description:'Regroupe les articles (ex. Pelouse, Feuilles, Neige).',placeholder:'ex. Pelouse'},
    {name:'season',type:'select',options:['Été','Automne','Hiver','Toutes saisons'],label:'Saison',description:'Saison associée à ce conseil.'},
    {name:'published',type:'boolean',default:true,label:'Publié',description:'Décochez pour garder en brouillon (caché du public).'}
   ]},
   testimonials:{ table:'testimonials', label:'Témoignages', orderBy:'id DESC', fields:[
    {name:'author',type:'text',required:true,label:'Nom du client',description:'Nom affiché sous le témoignage.',placeholder:'ex. Sylvie T.'},
    {name:'location',type:'text',label:'Ville',description:'Ville du client.',placeholder:'ex. Shawinigan'},
    {name:'content',type:'textarea',required:true,label:'Témoignage',description:'Le texte du témoignage.',placeholder:'ex. Service rapide et impeccable…'},
    {name:'rating',type:'number',min:1,max:5,step:1,label:'Note (1-5)',description:'Nombre d étoiles affichées.',placeholder:'5'},
    {name:'image_url',type:'image',label:'Photo (optionnel)',description:'Photo ou avatar du client. Carré 200x200px.'}
   ]},
   quotes:{ table:'quotes', label:'Soumissions / Contacts', orderBy:'created_at DESC', fields:[
    {name:'customer_name',type:'text',label:'Client',description:'Nom de la personne.'},
    {name:'email',type:'email',label:'Courriel',description:'Adresse courriel.'},
    {name:'phone',type:'text',label:'Téléphone',description:'Numéro de téléphone.'},
    {name:'address',type:'text',label:'Adresse',description:'Adresse du terrain.'},
    {name:'service_type',type:'text',label:'Type de service',description:'Service demandé.'},
    {name:'property_size',type:'text',label:'Taille du terrain',description:'Estimation de la taille.'},
    {name:'message',type:'textarea',label:'Message',description:'Détails de la demande.'},
    {name:'source',type:'select',options:['Soumission','Contact'],label:'Source',description:'Provenance de la demande.'},
    {name:'status',type:'select',options:['Nouveau','Contacté','Soumis','Gagné','Perdu'],label:'Statut',description:'Suivi de la demande.'}
   ]},
   bookings:{ table:'bookings', label:'Rendez-vous', orderBy:'created_at DESC', fields:[
    {name:'customer_name',type:'text',label:'Client',description:'Nom de la personne.'},
    {name:'email',type:'email',label:'Courriel',description:'Adresse courriel.'},
    {name:'phone',type:'text',label:'Téléphone',description:'Numéro de téléphone.'},
    {name:'address',type:'text',label:'Adresse',description:'Adresse du terrain.'},
    {name:'service',type:'text',label:'Service',description:'Service souhaité.'},
    {name:'preferred_date',type:'date',label:'Date souhaitée',description:'Date demandée.'},
    {name:'preferred_time',type:'text',label:'Moment',description:'Moment de la journée.'},
    {name:'message',type:'textarea',label:'Détails',description:'Précisions du client.'},
    {name:'status',type:'select',options:['Nouveau','Confirmé','Terminé','Annulé'],label:'Statut',description:'Suivi du rendez-vous.'}
   ]},
   orders:{ table:'orders', label:'Commandes', orderBy:'created_at DESC', fields:[
    {name:'customer_name',type:'text',label:'Client',description:'Nom du client.'},
    {name:'email',type:'email',label:'Courriel',description:'Courriel du client.'},
    {name:'phone',type:'text',label:'Téléphone',description:'Téléphone du client.'},
    {name:'address',type:'text',label:'Adresse',description:'Adresse de livraison.'},
    {name:'items',type:'readonly',label:'Articles',description:'Produits commandés.'},
    {name:'total',type:'readonly',label:'Total ($)',description:'Montant total de la commande.'},
    {name:'status',type:'select',options:['Reçue','Payée','En préparation','Livrée','Annulée'],label:'Statut',description:'Suivi de la commande.'},
    {name:'notes',type:'textarea',label:'Notes internes',description:'Notes privées non visibles par le client.'}
   ]}
  };
  var MODULE_META = [ {key:'services',icon:'list'},{key:'products',icon:'package'},{key:'posts',icon:'edit'},{key:'testimonials',icon:'star'},{key:'quotes',icon:'edit'},{key:'bookings',icon:'calendar'},{key:'orders',icon:'package'} ];
  var SETTINGS_FIELDS=[ {name:'tagline',type:'text',label:'Slogan',description:'Slogan affiché dans le pied de page.'}, {name:'hero_eyebrow',type:'text',label:'Surtitre de l accueil',description:'Petit texte au-dessus du titre principal.'}, {name:'hero_title',type:'text',label:'Titre de l accueil',description:'Grand titre de la page d accueil.'}, {name:'hero_subtitle',type:'textarea',label:'Sous-titre de l accueil',description:'Texte descriptif sous le titre principal.'}, {name:'about_title',type:'text',label:'Titre - À propos',description:'Titre de la section à propos.'}, {name:'about_text',type:'textarea',label:'Texte - À propos',description:'Paragraphe de présentation de l entreprise.'}, {name:'cta_title',type:'text',label:'Titre - Appel à l action',description:'Titre de la bannière de soumission.'}, {name:'cta_text',type:'textarea',label:'Texte - Appel à l action',description:'Texte de la bannière de soumission.'}, {name:'service_area_note',type:'text',label:'Territoire desservi',description:'Phrase listant les villes desservies.'}, {name:'business_hours',type:'text',label:'Heures d ouverture',description:'Affichées dans le pied de page et la page contact.'}, {name:'payment_instructions',type:'textarea',label:'Instructions de paiement',description:'Affichées à la confirmation de commande.'}, {name:'etransfer_email',type:'text',label:'Courriel pour virement Interac',description:'Courriel affiché pour le paiement Interac (laissez vide pour utiliser le courriel de contact).'}, {name:'guarantee_text',type:'text',label:'Texte de garantie',description:'Petite mention de garantie.'}, {name:'contact_phone',type:'text',label:'Téléphone',description:'Numéro de téléphone affiché sur le site.'}, {name:'contact_email',type:'email',label:'Courriel de contact',description:'Adresse courriel principale affichée sur le site.'}, {name:'business_address',type:'text',label:'Adresse',description:'Adresse de l entreprise.'}, {name:'business_name',type:'text',label:'Nom de l entreprise',description:'Nom affiché dans l en-tête et le pied de page.'} ];

  function requireAdmin(req,res,next){ if(!services.admin.isAdmin(req)) return res.status(403).json({error:'Accès refusé'}); next(); }
  function colsVals(m,body){ var cols=[],vals=[]; m.fields.forEach(function(f){ if(f.type==='readonly'||f.type==='hidden') return; if(!Object.prototype.hasOwnProperty.call(body,f.name)) return; var v=body[f.name]; if(f.type==='boolean') v=(v===true||v==='true'||v===1||v==='1'||v==='on')?1:0; else if(f.type==='number') v=(v===''||v===null||v===undefined)?null:Number(v); cols.push(f.name); vals.push(v); }); return {cols:cols,vals:vals}; }

  if(services.auth && services.auth.optionalAuth) router.use(services.auth.optionalAuth);
  router.use(async function(req,res,next){ if(req.method==='GET' && req.path.indexOf('/api')!==0 && req.path.indexOf('/admin')!==0 && req.path.indexOf('.')===-1){ try{ await db.run('INSERT INTO site_visits (path) VALUES ($1)',[req.path]); }catch(e){} } next(); });

  router.get('/', async function(req,res){ try{ var srv=await db.all('SELECT * FROM services ORDER BY sort_order ASC, id ASC'); var products=await db.all('SELECT * FROM products WHERE featured=1 AND in_stock=1 ORDER BY id DESC LIMIT 4'); var testimonials=await db.all('SELECT * FROM testimonials ORDER BY id DESC LIMIT 6'); var posts=await db.all('SELECT * FROM posts WHERE published=1 ORDER BY created_at DESC LIMIT 3'); await renderPage(req,res,'index',{services:srv,products:products,testimonials:testimonials,posts:posts}); }catch(e){ console.error('home',e.message); res.status(500).send('Erreur temporaire.'); } });
  router.get('/services', async function(req,res){ try{ var srv=await db.all('SELECT * FROM services ORDER BY sort_order ASC, id ASC'); await renderPage(req,res,'services',{services:srv}); }catch(e){ res.status(500).send('Erreur'); } });
  router.get('/boutique', async function(req,res){ try{ var cat=req.query.cat||null; var products; if(cat) products=await db.all('SELECT * FROM products WHERE category=$1 ORDER BY id DESC',[cat]); else products=await db.all('SELECT * FROM products ORDER BY featured DESC, id DESC'); var crows=await db.all("SELECT DISTINCT category FROM products WHERE category IS NOT NULL AND category<>'' ORDER BY category"); var categories=crows.map(function(r){return r.category;}); await renderPage(req,res,'boutique',{products:products,categories:categories,activeCat:cat}); }catch(e){ res.status(500).send('Erreur'); } });
  router.get('/boutique/:id', async function(req,res){ try{ var product=await db.get('SELECT * FROM products WHERE id=$1',[req.params.id]); if(!product) return res.redirect('boutique'); await renderPage(req,res,'produit',{product:product}); }catch(e){ res.redirect('boutique'); } });
  router.get('/conseils', async function(req,res){ try{ var posts=await db.all('SELECT * FROM posts WHERE published=1 ORDER BY created_at DESC'); await renderPage(req,res,'conseils',{posts:posts}); }catch(e){ res.status(500).send('Erreur'); } });
  router.get('/conseils/:id', async function(req,res){ try{ var post=await db.get('SELECT * FROM posts WHERE id=$1',[req.params.id]); if(!post||post.published===0) return res.redirect('conseils'); await renderPage(req,res,'article',{post:post}); }catch(e){ res.redirect('conseils'); } });
  router.get('/rendez-vous', async function(req,res){ try{ var srv=await db.all('SELECT * FROM services ORDER BY sort_order ASC, id ASC'); await renderPage(req,res,'rendezvous',{services:srv}); }catch(e){ res.status(500).send('Erreur'); } });
  router.get('/soumission', async function(req,res){ await renderPage(req,res,'soumission',{}); });
  router.get('/contact', async function(req,res){ await renderPage(req,res,'contact',{}); });
  router.get('/panier', async function(req,res){ await renderPage(req,res,'panier',{}); });
  router.get('/paiement', async function(req,res){ await renderPage(req,res,'paiement',{}); });
  router.get('/confirmation/:id', async function(req,res){ try{ var order=await db.get('SELECT * FROM orders WHERE id=$1',[req.params.id]); if(!order) return res.redirect('.'); var orderItems=[]; try{ orderItems=JSON.parse(order.items||'[]'); }catch(e){} await renderPage(req,res,'confirmation',{order:order,orderItems:orderItems}); }catch(e){ res.redirect('.'); } });
  router.get('/mes-commandes', async function(req,res){ await renderPage(req,res,'commandes',{}); });

  router.post('/api/soumission', async function(req,res){ try{ var b=req.body||{}; if(!b.customer_name || (!b.phone && !b.email)) return res.status(400).json({error:'Veuillez indiquer votre nom et un moyen de vous joindre.'}); await db.run('INSERT INTO quotes (customer_name,email,phone,address,service_type,property_size,message,source,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[b.customer_name,b.email||'',b.phone||'',b.address||'',b.service_type||'',b.property_size||'',b.message||'','Soumission','Nouveau']); try{ if(services.config.contactEmail){ await services.email.send({to:services.config.contactEmail,subject:'Nouvelle demande de soumission',html:'<p><b>'+b.customer_name+'</b> ('+(b.email||'')+' / '+(b.phone||'')+')</p><p>Service: '+(b.service_type||'')+'</p><p>Terrain: '+(b.property_size||'')+'</p><p>Adresse: '+(b.address||'')+'</p><p>'+(b.message||'')+'</p>'}); } }catch(em){ console.error('email',em.message); } res.json({success:true}); }catch(e){ console.error('soumission',e.message); res.status(500).json({error:'La demande n a pas pu être enregistrée.'}); } });
  router.post('/api/rendez-vous', async function(req,res){ try{ var b=req.body||{}; if(!b.customer_name || !b.phone) return res.status(400).json({error:'Veuillez indiquer votre nom et votre téléphone.'}); await db.run('INSERT INTO bookings (customer_name,email,phone,address,service,preferred_date,preferred_time,message,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)',[b.customer_name,b.email||'',b.phone||'',b.address||'',b.service||'',b.preferred_date||'',b.preferred_time||'',b.message||'','Nouveau']); try{ if(services.config.contactEmail){ await services.email.send({to:services.config.contactEmail,subject:'Nouvelle demande de rendez-vous',html:'<p><b>'+b.customer_name+'</b> ('+(b.email||'')+' / '+(b.phone||'')+')</p><p>Service: '+(b.service||'')+'</p><p>Date: '+(b.preferred_date||'')+' '+(b.preferred_time||'')+'</p><p>Adresse: '+(b.address||'')+'</p><p>'+(b.message||'')+'</p>'}); } }catch(em){ console.error('email',em.message); } res.json({success:true}); }catch(e){ console.error('rdv',e.message); res.status(500).json({error:'La demande n a pas pu être enregistrée.'}); } });
  router.post('/api/contact', async function(req,res){ try{ var b=req.body||{}; if(!b.customer_name || !b.message) return res.status(400).json({error:'Veuillez remplir les champs obligatoires.'}); await db.run('INSERT INTO quotes (customer_name,email,phone,message,source,status) VALUES ($1,$2,$3,$4,$5,$6)',[b.customer_name,b.email||'',b.phone||'',b.message||'','Contact','Nouveau']); try{ if(services.config.contactEmail){ await services.email.send({to:services.config.contactEmail,subject:'Nouveau message de contact',html:'<p><b>'+b.customer_name+'</b> ('+(b.email||'')+' / '+(b.phone||'')+')</p><p>'+(b.message||'')+'</p>'}); } }catch(em){ console.error('email',em.message); } res.json({success:true}); }catch(e){ console.error('contact',e.message); res.status(500).json({error:'Le message n a pas pu être envoyé.'}); } });
  router.post('/api/order', async function(req,res){ try{ var b=req.body||{}; if(!b.customer_name || !b.email || !b.phone) return res.status(400).json({error:'Veuillez remplir vos coordonnées.'}); if(!Array.isArray(b.items) || !b.items.length) return res.status(400).json({error:'Votre panier est vide.'}); var total=0, lines=[]; for(var i=0;i<b.items.length;i++){ var it=b.items[i]; var p=await db.get('SELECT * FROM products WHERE id=$1',[it.id]); if(!p || p.in_stock===0) continue; var qty=Math.max(1,parseInt(it.qty)||1); total+=Number(p.price)*qty; lines.push({id:p.id,name:p.name,price:Number(p.price),qty:qty}); } if(!lines.length) return res.status(400).json({error:'Aucun produit valide dans le panier.'}); var uid=(req.user)?req.user.id:null; var r=await db.run('INSERT INTO orders (user_id,customer_name,email,phone,address,items,total,status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[uid,b.customer_name,b.email,b.phone,b.address||'',JSON.stringify(lines),total,'Reçue']); var orderId=r.lastInsertRowid; try{ if(services.config.contactEmail){ await services.email.send({to:services.config.contactEmail,subject:'Nouvelle commande #'+orderId,html:'<p>Commande de <b>'+b.customer_name+'</b> ('+b.email+' / '+b.phone+')</p><p>Total: '+total.toFixed(2)+' $</p>'}); } }catch(em){ console.error('email',em.message); } res.json({success:true,orderId:orderId}); }catch(e){ console.error('order',e.message); res.status(500).json({error:'La commande n a pas pu être enregistrée.'}); } });
  router.get('/api/my-orders', services.auth.requireAuth, async function(req,res){ try{ var rows=await db.all('SELECT * FROM orders WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]); res.json({orders:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/stats', requireAdmin, async function(req,res){ try{ var stats={}; stats.visitsTotal=await count('site_visits'); stats.visits7=await count('site_visits',"created_at>NOW()-INTERVAL '7 days'"); try{ stats.users=await services.auth.getUserCount(); }catch(e){ stats.users=0; } try{ stats.pushSubs=await services.push.getSubscriptionCount(); }catch(e){ stats.pushSubs=0; } res.json(stats); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.get('/api/admin/modules', requireAdmin, function(req,res){ res.json({ modules: MODULE_META.map(function(mm){ var m=MODULES[mm.key]; return {key:mm.key,label:m.label,icon:mm.icon,fields:m.fields}; }), settingsFields:SETTINGS_FIELDS }); });
  router.get('/api/admin/submissions', requireAdmin, async function(req,res){ try{ var quotes=await db.all('SELECT * FROM quotes ORDER BY created_at DESC LIMIT 50'); var bookings=await db.all('SELECT * FROM bookings ORDER BY created_at DESC LIMIT 50'); res.json({quotes:quotes,bookings:bookings}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/upload', requireAdmin, async function(req,res){ try{ var dataUri=(req.body||{}).dataUri; if(!dataUri) return res.status(400).json({error:'Aucune image fournie.'}); if(!(services.cloudinary && services.cloudinary.uploader && typeof services.cloudinary.uploader.upload==='function')) return res.status(503).json({error:'Téléversement indisponible.'}); var r=await services.cloudinary.uploader.upload(dataUri,{folder:'lamontagne-raymond'}); res.json({url:r.secure_url}); }catch(e){ console.error('upload',e.message); res.status(500).json({error:'Échec du téléversement.'}); } });
  router.post('/api/admin/generate-image', requireAdmin, async function(req,res){ var b=req.body||{}; if(!b.prompt) return res.status(400).json({error:'Veuillez décrire l image.'}); try{ var url=await services.ai.generateImage(b.prompt,{aspectRatio:b.aspectRatio||'4:3'}); res.json({imageUrl:url}); }catch(e){ console.error('genimg',e.message); res.status(500).json({error:'Échec de la génération. Téléversez une image manuellement.'}); } });
  router.get('/api/admin/settings', requireAdmin, async function(req,res){ try{ var rows=await db.all('SELECT key,value FROM admin_settings'); var o={}; rows.forEach(function(r){ o[r.key]=r.value; }); res.json(o); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/settings', requireAdmin, async function(req,res){ try{ var b=req.body||{}; if(!b.key) return res.status(400).json({error:'Clé manquante'}); await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()',[b.key,b.value||'']); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  // Explicit CRUD routes per module (validator requires named paths, not only /:module wildcard)
  router.get('/api/admin/posts', requireAdmin, async function(req,res){ try{ var m=MODULES.posts; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({posts:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/posts', requireAdmin, async function(req,res){ try{ var m=MODULES.posts; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/posts/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.posts; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/posts/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM posts WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/services', requireAdmin, async function(req,res){ try{ var m=MODULES.services; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({services:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/services', requireAdmin, async function(req,res){ try{ var m=MODULES.services; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/services/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.services; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/services/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM services WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/products', requireAdmin, async function(req,res){ try{ var m=MODULES.products; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({products:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/products', requireAdmin, async function(req,res){ try{ var m=MODULES.products; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/products/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.products; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/products/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM products WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/testimonials', requireAdmin, async function(req,res){ try{ var m=MODULES.testimonials; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({testimonials:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/testimonials', requireAdmin, async function(req,res){ try{ var m=MODULES.testimonials; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/testimonials/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.testimonials; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/testimonials/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM testimonials WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/bookings', requireAdmin, async function(req,res){ try{ var m=MODULES.bookings; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({bookings:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/bookings', requireAdmin, async function(req,res){ try{ var m=MODULES.bookings; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/bookings/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.bookings; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/bookings/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM bookings WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/quotes', requireAdmin, async function(req,res){ try{ var m=MODULES.quotes; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({quotes:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/quotes', requireAdmin, async function(req,res){ try{ var m=MODULES.quotes; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/quotes/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.quotes; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/quotes/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM quotes WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/api/admin/orders', requireAdmin, async function(req,res){ try{ var m=MODULES.orders; var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+m.orderBy); res.json({orders:rows}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/orders', requireAdmin, async function(req,res){ try{ var m=MODULES.orders; var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.put('/api/admin/orders/:id', requireAdmin, async function(req,res){ try{ var m=MODULES.orders; var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.concat([req.params.id]); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ res.status(500).json({error:'Erreur'}); } });
  router.delete('/api/admin/orders/:id', requireAdmin, async function(req,res){ try{ await db.run('DELETE FROM orders WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  // Generic fallback CRUD for any future modules
  router.get('/api/admin/:module', requireAdmin, async function(req,res){ try{ var m=MODULES[req.params.module]; if(!m) return res.status(404).json({error:'Module introuvable'}); var rows=await db.all('SELECT * FROM '+m.table+' ORDER BY '+(m.orderBy||'id DESC')); var o={}; o[req.params.module]=rows; res.json(o); }catch(e){ console.error('adminget',e.message); res.status(500).json({error:'Erreur'}); } });
  router.post('/api/admin/:module', requireAdmin, async function(req,res){ try{ var m=MODULES[req.params.module]; if(!m) return res.status(404).json({error:'Module introuvable'}); var cv=colsVals(m,req.body||{}); if(!cv.cols.length) return res.status(400).json({error:'Aucune donnée'}); var ph=cv.cols.map(function(c,i){ return '$'+(i+1); }); var r=await db.run('INSERT INTO '+m.table+' ('+cv.cols.join(',')+') VALUES ('+ph.join(',')+') RETURNING id',cv.vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[r.lastInsertRowid]); res.json({item:row}); }catch(e){ console.error('adminpost',e.message); res.status(500).json({error:'Erreur d enregistrement'}); } });
  router.put('/api/admin/:module/:id', requireAdmin, async function(req,res){ try{ var m=MODULES[req.params.module]; if(!m) return res.status(404).json({error:'Module introuvable'}); var cv=colsVals(m,req.body||{}); var set=cv.cols.map(function(c,i){ return c+'=$'+(i+1); }); set.push('updated_at=NOW()'); var vals=cv.vals.slice(); vals.push(req.params.id); await db.run('UPDATE '+m.table+' SET '+set.join(',')+' WHERE id=$'+vals.length,vals); var row=await db.get('SELECT * FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({item:row}); }catch(e){ console.error('adminput',e.message); res.status(500).json({error:'Erreur de mise à jour'}); } });
  router.delete('/api/admin/:module/:id', requireAdmin, async function(req,res){ try{ var m=MODULES[req.params.module]; if(!m) return res.status(404).json({error:'Module introuvable'}); await db.run('DELETE FROM '+m.table+' WHERE id=$1',[req.params.id]); res.json({success:true}); }catch(e){ res.status(500).json({error:'Erreur'}); } });

  router.get('/admin', async function(req,res){ if(!services.admin.isAdmin(req)) return res.redirect('admin/login'); try{ var settings=await getSettings(); var stats={}; stats.visitsTotal=await count('site_visits'); stats.visits7=await count('site_visits',"created_at>NOW()-INTERVAL '7 days'"); try{ stats.users=await services.auth.getUserCount(); }catch(e){ stats.users=0; } try{ stats.pushSubs=await services.push.getSubscriptionCount(); }catch(e){ stats.pushSubs=0; } stats.services=await count('services'); stats.products=await count('products'); stats.posts=await count('posts'); stats.testimonials=await count('testimonials'); stats.quotesNew=await count('quotes',"status='Nouveau'"); stats.bookingsNew=await count('bookings',"status='Nouveau'"); stats.ordersNew=await count('orders',"status IN ('Reçue','En préparation')"); var recentQuotes=await db.all('SELECT * FROM quotes ORDER BY created_at DESC LIMIT 6'); var recentOrders=await db.all('SELECT * FROM orders ORDER BY created_at DESC LIMIT 6'); res.render('admin',{settings:settings,stats:stats,recentQuotes:recentQuotes,recentOrders:recentOrders,formatDate:formatDate,active:'dashboard'}); }catch(e){ console.error('admin',e.message); res.status(500).send('Erreur'); } });
  router.get('/admin/settings', async function(req,res){ if(!services.admin.isAdmin(req)) return res.redirect('admin/login'); try{ var settings=await getSettings(); res.render('admin-settings',{settings:settings,active:'settings',settingsFields:SETTINGS_FIELDS}); }catch(e){ console.error('adminsettings',e.message); res.status(500).send('Erreur'); } });
  MODULE_META.forEach(function(mm){ router.get('/admin/'+mm.key, async function(req,res){ if(!services.admin.isAdmin(req)) return res.redirect('admin/login'); var settings=await getSettings(); var m=MODULES[mm.key]; res.render('admin-shell',{settings:settings,title:m.label,moduleKey:mm.key,moduleLabel:m.label,fields:m.fields,active:mm.key}); }); });

  router.get('*', function(req,res,next){ if(req.path.indexOf('/admin')===0 || req.path.indexOf('/api')===0) return next(); res.redirect('.'); });
  return router;
};
