/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecatech_jsn_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813193/tapavis_tenant_mecatech_jsn_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813193/tapavis_tenant_mecatech_jsn_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813225/tapavis_tenant_mecatech_jsn_inc/hero_2fef1586-0e91-423b-a6fc-4d503c33917f.png",
  "services": {
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813208/tapavis_tenant_mecatech_jsn_inc/suspension_55dd2f95-fcee-4d4b-adba-2f97ca87940e.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813226/tapavis_tenant_mecatech_jsn_inc/vidange-huile_ae774353-00cc-4fc7-9512-0af964e8f8de.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813228/tapavis_tenant_mecatech_jsn_inc/mecanique-generale_4d258838-45de-442e-b70d-1b2276af5558.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813234/tapavis_tenant_mecatech_jsn_inc/freins_76228e27-ae06-4bc5-8346-367f5c103cbc.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813239/tapavis_tenant_mecatech_jsn_inc/climatisation_39c26a9f-b7eb-415b-a9cb-efe76726b0a5.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813241/tapavis_tenant_mecatech_jsn_inc/transmission_88064b49-b03e-410f-b398-2b398f8bb58d.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815446/tapavis_tenant_mecatech_jsn_inc/silencieux_c37e37d0-8d58-45e8-ac2b-4c77202aab57.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815448/tapavis_tenant_mecatech_jsn_inc/mise-au-point_3eae244b-02dc-4c77-b118-47ed182b6cd6.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815448/tapavis_tenant_mecatech_jsn_inc/systeme-de-refroidissement_8bf36efa-2b24-4dac-84d8-a8904280f7bf.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815449/tapavis_tenant_mecatech_jsn_inc/equilibrage-rotation-pneus_b6675666-affa-4964-870f-e497c6ff32d5.png"
  }
};
