const T=require('./lib/i18n');
const site=require('./lib/site');
module.exports=async function(db,services) {
if(services && services.config) await site.seedConfig(db,services.config);
const settings={brand_electro:'Electro',brand_plus:'Plus',contact_verified:'0',location_verified:'0',hours_verified:'0',hero_photo_real:'0'};
for(const key of site.localizedKeys) settings[key]=JSON.stringify({fr:T.fr[key] || '',en:T.en[key] || ''});
for(const key of Object.keys(settings)) await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[key,settings[key]]);
await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',['_p_hero_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1789530614/tapavis_tenant_electro-plus/build_electro-plus_c5e3b918-7f4c-484f-851b-27a66fa28fb7.png']);
const products=[
['fridge','Réfrigérateur à portes françaises','French-door refrigerator','Un format à explorer. Demandez au magasin le modèle exact, les dimensions et l’état de chaque appareil réellement proposé.','A format to explore. Ask the store for the exact model, dimensions and condition of appliances actually available.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530612/tapavis_tenant_electro-plus/build_electro-plus_9dcda947-7bda-41fc-ab6d-39dc0a3f32c7.png'],
['range','Cuisinière à surface lisse','Smooth-top range','Repérez le type de commandes et la configuration qui vous conviennent. Les caractéristiques d’une offre réelle seront indiquées sur sa fiche.','Explore the controls and layout you prefer. Verified features of a real offer will appear in its listing.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_d3bd3c4f-ecf8-4533-a78e-1e0b78c2b214.png'],
['washer','Laveuse à chargement frontal','Front-load washer','Préparez les dimensions de votre espace avant de choisir. Ce visuel ne correspond pas à un appareil disponible confirmé.','Have your space measurements ready before choosing. This illustration does not represent a confirmed available appliance.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_1769b127-2745-4186-b893-e4b377dbb840.png'],
['dryer','Sécheuse avec porte vitrée','Dryer with glass door','Une idée de format pour votre coin lavage. Confirmez le modèle, les dimensions et les détails de l’appareil avec le magasin.','A possible format for your laundry space. Confirm the model, measurements and appliance details with the store.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530614/tapavis_tenant_electro-plus/build_electro-plus_6ed453ce-a0ee-4969-99f7-4148ff38659c.png'],
['dishwasher','Lave-vaisselle en acier inoxydable','Stainless-steel dishwasher','Comparez les dimensions et la disposition intérieure des modèles réellement présentés en magasin.','Compare the dimensions and interior layouts of models actually displayed in the store.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_7dfa017a-b27f-4bcb-be1b-5b4b5de857ba.png'],
['freezer','Congélateur vertical','Upright freezer','Un format de rangement à découvrir. Demandez quelles options sont réellement offertes avant de vous déplacer.','A storage format to explore. Ask which options are actually offered before visiting.','https://res.cloudinary.com/duhp69meg/image/upload/v1789530612/tapavis_tenant_electro-plus/build_electro-plus_97830977-12e1-45af-be58-e586129398a2.png']
];
for(const p of products) await db.run('INSERT INTO products (seed_key,category,title,title_en,description,description_en,image_url,is_example,verified,published) VALUES ($1,$2,$3,$4,$5,$6,$7,1,0,1) ON CONFLICT (seed_key) DO NOTHING',['example-'+p[0],p[0],p[1],p[2],p[3],p[4],p[5]]);
const posts=[
['preparer','Préparer sa visite','Prepare your visit','Notez le modèle qui vous intéresse et les dimensions de l’espace où il sera placé. Appelez pour confirmer les détails de l’appareil.','Write down the model you are interested in and the dimensions of its intended space. Call to confirm the appliance details.','Préparation','https://res.cloudinary.com/duhp69meg/image/upload/v1789530612/tapavis_tenant_electro-plus/build_electro-plus_9dcda947-7bda-41fc-ab6d-39dc0a3f32c7.png'],
['etat','Bien regarder l’état déclaré','Read the reported condition','Une fiche utile décrit l’appareil tel qu’il est. Ajoutez des photos précises des marques visibles et des détails connus.','A useful listing describes the appliance as it is. Add clear photos of visible marks and known details.','Fiches','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_d3bd3c4f-ecf8-4533-a78e-1e0b78c2b214.png'],
['reference','Garder la référence du modèle','Keep the model reference','Le nom de la marque et le numéro de modèle aident à parler du bon appareil lors d’un appel ou en magasin.','The brand and model number help identify the right appliance when calling or visiting.','Préparation','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_1769b127-2745-4186-b893-e4b377dbb840.png'],
['photos','Des photos qui montrent l’appareil','Photographs that show the appliance','Photographiez l’appareil entier et les détails importants. Une illustration ne doit jamais remplacer une photo réelle dans une offre confirmée.','Photograph the entire appliance and important details. An illustration must never replace an actual photograph in a confirmed offer.','Fiches','https://res.cloudinary.com/duhp69meg/image/upload/v1789530613/tapavis_tenant_electro-plus/build_electro-plus_7dfa017a-b27f-4bcb-be1b-5b4b5de857ba.png']
];
for(const p of posts) await db.run('INSERT INTO posts (seed_key,title,title_en,content,content_en,category,image_url,published) VALUES ($1,$2,$3,$4,$5,$6,$7,0) ON CONFLICT (seed_key) DO NOTHING',p);
};