/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_rs_customs).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048458/tapavis_tenant_rs_customs/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048458/tapavis_tenant_rs_customs/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050333/tapavis_tenant_rs_customs/hero_a45849a6-d27d-4627-9819-3eedf57edc2b.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791048472/tapavis_tenant_rs_customs/freins_7d890685-8f18-4259-a076-0a079f8efd50.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048473/tapavis_tenant_rs_customs/vidange-huile_ad21de27-29af-44e6-870a-36ed46e31613.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048475/tapavis_tenant_rs_customs/mecanique-generale_b912263e-0d4c-4540-9556-b68202fc3854.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048483/tapavis_tenant_rs_customs/suspension_b44edb5a-7cb0-4aac-8658-fbd821a46cfb.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048484/tapavis_tenant_rs_customs/silencieux_3ba8ab0b-c1f5-4e26-886b-c3737f32c794.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048484/tapavis_tenant_rs_customs/equilibrage-rotation-pneus_92674b74-0880-4972-8817-33b2233e0cb1.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048485/tapavis_tenant_rs_customs/systeme-de-refroidissement_35ee2a60-747e-4c11-a452-ed8c3756b95d.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048494/tapavis_tenant_rs_customs/climatisation_914f764c-193e-44ca-8acb-e19a36a5378d.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048495/tapavis_tenant_rs_customs/mise-au-point_657eafb8-6a83-4b27-99cb-f1970a8eeabc.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048495/tapavis_tenant_rs_customs/transmission_de4e5b3f-bd68-4976-a444-5442d7222910.webp"
  }
};
