/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_vision_nrd).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963867/tapavis_tenant_vision_nrd/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963867/tapavis_tenant_vision_nrd/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963883/tapavis_tenant_vision_nrd/hero_bee7820a-6a6a-45ea-9194-285924dc5bfc.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790963882/tapavis_tenant_vision_nrd/vidange-huile_341db43a-9942-4775-afe1-9a248caa16ee.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963883/tapavis_tenant_vision_nrd/mecanique-generale_0790df62-3440-4f03-8b9d-0828bb3fc3de.webp",
    "freins": "https://media.liasse.tech/upload/v1790963884/tapavis_tenant_vision_nrd/freins_6b5292d3-3c0e-414c-a75a-e534c835fa58.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963892/tapavis_tenant_vision_nrd/equilibrage-rotation-pneus_bd9cf382-0789-49db-aa23-0701ea60fd0e.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963892/tapavis_tenant_vision_nrd/silencieux_0f8926e4-f4d9-452f-832e-dafac4c2cb1c.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963894/tapavis_tenant_vision_nrd/suspension_cc3bc8b3-f80a-45a9-bda6-bcc1d7941f36.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963896/tapavis_tenant_vision_nrd/systeme-de-refroidissement_ac32accb-ff54-4b92-9f5e-f83121e69220.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963902/tapavis_tenant_vision_nrd/mise-au-point_fc289640-d8cc-41cf-96a2-0a9b43f7d61a.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963903/tapavis_tenant_vision_nrd/climatisation_fc050990-9552-46a0-bca4-a48b978da2e8.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963905/tapavis_tenant_vision_nrd/transmission_32b62c09-c6f6-498d-8fbe-eab16a8f3281.webp"
  }
};
