/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_saindon_1987_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732329/tapavis_tenant_garage_saindon_1987_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732329/tapavis_tenant_garage_saindon_1987_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732339/tapavis_tenant_garage_saindon_1987_inc/hero_0febb75e-2016-4088-9cc1-8579e5c8d1da.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732339/tapavis_tenant_garage_saindon_1987_inc/vidange-huile_bb56db5f-eefb-4010-a074-d4dd067acd91.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732340/tapavis_tenant_garage_saindon_1987_inc/mecanique-generale_45fead87-b029-4820-8e72-66040c5b89b6.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732341/tapavis_tenant_garage_saindon_1987_inc/freins_c0bb4d53-27cd-47b0-b681-3f7167f3089f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732350/tapavis_tenant_garage_saindon_1987_inc/suspension_8df853e0-7593-4922-8e82-5e1c8a274661.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732349/tapavis_tenant_garage_saindon_1987_inc/silencieux_0b93d3d3-f11d-42b3-aa0f-729bc6bdc066.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732350/tapavis_tenant_garage_saindon_1987_inc/equilibrage-rotation-pneus_efcc46b9-8da8-42bf-aa57-02063f042981.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732354/tapavis_tenant_garage_saindon_1987_inc/systeme-de-refroidissement_0266c963-ee6d-4a05-bd4e-d580943b2599.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732360/tapavis_tenant_garage_saindon_1987_inc/transmission_dd3f741b-8dd8-4f23-9034-358517fbae1c.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732360/tapavis_tenant_garage_saindon_1987_inc/mise-au-point_1ddd4750-3461-40a0-9d18-64c067c74a6d.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732362/tapavis_tenant_garage_saindon_1987_inc/climatisation_8450ff9c-a0a3-4479-a599-9d79d9239fb5.png"
  }
};
