/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_atelier_de_reparation_marcil).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791049679/tapavis_tenant_atelier_de_reparation_marcil/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791049679/tapavis_tenant_atelier_de_reparation_marcil/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050788/tapavis_tenant_atelier_de_reparation_marcil/hero_d1ffed6f-c547-42ea-971d-8d24f87aff2e.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791049693/tapavis_tenant_atelier_de_reparation_marcil/vidange-huile_95f47295-df1d-43e1-82f1-9e9160d5f347.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791049694/tapavis_tenant_atelier_de_reparation_marcil/mecanique-generale_00d9a9ca-835c-4e0f-941a-de52449bcb7e.webp",
    "freins": "https://media.liasse.tech/upload/v1791049695/tapavis_tenant_atelier_de_reparation_marcil/freins_81b6ea09-cbb6-43a3-b68f-fcc408e221a5.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791049703/tapavis_tenant_atelier_de_reparation_marcil/equilibrage-rotation-pneus_460d2557-1816-48ea-9272-121562588f75.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791049703/tapavis_tenant_atelier_de_reparation_marcil/silencieux_83733e92-f245-483b-87c6-5d9c33a6ead7.webp",
    "suspension": "https://media.liasse.tech/upload/v1791049704/tapavis_tenant_atelier_de_reparation_marcil/suspension_6f60821a-2a0b-47a2-bb54-a6ad36832b36.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791049706/tapavis_tenant_atelier_de_reparation_marcil/systeme-de-refroidissement_7331d2e7-057e-4b7e-a67c-20a11923fb00.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791049713/tapavis_tenant_atelier_de_reparation_marcil/mise-au-point_50da18e2-6e83-4353-a027-c6e3f203fe3c.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791049714/tapavis_tenant_atelier_de_reparation_marcil/climatisation_f99dc864-4959-4717-997f-9b904d66d4b6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791049714/tapavis_tenant_atelier_de_reparation_marcil/transmission_350e73cc-5191-4dd7-935e-bea7900f59ab.webp"
  }
};
