/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_lp_mecanique_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736000/tapavis_tenant_lp_mecanique_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736000/tapavis_tenant_lp_mecanique_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736011/tapavis_tenant_lp_mecanique_inc/hero_0f7d5336-b831-4af7-bb71-f588b6494a5c.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736011/tapavis_tenant_lp_mecanique_inc/vidange-huile_66904eae-59b6-4c0e-ad97-e2f9ce1d9441.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736011/tapavis_tenant_lp_mecanique_inc/freins_a13b6616-7c6d-44ac-81da-d0b78bdb560d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736012/tapavis_tenant_lp_mecanique_inc/mecanique-generale_e96d0f43-1fc3-483b-9a5c-8ce92f3c06f6.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736021/tapavis_tenant_lp_mecanique_inc/silencieux_1322ac65-e7d5-4679-8e54-d82c4b1ff2f4.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736021/tapavis_tenant_lp_mecanique_inc/equilibrage-rotation-pneus_6ca772f3-35f2-4898-95da-60ecf1d6ab91.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736021/tapavis_tenant_lp_mecanique_inc/suspension_37ae007c-ceca-49ba-9fb6-84447a633026.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736024/tapavis_tenant_lp_mecanique_inc/systeme-de-refroidissement_0bb88f35-84f4-48d6-b73a-063415eeb0fa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736032/tapavis_tenant_lp_mecanique_inc/transmission_a9dcf8c9-6bdf-4887-aff2-c712d3663bde.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736033/tapavis_tenant_lp_mecanique_inc/mise-au-point_7aa52b88-581e-431e-8eca-d8cc019864ba.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736034/tapavis_tenant_lp_mecanique_inc/climatisation_b9302bec-1cdc-4d96-8ecc-6f1cc8ed35f9.png"
  }
};
