/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_alignement_mila).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048969/tapavis_tenant_alignement_mila/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048969/tapavis_tenant_alignement_mila/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050587/tapavis_tenant_alignement_mila/hero_fba68cf5-b515-4e3d-949e-98e2abb44b0a.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791048984/tapavis_tenant_alignement_mila/freins_30c82c11-d526-4214-9bd3-f57154e2cfa5.webp",
    "alignement": "https://media.liasse.tech/upload/v1791048985/tapavis_tenant_alignement_mila/alignement_c81c12a1-b2ee-4e6d-a249-187c75ab5aed.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048986/tapavis_tenant_alignement_mila/mecanique-generale_42137ab5-005c-4e5a-b284-113f382ae199.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048995/tapavis_tenant_alignement_mila/silencieux_dcfdb401-ca6f-449f-a156-0738ddc12ca1.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048995/tapavis_tenant_alignement_mila/vidange-huile_8f20d93c-54b9-4485-bbd1-234d4450d266.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048995/tapavis_tenant_alignement_mila/equilibrage-rotation-pneus_066138ab-23ef-4912-b402-5a506bd9a58d.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048996/tapavis_tenant_alignement_mila/suspension_3376aea1-189e-43dc-943c-0840bcf7a61c.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791049004/tapavis_tenant_alignement_mila/systeme-de-refroidissement_b4ce9b09-eb80-4f78-b9e0-d1f81d8f87f6.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791049005/tapavis_tenant_alignement_mila/mise-au-point_6426def2-28a5-448a-a66e-735bc21b0f42.webp",
    "transmission": "https://media.liasse.tech/upload/v1791049006/tapavis_tenant_alignement_mila/transmission_ddcd9721-0141-43a1-ab15-7b721835cff1.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791049007/tapavis_tenant_alignement_mila/climatisation_aa51a136-b2ba-4fc2-b130-befab8b12f92.webp"
  }
};
