/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_luc_bougie_auto_electrique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048562/tapavis_tenant_luc_bougie_auto_electrique/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048562/tapavis_tenant_luc_bougie_auto_electrique/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050375/tapavis_tenant_luc_bougie_auto_electrique/hero_3fcbf0a8-c112-4919-9ea3-67f3d115fce8.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791048578/tapavis_tenant_luc_bougie_auto_electrique/freins_f867964f-861d-4732-aa09-1143b78e1e40.webp",
    "systeme-electrique": "https://media.liasse.tech/upload/v1791048579/tapavis_tenant_luc_bougie_auto_electrique/systeme-electrique_f3b2aa4c-226b-4852-a5fc-559e90b7a72e.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048580/tapavis_tenant_luc_bougie_auto_electrique/mecanique-generale_efdfe6aa-7b51-4147-b3b1-2b21508d0f4a.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048587/tapavis_tenant_luc_bougie_auto_electrique/vidange-huile_81d662ff-1451-4886-a7bd-1de92bef1b06.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048588/tapavis_tenant_luc_bougie_auto_electrique/suspension_06fa45d3-edd0-4b47-8008-7ab89f7f7a5a.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048589/tapavis_tenant_luc_bougie_auto_electrique/silencieux_76f726b7-402d-40e2-ba01-865e7469ba2b.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048590/tapavis_tenant_luc_bougie_auto_electrique/equilibrage-rotation-pneus_3e300d24-fe1a-4102-abf4-52fbd04a46df.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048596/tapavis_tenant_luc_bougie_auto_electrique/systeme-de-refroidissement_8f020a03-5da4-44d0-b0ee-9fab573a9f50.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048599/tapavis_tenant_luc_bougie_auto_electrique/climatisation_1ad5afd7-784e-493e-9632-733d25dca39f.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048599/tapavis_tenant_luc_bougie_auto_electrique/mise-au-point_bc3e1070-59aa-4340-90df-40245ae29e64.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048600/tapavis_tenant_luc_bougie_auto_electrique/transmission_5b5fdcd9-071f-474a-8f47-cdd639f2d581.webp"
  }
};
