/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_francois_duval).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962485/tapavis_tenant_garage_francois_duval/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962485/tapavis_tenant_garage_francois_duval/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963850/tapavis_tenant_garage_francois_duval/hero_cd0a5a07-c57a-4425-ab2f-e57d7f91449d.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790962501/tapavis_tenant_garage_francois_duval/vidange-huile_318e22a9-48b1-444d-92a0-0cce952367a0.webp",
    "freins": "https://media.liasse.tech/upload/v1790962502/tapavis_tenant_garage_francois_duval/freins_a36f10d6-67b6-4d09-baae-63840fc9fb9f.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962508/tapavis_tenant_garage_francois_duval/mecanique-generale_8459dcd5-505b-49d0-b1fb-a26a5fe332a5.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962510/tapavis_tenant_garage_francois_duval/equilibrage-rotation-pneus_404fb64e-82c4-4057-bf32-031b8f5199fc.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962512/tapavis_tenant_garage_francois_duval/silencieux_28bbae54-b0c7-4b6a-84e4-56dec68f81de.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962513/tapavis_tenant_garage_francois_duval/suspension_5f5a155c-6312-4b1d-bbc5-41fadebff3e7.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962519/tapavis_tenant_garage_francois_duval/systeme-de-refroidissement_f64bdb26-53ce-4ecc-9a0a-4c55eb0a4ec4.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790962521/tapavis_tenant_garage_francois_duval/climatisation_499c52f1-0b9d-47c9-ae3b-f28d52c93dad.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790962522/tapavis_tenant_garage_francois_duval/mise-au-point_8416bc61-5400-49b5-a323-3f3c8cb72ee5.webp",
    "transmission": "https://media.liasse.tech/upload/v1790962524/tapavis_tenant_garage_francois_duval/transmission_5dd0544f-934e-4b50-ac80-13fc2dadb4a1.webp"
  }
};
