/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_raymond_auclair_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962646/tapavis_tenant_garage_raymond_auclair_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962646/tapavis_tenant_garage_raymond_auclair_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790962663/tapavis_tenant_garage_raymond_auclair_inc/hero_b2f4d32b-8087-462e-9fe9-ca35155bcd24.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1790962661/tapavis_tenant_garage_raymond_auclair_inc/freins_a36e741d-d89b-45f1-8a7a-54aacfddc970.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790962663/tapavis_tenant_garage_raymond_auclair_inc/vidange-huile_d9aa52ec-8dd7-495c-a6ef-86d4771bc4c4.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962663/tapavis_tenant_garage_raymond_auclair_inc/mecanique-generale_89ebcd8e-14e2-44c1-aa4d-f480795ae4ad.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962672/tapavis_tenant_garage_raymond_auclair_inc/silencieux_0fb15a03-a94d-4155-8258-3edacb68a80d.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962672/tapavis_tenant_garage_raymond_auclair_inc/equilibrage-rotation-pneus_b77b3bb4-6e5b-47dc-9ed8-11c18e5d4b74.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962673/tapavis_tenant_garage_raymond_auclair_inc/suspension_23c14dc3-a3eb-4f00-86be-239e34c5c702.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962673/tapavis_tenant_garage_raymond_auclair_inc/systeme-de-refroidissement_aa6e7046-38c6-48dc-9908-621696f2a1a5.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790962684/tapavis_tenant_garage_raymond_auclair_inc/climatisation_595fd3f8-3e9c-4838-9c43-923e5a979bac.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790962684/tapavis_tenant_garage_raymond_auclair_inc/mise-au-point_5985ad88-cd58-4dd1-b4b0-8f778ac2c405.webp",
    "transmission": "https://media.liasse.tech/upload/v1790962685/tapavis_tenant_garage_raymond_auclair_inc/transmission_91bbab2d-00f9-48a7-965e-88d3bf3a028e.webp"
  }
};
