/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_cp).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812835/tapavis_tenant_mecanique_cp/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812835/tapavis_tenant_mecanique_cp/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815777/tapavis_tenant_mecanique_cp/hero_0f0ede62-217b-4335-ad4d-050c754f8878.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812861/tapavis_tenant_mecanique_cp/vidange-huile_b6ece43c-0167-4495-b4d3-4359c0334426.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812863/tapavis_tenant_mecanique_cp/freins_725fbce1-7b40-48a8-83f4-7f53a9c34d69.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812864/tapavis_tenant_mecanique_cp/mecanique-generale_0a616803-bc14-4c72-8ef7-30353d1dd8cf.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812874/tapavis_tenant_mecanique_cp/equilibrage-rotation-pneus_1253a904-2c33-4582-afbf-9e7249ddf294.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812880/tapavis_tenant_mecanique_cp/silencieux_b96da88f-4744-4feb-9337-493943962ae8.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812882/tapavis_tenant_mecanique_cp/suspension_84cdf6aa-632e-4761-a37d-a91ea025352c.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812888/tapavis_tenant_mecanique_cp/systeme-de-refroidissement_3bf956f0-bbfd-40d2-9ac5-336f1ed0360f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812896/tapavis_tenant_mecanique_cp/climatisation_c913efbd-43be-4258-9d3a-45eda795da56.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812905/tapavis_tenant_mecanique_cp/mise-au-point_b0a25fbd-db8f-454a-a092-3d1125351a77.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812907/tapavis_tenant_mecanique_cp/transmission_3a7b4134-4530-45f6-a642-5811603b01f7.png"
  }
};
