/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_jg_lussier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963094/tapavis_tenant_garage_jg_lussier/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963094/tapavis_tenant_garage_jg_lussier/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963111/tapavis_tenant_garage_jg_lussier/hero_4aab786c-739e-441e-9cc8-9476193fee51.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963111/tapavis_tenant_garage_jg_lussier/mecanique-generale_94245618-fa5d-4ad2-b9ca-604f92066a63.webp",
    "freins": "https://media.liasse.tech/upload/v1790963112/tapavis_tenant_garage_jg_lussier/freins_b1f61b97-1f03-4d1c-8dc2-19ad9b7e23e7.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790963112/tapavis_tenant_garage_jg_lussier/vidange-huile_4ddaaa56-ae6b-44fb-b83e-116888bb22ca.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963121/tapavis_tenant_garage_jg_lussier/equilibrage-rotation-pneus_aa2b197a-2611-4e83-9b0d-9df275953711.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963122/tapavis_tenant_garage_jg_lussier/silencieux_b161a35c-6aad-4021-af77-b0ab1bfbbdbb.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963122/tapavis_tenant_garage_jg_lussier/suspension_55415915-6625-4d7f-abf6-d6147aaed195.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963124/tapavis_tenant_garage_jg_lussier/systeme-de-refroidissement_d27a1759-194e-4558-b7d6-f7fc6ee2f998.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963132/tapavis_tenant_garage_jg_lussier/mise-au-point_41e44246-e505-4c67-9428-79ff173c0deb.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963133/tapavis_tenant_garage_jg_lussier/transmission_62f3fd17-3373-4fae-984c-7eb39583ed36.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963134/tapavis_tenant_garage_jg_lussier/climatisation_e9fbc8a5-8685-4e29-be33-3cb57c131137.webp"
  }
};
