/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_sr_auto_shop).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813472/tapavis_tenant_sr_auto_shop/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813472/tapavis_tenant_sr_auto_shop/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813484/tapavis_tenant_sr_auto_shop/hero_86d32fa4-406d-4db3-a3f9-940555feb29c.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813485/tapavis_tenant_sr_auto_shop/freins_f1e2d72c-558a-4521-9593-4ad4112600a1.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813486/tapavis_tenant_sr_auto_shop/vidange-huile_9de87b30-3f8f-4a34-be57-722c13e5eece.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813487/tapavis_tenant_sr_auto_shop/mecanique-generale_a8d5b72e-087e-4a68-ad23-71c97e3a0b07.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813495/tapavis_tenant_sr_auto_shop/equilibrage-rotation-pneus_8b4748e4-6e14-4512-9332-0c7ab0e4c499.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813495/tapavis_tenant_sr_auto_shop/silencieux_8ba4d5f6-b918-4cc0-b867-2e80cdb5cbd4.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813495/tapavis_tenant_sr_auto_shop/suspension_30ce58f3-2230-400c-8cf6-ac28b5cb6cd2.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813498/tapavis_tenant_sr_auto_shop/systeme-de-refroidissement_9b1fc45d-6899-4aad-9724-0de783ec616b.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813506/tapavis_tenant_sr_auto_shop/climatisation_fce9799a-c2ca-4a42-aef2-b90ee4285dfe.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813506/tapavis_tenant_sr_auto_shop/mise-au-point_4c72a549-3055-4571-933e-2fa95ac10377.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813507/tapavis_tenant_sr_auto_shop/transmission_1aa3c872-3980-46cd-9716-264e71f4aa6b.png"
  }
};
