module.exports={
 fr:{
  c_limit:"Les 4 000 adresses les plus proches sont affichées. Réduisez le rayon ou dessinez une zone pour affiner la recherche.",
  c_price_changed:"Votre crédit a changé dans un autre onglet. Fermez cette fenêtre et vérifiez le prix actualisé.",
  c_quick_review:"Vérifier mon envoi",
  c_restore_shared:"Ouvrir le brouillon enregistré",
  c_restore_confirm:"Remplacer la sélection de cet onglet par le brouillon enregistré ? Exportez votre sélection si vous souhaitez la garder.",
  c_rescan:"Zone modifiée. Analysez ce secteur pour actualiser les adresses.",
  c_title:"Le quartier, la rue, la porte. Choisissez.",
  c_intro:"Cherchez un quartier, dessinez votre zone, gardez les adresses qui comptent. Nous imprimons, mettons sous enveloppe et déposons chez Postes Canada.",
  c_eyebrow:"Vos campagnes postales",
  c_letter:"Voir la lettre",
  c_letter_title:"Votre lettre, prête pour la boîte aux lettres.",
  c_print:"Ouvrir / imprimer",
  c_close:"Fermer",
  c_letter_note:"Votre lettre personnalisée et son code QR, imprimée recto-verso en français et en anglais. La page doit être publiée avant l’envoi.",
  c_search:"Où voulez-vous prospecter ?",
  c_search_ph:"Une adresse, un quartier ou une ville au Québec",
  c_search_btn:"Trouver mon secteur",
  c_pick:"Choisir sur la carte",
  c_radius:"Rayon de recherche",
  c_target:"Objectif d’adresses",
  c_target_note:"Un objectif de sélection, jamais un minimum facturé.",
  c_scan:"Analyser ce secteur",
  c_cancel:"Annuler la recherche",
  c_quebec:"Tout le Québec",
  c_fit:"Ma sélection",
  c_draw:"Dessiner une zone",
  c_finish:"Terminer la zone",
  c_clear_zone:"Effacer la zone",
  c_here:"Chercher ici",
  c_fullscreen:"Agrandir",
  c_map:"Carte du territoire",
  c_initial:"Tout le Québec, à la porte près.",
  c_initial_note:"Cherchez un quartier ou choisissez un centre sur la carte pour commencer.",
  c_map_hint:"Cliquez sur une adresse pour consulter sa fiche ou la retirer.",
  c_pick_hint:"Cliquez sur la carte pour placer le centre de votre secteur.",
  c_draw_hint:"Cliquez pour dessiner votre zone, puis « Terminer la zone ». Zoomez sur un quartier.",
  c_zoom_hint:"Zoomez sur un quartier : une recherche couvre au maximum 5 km autour du centre.",
  c_selection:"Votre sélection",
  c_letters:"lettres",
  c_candidates:"adresses trouvées",
  c_units:"logements documentés",
  c_unknown_units:"immeubles sans nombre de logements",
  c_review:"à vérifier",
  c_filters:"Affiner le ciblage",
  c_all_types:"Tous les types",
  c_type:"Type de propriété",
  c_house:"Maison",
  c_plex:"Plex · 2 à 5 logements",
  c_apartment:"Immeuble résidentiel",
  c_condo:"Copropriété / condos",
  c_residential:"Résidentiel · type à préciser",
  c_nonresidential:"Non résidentiel",
  c_unknown:"Type inconnu",
  c_all_units:"Tous les nombres de logements",
  c_one_unit:"1 logement documenté",
  c_small_units:"2 à 5 logements documentés",
  c_large_units:"6 logements et plus",
  c_all_sources:"Toutes les adresses",
  c_points:"Adresses cartographiées",
  c_interpolated:"Numéros interpolés · à vérifier",
  c_find_address:"Rechercher une rue ou un numéro",
  c_view_all:"Toutes",
  c_view_selected:"Sélectionnées",
  c_view_removed:"Retirées",
  c_select_results:"Sélectionner les résultats",
  c_remove_results:"Retirer les résultats",
  c_undo:"Annuler le dernier changement",
  c_add:"Ajouter",
  c_remove:"Retirer",
  c_locate:"Voir sur la carte",
  c_more:"Afficher plus d’adresses",
  c_no_results:"Aucune adresse ne correspond à ces filtres.",
  c_empty:"Les adresses de votre secteur apparaîtront ici.",
  c_selected:"Sélectionnée",
  c_removed:"Retirée",
  c_distance:"du centre",
  c_dwellings:"Logements documentés",
  c_levels:"Étages",
  c_year:"Construction",
  c_not_known:"Non renseigné",
  c_source:"Source",
  c_osm:"OpenStreetMap · données cartographiques",
  c_montreal:"Ville de Montréal · rôle d’évaluation",
  c_assessment_scope:"Nombre de logements des unités d’évaluation correspondantes. Ce n’est pas une liste de boîtes aux lettres.",
  c_osm_scope:"Information cartographique disponible; les étages ne servent jamais à deviner le nombre de logements.",
  c_estimated_address:"Numéro interpolé depuis une plage de rue : existence à vérifier.",
  c_data_note:"Les logements décrivent le bâti. Chaque adresse sélectionnée correspond à une lettre; aucun appartement n’est inventé ou ajouté automatiquement.",
  c_analyzing:"Recherche des adresses et des bâtiments…",
  c_enriching:"Vérification des caractéristiques disponibles…",
  c_ready:"Votre secteur est prêt à explorer.",
  c_no_addresses:"Aucune adresse trouvée dans cette zone. Élargissez le rayon ou choisissez un autre centre.",
  c_search_error:"La recherche ne répond pas. Votre sélection est conservée; réessayez dans un instant.",
  c_analysis_partial:"Certaines caractéristiques n’ont pas pu être vérifiées. Les informations absentes restent inconnues.",
  c_search_not_found:"Aucun lieu trouvé au Québec. Précisez la ville ou choisissez directement sur la carte.",
  c_map_error:"Le fond de carte est indisponible. Vos adresses et votre sélection restent utilisables.",
  c_too_many:"La sélection est limitée à 1 200 adresses.",
  c_local:"Enregistré sur cet appareil",
  c_saving:"Enregistrement du brouillon…",
  c_saved:"Brouillon enregistré",
  c_save_failed:"Enregistrement indisponible. Gardez cet onglet ouvert, réessayez ou exportez votre sélection.",
  c_save_conflict:"Un autre onglet a modifié ce brouillon. Votre sélection reste sur cet appareil; exportez-la, puis ouvrez le brouillon enregistré.",
  c_retry:"Réessayer",
  c_export:"Exporter ma sélection",
  c_export_empty:"Sélectionnez au moins une adresse.",
  c_notes:"Consignes pour notre équipe",
  c_notes_ph:"Accès particuliers, exclusions, instructions…",
  c_summary:"Votre envoi, en un coup d’œil",
  c_selected_count:"Adresses sélectionnées",
  c_credit:"Lettres incluses utilisées",
  c_extra:"Lettres supplémentaires",
  c_before_tax:"Sous-total",
  c_tax:"TPS + TVQ",
  c_total:"Total de cet envoi",
  c_included:"Inclus avec l’adhésion",
  c_quote_loading:"Calcul du prix exact…",
  c_quote_failed:"Prix indisponible. Réessayez avant de confirmer.",
  c_credit_note:"Une campagne incluse par année. Envoyer moins de 150 lettres utilise cette campagne; le solde n’est pas reporté.",
  c_checkout:"Vérifier et préparer mon envoi",
  c_confirm:"Confirmer cet envoi",
  c_pay:"Continuer vers PayPal",
  c_activate:"Activer mon adhésion",
  c_review_title:"Vérifiez votre sélection avant de lancer.",
  c_review_note:"Les adresses retirées sont exclues. Notre équipe vérifie la distribution postale, imprime, met sous enveloppe et dépose chez Postes Canada.",
  c_review_warning:"Votre sélection comprend des numéros interpolés, des types inconnus ou des propriétés non résidentielles.",
  c_publish_note:"Votre page sera publiée pour que le code QR de la lettre fonctionne.",
  c_membership_note:"L’activation de l’adhésion est requise avant l’envoi. Votre sélection sera conservée pendant le paiement.",
  c_membership_total:"Adhésion annuelle, taxes incluses",
  c_working:"Préparation…",
  c_success:"Campagne reçue. Notre équipe prend le relais : suivez son état ci-dessous.",
  c_error:"Impossible de terminer. Votre sélection est conservée; réessayez.",
  c_history:"Mes campagnes",
  c_new:"Nouveau secteur",
  c_new_confirm:"Commencer un nouveau secteur ? Le brouillon actuel sera remplacé.",
  c_loading:"Chargement du brouillon…",
  c_source_checked:"Consulté le",
  c_mobile_map:"Carte",
  c_mobile_list:"Adresses",
  c_selected_label:"Inclure cette adresse",
  c_map_only:"Les adresses retirées restent visibles en gris.",
  c_payment_cancelled:"Paiement interrompu. Votre sélection est conservée.",
  c_payment_success:"Paiement confirmé. Votre campagne est en préparation.",
  c_sub_ready:"Adhésion active. Vérifiez votre sélection pour lancer votre campagne.",
  c_postal:"Code postal",
  c_apartment_unit:"Appartement / local",
  c_under_target:"Compléter jusqu’à mon objectif",
  c_under_target_note:"Ajoute les adresses les plus proches parmi les résultats affichés.",
  c_review_later:"Revenir au ciblage"
 },
 en:{
  c_limit:"Showing the nearest 4,000 addresses. Reduce the radius or draw an area to narrow your search.",
  c_price_changed:"Your credit changed in another tab. Close this window and review the updated price.",
  c_quick_review:"Review my mailing",
  c_restore_shared:"Open saved draft",
  c_restore_confirm:"Replace this tab’s selection with the saved draft? Export your selection first if you want to keep it.",
  c_rescan:"Area changed. Analyze this area to refresh the addresses.",
  c_title:"The neighbourhood, the street, the door. Choose.",
  c_intro:"Search a neighbourhood, draw your area, keep the addresses that matter. We print, stuff the envelopes and hand off to Canada Post.",
  c_eyebrow:"Your mail campaigns",
  c_letter:"Preview the letter",
  c_letter_title:"Your letter, ready for the mailbox.",
  c_print:"Open / print",
  c_close:"Close",
  c_letter_note:"Your personalized letter and QR code, printed double-sided in French and English. Your page must be published before mailing.",
  c_search:"Where would you like to prospect?",
  c_search_ph:"An address, neighbourhood or city in Québec",
  c_search_btn:"Find my area",
  c_pick:"Choose on the map",
  c_radius:"Search radius",
  c_target:"Address target",
  c_target_note:"A selection goal, never a billed minimum.",
  c_scan:"Analyze this area",
  c_cancel:"Cancel search",
  c_quebec:"All of Québec",
  c_fit:"My selection",
  c_draw:"Draw an area",
  c_finish:"Finish area",
  c_clear_zone:"Clear area",
  c_here:"Search here",
  c_fullscreen:"Expand",
  c_map:"Territory map",
  c_initial:"All of Québec, down to the door.",
  c_initial_note:"Search for a neighbourhood or choose a centre on the map to begin.",
  c_map_hint:"Click an address to view its details or remove it.",
  c_pick_hint:"Click the map to place the centre of your area.",
  c_draw_hint:"Click to draw your area, then “Finish area”. Zoom in on a neighbourhood.",
  c_zoom_hint:"Zoom in on a neighbourhood: searches cover at most 5 km around the centre.",
  c_selection:"Your selection",
  c_letters:"letters",
  c_candidates:"addresses found",
  c_units:"documented dwellings",
  c_unknown_units:"properties without a dwelling count",
  c_review:"to verify",
  c_filters:"Refine your targeting",
  c_all_types:"All property types",
  c_type:"Property type",
  c_house:"House",
  c_plex:"Plex · 2–5 dwellings",
  c_apartment:"Residential building",
  c_condo:"Condominium",
  c_residential:"Residential · type unspecified",
  c_nonresidential:"Non-residential",
  c_unknown:"Unknown type",
  c_all_units:"All dwelling counts",
  c_one_unit:"1 documented dwelling",
  c_small_units:"2–5 documented dwellings",
  c_large_units:"6 or more dwellings",
  c_all_sources:"All addresses",
  c_points:"Mapped addresses",
  c_interpolated:"Interpolated numbers · verify",
  c_find_address:"Search a street or civic number",
  c_view_all:"All",
  c_view_selected:"Selected",
  c_view_removed:"Removed",
  c_select_results:"Select results",
  c_remove_results:"Remove results",
  c_undo:"Undo last change",
  c_add:"Add",
  c_remove:"Remove",
  c_locate:"Show on map",
  c_more:"Show more addresses",
  c_no_results:"No addresses match these filters.",
  c_empty:"Addresses in your area will appear here.",
  c_selected:"Selected",
  c_removed:"Removed",
  c_distance:"from centre",
  c_dwellings:"Documented dwellings",
  c_levels:"Storeys",
  c_year:"Built",
  c_not_known:"Not available",
  c_source:"Source",
  c_osm:"OpenStreetMap · mapped information",
  c_montreal:"Ville de Montréal · property assessment",
  c_assessment_scope:"Dwelling count from the matching assessment units. This is not a list of mailboxes.",
  c_osm_scope:"Available mapped information; storeys are never used to guess dwelling counts.",
  c_estimated_address:"Number interpolated from a street range: verify that it exists.",
  c_data_note:"Dwelling counts describe the property. Each selected address receives one letter; apartments are never invented or added automatically.",
  c_analyzing:"Finding addresses and buildings…",
  c_enriching:"Checking available property details…",
  c_ready:"Your area is ready to explore.",
  c_no_addresses:"No addresses found here. Expand the radius or choose another centre.",
  c_search_error:"Search is unavailable. Your selection is preserved; try again shortly.",
  c_analysis_partial:"Some property details could not be checked. Missing information remains unknown.",
  c_search_not_found:"No Québec location found. Specify the city or choose a point on the map.",
  c_map_error:"The base map is unavailable. Your addresses and selection are still usable.",
  c_too_many:"Selections are limited to 1,200 addresses.",
  c_local:"Saved on this device",
  c_saving:"Saving draft…",
  c_saved:"Draft saved",
  c_save_failed:"Saving is unavailable. Keep this tab open, retry or export your selection.",
  c_save_conflict:"Another tab changed this draft. Your selection remains on this device; export it, then open the saved draft.",
  c_retry:"Retry",
  c_export:"Export my selection",
  c_export_empty:"Select at least one address.",
  c_notes:"Instructions for our team",
  c_notes_ph:"Access details, exclusions, instructions…",
  c_summary:"Your mailing at a glance",
  c_selected_count:"Selected addresses",
  c_credit:"Included letters used",
  c_extra:"Additional letters",
  c_before_tax:"Subtotal",
  c_tax:"GST + QST",
  c_total:"Total for this mailing",
  c_included:"Included with membership",
  c_quote_loading:"Calculating the exact price…",
  c_quote_failed:"Price unavailable. Retry before confirming.",
  c_credit_note:"One included campaign each year. Sending fewer than 150 letters uses that campaign; unused letters do not roll over.",
  c_checkout:"Review and prepare my mailing",
  c_confirm:"Confirm this mailing",
  c_pay:"Continue to PayPal",
  c_activate:"Activate my membership",
  c_review_title:"Review your selection before launching.",
  c_review_note:"Removed addresses are excluded. Our team checks postal delivery, prints, stuffs the envelopes and hands off to Canada Post.",
  c_review_warning:"Your selection contains interpolated numbers, unknown property types or non-residential properties.",
  c_publish_note:"Your page will be published so the letter’s QR code works.",
  c_membership_note:"Membership activation is required before mailing. Your selection will be kept during payment.",
  c_membership_total:"Annual membership, taxes included",
  c_working:"Preparing…",
  c_success:"Campaign received. Our team takes over: track its progress below.",
  c_error:"This could not be completed. Your selection is preserved; please retry.",
  c_history:"My campaigns",
  c_new:"New area",
  c_new_confirm:"Start a new area? Your current draft will be replaced.",
  c_loading:"Loading draft…",
  c_source_checked:"Checked on",
  c_mobile_map:"Map",
  c_mobile_list:"Addresses",
  c_selected_label:"Include this address",
  c_map_only:"Removed addresses remain visible in grey.",
  c_payment_cancelled:"Payment interrupted. Your selection is preserved.",
  c_payment_success:"Payment confirmed. Your campaign is being prepared.",
  c_sub_ready:"Membership is active. Review your selection to launch your campaign.",
  c_postal:"Postal code",
  c_apartment_unit:"Apartment / unit",
  c_under_target:"Fill to my target",
  c_under_target_note:"Adds the nearest addresses from the displayed results.",
  c_review_later:"Back to targeting"
 }
};

// One targeting method throughout Québec: a location and a radius.
Object.assign(module.exports.fr, {
 c_intro: 'Cherchez une adresse, un quartier ou une ville, choisissez votre rayon, puis retirez les adresses à exclure de votre envoi.',
 c_initial_note: 'Recherchez un lieu, choisissez un rayon et lancez la recherche d’adresses.',
 c_scan: 'Rechercher les adresses',
 c_analyzing: 'Recherche des adresses dans ce rayon…',
 c_center_ready: 'Centre choisi. Ajustez le rayon, puis recherchez les adresses.',
 c_rescan: 'Secteur modifié. Cliquez sur « Rechercher les adresses » pour actualiser la liste.',
 c_fit: 'Voir le secteur',
 c_map_hint: 'Le cercle indique le rayon. Cliquez sur une adresse pour la retirer ou la remettre.',
 c_search_not_found: 'Aucun lieu trouvé au Québec. Précisez l’adresse ou le nom de la ville.',
 c_remove_hint: 'Décochez une adresse pour la retirer de l’envoi. Vous pouvez la remettre à tout moment.',
 c_data_note: 'Chaque adresse sélectionnée correspond à une lettre. Aucun appartement n’est ajouté automatiquement.',
 c_review_warning: 'Votre sélection contient des numéros d’adresse estimés. Vérifiez-les avant de confirmer.'
});
Object.assign(module.exports.en, {
 c_intro: 'Search for an address, neighbourhood or city, choose your radius, then remove any addresses you want to exclude from your mailing.',
 c_initial_note: 'Search for a location, choose a radius and find the addresses.',
 c_scan: 'Find addresses',
 c_analyzing: 'Finding addresses within this radius…',
 c_center_ready: 'Centre selected. Adjust the radius, then find addresses.',
 c_rescan: 'Area changed. Click “Find addresses” to update the list.',
 c_fit: 'View area',
 c_map_hint: 'The circle shows the radius. Click an address to remove or restore it.',
 c_search_not_found: 'No Québec location found. Specify the address or city name.',
 c_remove_hint: 'Uncheck an address to remove it from your mailing. You can restore it at any time.',
 c_data_note: 'Each selected address receives one letter. Apartments are never added automatically.',
 c_review_warning: 'Your selection includes estimated address numbers. Check them before confirming.'
});
