 'use strict';
// Rates reviewed 2026-09-07. Only confirmed purchaser addresses establish
// the general-services jurisdiction. Marketing geography is not an address.
const provinces={AB:'Alberta',BC:'British Columbia',MB:'Manitoba',NB:'New Brunswick',NL:'Newfoundland and Labrador',NS:'Nova Scotia',NT:'Northwest Territories',NU:'Nunavut',ON:'Ontario',PE:'Prince Edward Island',QC:'Québec',SK:'Saskatchewan',YT:'Yukon'};
const postalProvinces={A:['NL'],B:['NS'],C:['PE'],E:['NB'],G:['QC'],H:['QC'],J:['QC'],K:['ON'],L:['ON'],M:['ON'],N:['ON'],P:['ON'],R:['MB'],S:['SK'],T:['AB'],V:['BC'],X:['NT','NU'],Y:['YT']};
function object(v){if(typeof v==='string'){try{return JSON.parse(v)||{};}catch(e){return {};}}return v&&typeof v==='object'?v:{};}
function province(v){const s=String(v||'').trim().toUpperCase();if(provinces[s])return s;return Object.keys(provinces).find(k=>provinces[k].normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase()===s.normalize('NFD').replace(/[\u0300-\u036f]/g,''))||'';}
function failure(code){const e=Error(code);e.code=code;throw e;}
function validate(v){v=object(v);const a={};for(const k of ['legal_name','line1','city','postal_code']){a[k]=String(v[k]||'').trim();if(!a[k]||a[k].length>160)failure('BILLING_ADDRESS_REQUIRED');}a.country=String(v.country||'').toUpperCase();a.province=province(v.province);a.postal_code=a.postal_code.toUpperCase().replace(/\s/g,'');if(a.country!=='CA'||!a.province)failure('CANADIAN_BILLING_REQUIRED');if(!/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]\d[ABCEGHJ-NPRSTV-Z]\d$/.test(a.postal_code)||!postalProvinces[a.postal_code[0]].includes(a.province))failure('BILLING_POSTAL_MISMATCH');if(a.postal_code[0]==='X'&&((['X0A','X0B','X0C'].includes(a.postal_code.slice(0,3))?'NU':'NT')!==a.province))failure('BILLING_POSTAL_MISMATCH');a.postal_code=a.postal_code.slice(0,3)+' '+a.postal_code.slice(3);return a;}
function billing(b){if(!b||!b.billing_confirmed_at)failure('BILLING_ADDRESS_REQUIRED');return validate(object(b.billing_address));}
function prefill(b){const p=object(b.profile);return Object.assign({legal_name:b.full_name||'',line1:p.business_address||p.office_address||'',city:p.city||'',province:province(p.province||p.mailing_province),postal_code:p.postal_code||p.postal||'',country:'CA'},object(b.billing_address));}
function calculate(subtotal,a,policy,now){if(!Number.isSafeInteger(subtotal)||subtotal<0||subtotal>100000000)failure('BAD_SUBTOTAL');a=validate(a);policy=object(policy);const p=a.province,date=(now||new Date()).toISOString().slice(0,10);let hst={ON:13,NB:15,NL:15,PE:15,NS:date<'2025-04-01'?15:14}[p]||0;const lines=[];function add(code,rate,number){lines.push({code,rate,amount_cents:Math.round(subtotal*Math.round(rate*1000)/100000),registration:number||''});}add(hst?'HST':'GST',hst||5,policy.gst_number);if(p==='QC')add('QST',9.975,policy.qst_number);if(['BC','MB','SK'].includes(p)&&policy.pst&&policy.pst[p]&&policy.pst[p].treatment==='taxable')add(p==='MB'?'RST':'PST',p==='SK'?6:7,policy.pst[p].registration);return {version:'ca-2026-09-07',date,province:p,basis:'confirmed_customer_business_address',billing_address:a,classification:'general_service',lines,subtotal_cents:subtotal,total_cents:subtotal+lines.reduce((n,l)=>n+l.amount_cents,0)};}
// Do not turn an unknown obligation into either an exemption or invented tax.
function assertCollectable(snapshot,policy){policy=object(policy);if(policy.campaign_classification!=='general_service')failure('TAX_CLASSIFICATION_REVIEW');if((snapshot.destination_provinces||[]).some(p=>['BC','MB','SK'].includes(p)&&p!==snapshot.province))failure('PROVINCIAL_TAX_REVIEW');if(['BC','MB','SK'].includes(snapshot.province)){const p=policy.pst&&policy.pst[snapshot.province];if(!p||!p.review_reference||!['taxable','not_applicable'].includes(p.treatment))failure('PROVINCIAL_TAX_REVIEW');}}
function rows(invoice){const s=object(invoice.tax_snapshot);if(Array.isArray(s.lines))return s.lines;return [{code:'GST',rate:5,amount_cents:Number(invoice.gst_cents)||0},{code:'QST',rate:9.975,amount_cents:Number(invoice.qst_cents)||0}];}
function label(l){return ({GST:'TPS / GST',HST:'TVH / HST',QST:'TVQ / QST',PST:'PST',RST:'RST'}[l.code]||l.code)+' ('+l.rate+'%)';}
function amounts(s){const r={gst:0,hst:0,qst:0,pst:0};s.lines.forEach(l=>r[l.code==='RST'?'pst':l.code.toLowerCase()]+=l.amount_cents);return r;}
module.exports={provinces,province,object,validate,billing,prefill,calculate,assertCollectable,rows,label,amounts};
