const previous=require('./homepage-copy-v5');
module.exports={fr:Object.assign({},previous.fr,{
 inv_eyebrow:'Courrier ciblé pour courtiers immobiliers',inv_title:'Le quartier que vous voulez développer. Une lettre à la fois.',
 inv_lede:'Choisissez les adresses de votre prochain secteur. VendVite prépare et poste votre campagne; votre page de capture à 0 $ transforme l’intérêt des propriétaires en conversations, directement avec vous.',
 inv_price_amount:'0 $',inv_price_term:'pour votre page de capture',inv_price_pitch:'Votre page est offerte exclusivement avec les campagnes postales VendVite. Vous payez vos envois : 1,59 $ par lettre, avant taxes, préparation et affranchissement compris.',
 inv_form_title:'Préparez votre première campagne',inv_form_sub:'Confirmez vos coordonnées. Nous vous envoyons un lien pour ouvrir votre espace gratuit.',inv_f_submit:'Ouvrir mon espace à 0 $',inv_f_sent:'Lien demandé',inv_fineprint:'Aucune carte requise. Aucun abonnement à la page. Vous validez chaque campagne avant de payer.',
 inv_done_title:'Votre prochain quartier commence ici.',inv_done_text:'Vérifiez votre courriel pour ouvrir votre espace gratuit, personnaliser votre page et choisir votre quartier.',inv_done_status:'Un compte existe déjà ? Utilisez Connexion courtier.',
 hp_cta:'Préparer ma campagne',hp_included:'Un service postal complet, une page à 0 $',hp_letters:'Les bonnes adresses',hp_letters_detail:'Choisissez le quartier et les portes que vous voulez rejoindre.',hp_page:'Votre page de capture à 0 $',hp_page_detail:'Votre nom, votre photo et vos coordonnées. Réservée à vos envois VendVite.',hp_mail_allowance:'1,59 $ par lettre, avant taxes. Données, impression, pliage, enveloppe, affranchissement et dépôt chez Postes Canada.',hp_price_note:'Page à 0 $. Campagnes à 1,59 $ par lettre, avant taxes. Aucun abonnement.',hp_gate_note:'Vous vérifiez le prix total de votre envoi avant de payer.',hp_offer:'Votre formule courrier ciblé',hp_form_note:'Votre espace gratuit, pour vos campagnes VendVite.',hp_page_title:'La page qui donne une suite à votre courrier.',
 hp_faq:[['Que coûte la page ?','0 $. Elle est réservée aux campagnes postales confiées à VendVite; elle n’est pas vendue comme un site autonome.'],['Que coûte un envoi ?','1,59 $ par lettre, avant taxes. Le total est affiché avant paiement. Vous choisissez jusqu’à 1 200 adresses par campagne.'],['Que faites-vous pour moi ?','Nous préparons les données postales, imprimons les lettres, les plions, les mettons sous enveloppe, les affranchissons et les déposons chez Postes Canada.'],['Comment fonctionne le code QR ?','Le code imprimé ouvre votre page personnalisée. Les propriétaires vous transmettent leur adresse, leurs coordonnées et leur échéancier. Vous préparez leur analyse comparative de marché et assurez le suivi.'],['La page fonctionne-t-elle pour mes autres publicités ?','Non. Cette offre à 0 $ est réservée aux campagnes postales traitées par VendVite. Les liens de collecte sont rattachés à ces campagnes.'],['Dois-je payer pour essayer ?','Non. Ouvrez votre espace, personnalisez votre page et préparez votre sélection sans carte. Vous payez uniquement lorsque vous commandez un envoi.'],['Les demandes ou les mandats sont-ils garantis ?','Non. Les résultats dépendent du secteur, de l’intérêt des propriétaires et de votre suivi.']]
}),en:Object.assign({},previous.en,{
 inv_eyebrow:'Targeted mail for real estate brokers',inv_title:'The neighbourhood you want to grow. One letter at a time.',inv_lede:'Choose the addresses in your next area. VendVite prepares and mails your campaign; your $0 lead capture page turns homeowner interest into conversations directly with you.',
 inv_price_amount:'$0',inv_price_term:'for your lead capture page',inv_price_pitch:'Your page is included exclusively with VendVite postal campaigns. You pay for your mailings: $1.59 per letter, before tax, including preparation and postage.',inv_form_title:'Prepare your first campaign',inv_form_sub:'Confirm your details. We will email a link to open your free workspace.',inv_f_submit:'Open my $0 workspace',inv_f_sent:'Link requested',inv_fineprint:'No card required. No page subscription. Review every campaign before paying.',inv_done_title:'Your next neighbourhood starts here.',inv_done_text:'Check your email to open your free workspace, personalize your page and choose your neighbourhood.',inv_done_status:'Already have an account? Use Broker sign-in.',hp_cta:'Prepare my campaign',hp_included:'A complete mailing service, a $0 page',hp_letters:'The right addresses',hp_letters_detail:'Choose the neighbourhood and doors you want to reach.',hp_page:'Your $0 lead capture page',hp_page_detail:'Your name, portrait and contact details. Reserved for your VendVite mailings.',hp_mail_allowance:'$1.59 per letter, before tax. Data, printing, folding, envelope insertion, postage and Canada Post deposit.',hp_price_note:'$0 page. Campaigns at $1.59 per letter, before tax. No subscription.',hp_gate_note:'Review the full cost of your mailing before paying.',hp_offer:'Your targeted mailing service',hp_form_note:'Your free workspace for VendVite campaigns.',hp_page_title:'The page that gives your mailing a next step.',
 hp_faq:[['What does the page cost?','$0. It is reserved for postal campaigns fulfilled by VendVite and is not sold as a standalone website.'],['What does a mailing cost?','$1.59 per letter, before tax. Review the total before paying. Choose up to 1,200 addresses per campaign.'],['What do you handle?','We prepare the postal data, print and fold the letters, insert them into envelopes, apply postage and deposit them with Canada Post.'],['How does the QR work?','The printed code opens your personalized page. Homeowners send you their address, contact details and timeline. You prepare their comparative market analysis and follow up.'],['Can I use the page for other advertising?','No. This $0 offer is reserved for postal campaigns fulfilled by VendVite. Lead capture links are tied to those campaigns.'],['Do I need to pay to try it?','No. Open your workspace, personalize your page and prepare your selection without a card. Pay only when you order a mailing.'],['Are requests or listings guaranteed?','No. Results depend on the area, homeowner interest and your follow-up.']]
})};
