// Homepage pitch v5 (no territory ask) — « Pourquoi gaspiller votre budget marketing sur Facebook ? »
// Courrier Postes Canada préparé par des professionnels + page de capture qui
// offre au propriétaire son analyse comparative gratuite. Both price variants of
// the homepage-price-v1 experiment share this copy; only the offer box differs.
module.exports = {
 fr: {
  inv_meta_title: 'Pourquoi gaspiller votre budget marketing sur Facebook ?',
  inv_meta_desc: 'Des campagnes Postes Canada préparées par des professionnels, livrées aux portes exactes que vous choisissez, et une page de capture qui offre au propriétaire son analyse comparative gratuite. Pour les courtiers immobiliers du Québec.',
  inv_eyebrow: 'Pour les courtiers immobiliers du Québec',
  inv_title: 'Pourquoi gaspiller votre budget marketing sur Facebook ?',
  inv_lede: 'Des campagnes Postes Canada préparées par des professionnels, livrées aux portes exactes que vous choisissez. Chaque lettre mène à votre page de capture, où le propriétaire reçoit quelque chose de concret — son analyse comparative de marché, gratuite — et où sa demande vous revient directement.',
  inv_form_title: 'Demandez votre accès.',
  inv_form_sub: 'Vos coordonnées suffisent. Vous recevrez un lien par courriel pour bâtir votre page de capture et voir le tarif.',
  inv_f_submit: 'Demander mon accès', inv_f_sending: 'Envoi en cours…', inv_f_sent: 'Demande reçue',
  inv_fineprint: 'Aucun paiement aujourd’hui. Aucune carte requise. Vos coordonnées servent à traiter votre demande et à vous recontacter.',
  inv_done_kicker: 'Demande reçue', inv_done_title: 'Votre demande est reçue.',
  inv_done_text: 'Vous recevrez rapidement un lien par courriel pour bâtir votre page de capture, puis choisir d’activer votre adhésion.',
  inv_done_status: 'Surveillez votre boîte de réception.',
  inv_foot: 'Pour les courtiers qui préfèrent les enveloppes aux impressions.',
  hp_cta: 'Demander mon accès', hp_secondary: 'Voir la différence', hp_reassurance: 'Sans engagement · Aucune carte requise',
  hp_included: 'Ce que comprend votre adhésion',
  hp_letters: 'Des campagnes Postes Canada clé en main', hp_letters_detail: 'Impression, pliage, enveloppes, affranchissement et dépôt — par des professionnels.',
  hp_page: 'Le ciblage à la porte près', hp_page_detail: 'Le quartier, la rue, le type de propriété : vous choisissez chaque adresse.',
  hp_leads: 'Votre page de capture', hp_leads_detail: 'Chaque lettre offre une analyse comparative gratuite. Les demandes vous arrivent directement.',
  hp_mail_allowance: 'Une campagne de 150 lettres comprise chaque année. Besoin de plus ? Les lettres supplémentaires sont facturées en sus.',
  hp_price_note: 'Facturation annuelle à l’activation. Annulable en tout temps.',
  hp_gate_title: 'Votre tarif, après votre demande', hp_gate_note: 'Le tarif annuel s’affiche dès l’envoi du formulaire, avant tout engagement.',
  hp_form_note: 'Une demande d’accès, pas un achat.', hp_offer: 'Voici votre adhésion VendVite',
  inv_price_pitch: 'Votre adhésion comprend le créateur de campagnes, votre page de capture, une campagne annuelle de 150 lettres — impression, enveloppes, affranchissement et dépôt Postes Canada compris — et la réception illimitée de demandes d’analyse.',
  hp_compare_eyebrow: 'Le calcul est simple',
  hp_compare_title: 'Facebook vend des impressions. Nous livrons des enveloppes.',
  hp_compare_lede: 'Une publicité paie pour être vue quelques secondes par des gens que l’algorithme a choisis. Une lettre arrive chez le propriétaire que vous avez choisi, avec une offre qu’il peut accepter.',
  hp_compare_fb: 'Publicité Facebook', hp_compare_vv: 'Campagne VendVite',
  hp_compare_rows: [
   ['Qui reçoit votre message', 'Les gens que l’algorithme choisit, dans un rayon approximatif', 'La porte exacte : le quartier, la rue, la maison que vous avez sélectionnée'],
   ['Ce que vous payez', 'Des impressions et des clics, la plupart sans intention de vendre', 'Des lettres livrées — une par adresse choisie, production et Postes Canada compris'],
   ['Ce que le propriétaire reçoit', 'Une publicité de plus dans son fil', 'Une offre concrète : son analyse comparative de marché, gratuite, via votre page'],
   ['Combien de temps ça vit', 'Quelques secondes, puis l’oubli', 'Sur le comptoir de la cuisine, jusqu’à ce qu’on décide quoi en faire'],
   ['Ce qu’il vous reste', 'Un rapport de portée', 'Des demandes nominatives : adresse, coordonnées et échéancier de vente']
  ],
  hp_compare_note: 'Aucun volume de demandes ni de mandats n’est garanti : les résultats dépendent de votre secteur, de l’intérêt des propriétaires et de votre suivi.',
  hp_shipping_label: 'Chaque campagne comprend',
  hp_shipping_steps: ['Impression', 'Pliage', 'Mise sous enveloppe', 'Affranchissement', 'Dépôt Postes Canada'],
  hp_builder_eyebrow: 'Votre créateur de campagnes',
  hp_builder_title: 'Le quartier, la rue, la porte. Vous choisissez.',
  hp_builder_lede: 'Dessinez votre zone, filtrez par type de propriété et retirez les adresses que vous ne voulez pas contacter. Une précision qu’aucun ciblage publicitaire ne vous vend — puis lancez la production en un clic.',
  hp_builder_caption: 'Illustration du créateur de campagnes · sélection de 300 adresses à titre d’exemple.',
  hp_ui_title: 'Ma prochaine campagne', hp_ui_saved: 'Brouillon enregistré', hp_ui_location: 'Où voulez-vous prospecter ?', hp_ui_radius: 'Rayon de recherche', hp_ui_goal: 'Objectif d’adresses',
  hp_ui_filter: 'Affiner le ciblage', hp_ui_type: 'Maisons et plex', hp_ui_street: 'Rechercher une rue ou un numéro', hp_ui_selection: 'Votre sélection', hp_ui_letters: 'lettres ciblées',
  hp_ui_excluded: 'Adresses retirées conservées', hp_ui_area: 'Dessiner une zone', hp_ui_map: 'Carte illustrative d’un secteur avec des adresses sélectionnées et exclues',
  hp_ui_selected: 'Sélectionnées', hp_ui_removed: 'Retirées', hp_ui_review: 'Vérifier mon envoi',
  hp_page_eyebrow: 'Votre page de capture',
  hp_page_title: 'Pas une publicité. Une offre que le propriétaire accepte.',
  hp_page_lede: 'Le propriétaire scanne le code QR de votre lettre et arrive sur votre page — à votre nom, avec votre photo. Il tape son adresse, voit son dossier se bâtir et demande son analyse comparative de marché, gratuite. Vous recevez la demande, l’adresse et l’échéancier de vente.',
  hp_page_points: [
   ['Il reçoit de la valeur', 'Une analyse comparative gratuite, appuyée par les ventes réelles de son secteur — pas un slogan.'],
   ['Vous recevez une demande', 'Nom, adresse, coordonnées, échéancier : la conversation est déjà ouverte quand vous l’appelez.'],
   ['Tout porte votre nom', 'Votre photo, vos chiffres, vos témoignages et la mention légale de votre agence.']
  ],
  hp_page_ui_broker: 'Votre nom · Courtier immobilier', hp_page_ui_addr: '1088, rue de Chambord, Saint-Jérôme', hp_page_ui_ref: 'VV-1088', hp_page_ui_coords: '45.7795° N · 74.0031° O',
  hp_page_caption: 'Illustration de votre page de capture · le propriétaire y demande son analyse gratuite.',
  hp_process_label: 'De la boîte aux lettres à votre téléphone',
  hp_process_title: 'Vous ciblez. Nous expédions. Vous répondez.',
  hp_steps: [
   ['Choisissez vos portes', 'Cherchez un quartier, dessinez votre zone, filtrez par type de propriété et vérifiez chaque adresse avant de confirmer.'],
   ['Nous produisons et déposons', 'Notre centre imprime vos lettres, les plie, les met sous enveloppe, les affranchit et remet le lot à Postes Canada.'],
   ['Les propriétaires vous répondent', 'Le code QR mène à votre page de capture. Chaque demande arrive dans votre espace et dans votre boîte courriel.']
  ],
  hp_faq_title: 'Avant de faire votre demande',
  hp_faq: [
   ['Pourquoi le courrier plutôt que Facebook ?', 'Parce que vous choisissez la porte, pas l’algorithme. Une lettre arrive chez un propriétaire précis, dans le quartier précis que vous voulez travailler, avec une offre concrète. Une publicité paie pour être vue par des gens dont la plupart n’ont aucune intention de vendre.'],
   ['Qu’est-ce qui est inclus ?', 'Le créateur de campagnes, votre page de capture, la réception illimitée de demandes et une campagne de 150 lettres par année — impression, enveloppes, affranchissement et dépôt Postes Canada compris.'],
   ['Puis-je envoyer des centaines de lettres ?', 'Oui. Le créateur permet de sélectionner jusqu’à 1 200 adresses par envoi. Une campagne allant jusqu’à 150 lettres est comprise chaque année; les lettres supplémentaires sont facturées en sus. Vous vérifiez le montant avant de confirmer.'],
   ['Dois-je imprimer les lettres ou préparer les enveloppes ?', 'Non. Notre centre s’occupe de l’impression, du pliage, de la mise sous enveloppe, de l’affranchissement et du dépôt chez Postes Canada. Rien à imprimer, rien à coller, rien à poster.'],
   ['Est-ce que je paie en envoyant le formulaire ?', 'Non. La demande est sans engagement. Vous bâtissez votre page avant de décider d’activer l’adhésion.'],
   ['Qui prépare l’analyse comparative de marché ?', 'Vous, le courtier. VendVite ouvre la conversation; votre expertise et votre suivi font le reste.'],
   ['Les demandes ou les mandats sont-ils garantis ?', 'Non. Les résultats dépendent notamment de votre secteur, de l’intérêt des propriétaires et de votre suivi. Aucun volume de demandes ni mandat n’est garanti.']
  ],
  hp_final: 'Votre prochain budget marketing peut acheter des impressions. Ou des enveloppes.',
  hp_preview: 'Aperçu du test — aucun envoi ni suivi de conversion.', hp_preview_done: 'Ceci est un aperçu. Aucune demande n’a été envoyée.',
  hp_sticky: 'Ciblez votre quartier', hp_back: 'Revenir au formulaire'
 },
 en: {
  inv_meta_title: 'Why waste your marketing budget on Facebook?',
  inv_meta_desc: 'Canada Post mail campaigns prepared by professionals, delivered to the exact doors you choose, and a lead-capture page that gives homeowners their free comparative market analysis. For real estate brokers in Quebec.',
  inv_eyebrow: 'For real estate brokers in Quebec',
  inv_title: 'Why waste your marketing budget on Facebook?',
  inv_lede: 'Canada Post mail campaigns prepared by professionals and delivered to the exact doors you choose. Every letter leads to your lead-capture page, where the homeowner gets something concrete — a free comparative market analysis — and their request comes straight to you.',
  inv_form_title: 'Request your access.',
  inv_form_sub: 'Your contact details are enough. You’ll receive an email link to build your lead-capture page and see the price.',
  inv_f_submit: 'Request my access', inv_f_sending: 'Sending…', inv_f_sent: 'Request received',
  inv_fineprint: 'No payment today. No card required. We use your details to review your request and contact you about it.',
  inv_done_kicker: 'Request received', inv_done_title: 'Your request was received.',
  inv_done_text: 'You’ll shortly receive an email link to build your lead-capture page, then decide whether to activate your membership.',
  inv_done_status: 'Keep an eye on your inbox.',
  inv_foot: 'For brokers who prefer envelopes to impressions.',
  hp_cta: 'Request my access', hp_secondary: 'See the difference', hp_reassurance: 'No commitment · No card required',
  hp_included: 'What your membership includes',
  hp_letters: 'Done-for-you Canada Post campaigns', hp_letters_detail: 'Printing, folding, envelopes, postage and handoff — by professionals.',
  hp_page: 'Targeting down to the door', hp_page_detail: 'The neighbourhood, the street, the property type: you choose every address.',
  hp_leads: 'Your lead-capture page', hp_leads_detail: 'Every letter offers a free comparative market analysis. Requests come straight to you.',
  hp_mail_allowance: 'One 150-letter campaign included every year. Need more? Additional letters are billed separately.',
  hp_price_note: 'Billed annually on activation. Cancel anytime.',
  hp_gate_title: 'Your price, after your request', hp_gate_note: 'See the annual price immediately after submitting the form, before committing.',
  hp_form_note: 'An access request, not a purchase.', hp_offer: 'Your VendVite membership',
  inv_price_pitch: 'Your membership includes the campaign builder, your lead-capture page, one annual campaign of 150 letters — printing, envelopes, postage and Canada Post handoff included — and unlimited market-analysis requests.',
  hp_compare_eyebrow: 'The math is simple',
  hp_compare_title: 'Facebook sells impressions. We deliver envelopes.',
  hp_compare_lede: 'An ad pays to be seen for a few seconds by people the algorithm picked. A letter lands with the homeowner you picked, carrying an offer they can accept.',
  hp_compare_fb: 'Facebook ad', hp_compare_vv: 'VendVite campaign',
  hp_compare_rows: [
   ['Who gets your message', 'Whoever the algorithm picks, within a rough radius', 'The exact door: the neighbourhood, the street, the house you selected'],
   ['What you pay for', 'Impressions and clicks, most with no intention of selling', 'Delivered letters — one per chosen address, production and Canada Post included'],
   ['What the homeowner receives', 'One more ad in their feed', 'A concrete offer: their free comparative market analysis, through your page'],
   ['How long it lives', 'A few seconds, then gone', 'On the kitchen counter until they decide what to do with it'],
   ['What you’re left with', 'A reach report', 'Named requests: address, contact details and selling timeline']
  ],
  hp_compare_note: 'No volume of requests or listings is guaranteed: results depend on your neighbourhood, homeowner interest and your follow-up.',
  hp_shipping_label: 'Every campaign includes',
  hp_shipping_steps: ['Printing', 'Folding', 'Envelope stuffing', 'Postage', 'Canada Post handoff'],
  hp_builder_eyebrow: 'Your campaign builder',
  hp_builder_title: 'The neighbourhood, the street, the door. You choose.',
  hp_builder_lede: 'Draw your area, filter by property type and remove the addresses you don’t want to contact. A precision no ad targeting sells you — then launch production in one click.',
  hp_builder_caption: 'Campaign builder illustration · example selection of 300 addresses.',
  hp_ui_title: 'My next campaign', hp_ui_saved: 'Draft saved', hp_ui_location: 'Where do you want to prospect?', hp_ui_radius: 'Search radius', hp_ui_goal: 'Target addresses',
  hp_ui_filter: 'Refine targeting', hp_ui_type: 'Houses and plexes', hp_ui_street: 'Search a street or number', hp_ui_selection: 'Your selection', hp_ui_letters: 'targeted letters',
  hp_ui_excluded: 'Removed addresses stay excluded', hp_ui_area: 'Draw an area', hp_ui_map: 'Illustrative neighbourhood map showing selected and excluded addresses',
  hp_ui_selected: 'Selected', hp_ui_removed: 'Removed', hp_ui_review: 'Review my mailing',
  hp_page_eyebrow: 'Your lead-capture page',
  hp_page_title: 'Not an ad. An offer the homeowner accepts.',
  hp_page_lede: 'The homeowner scans the QR code on your letter and lands on your page — in your name, with your photo. They type their address, watch their property dossier take shape and request their free comparative market analysis. You receive the request, the address and the selling timeline.',
  hp_page_points: [
   ['They get real value', 'A free comparative market analysis backed by real sales in their area — not a slogan.'],
   ['You get a request', 'Name, address, contact details, timeline: the conversation is already open when you call.'],
   ['Everything carries your name', 'Your photo, your numbers, your testimonials and your agency’s legal notice.']
  ],
  hp_page_ui_broker: 'Your name · Real estate broker', hp_page_ui_addr: '1088 rue de Chambord, Saint-Jérôme', hp_page_ui_ref: 'VV-1088', hp_page_ui_coords: '45.7795° N · 74.0031° W',
  hp_page_caption: 'Illustration of your lead-capture page · the homeowner requests their free analysis here.',
  hp_process_label: 'From their mailbox to your phone',
  hp_process_title: 'You target. We ship. You answer.',
  hp_steps: [
   ['Choose your doors', 'Search a neighbourhood, draw your area, filter by property type and check every address before confirming.'],
   ['We produce and hand off', 'Our centre prints your letters, folds them, stuffs the envelopes, adds postage and hands the batch to Canada Post.'],
   ['Homeowners answer you', 'The QR code leads to your lead-capture page. Every request lands in your workspace and your inbox.']
  ],
  hp_faq_title: 'Before you request access',
  hp_faq: [
   ['Why mail instead of Facebook?', 'Because you choose the door, not the algorithm. A letter reaches a specific homeowner, in the specific neighbourhood you want to work, with a concrete offer. An ad pays to be seen by people, most of whom have no intention of selling.'],
   ['What’s included?', 'The campaign builder, your lead-capture page, unlimited requests and one 150-letter campaign each year — printing, envelopes, postage and Canada Post handoff included.'],
   ['Can I send hundreds of letters?', 'Yes. Select up to 1,200 addresses per mailing in the builder. One campaign of up to 150 letters is included each year; additional letters are billed separately. You review the amount before confirming.'],
   ['Do I need to print letters or prepare envelopes?', 'No. Our centre handles printing, folding, envelope stuffing, postage and handoff to Canada Post. Nothing to print, nothing to seal, nothing to mail.'],
   ['Do I pay when I submit the form?', 'No. Your request comes with no commitment. You build your page before deciding to activate your membership.'],
   ['Who prepares the comparative market analysis?', 'You, the broker. VendVite opens the conversation; your expertise and follow-up take it from there.'],
   ['Are leads or listings guaranteed?', 'No. Results depend on your neighbourhood, homeowner interest and your follow-up. There is no guaranteed number of requests or listings.']
  ],
  hp_final: 'Your next marketing budget can buy impressions. Or envelopes.',
  hp_preview: 'Test preview — no messages sent or conversions recorded.', hp_preview_done: 'This is a preview. No request was sent.',
  hp_sticky: 'Target your neighbourhood', hp_back: 'Back to the form'
 }
};
