module.exports = {
 fr: {
  inv_meta_title:'Des propriétaires de votre secteur à votre prochaine conversation',
  inv_meta_desc:'Votre page de capture et 150 lettres ciblées par année pour inviter les propriétaires de votre secteur à demander une analyse comparative de marché.',
  inv_eyebrow:'Pour les courtiers immobiliers du Québec',
  inv_title:'Votre prochain mandat commence par une conversation.',
  inv_lede:'Invitez les propriétaires de votre secteur à demander une analyse comparative de marché. VendVite prépare le point de contact. Vous prenez la relation en main.',
  inv_form_title:'Faites le premier pas dans votre secteur.',
  inv_form_sub:'Indiquez vos coordonnées et le quartier que vous souhaitez développer. Nous étudierons votre demande d’accès.',
  inv_f_submit:'Demander mon accès', inv_f_sending:'Envoi en cours…', inv_f_sent:'Demande reçue',
  inv_fineprint:'Aucun paiement aujourd’hui. Aucune carte requise. Vos coordonnées servent à traiter votre demande et à vous recontacter.',
  inv_done_kicker:'Demande reçue', inv_done_title:'Votre prochain pas est entre nos mains.',
  inv_done_text:'Nous étudions votre demande et votre secteur. Si votre accès est approuvé, vous recevrez un lien par courriel pour préparer votre page, puis choisir d’activer votre adhésion.',
  inv_done_status:'Surveillez votre boîte de réception.', inv_foot:'Pour les courtiers qui développent leur secteur.',
  hp_cta:'Demander mon accès', hp_secondary:'Comment ça fonctionne', hp_reassurance:'Sans engagement · Aucune carte requise',
  hp_included:'Tout commence avec votre adhésion', hp_letters:'150 lettres ciblées', hp_letters_detail:'Une campagne postale incluse chaque année.',
  hp_page:'Votre page, à votre image', hp_page_detail:'Votre nom, votre photo et vos coordonnées.',
  hp_leads:'Les demandes, directement à vous', hp_leads_detail:'Adresse, coordonnées et échéancier du propriétaire.',
  hp_price_note:'Facturation annuelle à l’activation. Renouvellement annuel, annulable depuis votre espace.',
  hp_gate_title:'Votre formule, après votre demande', hp_gate_note:'Le tarif annuel s’affiche dès l’envoi du formulaire, avant tout engagement.',
  hp_form_note:'Une demande d’accès, pas un achat.', hp_offer:'Voici votre adhésion VendVite',
  hp_process_label:'De la boîte aux lettres à votre téléphone', hp_process_title:'Un parcours simple. Une relation qui vous appartient.',
  hp_steps:[['Choisissez votre secteur','Personnalisez votre page et ciblez le quartier que vous souhaitez développer.'],['Nous préparons votre envoi','Votre campagne incluse : 150 lettres ciblées, imprimées, mises sous enveloppe et déposées chez Postes Canada.'],['Prenez la conversation en main','Les propriétaires intéressés vous transmettent leur demande. Vous préparez leur analyse et assurez le suivi.']],
  hp_faq_title:'Avant de faire votre demande',
  hp_faq:[['Qu’est-ce qui est inclus ?','Une page personnalisée, une campagne annuelle de 150 lettres ciblées et la réception illimitée de demandes d’analyse dans votre espace VendVite.'],['Est-ce que je paie en envoyant le formulaire ?','Non. La demande est sans engagement. Si elle est approuvée, vous pouvez préparer votre page avant de décider d’activer l’adhésion.'],['Qui prépare l’analyse comparative de marché ?','Vous, le courtier. VendVite facilite la prise de contact; votre expertise et votre suivi font le reste.'],['Les demandes ou les mandats sont-ils garantis ?','Non. Les résultats dépendent notamment de votre secteur, de l’intérêt des propriétaires et de votre suivi. Aucun volume de demandes ni mandat n’est garanti.']],
  hp_final:'Faites de votre secteur le début de votre prochaine conversation.', hp_preview:'Aperçu du test — aucun envoi ni suivi de conversion.',
  hp_preview_done:'Ceci est un aperçu. Aucune demande n’a été envoyée.', hp_sticky:'Développez votre secteur', hp_back:'Revenir au formulaire'
 },
 en: {
  inv_meta_title:'Turn neighbourhood interest into your next conversation',
  inv_meta_desc:'Your own lead-capture page and 150 targeted letters each year to invite local homeowners to request a comparative market analysis.',
  inv_eyebrow:'For real estate brokers in Quebec',
  inv_title:'Your next listing starts with a conversation.',
  inv_lede:'Invite homeowners in your area to request a comparative market analysis. VendVite creates the first point of contact. You build the relationship.',
  inv_form_title:'Take the first step in your neighbourhood.',
  inv_form_sub:'Tell us how to reach you and which area you want to develop. We’ll review your access request.',
  inv_f_submit:'Request my access', inv_f_sending:'Sending…', inv_f_sent:'Request received',
  inv_fineprint:'No payment today. No card required. We use your details to review your request and contact you about it.',
  inv_done_kicker:'Request received', inv_done_title:'We’ll take it from here.',
  inv_done_text:'We’re reviewing your request and target area. If approved, you’ll receive an email link to prepare your page, then decide whether to activate your membership.',
  inv_done_status:'Keep an eye on your inbox.', inv_foot:'For brokers building their local presence.',
  hp_cta:'Request my access', hp_secondary:'How it works', hp_reassurance:'No commitment · No card required',
  hp_included:'It starts with your membership', hp_letters:'150 targeted letters', hp_letters_detail:'One postal campaign included every year.',
  hp_page:'Your page. Your name.', hp_page_detail:'Your photo, your branding and your contact details.',
  hp_leads:'Homeowner requests come to you', hp_leads_detail:'Their address, contact details and selling timeline.',
  hp_price_note:'Billed annually on activation. Renews yearly; cancel from your account.',
  hp_gate_title:'Your membership, after your request', hp_gate_note:'See the annual price immediately after submitting the form, before committing.',
  hp_form_note:'An access request, not a purchase.', hp_offer:'Your VendVite membership',
  hp_process_label:'From their mailbox to your next conversation', hp_process_title:'A simple path. A relationship you own.',
  hp_steps:[['Choose your neighbourhood','Personalize your page and target the area you want to develop.'],['We prepare your mailing','Your included campaign: 150 targeted letters, printed, put in envelopes and handed to Canada Post.'],['Start the conversation','Interested homeowners send you a request. You prepare their market analysis and handle the follow-up.']],
  hp_faq_title:'Before you request access',
  hp_faq:[['What’s included?','A personalized page, one annual campaign of 150 targeted letters, and unlimited market-analysis requests in your VendVite workspace.'],['Do I pay when I submit the form?','No. Your request comes with no commitment. If approved, you can prepare your page before deciding to activate your membership.'],['Who prepares the comparative market analysis?','You, the broker. VendVite helps start the conversation; your expertise and follow-up take it from there.'],['Are leads or listings guaranteed?','No. Results depend on your neighbourhood, homeowner interest and your follow-up. There is no guaranteed number of requests or listings.']],
  hp_final:'Make your neighbourhood the start of your next conversation.', hp_preview:'Test preview — no messages sent or conversions recorded.',
  hp_preview_done:'This is a preview. No request was sent.', hp_sticky:'Build your local presence', hp_back:'Back to the form'
 }
};
