'use strict';
const H=require('./campaign-history-v2');
const crypto=require('crypto'),M=require('./public/js/campaign-model-v2'),G=require('./public/js/canada-geography-v1');
const columns=['address_id','house_number','street','unit','city','province','postal_code'];
const original=c=>(typeof c.addresses==='string'?JSON.parse(c.addresses):c.addresses||[]).map(a=>({...a,ville:a.ville||c.city||'',province:a.province||M.province(a)||c.province||''}));
const building=a=>[M.norm(a.numero),M.street(a.rue),M.norm(a.ville),a.province||M.province(a)].join('|');
const digest=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,24);
const addressId=a=>'addr_'+digest(building(a)+'|'+M.norm(a.unit));
function field(v){let s=String(v==null?'':v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function csv(rows){return '\uFEFF'+[columns,...rows].map(r=>r.map(field).join(',')).join('\r\n');}
function template(c){return csv(original(c).map(a=>[addressId(a),a.numero,a.rue,a.unit||'',a.ville||c.city||'',a.province||M.province(a),a.postal||'']));}
function parse(raw){if(typeof raw!=='string'||raw.length>3000000)throw Error('Fichier CSV limité à 3 Mo.');raw=raw.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false;
 for(let i=0;i<raw.length;i++){const ch=raw[i];if(ch==='"'){if(quoted&&raw[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell!=='')throw Error('CSV invalide : guillemet inattendu.');else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell.trim());cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&raw[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=ch;}
 if(quoted)throw Error('CSV invalide : guillemets non fermés.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(!rows.length||JSON.stringify(rows.shift())!==JSON.stringify(columns))throw Error('Utilisez exactement les colonnes du fichier modèle.');if(!rows.length||rows.length>12000)throw Error('Importez entre 1 et 12 000 lignes.');return rows;
}
function stage(c,raw){const rows=parse(raw),source=new Map(original(c).map(a=>[addressId(a),a])),candidates=[],seen=new Set();
 for(const [index,r] of rows.entries()){
  if(r.length!==7)throw Error('Ligne '+(index+2)+' : 7 colonnes requises.');const [id,numero,rue,unit,ville,province,postalInput]=r,a=source.get(id);if(!a)throw Error('Ligne '+(index+2)+' : address_id inconnu pour cette commande.');
  if([numero,rue,unit,ville,province,postalInput].some(s=>s.length>160||/[\u0000-\u001f\u007f]/.test(s))||unit.length>20)throw Error('Ligne trop longue.');
  const clean={...a,numero,rue,unit,ville,province:province.toUpperCase(),postal:postalInput.toUpperCase().replace(/\s/g,'')};
  if(building(clean)!==building(a))throw Error('Ligne '+(index+2)+' : le bâtiment diffère de la commande. Conservez numéro, rue, ville et province.');
  const key=digest(building(clean)+'|'+M.norm(unit));if(seen.has(key))throw Error('Ligne '+(index+2)+' : unité en double.');seen.add(key);
  const postalOK=/^[ABCEGHJ-NPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]\d[ABCEGHJ-NPRSTV-Z]\d$/.test(clean.postal)&&(!G.postalProvince(clean.postal)||G.postalProvince(clean.postal)===clean.province);
  if(postalOK)clean.postal=clean.postal.slice(0,3)+' '+clean.postal.slice(3);
  candidates.push({id:key,addressId:id,building:building(clean),address:clean,postalOK});
 }
 const groups=new Map();for(const a of original(c)){const key=building(a);if(!groups.has(key))groups.set(key,{key,address:a,knownUnits:0,flagged:false});const g=groups.get(key),p=a.analysis||{};g.knownUnits=Math.max(g.knownUnits,Number(p.units)||0);g.flagged=g.flagged||!!a.unit||g.knownUnits>1||['plex','apartment','condo'].includes(p.type);}
 for(const g of groups.values()){g.candidates=candidates.filter(a=>a.building===g.key);g.flagged=g.flagged||g.candidates.length>1||g.candidates.some(a=>!!a.address.unit);}
 const selected=[];for(const g of groups.values())if(!g.flagged&&g.candidates.length===1&&g.candidates[0].postalOK)selected.push(g.candidates[0].id);
 return {audit:(c.production||{}).audit||[],previousVersions:(c.production||{}).previousVersions||[],correctionPending:!!(c.production||{}).correctionPending,revision:Number((c.production||{}).revision||0)+1,importedAt:new Date().toISOString(),candidates,groups:Array.from(groups.values()),selected,approvedAt:null};
}
function approve(c,selected,options={}){const p=c.production;if(!p||!Array.isArray(p.candidates)||!Array.isArray(selected)||!selected.length)throw Error('Sélectionnez les destinataires à imprimer.');if(new Set(selected).size!==selected.length||selected.length>Number(c.address_count))throw Error('Nombre de lettres invalide.');if(!options.allowUnsettled&&selected.length<Number(c.address_count)&&!accepted(c,selected))throw Error('Accord explicite du courtier requis pour le nombre de lettres manquantes.');const byId=new Map(p.candidates.map(a=>[a.id,a])),groups=new Set(),recipients=[];
 for(const id of selected){const a=byId.get(id);if(a&&a.historyBlocked)throw Error('Adresse déjà ciblée le '+new Date(a.targetedAt).toLocaleDateString('fr-CA')+' : choisissez une autre unité.');if(!a||!a.postalOK)throw Error('Chaque destinataire doit avoir un code postal valide.');if(groups.has(a.building))throw Error('Une seule unité par bâtiment est permise.');const g=p.groups.find(g=>g.key===a.building);if(g.flagged&&!a.address.unit)throw Error('Précisez l’unité choisie pour ce bâtiment.');groups.add(a.building);const previous=p.correctionPending?null:original(c).find(old=>building(old)===a.building&&M.norm(old.unit)===M.norm(a.address.unit));recipients.push({...a.address,mailing_id:previous&&/^[a-f0-9]{32}$/.test(previous.mailing_id||'')?previous.mailing_id:crypto.randomBytes(16).toString('hex')});}
 const report=p.groups.map(g=>{const chosen=p.candidates.find(a=>a.building===g.key&&selected.includes(a.id));return {address:g.address,knownUnits:g.knownUnits,multiUnit:g.flagged,selected:chosen?chosen.address:null,omitted:g.candidates.filter(a=>a.building===g.key&&!selected.includes(a.id)).map(a=>({address:a.address,reason:a.historyBlocked?'Déjà ciblée le '+a.targetedAt:a.postalOK?'Unité ou adresse non retenue':'Code postal manquant ou invalide'})),missing:g.candidates.length===0};}).filter(g=>g.multiUnit||g.missing||g.omitted.length||!g.selected);
 return {...p,revision:p.revision+1,selected,recipients,report,approvedAt:new Date().toISOString(),correctionPending:false,orderedCount:Number(c.address_count),preparedCount:recipients.length};
}
function ready(c){return !!(c.production&&c.production.approvedAt&&c.production.recipients&&c.production.recipients.length&&(!c.production.orderedCount||c.production.preparedCount>=c.production.orderedCount||accepted(c,c.production.selected)));}
function editable(c){return ['confirmed','processing'].includes(c.status)&&(c.payment_status==='paid'||c.kind==='included'&&c.payment_status==='none')&&!ready(c);}
function fingerprint(c,selected){return digest(JSON.stringify({id:c.id,selected:[...selected].sort(),addresses:(c.production.candidates||[]).filter(a=>selected.includes(a.id)).map(a=>[a.id,a.address.postal]),ordered:Number(c.address_count),total:Number(c.total_cents),policy:H.policy(c.history_policy)}));}
function accepted(c,selected){const x=(c.production||{}).shortfall;return !!(x&&x.state==='accepted'&&x.brokerId===c.broker_id&&x.fingerprint===fingerprint(c,selected));}
function requestDecision(c,selected){const approved=approve(c,selected,{allowUnsettled:true});if(approved.preparedCount>=Number(c.address_count))throw Error('La quantité complète ne nécessite aucun accord de réduction.');const at=new Date().toISOString();return {...c.production,revision:c.production.revision+1,selected,shortfall:{state:'requested',requestedAt:at,orderedCount:Number(c.address_count),preparedCount:approved.preparedCount,missingCount:Number(c.address_count)-approved.preparedCount,totalCents:Number(c.total_cents),fingerprint:fingerprint(c,selected),report:approved.report,termsVersion:1,terms:'Envoi du nombre préparé indiqué pour le montant initial intégral. Aucun remboursement ni crédit pour les lettres manquantes. Vous pouvez refuser; la commande restera en attente d’une résolution avec VendVite.'},audit:[...(c.production.audit||[]),{at,action:'shortfall_requested',actor:'tenant_admin',preparedCount:approved.preparedCount}]};}
function decide(c,brokerId,decision){const p=c.production,x=p.shortfall;if(!x||x.state!=='requested'||x.fingerprint!==fingerprint(c,p.selected)||!['accept','reject'].includes(decision)||brokerId!==c.broker_id)throw Error('Cette décision a changé. Actualisez la page.');const at=new Date().toISOString();return {...p,revision:p.revision+1,shortfall:{...x,state:decision==='accept'?'accepted':'rejected',brokerId,decidedAt:at},audit:[...(p.audit||[]),{at,action:'shortfall_'+decision,brokerId}]};}
async function checkHistory(db,c,p){const filter=H.policy(c.history_policy),since=filter.mode==='days'?new Date(Date.now()-filter.days*86400000):null;let old=[];if(filter.mode!=='off')old=await db.all("SELECT id,addresses,production,city,province,COALESCE(mailed_at,created_at) targeted_at FROM broker_campaigns WHERE broker_id=$1 AND id<>$2 AND is_test=0 AND paypal_mode<>'sandbox' AND status IN ('confirmed','processing','mailed') AND (payment_status='paid' OR kind='included' AND payment_status='none') AND ($3::timestamptz IS NULL OR COALESCE(mailed_at,created_at)>=$3) ORDER BY COALESCE(mailed_at,created_at) DESC",[c.broker_id,c.id,since]);const latest=new Map();for(const prior of old)for(const a of (prior.production&&prior.production.approvedAt?prior.production.recipients:prior.addresses)||[]){const k=H.key(a,prior.city,prior.province);if(!latest.has(k))latest.set(k,{at:new Date(prior.targeted_at).toISOString(),campaignId:prior.id});}const candidates=p.candidates.map(a=>({...a,historyBlocked:latest.has(H.key(a.address)),targetedAt:(latest.get(H.key(a.address))||{}).at||null,targetedCampaignId:(latest.get(H.key(a.address))||{}).campaignId||null}));return {...p,historyPolicy:filter,historyCheckedAt:new Date().toISOString(),candidates,groups:p.groups.map(g=>({...g,candidates:candidates.filter(a=>a.building===g.key)})),selected:(p.selected||[]).filter(id=>!candidates.find(a=>a.id===id&&a.historyBlocked))};}
function reopen(c,reason){if(c.status==='mailed'||!ready(c))throw Error('Seule une préparation validée et non déposée peut être corrigée.');reason=String(reason||'').trim();if(reason.length<10||reason.length>1000)throw Error('Décrivez la correction (10 à 1000 caractères).');const p=c.production,at=new Date().toISOString(),version={revision:p.revision,approvedAt:p.approvedAt,preparedCount:p.preparedCount,recipients:p.recipients,printSnapshot:p.printSnapshot,printBatches:p.printBatches||[],shortfall:p.shortfall||null,report:p.report,invalidatedAt:at,reason};return {revision:p.revision+1,correctionPending:true,audit:[...(p.audit||[]),{at,action:'reopened',actor:'tenant_admin',reason,invalidatedRevision:p.revision}],previousVersions:[...(p.previousVersions||[]),version]};}
function batches(c){const p=c.production||{};return Array.from({length:Math.ceil((p.preparedCount||0)/100)},(_,i)=>({number:i+1,start:i*100+1,end:Math.min((i+1)*100,p.preparedCount),count:Math.min(100,p.preparedCount-i*100),record:(p.printBatches||[]).find(b=>b.number===i+1)}));}
function deposit(c,count,date){const p=c.production;if(c.status!=='processing'||!ready(c))throw Error('Préparation prête et non déposée requise.');if(Number(count)!==p.preparedCount)throw Error('Le dépôt doit couvrir exactement la quantité préparée. Corrigez la préparation avant tout dépôt incomplet.');if(batches(c).some(b=>!b.record))throw Error('Générez chaque lot d’impression avant de déclarer le dépôt.');const at=new Date(date),now=new Date();if(!Number.isFinite(at.getTime())||at>now||at.getTime()<Math.floor(new Date(p.approvedAt).getTime()/1000)*1000)throw Error('Date du dépôt invalide : entre la validation et maintenant.');return {...p,deposited:{at:at.toISOString(),count:Number(count),recordedAt:now.toISOString()},audit:[...(p.audit||[]),{at:now.toISOString(),action:'deposited',actor:'tenant_admin',count:Number(count),depositedAt:at.toISOString()}]};}
module.exports={columns,original,building,addressId,csv,template,parse,stage,approve,ready,editable,fingerprint,accepted,requestDecision,decide,checkHistory,reopen,batches,deposit};
