/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_luc_venne).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812886/tapavis_tenant_garage_luc_venne/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812886/tapavis_tenant_garage_luc_venne/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812910/tapavis_tenant_garage_luc_venne/hero_af468f87-f7f9-429e-a4ff-abf625ce82eb.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812908/tapavis_tenant_garage_luc_venne/vidange-huile_ce61767e-a32e-46c5-af01-a0ec80268885.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812909/tapavis_tenant_garage_luc_venne/freins_0aeff6a2-5aec-4b5f-9374-ead263e3e5da.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812911/tapavis_tenant_garage_luc_venne/mecanique-generale_ecf4601b-f783-44f7-b9f2-899785cddd8a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812932/tapavis_tenant_garage_luc_venne/silencieux_b29ab813-bbc2-4ade-8fb4-db5cd08415ee.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812933/tapavis_tenant_garage_luc_venne/suspension_7f7624a7-1d9d-4391-9df2-3b488d2e2b74.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812934/tapavis_tenant_garage_luc_venne/equilibrage-rotation-pneus_ab16fa1c-f490-4b62-bfed-65405b68e90b.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812936/tapavis_tenant_garage_luc_venne/mise-au-point_afdc7f61-e574-4b45-affa-7ba0704deb5b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812948/tapavis_tenant_garage_luc_venne/transmission_c7253ef5-2f2f-472b-9652-3d7bfca19902.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812965/tapavis_tenant_garage_luc_venne/climatisation_2c460d21-b300-47c1-b407-e7ef3801511a.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812965/tapavis_tenant_garage_luc_venne/systeme-de-refroidissement_4b0e91cf-b350-4977-b9e2-43aa74fc8133.png"
  }
};
