/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_autos_pneus_jmf).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738562/tapavis_tenant_autos_pneus_jmf/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738562/tapavis_tenant_autos_pneus_jmf/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738574/tapavis_tenant_autos_pneus_jmf/hero_4d47f280-e5e6-493f-a2a8-c4313ba97cd4.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738575/tapavis_tenant_autos_pneus_jmf/freins_25fc4800-1fdd-4b91-b401-1d191f2dbacb.png",
    "pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738576/tapavis_tenant_autos_pneus_jmf/pneus_20857ee9-a8db-4fb6-8659-b44dab90e8ab.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738577/tapavis_tenant_autos_pneus_jmf/mecanique-generale_5c433294-f283-4a6c-95f2-9d5b77650bfd.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738588/tapavis_tenant_autos_pneus_jmf/silencieux_c32fe6bd-8eec-406a-9650-b67ca4bbd9c4.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738589/tapavis_tenant_autos_pneus_jmf/vidange-huile_3028df06-0d85-4ed9-8fba-1d1b7f0c24e5.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738588/tapavis_tenant_autos_pneus_jmf/equilibrage-rotation-pneus_614bb719-22ba-421b-8844-074eb02a17b4.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738589/tapavis_tenant_autos_pneus_jmf/suspension_311934fa-f929-4379-988c-dab26f9c638f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738601/tapavis_tenant_autos_pneus_jmf/climatisation_d034bc81-77bc-496b-9505-971c4589c71e.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738601/tapavis_tenant_autos_pneus_jmf/systeme-de-refroidissement_7ebc38ad-5e4d-4892-9b56-da951c1fb6b7.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738603/tapavis_tenant_autos_pneus_jmf/transmission_d1ddf657-bfd7-46dd-9e51-f391e55907de.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738614/tapavis_tenant_autos_pneus_jmf/mise-au-point_28256a80-25d1-4e6a-bc89-5de83dfe4afb.png"
  }
};
