/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_roger_choquette).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929865/tapavis_tenant_garage_roger_choquette/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929865/tapavis_tenant_garage_roger_choquette/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929876/tapavis_tenant_garage_roger_choquette/hero_8419e6c4-2f8e-401a-b6a4-bbe5c3fdcaf6.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929876/tapavis_tenant_garage_roger_choquette/freins_53522f50-f879-43c8-ad1d-ad6fd0ec7954.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929876/tapavis_tenant_garage_roger_choquette/vidange-huile_d20c60dd-68f7-401b-b09b-ff13f939c178.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929880/tapavis_tenant_garage_roger_choquette/mecanique-generale_74d94a53-8cde-43ec-a135-a8fdbb32f11b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929885/tapavis_tenant_garage_roger_choquette/silencieux_318c947c-07cd-4163-a12d-7b5fd9799704.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929886/tapavis_tenant_garage_roger_choquette/equilibrage-rotation-pneus_49a77b1b-f526-4bbc-8309-be522669961f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929888/tapavis_tenant_garage_roger_choquette/suspension_cdd38060-1422-48e4-b532-c2a3aff05f48.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929891/tapavis_tenant_garage_roger_choquette/systeme-de-refroidissement_88d00438-01aa-49cf-9229-8d7d27a4ec02.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929897/tapavis_tenant_garage_roger_choquette/mise-au-point_fe381baf-11dc-41d5-9885-740c29889dbb.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929897/tapavis_tenant_garage_roger_choquette/climatisation_4e25de62-d05f-4508-bf03-d14e3e65a565.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929900/tapavis_tenant_garage_roger_choquette/transmission_97f9f4ca-63c2-4d59-a11e-6ca15bd36f81.png"
  }
};
