/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_atelier_mecanique_eric_bouchard).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734588/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734588/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734599/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/hero_475bf669-cf8a-495d-b0b5-d423790c8fc2.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734599/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/vidange-huile_299cba4f-3593-4ca8-a622-95dfd9175647.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734600/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/freins_37aa1f3c-1b10-4f9a-893f-e5975393c6e6.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734601/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/mecanique-generale_48439fa8-aee2-4ec5-a31f-b86bbe544a3d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734610/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/equilibrage-rotation-pneus_ed2965eb-7a0d-4427-9d94-9a47507dd1b6.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734611/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/suspension_2edf87c4-0bd7-43fd-9eab-522abc581d18.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734610/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/silencieux_5c7dfb0d-8376-4e4d-ab3b-411046ee3273.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734613/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/systeme-de-refroidissement_13a57f32-9227-46f7-b561-b44a61d5c389.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734621/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/mise-au-point_dde5fc49-b543-4f4b-8c10-e35fd50ac780.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734623/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/transmission_30a74b1b-284c-469b-8de2-d1eba4026fe7.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734628/tapavis_tenant_garage_atelier_mecanique_eric_bouchard/climatisation_e610ba8c-4be2-424f-950c-d4ee6fa8f284.png"
  }
};
