/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_service_mecanique_ip).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738157/tapavis_tenant_service_mecanique_ip/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738157/tapavis_tenant_service_mecanique_ip/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738168/tapavis_tenant_service_mecanique_ip/hero_be0aef25-92ff-42aa-8a78-9dcd9722cd75.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738168/tapavis_tenant_service_mecanique_ip/vidange-huile_d898f638-7c01-437e-b8f8-0e7675e62dfc.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738169/tapavis_tenant_service_mecanique_ip/mecanique-generale_b8f19545-e0fc-41f5-8c81-b9624df1b692.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738170/tapavis_tenant_service_mecanique_ip/freins_485ca26d-fe52-43a1-90ac-24109473fe1b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738178/tapavis_tenant_service_mecanique_ip/silencieux_f07880a1-318b-49b3-a825-efefe46db26d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738179/tapavis_tenant_service_mecanique_ip/equilibrage-rotation-pneus_18d22256-df1e-4fb6-b28b-2403e1d6ec19.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738180/tapavis_tenant_service_mecanique_ip/suspension_a13908bc-4185-4e37-829f-fa731cefc29e.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738181/tapavis_tenant_service_mecanique_ip/systeme-de-refroidissement_b6aa6bf8-0a0a-4f0b-a2ca-a163d5923ab9.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738191/tapavis_tenant_service_mecanique_ip/mise-au-point_c957afea-8cdc-452d-9d7f-37e40915aa8c.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738191/tapavis_tenant_service_mecanique_ip/climatisation_c53ab65b-0758-4c0b-bd55-63299bc1d3ec.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738193/tapavis_tenant_service_mecanique_ip/transmission_bb7236cc-b450-4db3-a015-342dda1d350f.png"
  }
};
