/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_rene_girard).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443484/tapavis_tenant_garage_rene_girard/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443484/tapavis_tenant_garage_rene_girard/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443622/tapavis_tenant_garage_rene_girard/hero_27d8a62e-04a9-4c04-8001-f98e718c3095.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443622/tapavis_tenant_garage_rene_girard/vidange-huile_ae7389c7-2a04-4785-aac4-236ed5c37d45.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443622/tapavis_tenant_garage_rene_girard/freins_ca9fa963-f959-4ebe-b0cf-c9063a98a8cd.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443658/tapavis_tenant_garage_rene_girard/equilibrage-rotation-pneus_7315ff5b-a6f0-4310-9528-ba09386201f8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443658/tapavis_tenant_garage_rene_girard/mecanique-generale_b8d09f4b-af9b-43d6-b89e-7e229114b437.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443671/tapavis_tenant_garage_rene_girard/climatisation_27bdc6c6-c5a6-4b6e-9f6e-841ea4a6d577.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443672/tapavis_tenant_garage_rene_girard/silencieux_ab7fd895-862b-4827-afc7-b8c41c990823.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443673/tapavis_tenant_garage_rene_girard/systeme-de-refroidissement_ea971b50-81db-4d65-96ac-34fa9024b31f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443673/tapavis_tenant_garage_rene_girard/suspension_17799a06-4b73-4950-b623-f701cf30c48d.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443683/tapavis_tenant_garage_rene_girard/mise-au-point_6c5e5a62-0ae8-46d9-bd43-e3818e4c5c75.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790443684/tapavis_tenant_garage_rene_girard/transmission_b5693372-0f65-4555-a8c9-93258f072c36.png"
  }
};
