/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_auto_alternative_r_d_p).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791050487/tapavis_tenant_auto_alternative_r_d_p/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791050487/tapavis_tenant_auto_alternative_r_d_p/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050503/tapavis_tenant_auto_alternative_r_d_p/hero_9d2d4750-c7c4-4f68-9f36-7210f68062fc.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791050502/tapavis_tenant_auto_alternative_r_d_p/vidange-huile_d7c26c05-5793-4739-b8a9-d23368da4810.webp",
    "freins": "https://media.liasse.tech/upload/v1791050502/tapavis_tenant_auto_alternative_r_d_p/freins_2a7cab12-8654-47d9-a0e7-6f03f272383b.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791050503/tapavis_tenant_auto_alternative_r_d_p/mecanique-generale_c715bf53-169d-4082-a7e2-615a3d9c4800.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791050512/tapavis_tenant_auto_alternative_r_d_p/equilibrage-rotation-pneus_5f6d2429-13db-457b-bb2c-356032eb634c.webp",
    "suspension": "https://media.liasse.tech/upload/v1791050512/tapavis_tenant_auto_alternative_r_d_p/suspension_f020a4e0-d2eb-4325-bcf7-7a1f5a273f47.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791050513/tapavis_tenant_auto_alternative_r_d_p/silencieux_c473af10-5856-4769-9b91-d0e4f9dc7035.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791050515/tapavis_tenant_auto_alternative_r_d_p/systeme-de-refroidissement_59bf89da-74f4-4de1-9097-543cbfba16dc.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791050523/tapavis_tenant_auto_alternative_r_d_p/climatisation_b2bb8fa1-24ae-45b3-bbf7-d9d60000b42d.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791050524/tapavis_tenant_auto_alternative_r_d_p/mise-au-point_28902b54-78d1-410e-930e-669c4aa728e6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791050525/tapavis_tenant_auto_alternative_r_d_p/transmission_3be939a4-4e55-45a5-ac17-756672b89205.webp"
  }
};
