/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_auto_village).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791052377/tapavis_tenant_auto_village/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791052377/tapavis_tenant_auto_village/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791054249/tapavis_tenant_auto_village/hero_714741e1-9412-4424-b094-37ec3ad5fcb9.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791052393/tapavis_tenant_auto_village/vidange-huile_29a1ef7b-370b-4e3a-bf17-2312f44d3730.webp",
    "freins": "https://media.liasse.tech/upload/v1791052393/tapavis_tenant_auto_village/freins_4ca3abc1-2921-4d34-977d-53650a5722e8.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791052393/tapavis_tenant_auto_village/mecanique-generale_35adf443-57a0-4b6d-91cc-b6876cfe98c4.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791052401/tapavis_tenant_auto_village/silencieux_1818b8e2-7015-4bfc-8b7f-403b7feea1bf.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791052402/tapavis_tenant_auto_village/equilibrage-rotation-pneus_d7ecf4bf-a390-465b-8579-c3c784c41985.webp",
    "suspension": "https://media.liasse.tech/upload/v1791052404/tapavis_tenant_auto_village/suspension_91d082ea-9d58-40a6-ada3-318e62e13c69.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791052404/tapavis_tenant_auto_village/systeme-de-refroidissement_2e3655a5-48f6-4a57-b4e2-1c5713072380.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791052412/tapavis_tenant_auto_village/climatisation_ac729ce8-0a49-4989-986a-b948e6c5c94c.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791052413/tapavis_tenant_auto_village/mise-au-point_cfa2496c-9d44-47d4-87c2-b78b1a789d2f.webp",
    "transmission": "https://media.liasse.tech/upload/v1791052414/tapavis_tenant_auto_village/transmission_da619953-59ac-462a-b3d2-ceb40588347b.webp"
  }
};
