/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_monsieur_4_roues).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791051056/tapavis_tenant_monsieur_4_roues/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791051056/tapavis_tenant_monsieur_4_roues/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791052362/tapavis_tenant_monsieur_4_roues/hero_62ab2d60-2782-4ea0-a95e-fbf183455922.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791051071/tapavis_tenant_monsieur_4_roues/vidange-huile_fafde507-56d8-408e-905a-c3715ae9adeb.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791051071/tapavis_tenant_monsieur_4_roues/mecanique-generale_b3a03820-9dcb-445b-8949-c5d9a0af299b.webp",
    "freins": "https://media.liasse.tech/upload/v1791051071/tapavis_tenant_monsieur_4_roues/freins_9a588269-6c1f-4949-93ea-a2047885d166.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791051080/tapavis_tenant_monsieur_4_roues/equilibrage-rotation-pneus_91d04845-0cfe-4ac8-b28c-c4a6cc8237a5.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791051080/tapavis_tenant_monsieur_4_roues/silencieux_5ebe1fdb-ddc2-4b84-ac50-931b2cf59852.webp",
    "suspension": "https://media.liasse.tech/upload/v1791051081/tapavis_tenant_monsieur_4_roues/suspension_18d39868-b82a-4051-8558-889c96c32a85.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791051082/tapavis_tenant_monsieur_4_roues/systeme-de-refroidissement_a6b71cad-77a4-43c9-b3f0-c99a522b1e6a.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791051091/tapavis_tenant_monsieur_4_roues/mise-au-point_4728f757-ee59-40d8-a7db-70567873b271.webp",
    "transmission": "https://media.liasse.tech/upload/v1791051092/tapavis_tenant_monsieur_4_roues/transmission_f4c7a4e3-0ece-4d1e-9217-c017b1651cdc.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791051092/tapavis_tenant_monsieur_4_roues/climatisation_2f890769-3684-4da6-8c77-ca84f61e6a55.webp"
  }
};
