/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mgb_mecanique_garage_baril).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667573/tapavis_tenant_mgb_mecanique_garage_baril/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667573/tapavis_tenant_mgb_mecanique_garage_baril/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667584/tapavis_tenant_mgb_mecanique_garage_baril/hero_55dfaa4c-7489-4dce-8640-c80cfa8ae136.png",
  "services": {
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667584/tapavis_tenant_mgb_mecanique_garage_baril/batterie-demarreur-alternateur_3f016fdc-1688-4927-8a31-b1ea4350a015.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667585/tapavis_tenant_mgb_mecanique_garage_baril/equilibrage-rotation-pneus_23f652e2-c99a-4d5b-892b-3a855a7c0c0c.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667585/tapavis_tenant_mgb_mecanique_garage_baril/mise-au-point_0e1e8bdd-957c-43f8-85e4-b14213ab8c3a.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667595/tapavis_tenant_mgb_mecanique_garage_baril/entretien-preventif_ef00a5df-f137-40de-a9fc-236d56ba0414.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667595/tapavis_tenant_mgb_mecanique_garage_baril/vidange-huile_457f8013-6195-498d-8a6b-858f380095cb.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667595/tapavis_tenant_mgb_mecanique_garage_baril/inspection-mecanique_bf9fc95a-b4e6-4f5d-a516-a902d660bf9c.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667598/tapavis_tenant_mgb_mecanique_garage_baril/systeme-electrique_1355baba-8963-4bc8-b630-0bf9f158b72b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667604/tapavis_tenant_mgb_mecanique_garage_baril/silencieux_587e29b0-e1dc-49fe-b625-a527e3fe9c8c.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667606/tapavis_tenant_mgb_mecanique_garage_baril/alignement_79977747-8113-40ed-9822-ed9715c3d57b.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667606/tapavis_tenant_mgb_mecanique_garage_baril/systeme-de-refroidissement_3545dd97-18c4-4136-a240-6728323a9bad.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667610/tapavis_tenant_mgb_mecanique_garage_baril/suspension_be3c2449-aba1-4e24-a9c1-8b5aa5e244f5.png",
    "injection": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667616/tapavis_tenant_mgb_mecanique_garage_baril/injection_f9623cd0-d97d-4f6d-87f2-a9ad3dc0aa71.png"
  }
};
