/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_bruce).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734099/tapavis_tenant_garage_bruce/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734099/tapavis_tenant_garage_bruce/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734112/tapavis_tenant_garage_bruce/hero_39cbaae7-6ee8-4926-905d-8cbaff1dd395.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734112/tapavis_tenant_garage_bruce/freins_4c4cfbb5-e955-4ca8-9468-19e26c7f722a.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734113/tapavis_tenant_garage_bruce/vidange-huile_2f24ea3b-41a6-476b-b340-907085ab7567.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734114/tapavis_tenant_garage_bruce/mecanique-generale_4584788a-15e4-4612-9168-46d457ec2497.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734124/tapavis_tenant_garage_bruce/suspension_dd725612-f05b-4745-bb81-e43684a729cf.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734125/tapavis_tenant_garage_bruce/silencieux_3ac34ee8-b3cb-47f2-be2d-b60308de39c7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734125/tapavis_tenant_garage_bruce/equilibrage-rotation-pneus_d7a1bae7-63e1-40ba-a19b-a9f653375c7e.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734126/tapavis_tenant_garage_bruce/systeme-de-refroidissement_47555446-e18b-4fbd-a8c3-c537366e24eb.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734136/tapavis_tenant_garage_bruce/climatisation_003edfa5-5583-47eb-abba-bda0f1d8d3a9.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734137/tapavis_tenant_garage_bruce/mise-au-point_3459cddc-76af-4820-8c2e-138e64c60b08.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734137/tapavis_tenant_garage_bruce/transmission_2d8c7d7e-3996-4194-bd46-cfcd80e532de.png"
  }
};
