/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_automatce).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813082/tapavis_tenant_automatce/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813082/tapavis_tenant_automatce/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813099/tapavis_tenant_automatce/hero_c8c07039-78eb-4645-be15-c5697b8e83d3.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813100/tapavis_tenant_automatce/freins_6642ad73-8028-4265-beab-e79a278b9df2.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813101/tapavis_tenant_automatce/vidange-huile_101c05cf-7f6d-4acb-afde-d61c48c3a297.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813101/tapavis_tenant_automatce/mecanique-generale_f371e3a3-da6b-4810-9dde-754a16ffb255.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813114/tapavis_tenant_automatce/climatisation_d6644bdd-98fe-4d0c-bfca-a2290d12ad88.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813130/tapavis_tenant_automatce/equilibrage-rotation-pneus_69e791b2-f273-4a4a-898c-f843efd1cc63.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814138/tapavis_tenant_automatce/suspension_06acf178-1dfe-4fa5-9bbf-6468c8ce21fc.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814138/tapavis_tenant_automatce/silencieux_0ec37f86-fc59-45d4-bdfb-e96e935a90b9.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814139/tapavis_tenant_automatce/mise-au-point_ca7465ef-08ac-4ae6-87fa-c56849e444e4.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814139/tapavis_tenant_automatce/systeme-de-refroidissement_e86f063f-67ec-4e2a-9b68-d238b676daa2.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814149/tapavis_tenant_automatce/transmission_a71f7ed9-4a44-4ca6-a2e1-f01061b071dc.png"
  }
};
