/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_glc_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791052979/tapavis_tenant_glc_auto/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791052979/tapavis_tenant_glc_auto/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791054356/tapavis_tenant_glc_auto/hero_0097dd8b-02c6-4845-8903-f92df1dc0f48.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791052994/tapavis_tenant_glc_auto/freins_a8e0ee1d-ba89-4d60-95b4-410d533ec261.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791052995/tapavis_tenant_glc_auto/vidange-huile_978eb1b0-3454-4bdc-8974-9b9c004de8bf.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791052995/tapavis_tenant_glc_auto/mecanique-generale_d2c74d23-19a8-47fc-af93-74c6c1373276.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791053003/tapavis_tenant_glc_auto/equilibrage-rotation-pneus_d21e1db9-eca0-4aa6-9aa1-7a965f4ea916.webp",
    "suspension": "https://media.liasse.tech/upload/v1791053005/tapavis_tenant_glc_auto/suspension_b9987252-518c-4a00-8628-6faf56ece381.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791053005/tapavis_tenant_glc_auto/silencieux_1665f165-db6f-43ee-a156-b0faebf04c1e.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791053006/tapavis_tenant_glc_auto/systeme-de-refroidissement_94b14096-cdfd-434e-aa7e-2ac922c0f82b.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791053014/tapavis_tenant_glc_auto/mise-au-point_cb0491ac-30be-45dd-9fa8-26e1c2ac43d6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791053017/tapavis_tenant_glc_auto/transmission_b6c0601d-b81f-49a5-b5c5-d5459505f242.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791053022/tapavis_tenant_glc_auto/climatisation_5aade90c-30c0-459f-8ea6-00afcca14142.webp"
  }
};
