ALTER TABLE razes ADD COLUMN IF NOT EXISTS total_tickets INTEGER DEFAULT 0;
ALTER TABLE razes ADD COLUMN IF NOT EXISTS drawn_at TIMESTAMPTZ;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS contact_email TEXT;