module.exports = async function(db){
  async function count(tbl){ try{ const r=await db.get('SELECT COUNT(*) c FROM '+tbl); return parseInt(r.c)||0; }catch(e){ return 0; } }
  const settings=[
    ['tagline','La salle des ventes des collectionneurs sérieux.'],
    ['refund_policy_fr','Tous les paiements de razes sont conservés en fiducie jusqu’au tirage. Si un raze est annulé par le vendeur ou la plateforme, chaque participant est intégralement remboursé par e-transfer dans un délai de 3 jours ouvrables. Les entrées payées mais non confirmées avant la clôture sont automatiquement remboursées. En cas de carte non conforme à sa description, le gagnant dispose de 7 jours pour signaler un litige et obtenir un remboursement complet.'],
    ['refund_policy_en','All raze payments are held in trust until the draw. If a raze is cancelled by the seller or the platform, every participant is fully refunded by e-transfer within 3 business days. Entries paid but not confirmed before close are automatically refunded. If a card does not match its description, the winner has 7 days to report a dispute and receive a full refund.'],
    ['transparency_intro_fr','Chaque tirage RAZZ·UP est aléatoire, certifié et vérifiable. Nous générons une graine cryptographique sécurisée au moment du tirage, puis publions une empreinte (preuve SHA-256) que personne ne peut modifier après coup. Le nombre exact de billets en jeu et l’empreinte sont affichés publiquement pour chaque raze tiré.'],
    ['transparency_intro_en','Every RAZZ·UP draw is random, certified and verifiable. We generate a secure cryptographic seed at the moment of the draw, then publish a fingerprint (SHA-256 proof) that nobody can alter afterward. The exact number of tickets in play and the fingerprint are publicly shown for every drawn raze.'],
    ['_p_hero_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215095.png']
  ];
  for(const [k,v] of settings){
    if(k.indexOf('_p_')===0 || (typeof v==='string' && v.indexOf('{{IMG')===0)){
      await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()',[k,v]);
    } else {
      await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[k,v]);
    }
  }
  if(await count('sellers')===0){
    const sellers=[
      ['Maison Tremblay Cartes','Vendeur fondateur de RAZZ·UP, spécialisé dans les recrues de hockey gradées. Plus de 12 ans à servir les collectionneurs du Québec.','https://placehold.co/400x400/1c2030/e8d8a4/png?text=MT',1,'Montréal, QC','tremblay@example.com',4.9,184,'2019','dory@liasse.tech'],
      ['Hardwood Holdings','Boutique haut de gamme NBA — recrues, refractors et numérotés. Authentification garantie sur chaque carte.','https://placehold.co/400x400/1c2030/e8d8a4/png?text=HH',1,'Toronto, ON','hardwood@example.com',4.8,212,'2020',null],
      ['Cooperstown Vault','Cartes de baseball vintage et modernes gradées PSA & SGC. Le coffre-fort des classiques.','https://placehold.co/400x400/1c2030/e8d8a4/png?text=CV',1,'Québec, QC','vault@example.com',5.0,97,'2021',null],
      ['Pitch & Prizm','Football et soccer — autographes certifiés et finitions holographiques rares.','https://placehold.co/400x400/1c2030/e8d8a4/png?text=PP',0,'Laval, QC','pitch@example.com',4.6,41,'2023',null],
      ['North Ice Collectibles','Recrues de hockey junior et de la LNH. Vendeur vérifié, expédition assurée.','https://placehold.co/400x400/1c2030/e8d8a4/png?text=NI',1,'Ottawa, ON','northice@example.com',4.7,73,'2022',null]
    ];
    for(const s of sellers) await db.run('INSERT INTO sellers (name,bio,image_url,verified,location,contact_email,rating,total_sales,member_since,featured) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[s[0],s[1],s[2],s[3],s[4],s[5],s[6],s[7],s[8],s[9]]);
  }
  if(await count('razes')===0){
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,status,starts_at,ends_at,featured,published) VALUES ('Recrue Connor Bedard — Young Guns','Carte recrue très convoitée, surface impeccable, centrage exceptionnel. Gradée et scellée.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215537.png','Connor Bedard Young Guns','2023','PSA 10','Hockey',1,'Maison Tremblay Cartes',1200,25,60,38,'active',NOW()-INTERVAL '1 day',NOW()+INTERVAL '4 days',1,1)");
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,status,starts_at,ends_at,featured,published) VALUES ('Victor Wembanyama Prizm Refractor','Recrue refractor numérotée, couleurs éclatantes. Une pièce de collection majeure.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464217/tapavis_tenant_razzup/build_razzup_1781464217285.png','Wembanyama Prizm Silver','2023','BGS 9.5','Basketball',2,'Hardwood Holdings',3500,40,80,61,'active',NOW()-INTERVAL '2 days',NOW()+INTERVAL '2 days',1,1)");
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,status,starts_at,ends_at,featured,published) VALUES ('Mickey Mantle 1956 Topps','Icône absolue du hobby. Surface vintage authentique, gradée et certifiée.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464217/tapavis_tenant_razzup/build_razzup_1781464217027.png','Mickey Mantle 1956 Topps','1956','SGC 5','Baseball',3,'Cooperstown Vault',8000,60,100,24,'active',NOW()-INTERVAL '1 day',NOW()+INTERVAL '6 days',1,1)");
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,status,starts_at,ends_at,featured,published) VALUES ('Patrick Mahomes Autographe','Carte signée sur la carte, certifiée. Lancement à venir — préparez vos entrées.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215755.png','Mahomes On-Card Auto','2017','BGS 9','Football',4,'Pitch & Prizm',2200,30,70,0,'upcoming',NOW()+INTERVAL '2 days',NOW()+INTERVAL '9 days',0,1)");
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,status,starts_at,ends_at,featured,published) VALUES ('Lionel Messi Holo','Finition holographique rare. Le raze se termine bientôt!','https://res.cloudinary.com/duhp69meg/image/upload/v1781464216/tapavis_tenant_razzup/build_razzup_1781464216490.png','Messi Holo Prizm','2018','PSA 9','Soccer',4,'Pitch & Prizm',900,20,50,47,'active',NOW()-INTERVAL '3 days',NOW()+INTERVAL '1 day',0,1)");
    await db.run("INSERT INTO razes (title,description,image_url,card_name,card_year,card_grade,sport,seller_id,seller_name,estimated_value,entry_price,max_entries,sold_entries,total_tickets,status,starts_at,ends_at,winner_name,draw_proof,drawn_at,featured,published) VALUES ('Wayne Gretzky O-Pee-Chee Recrue','Le Saint-Graal du hockey. Raze complété et tiré de façon certifiée.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215537.png','Gretzky OPC Rookie','1979','PSA 7','Hockey',2,'Hardwood Holdings',15000,50,120,120,120,'drawn',NOW()-INTERVAL '12 days',NOW()-INTERVAL '2 days','M. Tremblay','9f2c4a8e1b6d7c0e5a3f9b2d8c1e4f60','draw',NOW()-INTERVAL '2 days',0,1)");
  }
  if(await count('raze_entries')===0){
    await db.run("INSERT INTO raze_entries (raze_id,user_id,user_name,user_email,quantity,amount,payment_status,etransfer_ref) VALUES (1,NULL,'A. Gagnon','agagnon@example.com',2,50,'confirmed','RZ1ABC')");
    await db.run("INSERT INTO raze_entries (raze_id,user_id,user_name,user_email,quantity,amount,payment_status,etransfer_ref) VALUES (1,NULL,'J. Côté','jcote@example.com',1,25,'confirmed','RZ1DEF')");
    await db.run("INSERT INTO raze_entries (raze_id,user_id,user_name,user_email,quantity,amount,payment_status,etransfer_ref) VALUES (2,NULL,'L. Roy','lroy@example.com',1,40,'pending','RZ2GHI')");
  }
  if(await count('winners')===0){
    await db.run("INSERT INTO winners (raze_id,raze_title,winner_name,card_name,image_url,draw_date,draw_proof,total_tickets) VALUES (6,'Wayne Gretzky O-Pee-Chee Recrue','M. Tremblay','Gretzky OPC Rookie','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215537.png',NOW()-INTERVAL '2 days','9f2c4a8e1b6d7c0e5a3f9b2d8c1e4f60',120)");
    await db.run("INSERT INTO winners (raze_id,raze_title,winner_name,card_name,image_url,draw_date,draw_proof,total_tickets) VALUES (NULL,'Sidney Crosby Recrue','S. Bélanger','Crosby The Cup Rookie','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215537.png',NOW()-INTERVAL '9 days','a1b2c3d4e5f60718293a4b5c6d7e8f90',90)");
    await db.run("INSERT INTO winners (raze_id,raze_title,winner_name,card_name,image_url,draw_date,draw_proof,total_tickets) VALUES (NULL,'Ja Morant Prizm','K. Patel','Morant Silver Prizm','https://res.cloudinary.com/duhp69meg/image/upload/v1781464217/tapavis_tenant_razzup/build_razzup_1781464217285.png',NOW()-INTERVAL '16 days','7e6d5c4b3a2918071625344352617080',75)");
    await db.run("INSERT INTO winners (raze_id,raze_title,winner_name,card_name,image_url,draw_date,draw_proof,total_tickets) VALUES (NULL,'Ronaldo Holo','M. Dubois','Ronaldo Holo Refractor','https://res.cloudinary.com/duhp69meg/image/upload/v1781464216/tapavis_tenant_razzup/build_razzup_1781464216490.png',NOW()-INTERVAL '22 days','c0ffee1234567890abcdef0987654321',60)");
  }
  if(await count('reviews')===0){
    await db.run("INSERT INTO reviews (seller_id,author_name,rating,content) VALUES (1,'Marc L.',5,'Transaction impeccable, carte exactement comme décrite. Emballage de qualité musée.')");
    await db.run("INSERT INTO reviews (seller_id,author_name,rating,content) VALUES (1,'Sophie R.',5,'Vendeur sérieux et rapide. Je recommande sans hésiter pour les recrues de hockey.')");
    await db.run("INSERT INTO reviews (seller_id,author_name,rating,content) VALUES (2,'Daniel P.',5,'Refractor superbe, exactement la cote annoncée. Service 5 étoiles.')");
    await db.run("INSERT INTO reviews (seller_id,author_name,rating,content) VALUES (3,'Émilie C.',5,'Le coffre-fort vintage par excellence. Carte authentique et bien protégée.')");
    await db.run("INSERT INTO reviews (seller_id,author_name,rating,content) VALUES (2,'Tom W.',4,'Bonne expérience, expédition un peu lente mais carte parfaite.')");
  }
  if(await count('posts')===0){
    await db.run("INSERT INTO posts (title,content,image_url,category) VALUES ('Comment fonctionne un raze certifié','Un raze combine l’accessibilité d’une loterie et l’excitation d’une enchère. Achetez une ou plusieurs entrées sur une carte gradée; à la clôture, notre système tire un gagnant de façon aléatoire et publie une preuve cryptographique vérifiable par tous. Transparence totale, à chaque tirage.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464216/tapavis_tenant_razzup/build_razzup_1781464216525.png','Guide')");
    await db.run("INSERT INTO posts (title,content,image_url,category) VALUES ('Trois recrues de hockey à surveiller cette saison','Le marché des recrues bouge vite. Voici les noms qui retiennent l’attention des collectionneurs sérieux et qui apparaîtront bientôt dans nos razes.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464215/tapavis_tenant_razzup/build_razzup_1781464215537.png','Marché')");
    await db.run("INSERT INTO posts (title,content,image_url,category) VALUES ('Devenir vendeur vérifié sur RAZZ·UP','Le badge Vendeur Vérifié rassure les acheteurs et augmente vos ventes. Découvrez les critères: historique, authentification des cartes et qualité du service.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464217/tapavis_tenant_razzup/build_razzup_1781464217285.png','Vendeurs')");
    await db.run("INSERT INTO posts (title,content,image_url,category) VALUES ('Protéger et conserver vos cartes gradées','Lumière, humidité et manipulation: nos conseils pour préserver la valeur de vos slabs sur le long terme.','https://res.cloudinary.com/duhp69meg/image/upload/v1781464217/tapavis_tenant_razzup/build_razzup_1781464217027.png','Conseils')");
  }
  if(await count('card_submissions')===0){
    await db.run("INSERT INTO card_submissions (submitter_name,submitter_email,card_name,card_year,card_grade,sport,description,asking_price,status) VALUES ('A. Bourque','abourque@example.com','Auston Matthews Young Guns','2016','PSA 9','Hockey','Recrue Young Guns, beau centrage.',650,'pending')");
    await db.run("INSERT INTO card_submissions (submitter_name,submitter_email,card_name,card_year,card_grade,sport,description,asking_price,status) VALUES ('F. Nguyen','fnguyen@example.com','Luka Doncic Prizm','2018','BGS 9.5','Basketball','Refractor argent, surface parfaite.',1100,'pending')");
  }
};