/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_oasis).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623850/tapavis_tenant_garage_oasis/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623850/tapavis_tenant_garage_oasis/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623861/tapavis_tenant_garage_oasis/hero_1577da8c-a3b7-4f78-a7c3-c169d23a24eb.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623862/tapavis_tenant_garage_oasis/vidange-huile_9e959e9c-e909-46f4-97c7-f7e32927d720.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623863/tapavis_tenant_garage_oasis/freins_50cc2e4a-dc19-4cbb-83a3-1aa3406b9cfc.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623863/tapavis_tenant_garage_oasis/mecanique-generale_5b6adc96-751e-411d-88be-489d5d7a106a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623878/tapavis_tenant_garage_oasis/silencieux_076b7702-f649-49dc-b40b-6fe363ff9975.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623878/tapavis_tenant_garage_oasis/equilibrage-rotation-pneus_14913eb8-43c4-427b-97c6-99bef5079e0e.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623879/tapavis_tenant_garage_oasis/suspension_b76c808d-f280-4b27-9d46-c26b5a11a062.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623879/tapavis_tenant_garage_oasis/systeme-de-refroidissement_465a637b-e0cb-483a-ba0c-60f558cc9903.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623891/tapavis_tenant_garage_oasis/mise-au-point_460269af-72d0-463f-8b25-880253ef1b4b.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623891/tapavis_tenant_garage_oasis/climatisation_4c61351e-603c-48f0-88e9-33549224fbaa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790623892/tapavis_tenant_garage_oasis/transmission_b1de71a4-e874-46da-ad11-cfe6fea13a0f.png"
  }
};
