/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_tgb_cf).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813347/tapavis_tenant_garage_tgb_cf/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813347/tapavis_tenant_garage_tgb_cf/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813357/tapavis_tenant_garage_tgb_cf/hero_b5181578-59b8-47e7-8f1f-63f8cfed3f3c.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813357/tapavis_tenant_garage_tgb_cf/vidange-huile_be43f280-1b19-4b11-b8fb-dcf97092c13d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813359/tapavis_tenant_garage_tgb_cf/mecanique-generale_b6764544-8264-48f3-9811-e45fe54750de.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813359/tapavis_tenant_garage_tgb_cf/freins_14be00b8-893d-4b07-ad86-33068bb698b0.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_garage_tgb_cf/silencieux_3194c96f-ad60-4084-b0f9-93db85d0b8a3.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_garage_tgb_cf/suspension_88be82a9-4bd4-4071-bd6d-67d8e6c299ec.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_garage_tgb_cf/equilibrage-rotation-pneus_e0a2e1f6-86f5-4e20-be7a-5901f536eea1.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813373/tapavis_tenant_garage_tgb_cf/systeme-de-refroidissement_d37082b6-921e-400d-82d1-ad0d0a863c28.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813384/tapavis_tenant_garage_tgb_cf/mise-au-point_bc6e5d9a-294c-4070-bb26-5c63c1429187.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813384/tapavis_tenant_garage_tgb_cf/climatisation_f1a3c5fd-7dcf-4f17-a546-92af2a35748e.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813384/tapavis_tenant_garage_tgb_cf/transmission_9c4de144-8c86-4140-8140-956d7b92bf2e.png"
  }
};
