/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_rods_automotive_luskville).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790972915/tapavis_tenant_rods_automotive_luskville/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790972915/tapavis_tenant_rods_automotive_luskville/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790972932/tapavis_tenant_rods_automotive_luskville/hero_d96b9a96-f299-47f3-9348-71f8446f6085.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790972932/tapavis_tenant_rods_automotive_luskville/vidange-huile_64ca19d3-4ec0-45fd-a13d-4c8c980573e0.webp",
    "freins": "https://media.liasse.tech/upload/v1790972932/tapavis_tenant_rods_automotive_luskville/freins_fa7cc5d0-c689-4254-bffa-523e6d40ec0a.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790972932/tapavis_tenant_rods_automotive_luskville/mecanique-generale_14e0aa86-168e-407a-962c-48af180a45d5.webp",
    "suspension": "https://media.liasse.tech/upload/v1790972942/tapavis_tenant_rods_automotive_luskville/suspension_21a54b31-d274-43c0-84ca-9b8ea5eb4ce2.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790972942/tapavis_tenant_rods_automotive_luskville/silencieux_464faf56-4fdf-453c-826d-22bce2f1ac31.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790972942/tapavis_tenant_rods_automotive_luskville/equilibrage-rotation-pneus_83b1c47f-da3e-4d35-b4f0-e928c62adc33.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790972944/tapavis_tenant_rods_automotive_luskville/systeme-de-refroidissement_524737b1-c209-4fed-86c0-9ae8d5827f6a.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790972953/tapavis_tenant_rods_automotive_luskville/climatisation_28a26f0c-6143-450d-ac23-f247fca2652b.webp",
    "transmission": "https://media.liasse.tech/upload/v1790972953/tapavis_tenant_rods_automotive_luskville/transmission_7e781163-8c12-490e-b030-4aca3a7758a9.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790972954/tapavis_tenant_rods_automotive_luskville/mise-au-point_5e47540d-6a3c-41d5-be99-cdd7c22faa4f.webp"
  }
};
