/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_swap_shop).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962604/tapavis_tenant_garage_swap_shop/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962604/tapavis_tenant_garage_swap_shop/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790962620/tapavis_tenant_garage_swap_shop/hero_3177903e-3b22-4ce4-8669-b93a684be0c0.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790962620/tapavis_tenant_garage_swap_shop/vidange-huile_ef400ed9-9a76-486f-8fbe-346a68fee778.webp",
    "freins": "https://media.liasse.tech/upload/v1790962621/tapavis_tenant_garage_swap_shop/freins_96c510b7-436a-4106-a815-5b52692f71b2.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962622/tapavis_tenant_garage_swap_shop/mecanique-generale_c49a57a1-b818-4e24-ad22-6ba9feb8aabf.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962631/tapavis_tenant_garage_swap_shop/equilibrage-rotation-pneus_7342beb1-5b24-4644-be58-d8c36e9f2d65.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962631/tapavis_tenant_garage_swap_shop/suspension_26e2398d-f51d-4598-a916-b155398f8f4e.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962633/tapavis_tenant_garage_swap_shop/systeme-de-refroidissement_d0573071-8a37-4f61-a488-d34c4428878a.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962635/tapavis_tenant_garage_swap_shop/silencieux_2ebdfbe1-76e7-4097-9f8f-9acce8de44ee.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790962641/tapavis_tenant_garage_swap_shop/mise-au-point_5bb502ae-32ce-49da-bda8-33c6bed32345.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790962642/tapavis_tenant_garage_swap_shop/climatisation_5b0346c1-7dc9-497f-9a15-9cae33537c0c.webp",
    "transmission": "https://media.liasse.tech/upload/v1790962645/tapavis_tenant_garage_swap_shop/transmission_e8ddf988-c301-443f-9c58-2e9998f1ddea.webp"
  }
};
