/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_costom_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813006/tapavis_tenant_mecanique_costom_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813006/tapavis_tenant_mecanique_costom_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813037/tapavis_tenant_mecanique_costom_inc/hero_e56f0e60-25ad-4dd4-ac46-0830aae92ba5.png",
  "services": {
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813024/tapavis_tenant_mecanique_costom_inc/silencieux_ddf7fbfb-d806-4ab4-baa2-317dce404ec0.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813024/tapavis_tenant_mecanique_costom_inc/suspension_19ba1810-d1f4-40fe-89ec-c67a4313bf66.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813026/tapavis_tenant_mecanique_costom_inc/mise-au-point_bd83d4f1-b413-4df4-94ee-d2ca8c7d287f.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813039/tapavis_tenant_mecanique_costom_inc/systeme-de-refroidissement_bdf39766-7762-4e4c-9f11-2d8cbbd1d192.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813040/tapavis_tenant_mecanique_costom_inc/mecanique-generale_18bd61b5-202f-420d-a690-1e516f51c1e2.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815141/tapavis_tenant_mecanique_costom_inc/vidange-huile_f0f22280-42f5-4223-820b-026c0dff9aec.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815142/tapavis_tenant_mecanique_costom_inc/equilibrage-rotation-pneus_4dfaed01-df12-47e7-a84b-808403154586.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815142/tapavis_tenant_mecanique_costom_inc/climatisation_b90cb7aa-49e5-4644-8628-b27cdc2ca260.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815143/tapavis_tenant_mecanique_costom_inc/freins_ba7cd38c-251d-4702-b4c7-13390df53263.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815152/tapavis_tenant_mecanique_costom_inc/transmission_783a2ae3-10cb-471a-9cad-f3c736a5e98c.png"
  }
};
