/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_les_pros_de_l_auto_granby).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537800/tapavis_tenant_garage_les_pros_de_l_auto_granby/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537800/tapavis_tenant_garage_les_pros_de_l_auto_granby/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537811/tapavis_tenant_garage_les_pros_de_l_auto_granby/hero_aa8fbd6d-2638-4a1d-824e-fa9c9ee18657.png",
  "services": {
    "embrayage": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537812/tapavis_tenant_garage_les_pros_de_l_auto_granby/embrayage_f1d04c89-9cb3-4535-b144-2aa1d8c3b1c1.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537812/tapavis_tenant_garage_les_pros_de_l_auto_granby/mise-au-point_be6531b6-8a86-4d67-956a-b683b28d5832.png",
    "carburateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537812/tapavis_tenant_garage_les_pros_de_l_auto_granby/carburateur_9aa25bba-6830-4a00-adf0-ed336ba4a253.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537822/tapavis_tenant_garage_les_pros_de_l_auto_granby/suspension_f155e038-4283-4a55-ab9b-7b71d6724ed2.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537822/tapavis_tenant_garage_les_pros_de_l_auto_granby/equilibrage-rotation-pneus_b8cca2cd-47cb-43dc-8d6b-cb92be3819f3.png",
    "antirouille": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537823/tapavis_tenant_garage_les_pros_de_l_auto_granby/antirouille_aa049044-7ff3-43ec-b7b9-4675155c6465.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537825/tapavis_tenant_garage_les_pros_de_l_auto_granby/systeme-de-refroidissement_8ae4df89-e732-4912-81f9-184a4b91a691.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537834/tapavis_tenant_garage_les_pros_de_l_auto_granby/silencieux_c3e5058c-fb48-401b-8cd0-e0f3272dae37.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537834/tapavis_tenant_garage_les_pros_de_l_auto_granby/vidange-huile_a7ff5518-9cda-4cb6-87e9-302370e1ace2.png",
    "diagnostic-electronique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537836/tapavis_tenant_garage_les_pros_de_l_auto_granby/diagnostic-electronique_ec39625a-ade1-4535-876c-5699f6eaf2ab.png",
    "electricite-electronique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537836/tapavis_tenant_garage_les_pros_de_l_auto_granby/electricite-electronique_6d1c2e04-5420-4c37-91ad-a58b405a0658.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537846/tapavis_tenant_garage_les_pros_de_l_auto_granby/entretien-preventif_e03b9cf2-fe09-4c3f-bead-c8098bd1de2b.png",
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537846/tapavis_tenant_garage_les_pros_de_l_auto_granby/batterie-demarreur-alternateur_6afbffa0-7c47-44e0-81c8-615ab63248f9.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537848/tapavis_tenant_garage_les_pros_de_l_auto_granby/inspection-mecanique_dc7a053c-4529-4cf5-852f-518bcfa349f9.png",
    "entretien-flotte": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537849/tapavis_tenant_garage_les_pros_de_l_auto_granby/entretien-flotte_aae0e223-b72c-4116-9cb9-df070c52c8a1.png"
  }
};
