/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_atelier_jean_yves_larose).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813331/tapavis_tenant_atelier_jean_yves_larose/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813331/tapavis_tenant_atelier_jean_yves_larose/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813341/tapavis_tenant_atelier_jean_yves_larose/hero_2a071c5a-e6ac-46be-92b2-85bc0d402f7a.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813341/tapavis_tenant_atelier_jean_yves_larose/vidange-huile_2edaee4c-e15e-40e9-88d8-805002ff0633.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813342/tapavis_tenant_atelier_jean_yves_larose/mecanique-generale_745b06e2-8f7b-4a34-9a7e-57e5579fabdf.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813342/tapavis_tenant_atelier_jean_yves_larose/freins_435b2696-3d00-4002-b508-cb0f08fedd82.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813353/tapavis_tenant_atelier_jean_yves_larose/silencieux_0647f729-35cb-46f1-8134-bf5d6c39bc54.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813354/tapavis_tenant_atelier_jean_yves_larose/equilibrage-rotation-pneus_478587ba-2882-4f02-a181-aac2eb9d102e.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813354/tapavis_tenant_atelier_jean_yves_larose/suspension_0faaf4cb-baac-42aa-9caa-bcdf599df66f.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813355/tapavis_tenant_atelier_jean_yves_larose/systeme-de-refroidissement_af19d9be-f32c-483f-99b3-f084e624c50b.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813367/tapavis_tenant_atelier_jean_yves_larose/mise-au-point_838c12e1-9655-4a07-bba6-d795bf77bd87.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_atelier_jean_yves_larose/transmission_ed533e48-87db-4b6b-9d0b-d66e52a9e202.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_atelier_jean_yves_larose/climatisation_c528d853-7127-4f15-bde3-ab14839ce10c.png"
  }
};
