/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_hilltop).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963340/tapavis_tenant_garage_hilltop/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963340/tapavis_tenant_garage_hilltop/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963356/tapavis_tenant_garage_hilltop/hero_44941976-5cda-4e31-b573-8dd808ec2e14.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790963356/tapavis_tenant_garage_hilltop/vidange-huile_dc57ef89-7ceb-41a2-820f-8ad181cbb8fc.webp",
    "freins": "https://media.liasse.tech/upload/v1790963358/tapavis_tenant_garage_hilltop/freins_ef100445-0d6f-43f5-80db-7b4a814f7eaf.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963359/tapavis_tenant_garage_hilltop/mecanique-generale_e6ef32d8-d195-4da7-9d91-75fa1836248f.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963365/tapavis_tenant_garage_hilltop/suspension_975998b4-1d87-4eaa-8d2e-41893e4d360c.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963367/tapavis_tenant_garage_hilltop/equilibrage-rotation-pneus_ac2ef34e-fcc1-4690-b872-4d367d7dfb1a.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963369/tapavis_tenant_garage_hilltop/silencieux_6664fc46-a235-49f7-9fc3-50aa27ac97a7.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963369/tapavis_tenant_garage_hilltop/systeme-de-refroidissement_c9142dd1-f7c5-469b-afb2-d0aec178d090.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963377/tapavis_tenant_garage_hilltop/climatisation_d77f714c-b3d4-4d14-8db8-f4039463aaf9.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963382/tapavis_tenant_garage_hilltop/transmission_9a5be2be-7e78-4811-8749-0043f33f4564.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963419/tapavis_tenant_garage_hilltop/mise-au-point_8ae3cbde-c79c-45f0-99cc-a6b1ced1b91e.webp"
  }
};
