/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_generale_saint_thomas).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736837/tapavis_tenant_mecanique_generale_saint_thomas/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736837/tapavis_tenant_mecanique_generale_saint_thomas/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736849/tapavis_tenant_mecanique_generale_saint_thomas/hero_ba0c17ad-5009-479b-89e3-11458bcb2ed9.png",
  "services": {
    "reparation-camions": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736848/tapavis_tenant_mecanique_generale_saint_thomas/reparation-camions_0b953ba1-1451-43ad-8e40-5cf2ae9e14e0.png",
    "essieux-chassis": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736851/tapavis_tenant_mecanique_generale_saint_thomas/essieux-chassis_24b22a44-ade2-48ee-908c-851506194d4a.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736852/tapavis_tenant_mecanique_generale_saint_thomas/mecanique-generale_5026d709-0aac-4c8f-96be-761b9642a815.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736858/tapavis_tenant_mecanique_generale_saint_thomas/freins_4f938345-d537-4a3c-be6c-f8627e9fa7f8.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736859/tapavis_tenant_mecanique_generale_saint_thomas/vidange-huile_20f86175-5b16-4629-bb4f-546c8dce08e7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736862/tapavis_tenant_mecanique_generale_saint_thomas/equilibrage-rotation-pneus_c5119a60-cabf-45e0-92ea-a6cce470b78f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736865/tapavis_tenant_mecanique_generale_saint_thomas/suspension_5df8e69c-4907-4a04-992d-35cf59defad4.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736868/tapavis_tenant_mecanique_generale_saint_thomas/silencieux_14c721ef-260e-45dd-a541-bcd78675307d.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736872/tapavis_tenant_mecanique_generale_saint_thomas/systeme-de-refroidissement_e11708f9-5194-45e3-b8f8-1d55f849b006.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736875/tapavis_tenant_mecanique_generale_saint_thomas/climatisation_0acdc73a-8e15-4659-9ee4-bb64046623e4.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736877/tapavis_tenant_mecanique_generale_saint_thomas/mise-au-point_71ebef7f-1d31-4da3-97f0-483e190d8f23.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736881/tapavis_tenant_mecanique_generale_saint_thomas/transmission_558c3a0c-561d-40a0-b7ec-fea2d8584950.png"
  }
};
