/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_centre_de_l_auto_lotbiniere).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577401/tapavis_tenant_centre_de_l_auto_lotbiniere/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577401/tapavis_tenant_centre_de_l_auto_lotbiniere/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577412/tapavis_tenant_centre_de_l_auto_lotbiniere/hero_5fde55b9-8c61-498e-92e2-b38e9fdecaff.png",
  "services": {
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577412/tapavis_tenant_centre_de_l_auto_lotbiniere/systeme-de-refroidissement_dc717b4f-d904-4e45-96e9-f50d59db8137.png",
    "injection": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577413/tapavis_tenant_centre_de_l_auto_lotbiniere/injection_00172484-cbd8-4120-a8d0-97a56b1db675.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577421/tapavis_tenant_centre_de_l_auto_lotbiniere/silencieux_829b85aa-6994-4d40-aa16-714f8d95b338.png",
    "embrayage": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577424/tapavis_tenant_centre_de_l_auto_lotbiniere/embrayage_9b94b6ce-c7e7-4b5a-a3f6-9ff3a6b6f87c.png",
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577425/tapavis_tenant_centre_de_l_auto_lotbiniere/batterie-demarreur-alternateur_90dd18ef-c281-4ac7-bd3f-a751d30d69a4.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577426/tapavis_tenant_centre_de_l_auto_lotbiniere/suspension_27a24325-3afa-49e4-bac8-3210d5f9f687.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577433/tapavis_tenant_centre_de_l_auto_lotbiniere/equilibrage-rotation-pneus_26e85b6d-d6da-4499-a5a8-1037ac49ec38.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577435/tapavis_tenant_centre_de_l_auto_lotbiniere/mise-au-point_bea64e5d-fb31-465a-8e9b-7ddcac782c75.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577438/tapavis_tenant_centre_de_l_auto_lotbiniere/inspection-mecanique_4a9d8176-cf90-46eb-b753-b2c9f026e0e5.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577439/tapavis_tenant_centre_de_l_auto_lotbiniere/entretien-preventif_3bafb653-142d-464c-a42f-5c2d2ac54dec.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577443/tapavis_tenant_centre_de_l_auto_lotbiniere/vidange-huile_f3140cab-e9a6-4586-b39e-62d6e54804fb.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577447/tapavis_tenant_centre_de_l_auto_lotbiniere/alignement_2dd266ca-d70d-4de9-9cdf-4a17733177a5.png"
  }
};
