/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_paquette_solutions_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537034/tapavis_tenant_paquette_solutions_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537034/tapavis_tenant_paquette_solutions_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537048/tapavis_tenant_paquette_solutions_mecanique/hero_04ad9520-0555-40de-86d1-390412c3b91a.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537046/tapavis_tenant_paquette_solutions_mecanique/vidange-huile_d4e8b7ba-66f3-4b74-b376-d1fad9dc457a.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537047/tapavis_tenant_paquette_solutions_mecanique/freins_0f15fd3b-80b1-4032-be6f-75efaae57aa5.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537048/tapavis_tenant_paquette_solutions_mecanique/mecanique-generale_360fbdc4-86f5-47bd-9aad-ea880c184ee9.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537060/tapavis_tenant_paquette_solutions_mecanique/equilibrage-rotation-pneus_ef91d176-2792-4543-af3c-8add0399792f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537059/tapavis_tenant_paquette_solutions_mecanique/suspension_5b984321-36be-4fa2-abca-4d8213159c41.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537062/tapavis_tenant_paquette_solutions_mecanique/systeme-de-refroidissement_8023c4e5-696e-48ba-99b4-d1aadbd3dae4.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537061/tapavis_tenant_paquette_solutions_mecanique/silencieux_6fbc4e35-74b1-41d3-8225-bab470963fe2.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537072/tapavis_tenant_paquette_solutions_mecanique/climatisation_7779b5fd-f507-473f-80d2-6064a2fc6b57.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537074/tapavis_tenant_paquette_solutions_mecanique/mise-au-point_2102f956-cf8c-4037-8875-fcb274bf762a.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790537076/tapavis_tenant_paquette_solutions_mecanique/transmission_a1eff79b-7b5c-408d-a328-eac078f5de38.png"
  }
};
