/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_centre_de_l_auto_rajcan).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929195/tapavis_tenant_centre_de_l_auto_rajcan/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929195/tapavis_tenant_centre_de_l_auto_rajcan/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790960181/tapavis_tenant_centre_de_l_auto_rajcan/hero_daef8e72-8d16-4ffc-a317-fe60498d0fa1.webp",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929206/tapavis_tenant_centre_de_l_auto_rajcan/vidange-huile_28c8ff40-ce44-4d68-b2cd-80e14953cf6b.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929207/tapavis_tenant_centre_de_l_auto_rajcan/mecanique-generale_19228b36-e440-4cfd-a130-18903b932aa0.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929207/tapavis_tenant_centre_de_l_auto_rajcan/freins_e57cdeac-d23e-42cc-87d5-9623c57e9d0f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929217/tapavis_tenant_centre_de_l_auto_rajcan/silencieux_9ce6d0f5-6a3d-497a-9bd1-867945be5543.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929217/tapavis_tenant_centre_de_l_auto_rajcan/equilibrage-rotation-pneus_54896bf6-b17b-4bf3-853e-670f2efb7340.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929219/tapavis_tenant_centre_de_l_auto_rajcan/suspension_f25de252-9c27-4599-bf73-bbe345291ca5.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929220/tapavis_tenant_centre_de_l_auto_rajcan/systeme-de-refroidissement_470d8932-75cf-479f-9b1e-54ed2caeedf7.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929228/tapavis_tenant_centre_de_l_auto_rajcan/mise-au-point_a2d4d670-91d9-4d1e-83a4-109d817c5f35.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929228/tapavis_tenant_centre_de_l_auto_rajcan/climatisation_26bce668-8ce5-4b36-8b25-a59e6af926da.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790929231/tapavis_tenant_centre_de_l_auto_rajcan/transmission_a9eef2b6-e3fa-496f-9169-b23520afa317.png"
  }
};
