/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_lemay_marcel).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813203/tapavis_tenant_lemay_marcel/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813203/tapavis_tenant_lemay_marcel/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790816059/tapavis_tenant_lemay_marcel/hero_e69866d8-aef6-4841-87ac-6a0d24b02092.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813217/tapavis_tenant_lemay_marcel/vidange-huile_d4f39d3c-578f-4d7d-8ed5-6e99d5ebeebf.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813219/tapavis_tenant_lemay_marcel/equilibrage-rotation-pneus_0afdc458-d511-48d1-ba6a-b8164219b33f.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813221/tapavis_tenant_lemay_marcel/transmission_53f68c92-9138-493d-8a2b-1a51c08c14e2.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813223/tapavis_tenant_lemay_marcel/systeme-de-refroidissement_ce752887-c7b3-47d6-bae3-9a85532b9669.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813237/tapavis_tenant_lemay_marcel/mecanique-generale_16535525-6518-43d1-8854-4e1ad5251729.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813237/tapavis_tenant_lemay_marcel/mise-au-point_4ca31108-5b52-446c-8be9-bc928edcbc34.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813237/tapavis_tenant_lemay_marcel/climatisation_8d29a635-84a9-48ef-9efe-334c0ea785fe.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790816058/tapavis_tenant_lemay_marcel/silencieux_78f47b66-a313-4c18-bcb5-ff27455763c5.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790816059/tapavis_tenant_lemay_marcel/freins_f70be4ba-12cb-4388-9969-bbbd0e61c841.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790816059/tapavis_tenant_lemay_marcel/suspension_d4f8bff9-a805-4091-8b7f-88ef772a4fbf.png"
  }
};
