/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_rejean_deblois).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813015/tapavis_tenant_garage_rejean_deblois/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813015/tapavis_tenant_garage_rejean_deblois/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815813/tapavis_tenant_garage_rejean_deblois/hero_4326338c-a99d-4571-829c-df358acade7b.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813032/tapavis_tenant_garage_rejean_deblois/freins_451c6d71-61f6-4f29-b091-e86dd5300a99.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813033/tapavis_tenant_garage_rejean_deblois/mecanique-generale_d52b9c35-bafa-49c5-b90f-4af898a5774f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813033/tapavis_tenant_garage_rejean_deblois/climatisation_a540fa25-7316-4b54-87e2-1bca761d0be0.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813034/tapavis_tenant_garage_rejean_deblois/transmission_74979396-ee4a-4609-904a-4b9a6c4f55b9.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813047/tapavis_tenant_garage_rejean_deblois/equilibrage-rotation-pneus_f66b8388-367b-4229-a368-b67005421fbe.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813047/tapavis_tenant_garage_rejean_deblois/vidange-huile_676bb07b-b637-4311-b173-2756b52194c8.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815152/tapavis_tenant_garage_rejean_deblois/silencieux_27f35c5f-fa5d-40f1-9cd8-2c97b8866db1.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815154/tapavis_tenant_garage_rejean_deblois/systeme-de-refroidissement_a121fda7-e714-4aec-bc4a-de3824db46a3.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815155/tapavis_tenant_garage_rejean_deblois/suspension_1109542c-dd33-495e-aaae-a9ccf4f76abb.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815164/tapavis_tenant_garage_rejean_deblois/mise-au-point_5f3c5d56-7e37-4473-a341-b64b8fd69cc8.png"
  }
};
