/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_claude_lamarre).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668468/tapavis_tenant_garage_claude_lamarre/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668468/tapavis_tenant_garage_claude_lamarre/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668480/tapavis_tenant_garage_claude_lamarre/hero_e0e11eaa-db82-4e78-a362-c5135b4f1964.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668479/tapavis_tenant_garage_claude_lamarre/vidange-huile_6bd81164-e383-4aa8-806f-a9fee64ce8df.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668480/tapavis_tenant_garage_claude_lamarre/freins_0e41f754-bd60-41c9-ad6b-5558ba32b30d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668481/tapavis_tenant_garage_claude_lamarre/mecanique-generale_6ccf1f4c-342a-45d7-95e6-0b9e71b70cc4.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668491/tapavis_tenant_garage_claude_lamarre/silencieux_c14efc16-f033-4daf-9956-8a30108d8ceb.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668491/tapavis_tenant_garage_claude_lamarre/suspension_eb795009-c230-4f46-b240-2b80319f8a0a.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668492/tapavis_tenant_garage_claude_lamarre/equilibrage-rotation-pneus_4177047f-13bf-4215-a5de-0cd6057423f3.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668492/tapavis_tenant_garage_claude_lamarre/systeme-de-refroidissement_2fb08048-f8c2-444b-b604-691d2223dbce.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668504/tapavis_tenant_garage_claude_lamarre/climatisation_a52c63e5-bff2-44ee-9a1a-da95bb7cb491.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668504/tapavis_tenant_garage_claude_lamarre/mise-au-point_f03bdb43-2e04-4f6c-b1bc-dd87c021bd94.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668505/tapavis_tenant_garage_claude_lamarre/transmission_7cb82418-311c-4958-8ef0-d7873986e24a.png"
  }
};
