/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_morin).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669819/tapavis_tenant_mecanique_morin/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669819/tapavis_tenant_mecanique_morin/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669831/tapavis_tenant_mecanique_morin/hero_d4eb41da-d108-48cb-bc6d-9d9b506d8663.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669830/tapavis_tenant_mecanique_morin/freins_2cfbb00e-5e86-4af5-93e1-10e27d728f5b.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669831/tapavis_tenant_mecanique_morin/vidange-huile_bfabf59c-0ee3-4b6e-a34e-54ce47dba251.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669831/tapavis_tenant_mecanique_morin/mecanique-generale_34c1840e-0d24-4c48-8231-bf748be16b1d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669841/tapavis_tenant_mecanique_morin/equilibrage-rotation-pneus_f218d9cd-9be3-4858-99fe-a86fc813e452.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669841/tapavis_tenant_mecanique_morin/silencieux_f2c77993-b7df-445a-bad9-19da8fdd48cd.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669841/tapavis_tenant_mecanique_morin/suspension_97e5e558-0ca0-4ff3-8243-98ba6006d616.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669842/tapavis_tenant_mecanique_morin/systeme-de-refroidissement_9ac2e2e2-d3a1-4ccc-abb6-78d4cf789c17.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669852/tapavis_tenant_mecanique_morin/mise-au-point_6648bd53-43bd-4439-b5cf-f107968ac5e7.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669852/tapavis_tenant_mecanique_morin/transmission_43bfa907-b7b1-4c3a-951d-c094a6de07c0.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790669853/tapavis_tenant_mecanique_morin/climatisation_c8296398-bfbb-4023-ab9f-00599182f54c.png"
  }
};
