/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_pierre_brassard_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812961/tapavis_tenant_garage_pierre_brassard_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812961/tapavis_tenant_garage_pierre_brassard_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815789/tapavis_tenant_garage_pierre_brassard_inc/hero_8b449711-a67d-4745-bd9f-f9a13b3fda15.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812973/tapavis_tenant_garage_pierre_brassard_inc/vidange-huile_c51f55ab-f43f-4c77-9e78-7127c451eab6.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812975/tapavis_tenant_garage_pierre_brassard_inc/freins_0db3bf0b-90ae-4209-b922-ebcb429f23fd.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812976/tapavis_tenant_garage_pierre_brassard_inc/mecanique-generale_08cdf1b8-3c7c-46bc-ae15-ed02a2b3a519.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812984/tapavis_tenant_garage_pierre_brassard_inc/silencieux_96a1e768-7725-48a2-998d-1d14f135714d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812984/tapavis_tenant_garage_pierre_brassard_inc/equilibrage-rotation-pneus_846b0280-69a2-4a55-9636-518721c8b4f8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812988/tapavis_tenant_garage_pierre_brassard_inc/mise-au-point_02b6db6f-3553-4e6d-a467-7b9adc24219f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812991/tapavis_tenant_garage_pierre_brassard_inc/climatisation_5cc497f5-1331-4ab4-8949-aaef362a52f6.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813004/tapavis_tenant_garage_pierre_brassard_inc/systeme-de-refroidissement_4634cb03-b549-4875-bdd9-2d060885657f.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815079/tapavis_tenant_garage_pierre_brassard_inc/suspension_85c20c8e-c657-456e-852b-87961f54ba1c.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815080/tapavis_tenant_garage_pierre_brassard_inc/transmission_fa0dcdfc-81ba-4f85-9b3e-98bf26b98899.png"
  }
};
