/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_cas_competition).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963222/tapavis_tenant_cas_competition/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963222/tapavis_tenant_cas_competition/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963238/tapavis_tenant_cas_competition/hero_3ec9bea0-7a87-4491-a1d3-d41c820aa7ff.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790963238/tapavis_tenant_cas_competition/vidange-huile_af7b1f94-73c5-4451-b92b-bde6319e1db6.webp",
    "freins": "https://media.liasse.tech/upload/v1790963239/tapavis_tenant_cas_competition/freins_71d07912-c1b7-4d12-b47a-96946400cd26.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963239/tapavis_tenant_cas_competition/mecanique-generale_03d44220-debf-4d48-88cb-b0fa7afc594d.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963248/tapavis_tenant_cas_competition/silencieux_fb384ab1-37cb-4ef9-aefe-0e834c5add51.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963248/tapavis_tenant_cas_competition/equilibrage-rotation-pneus_2a213a58-3fb3-4064-a267-744586074c38.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963250/tapavis_tenant_cas_competition/suspension_2a4faedc-4fcf-4214-8c22-fcb09195d3be.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963251/tapavis_tenant_cas_competition/systeme-de-refroidissement_b51457e3-25f3-46af-a972-2329c63cbb2b.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963260/tapavis_tenant_cas_competition/mise-au-point_89b40877-9df1-4c8e-9f45-f5c239666b97.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963260/tapavis_tenant_cas_competition/transmission_683a92fe-125a-4270-a1c7-92c7785ced8f.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963261/tapavis_tenant_cas_competition/climatisation_395b3b0f-cd2c-4cd9-ac27-b3910c364f39.webp"
  }
};
