/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_solution_mecanique_jm).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812708/tapavis_tenant_solution_mecanique_jm/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812708/tapavis_tenant_solution_mecanique_jm/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812727/tapavis_tenant_solution_mecanique_jm/hero_c5915c58-7046-49d0-b944-3fed44986e1c.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812726/tapavis_tenant_solution_mecanique_jm/vidange-huile_45acd40a-503e-43d0-99f6-f22884f8937b.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812727/tapavis_tenant_solution_mecanique_jm/freins_cd51544e-e793-47eb-87c0-1aa2b5b4a126.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812729/tapavis_tenant_solution_mecanique_jm/mecanique-generale_8ca885f2-d0fa-47a6-98e2-c4b1d7642a93.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812738/tapavis_tenant_solution_mecanique_jm/suspension_3698b3cf-319b-4bdb-8623-fd62b628e649.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812738/tapavis_tenant_solution_mecanique_jm/silencieux_ad6afeb2-13f6-42c6-87fe-1efed6142873.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812739/tapavis_tenant_solution_mecanique_jm/equilibrage-rotation-pneus_c9067cf3-1565-42d0-94fb-b40b2278b105.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812744/tapavis_tenant_solution_mecanique_jm/systeme-de-refroidissement_4875b104-eaf4-4b40-a9cc-722c5a241a13.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812750/tapavis_tenant_solution_mecanique_jm/mise-au-point_97ca2917-d180-4c23-b578-4ce91f4a1c60.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812750/tapavis_tenant_solution_mecanique_jm/climatisation_b12fdef3-ef86-49af-93f4-e5f64b914528.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812752/tapavis_tenant_solution_mecanique_jm/transmission_e5bbf3dc-19a7-4989-bbb9-27fb11e0d0be.png"
  }
};
