/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_entretien_automobile_vincia).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736191/tapavis_tenant_entretien_automobile_vincia/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736191/tapavis_tenant_entretien_automobile_vincia/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736201/tapavis_tenant_entretien_automobile_vincia/hero_19eea42c-3591-4ec2-950a-96bcbc7096fa.png",
  "services": {
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736200/tapavis_tenant_entretien_automobile_vincia/entretien-preventif_19681118-9c74-48e0-8f5a-84c808d3a866.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736202/tapavis_tenant_entretien_automobile_vincia/freins_d5ef8d5f-a068-4c2e-bacd-96eb8c4dae6b.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736202/tapavis_tenant_entretien_automobile_vincia/mecanique-generale_0bbd723a-15df-46dd-8fe0-d1aa9b8c738a.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736211/tapavis_tenant_entretien_automobile_vincia/vidange-huile_fa6c7b38-9f3e-47c1-8eb5-b976800ac677.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736212/tapavis_tenant_entretien_automobile_vincia/equilibrage-rotation-pneus_085f1d94-408d-490c-875e-e773fbe351f2.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736211/tapavis_tenant_entretien_automobile_vincia/silencieux_45d8bd56-8b8b-40ec-b7bc-17598b240eea.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736212/tapavis_tenant_entretien_automobile_vincia/suspension_66f66463-1054-4387-9f6c-d8234e7c27a5.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736222/tapavis_tenant_entretien_automobile_vincia/systeme-de-refroidissement_31d35f4c-ae04-4fb0-bdc8-17402661c44d.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736223/tapavis_tenant_entretien_automobile_vincia/mise-au-point_910563e5-2432-4b39-bb27-5ccf58d93c03.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736224/tapavis_tenant_entretien_automobile_vincia/transmission_65c0d02b-bdb8-4caf-ba2c-07731277ee52.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736225/tapavis_tenant_entretien_automobile_vincia/climatisation_aad3becd-cbb8-4bec-8b4a-a644cac13994.png"
  }
};
