module.exports = async function(db,services) {
  const config = services && services.config ? services.config : {};
  const defaults = {business_name:config.businessName || config.displayName || 'Kilowatt Services',installation_name:'Jason',installation_email:'',installation_phone:'',service_name:'Benoit Lefebvre',mail_delivery_enabled:'false'};
  if (config.contactEmail) defaults.contact_email = config.contactEmail;
  if (config.contactPhone) defaults.contact_phone = config.contactPhone;
  if (config.businessAddress) defaults.business_address = config.businessAddress;
  for (const [key,value] of Object.entries(defaults)) await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[key,String(value)]);
  await db.run("INSERT INTO admin_settings (key,value) VALUES ('_p_nav_logo_url',$1) ON CONFLICT (key) DO NOTHING",['https://pub-007338adea45415ba231abbf2404da85.r2.dev/website-imports/70550455-f018-4944-82df-6ca4690e26fe/3a1fcdb26f086a5fc6ad5069e0226dad61d4b1bdbc684ba4de476b4a7338c6ec.webp']);
  const serviceRows = [
    ['Évaluer et choisir','Assess and choose','Une soumission sur place sans frais permet de préciser les besoins de votre résidence ou de votre entreprise. Nous proposons la génératrice stationnaire et l’inverseur automatique adaptés au projet.','A no-charge on-site quote helps establish what your home or business needs. We help select a standby generator and automatic transfer switch suited to your project.','sale','quote',1],
    ['Installer, du début à la mise en service','Install, from planning to commissioning','Nous coordonnons les intervenants électriques et les fournisseurs et techniciens en gaz, puis la mise en service de la génératrice. Une installation en une journée peut être réalisable selon le projet; cette possibilité se confirme lors de l’évaluation.','We coordinate electrical contractors, gas suppliers and gas technicians, followed by generator commissioning. A one-day installation may be possible for some projects; this is confirmed during the assessment.','installation','quote',2],
    ['Entretenir et remettre en marche','Maintain and start up','Confiez l’entretien annuel et la mise en marche à des techniciens certifiés Generac. Décrivez votre équipement et votre besoin pour organiser la prochaine intervention.','Arrange annual maintenance and startup with Generac-certified technicians. Tell us about your equipment and what you need to plan the next visit.','maintenance','maintenance',3],
    ['Réparer et accompagner la garantie','Repair and support warranty service','Nous offrons les réparations, le soutien après-vente et le service sous garantie. L’admissibilité et les conditions applicables doivent être vérifiées selon votre appareil et sa couverture.','We provide repairs, after-sales support and warranty service. Eligibility and applicable conditions must be checked for your equipment and its coverage.','repair','repair',4],
    ['Trouver les pièces nécessaires','Find the parts you need','Nous vendons des pièces pour répondre aux besoins d’entretien et de réparation. Indiquez le modèle et, si possible, le numéro de série; la disponibilité sera confirmée par l’équipe.','We sell parts for maintenance and repair needs. Share the model and, if available, the serial number; our team will confirm availability.','parts','parts',5]
  ];
  for (const row of serviceRows) await db.run('INSERT INTO services (title,title_en,content,content_en,anchor,action,position) SELECT $1,$2,$3,$4,$5,$6,$7 WHERE NOT EXISTS (SELECT 1 FROM services WHERE anchor = $5)',row);
  const stepRows = [
    ['Évaluer sur place','Assess on site','Nous précisons les besoins et le choix de l’équipement avec vous. La soumission sur place est sans frais.','We discuss your needs and equipment options with you. The on-site quote is provided at no charge.','sale',1],
    ['Coordonner les intervenants','Coordinate the work','Électricien, alimentation en gaz et technicien : nous réunissons les intervenants du projet. Vous gardez un seul point de contact.','Electrical work, gas supply and technicians: we bring the project’s specialists together. You keep one point of contact.','installation',2],
    ['Installer et mettre en service','Install and commission','Nous prenons en charge l’installation complète et la mise en service. Le déroulement est établi selon les besoins du chantier.','We handle complete installation and commissioning. The work is planned around your project’s requirements.','installation',3],
    ['Assurer le suivi','Provide ongoing support','Entretien annuel, réparations, garantie et pièces : le suivi continue après l’installation. Faites-nous part du besoin de votre génératrice.','Annual maintenance, repairs, warranty service and parts: support continues after installation. Let us know what your generator needs.','maintenance',4]
  ];
  for (const row of stepRows) await db.run('INSERT INTO steps (title,title_en,content,content_en,target,position) SELECT $1,$2,$3,$4,$5,$6 WHERE NOT EXISTS (SELECT 1 FROM steps WHERE position = $6)',row);
  const faqRows = [
    ['Offrez-vous du financement ?','Is financing available?','Oui, le financement est offert. Demandez les modalités applicables à votre projet; aucun taux n’est présenté ici.','Yes, financing is available. Ask about the terms for your project; no rates are quoted here.',1],
    ['L’installation se fait-elle en une journée ?','Can installation take one day?','Cette possibilité existe selon le projet. La durée et les conditions de réalisation sont à confirmer lors de l’évaluation, et non garanties pour chaque installation.','This may be possible depending on the project. The duration and requirements are confirmed during the assessment, not guaranteed for every installation.',2],
    ['Dois-je trouver l’électricien et le fournisseur de gaz ?','Do I need to find an electrician and gas supplier?','Nous coordonnons les intervenants nécessaires aux raccordements électriques, à l’alimentation en gaz et à la mise en service.','We coordinate the specialists needed for electrical connections, gas supply and commissioning.',3],
    ['Intervenez-vous au résidentiel et au commercial ?','Do you serve homes and businesses?','Oui. Nous accompagnons les clients résidentiels et commerciaux dans les Laurentides, selon les besoins de leur projet.','Yes. We support residential and commercial customers in the Laurentians according to their project needs.',4]
  ];
  for (const row of faqRows) await db.run('INSERT INTO faqs (title,title_en,content,content_en,position) SELECT $1,$2,$3,$4,$5 WHERE NOT EXISTS (SELECT 1 FROM faqs WHERE position = $5)',row);
  const postRows = [
    ['Préparer votre demande d’installation','Prepare your installation request','Précisez la municipalité, le type de bâtiment et les besoins à discuter lors de la soumission sur place.','Share your municipality, building type and the needs to discuss during the on-site quote.','Installation'],
    ['Planifier l’entretien annuel','Plan annual maintenance','Communiquez le modèle de votre génératrice et le motif de votre demande pour préparer le suivi.','Share your generator model and the reason for your request to prepare for follow-up.','Entretien'],
    ['Un projet coordonné','A coordinated project','L’installation réunit plusieurs intervenants. Notre approche clé en main facilite cette coordination.','Installation involves several specialists. Our turnkey approach helps coordinate their work.','Installation'],
    ['Demander une pièce','Request a part','Le modèle et le numéro de série aident l’équipe à examiner votre demande de pièces. La disponibilité doit être confirmée.','The model and serial number help our team review a parts request. Availability must be confirmed.','Pièces']
  ];
  for (const row of postRows) await db.run('INSERT INTO posts (title,title_en,content,content_en,category,published) SELECT $1,$2,$3,$4,$5,0 WHERE NOT EXISTS (SELECT 1 FROM posts WHERE title = $1)',row);
};