/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_dsm).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790962968/tapavis_tenant_garage_dsm/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790962968/tapavis_tenant_garage_dsm/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790962986/tapavis_tenant_garage_dsm/hero_3c26adca-6085-40da-8196-baf52313423f.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790962984/tapavis_tenant_garage_dsm/mecanique-generale_403506f2-1b04-4159-9a29-339cb508e905.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790962986/tapavis_tenant_garage_dsm/vidange-huile_e0a21a2a-b2ad-40dd-bc7d-480da5a0d2e3.webp",
    "freins": "https://media.liasse.tech/upload/v1790962987/tapavis_tenant_garage_dsm/freins_78580da3-16ed-47f8-84fa-0dd72447e07c.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790962995/tapavis_tenant_garage_dsm/equilibrage-rotation-pneus_74ed73de-bd22-42ae-b780-a26bbd0ee7a9.webp",
    "suspension": "https://media.liasse.tech/upload/v1790962995/tapavis_tenant_garage_dsm/suspension_780f3524-775b-41e1-8972-934648597661.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790962996/tapavis_tenant_garage_dsm/silencieux_e46e33bc-5f2f-4e64-8961-c80d52ddd3dd.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790962999/tapavis_tenant_garage_dsm/systeme-de-refroidissement_97f2418a-07d2-4173-8f29-2409e6418a23.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963006/tapavis_tenant_garage_dsm/mise-au-point_1647d62f-ddd6-457b-a815-06fb4ebbb2fd.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963006/tapavis_tenant_garage_dsm/climatisation_946bb505-d9f4-4396-a253-5ee9069453d8.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963008/tapavis_tenant_garage_dsm/transmission_dab7dee9-a1e7-438c-a551-e176b16a0e14.webp"
  }
};
