/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_la_mite_a_fer).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790963137/tapavis_tenant_garage_la_mite_a_fer/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790963137/tapavis_tenant_garage_la_mite_a_fer/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790963153/tapavis_tenant_garage_la_mite_a_fer/hero_d7be9aa0-fc00-4837-9490-b0fe9ba9550f.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1790963154/tapavis_tenant_garage_la_mite_a_fer/mecanique-generale_c3660770-fdc1-4d68-9446-cce0fbce3e7e.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1790963154/tapavis_tenant_garage_la_mite_a_fer/vidange-huile_47d936ad-870b-45aa-90d9-d020fa8347dc.webp",
    "freins": "https://media.liasse.tech/upload/v1790963155/tapavis_tenant_garage_la_mite_a_fer/freins_efedbcf0-5bd5-4559-9e9d-2b9fdb59818f.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790963163/tapavis_tenant_garage_la_mite_a_fer/equilibrage-rotation-pneus_213f5965-076b-4c63-94ef-8800aba132c5.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790963164/tapavis_tenant_garage_la_mite_a_fer/silencieux_13470f60-8a60-4621-95a4-af29291dd29d.webp",
    "suspension": "https://media.liasse.tech/upload/v1790963165/tapavis_tenant_garage_la_mite_a_fer/suspension_ddffebf1-d2ba-477e-866a-59e45d26f6f5.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790963166/tapavis_tenant_garage_la_mite_a_fer/systeme-de-refroidissement_8be0f1e7-43fd-48cf-a09c-498072002c8d.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790963175/tapavis_tenant_garage_la_mite_a_fer/mise-au-point_4a0eeaae-8782-416c-8155-7d9a5ecc3f0e.webp",
    "transmission": "https://media.liasse.tech/upload/v1790963176/tapavis_tenant_garage_la_mite_a_fer/transmission_11f4f542-17b8-45f2-afb0-7c315dcc8f51.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790963179/tapavis_tenant_garage_la_mite_a_fer/climatisation_c80bbabe-ebf3-44cd-9096-82fc00fe83a9.webp"
  }
};
