/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_radiateur_d_auto_lefort_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740268/tapavis_tenant_radiateur_d_auto_lefort_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740268/tapavis_tenant_radiateur_d_auto_lefort_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740279/tapavis_tenant_radiateur_d_auto_lefort_inc/hero_4076a77b-c5e1-43cc-b18c-8fed889d4aa7.png",
  "services": {
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740279/tapavis_tenant_radiateur_d_auto_lefort_inc/systeme-de-refroidissement_add18b25-607e-4145-80d4-f08b77c572ae.png",
    "soudure": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740280/tapavis_tenant_radiateur_d_auto_lefort_inc/soudure_ca677090-dadc-4ff0-a3b6-385cef485b17.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740280/tapavis_tenant_radiateur_d_auto_lefort_inc/climatisation_4be5f0c6-f524-4046-8dfe-eb03576d3758.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740290/tapavis_tenant_radiateur_d_auto_lefort_inc/mecanique-generale_18ba82ae-e43d-4232-9777-e776bcf1b6db.png"
  }
};
