/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_nistech).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813315/tapavis_tenant_garage_nistech/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813315/tapavis_tenant_garage_nistech/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813337/tapavis_tenant_garage_nistech/hero_1526d5b3-dc9c-486f-bf85-c67fd1146e27.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813336/tapavis_tenant_garage_nistech/freins_774a453a-9ab5-48db-b4b3-a9458ecd212c.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813337/tapavis_tenant_garage_nistech/vidange-huile_53f201a4-37db-4c49-8047-09d224c8b1ff.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813338/tapavis_tenant_garage_nistech/mecanique-generale_f5dc4607-8269-42a9-b097-2113f3da70f9.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813351/tapavis_tenant_garage_nistech/silencieux_c1f06545-9897-4588-ab4b-1bb1ee7dceb6.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813353/tapavis_tenant_garage_nistech/suspension_94b18cc3-6a76-40da-9671-bab89ba5b929.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813354/tapavis_tenant_garage_nistech/equilibrage-rotation-pneus_84b692bd-5c87-442c-89f4-64d9cbbb9fb0.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813355/tapavis_tenant_garage_nistech/systeme-de-refroidissement_c65eda4b-5c6b-4e0e-808d-2387b9bac8fe.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_garage_nistech/climatisation_5009fd49-ca84-4e5e-8f73-afa82a3005bb.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813370/tapavis_tenant_garage_nistech/mise-au-point_fdc6008a-f605-4022-a2c0-22ed1186ec30.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813374/tapavis_tenant_garage_nistech/transmission_073d587d-ea37-4022-a0d7-7aef3334da7e.png"
  }
};
