/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_thibodeau_fils_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048439/tapavis_tenant_garage_thibodeau_fils_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048439/tapavis_tenant_garage_thibodeau_fils_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791048454/tapavis_tenant_garage_thibodeau_fils_inc/hero_ffb3e3e5-e500-4935-a73d-2c90d0fa8a9d.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048454/tapavis_tenant_garage_thibodeau_fils_inc/mecanique-generale_506eb515-050d-4122-8f94-9a357181ae6f.webp",
    "freins": "https://media.liasse.tech/upload/v1791048455/tapavis_tenant_garage_thibodeau_fils_inc/freins_f922be9f-a127-4fc4-87ea-530f202265e8.webp",
    "soudure": "https://media.liasse.tech/upload/v1791048456/tapavis_tenant_garage_thibodeau_fils_inc/soudure_a45520b8-16d4-46fb-9409-501f16992d71.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048464/tapavis_tenant_garage_thibodeau_fils_inc/silencieux_0648dfca-4c1b-4a01-974a-aa9ca2e85b05.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048465/tapavis_tenant_garage_thibodeau_fils_inc/equilibrage-rotation-pneus_459a9e97-246a-448c-b680-bbed1cf20f4b.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048465/tapavis_tenant_garage_thibodeau_fils_inc/vidange-huile_f78f90ac-ce2b-449b-87f3-5ef18c6afdff.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048465/tapavis_tenant_garage_thibodeau_fils_inc/suspension_f9923c15-3d3f-4528-9fe5-4db9a6a823ae.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048475/tapavis_tenant_garage_thibodeau_fils_inc/mise-au-point_a584c6db-1da0-4aa6-ab66-8a15e69f60d4.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048475/tapavis_tenant_garage_thibodeau_fils_inc/climatisation_e460fdc6-06bf-48dc-a419-8c83a7ae9a8e.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048475/tapavis_tenant_garage_thibodeau_fils_inc/systeme-de-refroidissement_ee3aff5c-761c-40c9-9ced-c4cd92488753.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048477/tapavis_tenant_garage_thibodeau_fils_inc/transmission_52a32823-cfb9-4c46-8b93-ae07f7693aef.webp"
  }
};
