/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_charlevoix_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555095/tapavis_tenant_garage_charlevoix_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555095/tapavis_tenant_garage_charlevoix_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555107/tapavis_tenant_garage_charlevoix_inc/hero_29a62bfe-ce45-451b-83b3-19d744a81d7c.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555106/tapavis_tenant_garage_charlevoix_inc/vidange-huile_309de872-21c3-4073-9aba-81a7d90fe748.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555107/tapavis_tenant_garage_charlevoix_inc/freins_2a7b349c-9bec-4b1c-8942-bd2ce9a5a424.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555109/tapavis_tenant_garage_charlevoix_inc/mecanique-generale_d1d02013-b12b-4f19-8068-e29e9db08751.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555117/tapavis_tenant_garage_charlevoix_inc/equilibrage-rotation-pneus_212d66ef-1dc7-45e6-8491-360680bd19f6.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555119/tapavis_tenant_garage_charlevoix_inc/silencieux_ca90781c-be3c-4829-adcd-9298ea98b99b.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555121/tapavis_tenant_garage_charlevoix_inc/suspension_256cfb63-7caf-430d-8a10-a16036ac08ba.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555122/tapavis_tenant_garage_charlevoix_inc/systeme-de-refroidissement_85efd293-700e-40c5-b66e-9523b7a609d1.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555129/tapavis_tenant_garage_charlevoix_inc/climatisation_58882de3-49ea-4b62-b1f1-bd358d1f0274.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555130/tapavis_tenant_garage_charlevoix_inc/mise-au-point_6bde37ec-4e54-444d-8b45-1400db58dd68.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790555135/tapavis_tenant_garage_charlevoix_inc/transmission_3d69b1ee-a12c-40aa-8ae5-50da22fcea49.png"
  }
};
