/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_g_l_gagnon_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790961108/tapavis_tenant_garage_g_l_gagnon_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790961108/tapavis_tenant_garage_g_l_gagnon_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790961123/tapavis_tenant_garage_g_l_gagnon_inc/hero_9db5fda1-e133-4627-b8a5-ae86c6b697d5.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790961124/tapavis_tenant_garage_g_l_gagnon_inc/vidange-huile_550e1105-5720-4316-85ac-8546ec54b569.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790961127/tapavis_tenant_garage_g_l_gagnon_inc/mecanique-generale_b7f69d11-6916-42c5-9520-9e6e51043b68.webp",
    "freins": "https://media.liasse.tech/upload/v1790961127/tapavis_tenant_garage_g_l_gagnon_inc/freins_4c2379cc-0617-44c3-9b7a-93696db872f5.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790961133/tapavis_tenant_garage_g_l_gagnon_inc/equilibrage-rotation-pneus_cbcadc6c-c771-42f0-9ef6-f0795884bbb9.webp",
    "suspension": "https://media.liasse.tech/upload/v1790961134/tapavis_tenant_garage_g_l_gagnon_inc/suspension_407a5657-8811-4b9f-9575-2c3c9165582b.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790961137/tapavis_tenant_garage_g_l_gagnon_inc/silencieux_0d7b6de1-4c8f-4e55-aca2-60dfa4821a49.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790961138/tapavis_tenant_garage_g_l_gagnon_inc/systeme-de-refroidissement_7c864c15-551e-459c-9960-203729d5b064.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790961145/tapavis_tenant_garage_g_l_gagnon_inc/mise-au-point_1a881d08-5a3f-44a9-bf8a-9660003e8d36.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790961145/tapavis_tenant_garage_g_l_gagnon_inc/climatisation_b3e12fac-c6f7-414d-8ac6-05740ca8c0ca.webp",
    "transmission": "https://media.liasse.tech/upload/v1790961149/tapavis_tenant_garage_g_l_gagnon_inc/transmission_c8ff34ea-3311-40dd-ac08-8f0db4005bab.webp"
  }
};
