/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_et_esthetique_pat_performance).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626162/tapavis_tenant_mecanique_et_esthetique_pat_performance/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626162/tapavis_tenant_mecanique_et_esthetique_pat_performance/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626173/tapavis_tenant_mecanique_et_esthetique_pat_performance/hero_0edf8638-f37f-4242-a051-270e65c3469a.png",
  "services": {
    "esthetique-automobile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626173/tapavis_tenant_mecanique_et_esthetique_pat_performance/esthetique-automobile_970d6890-7b62-4bb7-93cb-7b385d5abbc6.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626174/tapavis_tenant_mecanique_et_esthetique_pat_performance/mecanique-generale_cec827c6-938b-4eb9-892d-e4af7220598c.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626183/tapavis_tenant_mecanique_et_esthetique_pat_performance/vidange-huile_d66c6b42-94e0-4e6b-bb69-fcc0e9a1a5fd.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626184/tapavis_tenant_mecanique_et_esthetique_pat_performance/equilibrage-rotation-pneus_4d03adfe-6438-410b-9478-b7832d8e8da8.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626184/tapavis_tenant_mecanique_et_esthetique_pat_performance/freins_48b88838-69b6-47c5-b760-b7ad196d24d0.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626186/tapavis_tenant_mecanique_et_esthetique_pat_performance/suspension_1326b564-8290-42cc-afef-3fe17af269e1.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626193/tapavis_tenant_mecanique_et_esthetique_pat_performance/silencieux_d945ced4-7214-4fd4-8c94-dcf6285cc8b8.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626195/tapavis_tenant_mecanique_et_esthetique_pat_performance/systeme-de-refroidissement_50cbc716-38bf-490a-996a-0ca009f48f6b.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626198/tapavis_tenant_mecanique_et_esthetique_pat_performance/climatisation_7090a7fc-e246-486d-9689-61cdc0f97e68.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626198/tapavis_tenant_mecanique_et_esthetique_pat_performance/mise-au-point_5043d290-2490-428d-8a01-2af56b11d252.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790626205/tapavis_tenant_mecanique_et_esthetique_pat_performance/transmission_c371a628-3b58-460b-b813-64f22167484b.png"
  }
};
