/**
 * Mécanique U.M. — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "suspension-pneumatique",
    "icon": "spring",
    "duration_min": 120,
    "bookable": 1,
    "featured": 1,
    "name": "Réparation de suspension à air",
    "name_en": "Air suspension repair",
    "tagline": "Coussins d’air, valves de nivellement, compresseur.",
    "tagline_en": "Air bags, leveling valves, compressor.",
    "body": "Sur les camions et véhicules lourds, la suspension à air porte la charge et garde le véhicule au bon niveau. Une fuite dans un coussin ou une conduite, une valve de nivellement déréglée ou un compresseur fatigué font baisser le véhicule et usent les autres composants. L’inspection repère la fuite et vérifie la hauteur de caisse.",
    "body_en": "On trucks and heavy vehicles, air suspension carries the load and keeps the vehicle level. A leak in an air bag or a line, a misadjusted leveling valve or a tired compressor makes the vehicle sag and wears other parts. The inspection finds the leak and checks the ride height.",
    "signs": "[\"Le véhicule penche ou s’affaisse à l’arrêt\", \"Sifflement d’air\", \"Compresseur qui tourne sans arrêt\", \"Conduite plus dure ou plus instable\"]",
    "signs_en": "[\"The vehicle leans or sags when parked\", \"A hissing air leak\", \"A compressor that runs constantly\", \"A harsher or less stable ride\"]",
    "confirmed": 1
  },
  {
    "slug": "camion-diesel",
    "icon": "gear",
    "duration_min": 120,
    "bookable": 1,
    "featured": 1,
    "name": "Réparation de camion diesel",
    "name_en": "Diesel truck repair",
    "tagline": "Moteurs diesel de camions et véhicules lourds.",
    "tagline_en": "Diesel engines in trucks and heavy vehicles.",
    "body": "Les moteurs diesel des camions travaillent sous forte charge pendant de longues heures. Leur entretien et leurs réparations touchent l’injection, le turbo, le refroidissement, les filtres et les systèmes antipollution. Le diagnostic commence par la lecture des codes et une inspection, avant toute réparation.",
    "body_en": "Truck diesel engines work under heavy load for long hours. Their maintenance and repairs involve injection, the turbo, cooling, filters and the emission systems. The diagnosis starts with reading the codes and an inspection, before any repair.",
    "signs": "[\"Perte de puissance en charge\", \"Fumée anormale à l’échappement\", \"Voyant moteur ou antipollution allumé\", \"Démarrage difficile par temps froid\"]",
    "signs_en": "[\"Loss of power under load\", \"Unusual exhaust smoke\", \"Engine or emissions warning light\", \"Hard starting in cold weather\"]",
    "confirmed": 1
  },
  {
    "slug": "camionnettes",
    "icon": "wrench",
    "duration_min": 90,
    "bookable": 1,
    "featured": 1,
    "name": "Réparation de camionnettes",
    "name_en": "Pickup and van repair",
    "tagline": "Camionnettes et fourgonnettes de travail.",
    "tagline_en": "Work pickups and vans.",
    "body": "Les camionnettes de travail roulent chargées, tirent des remorques et font de longues journées. Freins, suspension, direction, refroidissement et entretien prévu au carnet : précisez le modèle, l’année et l’usage en réservant.",
    "body_en": "Work pickups carry loads, tow trailers and put in long days. Brakes, suspension, steering, cooling and scheduled maintenance: give the model, year and use when you book.",
    "signs": "[\"Freins qui chauffent en remorquant\", \"Bruit ou vibration sous charge\", \"Voyant allumé\", \"Entretien prévu au carnet\"]",
    "signs_en": "[\"Brakes overheating when towing\", \"Noise or vibration under load\", \"A warning light on\", \"Scheduled maintenance due\"]",
    "confirmed": 1
  },
  {
    "slug": "remorques-camions",
    "icon": "tow",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "name": "Remorques et camions",
    "name_en": "Trailers and trucks",
    "tagline": "Un besoin pour une remorque ou un camion? Appelez le garage.",
    "tagline_en": "A trailer or truck job? Call the garage.",
    "body": "La fiche du garage indique un service « Remorques · Camions ». Appelez le garage pour décrire votre besoin : il vous dira ce qu’il prend en charge et comment procéder.",
    "body_en": "The garage’s listing mentions a « trailers · trucks » service. Call the garage to describe what you need: it will tell you what it handles and how to proceed.",
    "signs": "[\"Remorque à faire vérifier\", \"Camion ou remorque immobilisé\", \"Question sur un travail précis\"]",
    "signs_en": "[\"A trailer to be checked\", \"A truck or trailer out of service\", \"A question about a specific job\"]",
    "confirmed": 1
  },
  {
    "slug": "assistance-routiere",
    "icon": "tow",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "name": "Assistance et dépannage routier 24/7",
    "name_en": "24/7 roadside assistance",
    "tagline": "En panne sur la route? Appelez, 24 h sur 24.",
    "tagline_en": "Broken down on the road? Call, day or night.",
    "body": "Le garage indique une assistance routière et un service de dépannage 24 heures sur 24, 7 jours sur 7. En panne avec un camion ou un véhicule? Appelez directement le garage et donnez l’endroit où vous êtes et le type de véhicule.",
    "body_en": "The garage lists roadside assistance and breakdown service 24 hours a day, 7 days a week. Broken down with a truck or a vehicle? Call the garage directly and give your location and the type of vehicle.",
    "signs": "[\"Le véhicule ne redémarre plus\", \"Voyant rouge ou perte de pression d’air\", \"Crevaison sur la route\"]",
    "signs_en": "[\"The vehicle will not restart\", \"A red warning light or lost air pressure\", \"A flat on the road\"]",
    "confirmed": 1
  },
  {
    "slug": "pre-inspection-saaq",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Pré-inspection SAAQ",
    "name_en": "SAAQ pre-inspection",
    "tagline": "Arriver prêt à la vérification mécanique.",
    "tagline_en": "Arrive ready for the mechanical inspection.",
    "body": "Avant une vérification mécanique exigée par la SAAQ, une pré-inspection passe en revue les points qui seront contrôlés — freins, direction, suspension, éclairage, pneus, pare-brise, échappement — pour corriger les défauts avant le rendez-vous officiel.",
    "body_en": "Before a mechanical inspection required by the SAAQ, a pre-inspection reviews the points that will be checked — brakes, steering, suspension, lights, tires, windshield, exhaust — so defects are fixed before the official appointment.",
    "signs": "[\"Avis de vérification mécanique reçu\", \"Achat ou immatriculation d’un véhicule\", \"Échéance d’inspection d’un véhicule lourd\"]",
    "signs_en": "[\"A mechanical inspection notice received\", \"Buying or registering a vehicle\", \"A heavy-vehicle inspection due\"]",
    "confirmed": 1
  },
  {
    "slug": "pare-brise",
    "icon": "car",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Remplacement de pare-brise",
    "name_en": "Windshield replacement",
    "tagline": "Pare-brise fissuré? Le remplacer avant l’hiver.",
    "tagline_en": "Cracked windshield? Replace it before winter.",
    "body": "Une fissure dans le champ de vision nuit à la visibilité et peut s’étendre avec le gel et les chocs thermiques. Le remplacement du pare-brise comprend la dépose, la préparation du cadre et la pose avec un adhésif adapté, avant un temps de séchage.",
    "body_en": "A crack in the driver’s field of view hurts visibility and can spread with frost and temperature swings. Windshield replacement covers removal, preparing the frame and fitting with a suitable adhesive, followed by a curing time.",
    "signs": "[\"Fissure qui s’allonge\", \"Éclat dans le champ de vision\", \"Avant une vérification mécanique\"]",
    "signs_en": "[\"A crack that keeps growing\", \"A chip in the driver’s view\", \"Before a mechanical inspection\"]",
    "confirmed": 1
  }
];
