/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_dominic_sylvestre).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813112/tapavis_tenant_garage_dominic_sylvestre/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813112/tapavis_tenant_garage_dominic_sylvestre/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815915/tapavis_tenant_garage_dominic_sylvestre/hero_eeaf8e6b-7597-4b71-99c9-78156c80ae97.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813124/tapavis_tenant_garage_dominic_sylvestre/vidange-huile_5189b196-a6e2-4fa2-a09d-7982785c52e5.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813124/tapavis_tenant_garage_dominic_sylvestre/equilibrage-rotation-pneus_5a2ce209-5490-40f6-81e8-667cb0c3bad4.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813149/tapavis_tenant_garage_dominic_sylvestre/climatisation_c6fadfc9-2d02-4d5b-8845-522f661384a1.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815912/tapavis_tenant_garage_dominic_sylvestre/suspension_49702067-ae0a-4a76-9c0c-6f9b6a79ec48.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815912/tapavis_tenant_garage_dominic_sylvestre/freins_ffb4e93a-d900-40fb-bff7-764704863d85.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815915/tapavis_tenant_garage_dominic_sylvestre/mecanique-generale_4fe6ffa0-ce35-455e-b236-5c2b3b8e13b5.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815923/tapavis_tenant_garage_dominic_sylvestre/silencieux_e072374a-b8c2-49ef-8674-ea5e2ba1c223.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815924/tapavis_tenant_garage_dominic_sylvestre/systeme-de-refroidissement_827b59ea-77c6-4160-acf5-2f3056baa8de.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815926/tapavis_tenant_garage_dominic_sylvestre/transmission_e3997d72-150b-4951-af74-83b7754f5497.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815927/tapavis_tenant_garage_dominic_sylvestre/mise-au-point_c1c262cb-ef81-4ef0-83bf-3c1cd6f61d4a.png"
  }
};
