/**
 * Garage Mécanique Débosselage G.S — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "mecanique-generale",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Mécanique générale",
    "name_en": "General repair",
    "tagline": "Diagnostic, freins, courroies, direction : on trouve la cause, on répare.",
    "tagline_en": "Diagnostics, brakes, belts, steering: we find the cause and fix it.",
    "body": "Un bruit nouveau, un voyant qui s’allume, une conduite qui a changé : la mécanique générale commence par un diagnostic. Le véhicule est inspecté, les codes d’erreur sont lus, et vous recevez une explication claire de ce qui se passe avant toute réparation.\nFreins, courroies, direction, démarreur, alternateur, batterie : la plupart des réparations courantes se font dans la même visite.",
    "body_en": "A new noise, a warning light, a car that drives differently: general repair starts with a diagnosis. The vehicle is inspected, fault codes are read, and you get a clear explanation of what is going on before any repair.\nBrakes, belts, steering, starter, alternator, battery: most everyday repairs are handled in the same visit.",
    "signs": "[\"Un voyant « Check engine » allumé\",\"Grincement ou vibration au freinage\",\"Difficulté à démarrer\",\"Odeur de brûlé ou fuite sous le véhicule\"]",
    "signs_en": "[\"A \\\"Check engine\\\" light\",\"Squealing or vibration when braking\",\"Hard starts\",\"A burning smell or a leak under the car\"]",
    "confirmed": 1
  },
  {
    "slug": "debosselage-peinture",
    "icon": "wrench",
    "duration_min": 180,
    "bookable": 1,
    "featured": 1,
    "name": "Débosselage et peinture",
    "name_en": "Dent repair and paint",
    "tagline": "Bosses, éraflures, retouches et peinture.",
    "tagline_en": "Dents, scratches, touch-ups and paint.",
    "body": "Après un accrochage, la grêle ou simplement avec le temps, le débosselage redonne sa forme à la carrosserie et la peinture la protège. Réservez pour une évaluation : le garage vous dit ce qui se répare, ce qui se remplace, et chiffre le travail avant de commencer.",
    "body_en": "After a scrape, hail or simply with time, dent repair restores the body’s shape and paint protects it. Book an assessment: the garage tells you what can be repaired, what must be replaced, and estimates the work before starting.",
    "signs": "[\"Bosse ou éraflure après un accrochage\", \"Peinture écaillée ou ternie\", \"Rouille qui perce la peinture\"]",
    "signs_en": "[\"A dent or scrape after a bump\", \"Chipped or faded paint\", \"Rust coming through the paint\"]",
    "confirmed": 1
  },
  {
    "slug": "antirouille-gs",
    "icon": "oil",
    "duration_min": 60,
    "bookable": 1,
    "featured": 1,
    "name": "Antirouille : vérification et traitement",
    "name_en": "Rust check and rustproofing",
    "tagline": "Vérification de rouille, traitement à l’huile, couche antirouille.",
    "tagline_en": "Rust checks, oil-based treatment, rust coating.",
    "body": "Le sel et le calcium de nos routes attaquent le dessous des véhicules. Le garage vérifie la rouille, applique un traitement antirouille à l’huile et une couche protectrice sur le châssis, les bas de caisse et les conduites. Idéalement chaque année, avant l’hiver.",
    "body_en": "Salt and calcium on our roads attack the underside of vehicles. The garage checks for rust, applies an oil-based rust treatment and a protective coating on the frame, rocker panels and lines. Ideally every year, before winter.",
    "signs": "[\"Avant l’hiver\", \"Taches de rouille sur le châssis\", \"Bas de caisse qui bullent\", \"Véhicule neuf ou récent\"]",
    "signs_en": "[\"Before winter\", \"Rust spots on the frame\", \"Bubbling rocker panels\", \"A new or recent vehicle\"]",
    "confirmed": 1
  },
  {
    "slug": "freins",
    "icon": "brake",
    "duration_min": 90,
    "bookable": 1,
    "featured": 1,
    "name": "Freins",
    "name_en": "Brakes",
    "tagline": "Plaquettes, disques, étriers et liquide : des freins qui répondent.",
    "tagline_en": "Pads, rotors, calipers and fluid: brakes that answer.",
    "body": "Les freins s’usent un peu à chaque arrêt. L’inspection mesure les plaquettes et les disques, vérifie les étriers, les conduites et le liquide de frein, puis vous dit ce qui est usé, ce qui peut attendre et ce qui presse.\nLe sel et les hivers québécois sont durs pour les étriers et les conduites : un bruit ou une vibration au freinage mérite d’être vérifié rapidement.",
    "body_en": "Brakes wear a little at every stop. The inspection measures the pads and rotors, checks the calipers, lines and brake fluid, then tells you what is worn, what can wait and what is urgent.\nSalt and Québec winters are hard on calipers and lines: a noise or vibration when braking deserves a quick check.",
    "signs": "[\"Grincement ou sifflement au freinage\",\"Vibration dans la pédale ou le volant\",\"La pédale est molle ou descend plus bas\",\"Le véhicule tire d’un côté au freinage\"]",
    "signs_en": "[\"Squealing or grinding when braking\",\"Vibration in the pedal or steering wheel\",\"The pedal feels soft or sinks lower\",\"The vehicle pulls to one side when braking\"]",
    "confirmed": 1
  },
  {
    "slug": "vidange-huile",
    "icon": "oil",
    "duration_min": 30,
    "bookable": 1,
    "featured": 0,
    "name": "Changement d’huile",
    "name_en": "Oil change",
    "tagline": "Huile, filtre et inspection des points essentiels.",
    "tagline_en": "Oil, filter and a check of the essentials.",
    "body": "La vidange est l’entretien le plus simple et le plus important pour la vie du moteur. Elle comprend l’huile appropriée à votre moteur, un filtre neuf et un coup d’œil aux niveaux, aux pneus et aux fuites. Réservez en ligne, déposez la voiture ou attendez sur place.",
    "body_en": "An oil change is the simplest and most important service for engine life. It includes the right oil for your engine, a new filter and a quick look at fluid levels, tires and leaks. Book online, drop the car off or wait on site.",
    "signs": "[\"Le rappel d’entretien s’affiche\",\"Kilométrage atteint depuis la dernière vidange\",\"Huile foncée ou niveau bas\"]",
    "signs_en": "[\"The service reminder appears\",\"Mileage reached since the last change\",\"Dark oil or a low level\"]",
    "confirmed": 1
  },
  {
    "slug": "restauration-epoque",
    "icon": "car",
    "duration_min": 240,
    "bookable": 1,
    "featured": 0,
    "name": "Restauration d’auto d’époque",
    "name_en": "Classic car restoration",
    "tagline": "Redonner vie à une voiture de collection.",
    "tagline_en": "Bringing a classic car back to life.",
    "body": "Une voiture d’époque se restaure par étapes : évaluation de la carrosserie et de la rouille, réparations, préparation et peinture. Décrivez le véhicule et le projet en réservant : le garage évalue le travail et le chiffre avant de commencer.",
    "body_en": "A classic car is restored in stages: assessing the body and rust, repairs, preparation and paint. Describe the vehicle and the project when you book: the garage assesses the work and estimates it before starting.",
    "signs": "[\"Voiture de collection à remettre en état\", \"Rouille sur un véhicule ancien\", \"Projet de restauration à évaluer\"]",
    "signs_en": "[\"A classic car to bring back\", \"Rust on an older vehicle\", \"A restoration project to assess\"]",
    "confirmed": 1
  },
  {
    "slug": "carrosserie-fibre",
    "icon": "wrench",
    "duration_min": 180,
    "bookable": 1,
    "featured": 0,
    "name": "Carrosserie de fibre de verre",
    "name_en": "Fibreglass body repair",
    "tagline": "Réparation des pièces en fibre de verre.",
    "tagline_en": "Repairing fibreglass parts.",
    "body": "Certaines carrosseries et pièces sont en fibre de verre : capots, ailes, pièces de camion ou de véhicule récréatif. Une fissure ou un trou se répare par stratification puis finition et peinture. Réservez pour une évaluation de la pièce.",
    "body_en": "Some bodies and parts are fibreglass: hoods, fenders, truck or RV parts. A crack or hole is repaired by laminating, then finishing and paint. Book an assessment of the part.",
    "signs": "[\"Fissure ou trou dans une pièce en fibre\", \"Pièce abîmée après un choc\", \"Écaillage de la finition\"]",
    "signs_en": "[\"A crack or hole in a fibreglass part\", \"A part damaged in an impact\", \"Flaking finish\"]",
    "confirmed": 1
  },
  {
    "slug": "peinture-camion",
    "icon": "wrench",
    "duration_min": 240,
    "bookable": 1,
    "featured": 0,
    "name": "Peinture de camion",
    "name_en": "Truck painting",
    "tagline": "Camions et camionnettes : préparation et peinture.",
    "tagline_en": "Trucks and pickups: prep and paint.",
    "body": "La peinture d’un camion protège la tôle contre la rouille et redonne de l’allure au véhicule de travail. Le travail comprend la préparation des surfaces, les réparations de carrosserie nécessaires puis la peinture. Précisez le véhicule en réservant pour une évaluation.",
    "body_en": "Painting a truck protects the metal from rust and gives the work vehicle a new look. The job covers surface preparation, any needed body repairs, then paint. Give the vehicle when you book for an assessment.",
    "signs": "[\"Peinture écaillée ou décolorée\", \"Rouille en surface\", \"Changement de couleur\"]",
    "signs_en": "[\"Chipped or faded paint\", \"Surface rust\", \"A colour change\"]",
    "confirmed": 1
  }
];
