/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_atelier_bohica_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791049861/tapavis_tenant_atelier_bohica_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791049861/tapavis_tenant_atelier_bohica_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791049876/tapavis_tenant_atelier_bohica_inc/hero_e9e262a0-1299-4081-b41e-c5215456e473.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791049876/tapavis_tenant_atelier_bohica_inc/vidange-huile_4c5573cc-9b47-434a-b2f6-167cbf6e64fc.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791049876/tapavis_tenant_atelier_bohica_inc/mecanique-generale_7ae35439-f772-42db-8fdc-3b31c03b96b6.webp",
    "freins": "https://media.liasse.tech/upload/v1791049877/tapavis_tenant_atelier_bohica_inc/freins_b2cade0d-4696-437b-af74-ce14cc98fa2a.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791049885/tapavis_tenant_atelier_bohica_inc/silencieux_b379edbc-82ae-404e-90ef-80ab90e5f5d1.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791049886/tapavis_tenant_atelier_bohica_inc/equilibrage-rotation-pneus_c6d1470d-47c0-41f5-9ad3-2b2cb6bc9b4c.webp",
    "suspension": "https://media.liasse.tech/upload/v1791049886/tapavis_tenant_atelier_bohica_inc/suspension_15eea6be-fc1c-4beb-b60b-f5e1ba8ef4c2.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791049887/tapavis_tenant_atelier_bohica_inc/systeme-de-refroidissement_08fd0189-3a29-44fb-b366-589a2604cbc6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791049896/tapavis_tenant_atelier_bohica_inc/transmission_e2ac87e2-90d6-4bfc-985f-549573c41fbe.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791049896/tapavis_tenant_atelier_bohica_inc/mise-au-point_f45bef7f-2e62-4e63-834b-90442abfdbe4.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791049897/tapavis_tenant_atelier_bohica_inc/climatisation_13428d4a-b78a-4b9d-b456-d55affff7af9.webp"
  }
};
