/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_d_mecanique).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576939/tapavis_tenant_d_mecanique/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576939/tapavis_tenant_d_mecanique/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576950/tapavis_tenant_d_mecanique/hero_ad1cb9f0-78dc-412e-afb0-2403f4d2008d.png",
  "services": {
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576948/tapavis_tenant_d_mecanique/silencieux_fcec02b8-5db3-45be-aae0-d8669b781b90.png",
    "reparation-camions": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576950/tapavis_tenant_d_mecanique/reparation-camions_ef2f8ec7-3623-423b-8b02-e050a14e1d34.png",
    "antirouille": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576952/tapavis_tenant_d_mecanique/antirouille_7e34ce9d-d01f-4ffe-835a-8c6bb703acf9.png",
    "pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576961/tapavis_tenant_d_mecanique/pneus_6ef74873-e1c3-4dec-888d-550eab7d8ec0.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576961/tapavis_tenant_d_mecanique/inspection-mecanique_2ed92f3b-533d-4262-8ab1-f3c26dac646f.png",
    "pare-brise": "https://res.cloudinary.com/duhp69meg/image/upload/v1790576962/tapavis_tenant_d_mecanique/pare-brise_d470351a-cc6c-4b9f-8ac5-948805d5e0ba.png"
  }
};
