/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_soucy_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791051348/tapavis_tenant_soucy_auto/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791051348/tapavis_tenant_soucy_auto/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791052458/tapavis_tenant_soucy_auto/hero_75c7a9a7-bcdf-400c-b8c5-e146b02083f6.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791051366/tapavis_tenant_soucy_auto/vidange-huile_ab0025a7-4295-435c-aef4-ceae4ebc2c08.webp",
    "freins": "https://media.liasse.tech/upload/v1791051366/tapavis_tenant_soucy_auto/freins_a92cc9a6-316c-4182-abc8-00452905f17c.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791051367/tapavis_tenant_soucy_auto/mecanique-generale_eb28c071-73ef-461d-8b70-2892e498d959.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791051375/tapavis_tenant_soucy_auto/silencieux_554a3c43-85c2-42ff-a3a6-4a659d5a44b6.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791051376/tapavis_tenant_soucy_auto/equilibrage-rotation-pneus_2621d330-612c-4333-a6c5-98f736ed4c2a.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791051378/tapavis_tenant_soucy_auto/systeme-de-refroidissement_ec4ad89a-a44c-4f0f-94aa-04283f2c35d7.webp",
    "suspension": "https://media.liasse.tech/upload/v1791051379/tapavis_tenant_soucy_auto/suspension_5672129c-431d-4ffc-9a6b-f37d0fe01136.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791051387/tapavis_tenant_soucy_auto/climatisation_840b8444-874c-4dca-9be0-a7e96b81d0e6.webp",
    "transmission": "https://media.liasse.tech/upload/v1791051387/tapavis_tenant_soucy_auto/transmission_921bae37-a0b6-4433-87b0-a2e349247eba.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791051388/tapavis_tenant_soucy_auto/mise-au-point_4eed84cb-e18f-4f39-a7a7-68fc536f366d.webp"
  }
};
