/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_auto_gt).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812839/tapavis_tenant_mecanique_auto_gt/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812839/tapavis_tenant_mecanique_auto_gt/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812864/tapavis_tenant_mecanique_auto_gt/hero_d534e364-33c0-4a97-8795-222b307dfafa.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812864/tapavis_tenant_mecanique_auto_gt/freins_c7694c3b-ebe1-4808-8d84-30f5c2a6895f.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812864/tapavis_tenant_mecanique_auto_gt/vidange-huile_18c61173-1059-4f59-98ca-3c6043c4643c.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812866/tapavis_tenant_mecanique_auto_gt/mecanique-generale_6603d5a4-26a3-4428-ad96-4d9d9d42d4f4.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812878/tapavis_tenant_mecanique_auto_gt/silencieux_ef70d154-8833-4885-af5b-44aab0e3bbc0.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812880/tapavis_tenant_mecanique_auto_gt/suspension_ed0bbfba-c1c3-4c30-b81a-5fc34490c7f7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812881/tapavis_tenant_mecanique_auto_gt/equilibrage-rotation-pneus_8b553f28-42c7-470b-aa3f-8847000273a1.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812890/tapavis_tenant_mecanique_auto_gt/systeme-de-refroidissement_36569680-01ea-4087-ad61-47224dc600cd.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812903/tapavis_tenant_mecanique_auto_gt/climatisation_4e01f48e-06e3-4884-9b77-39891ecefff8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812903/tapavis_tenant_mecanique_auto_gt/mise-au-point_21306c4b-785f-4532-a10b-13b015f34023.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812907/tapavis_tenant_mecanique_auto_gt/transmission_0da8a557-46e0-4e42-a472-357e40ec5672.png"
  }
};
