/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_depaneur_mecanique_roland_leblanc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1790964193/tapavis_tenant_depaneur_mecanique_roland_leblanc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1790964193/tapavis_tenant_depaneur_mecanique_roland_leblanc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1790965251/tapavis_tenant_depaneur_mecanique_roland_leblanc/hero_3b999c11-dc8d-4ccc-bc02-31a78c9876e4.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1790964209/tapavis_tenant_depaneur_mecanique_roland_leblanc/vidange-huile_f68218ee-03a2-45f4-b590-02da392da5f6.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1790964210/tapavis_tenant_depaneur_mecanique_roland_leblanc/mecanique-generale_e7ecfaff-eb73-4660-a4b9-1be5c46ae06c.webp",
    "freins": "https://media.liasse.tech/upload/v1790964211/tapavis_tenant_depaneur_mecanique_roland_leblanc/freins_02b40e6b-e8c0-4f27-b3c5-398352ad429d.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1790964219/tapavis_tenant_depaneur_mecanique_roland_leblanc/equilibrage-rotation-pneus_077c941a-9556-44ad-afa9-2790507c44a8.webp",
    "silencieux": "https://media.liasse.tech/upload/v1790964220/tapavis_tenant_depaneur_mecanique_roland_leblanc/silencieux_03856c33-7d58-45f5-8e38-c2798a7887ce.webp",
    "suspension": "https://media.liasse.tech/upload/v1790964220/tapavis_tenant_depaneur_mecanique_roland_leblanc/suspension_11510554-c092-4da9-b15a-e745cab8dfc7.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1790964223/tapavis_tenant_depaneur_mecanique_roland_leblanc/systeme-de-refroidissement_bc51faeb-d4d4-4075-94ca-c8a8755f6452.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1790964230/tapavis_tenant_depaneur_mecanique_roland_leblanc/mise-au-point_69af5165-4689-4de7-a8fa-64d6e8ab4d98.webp",
    "climatisation": "https://media.liasse.tech/upload/v1790964230/tapavis_tenant_depaneur_mecanique_roland_leblanc/climatisation_0d679f0a-5297-4d12-8633-f0a1a15753d9.webp",
    "transmission": "https://media.liasse.tech/upload/v1790964231/tapavis_tenant_depaneur_mecanique_roland_leblanc/transmission_a9428608-ba9f-479c-b314-29221de7fbca.webp"
  }
};
