/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_mecanique_cm_performance).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666632/tapavis_tenant_garage_mecanique_cm_performance/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666632/tapavis_tenant_garage_mecanique_cm_performance/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666643/tapavis_tenant_garage_mecanique_cm_performance/hero_ec5ce86c-c24c-4df0-b889-8c7b63bd3967.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666643/tapavis_tenant_garage_mecanique_cm_performance/vidange-huile_f21e8b58-cbcf-4078-a96d-9e9931c7791f.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666644/tapavis_tenant_garage_mecanique_cm_performance/freins_71df01e1-deb5-4ade-9904-af11fa455de6.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666645/tapavis_tenant_garage_mecanique_cm_performance/mecanique-generale_81266192-c903-4ce1-a4aa-66b4e6825ebd.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666654/tapavis_tenant_garage_mecanique_cm_performance/equilibrage-rotation-pneus_b894c1e7-dc51-4031-bda0-7c837891563c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666654/tapavis_tenant_garage_mecanique_cm_performance/silencieux_e4408ce5-4949-47aa-8de3-f4a88dd9cb45.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666656/tapavis_tenant_garage_mecanique_cm_performance/suspension_0db1f6e2-cc2c-4b0c-ad7c-28bd2a60d6c6.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666660/tapavis_tenant_garage_mecanique_cm_performance/systeme-de-refroidissement_931b72ca-d12e-4852-83ab-148e7eb0e9c4.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666667/tapavis_tenant_garage_mecanique_cm_performance/climatisation_d9c35e3c-0b74-495e-890c-4ce29f470ea7.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666667/tapavis_tenant_garage_mecanique_cm_performance/mise-au-point_ce408f97-5655-443c-8c3f-5805ba3e3d86.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666668/tapavis_tenant_garage_mecanique_cm_performance/transmission_fba4464f-410e-47c5-912b-34079c04d568.png"
  }
};
