/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_d_m_w_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812709/tapavis_tenant_garage_d_m_w_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812709/tapavis_tenant_garage_d_m_w_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812727/tapavis_tenant_garage_d_m_w_inc/hero_ee4e193d-e737-4d2a-b5d9-a59d78f3b393.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812727/tapavis_tenant_garage_d_m_w_inc/freins_163f4e56-bc46-41ca-950d-e2c0e7a13972.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812728/tapavis_tenant_garage_d_m_w_inc/vidange-huile_3093700e-1663-4583-b702-82dbbaa55ad1.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812729/tapavis_tenant_garage_d_m_w_inc/mecanique-generale_110ea316-0e21-4829-93f7-f273008a9c2c.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812740/tapavis_tenant_garage_d_m_w_inc/silencieux_ea81094a-fee3-411f-a10f-c65a46485028.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812740/tapavis_tenant_garage_d_m_w_inc/equilibrage-rotation-pneus_e172c2c2-6b63-4f5a-b443-b8a81823a736.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812742/tapavis_tenant_garage_d_m_w_inc/suspension_ab385fc4-9697-4ae6-8283-cfd692857f64.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812742/tapavis_tenant_garage_d_m_w_inc/systeme-de-refroidissement_9fdc04d0-6d26-4085-ae74-8b22ede175d5.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812752/tapavis_tenant_garage_d_m_w_inc/climatisation_e1bf430d-363b-4b5a-ab1e-1932cc04a727.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812751/tapavis_tenant_garage_d_m_w_inc/mise-au-point_d0c62140-08df-4a3f-bbe2-a42eac494313.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812757/tapavis_tenant_garage_d_m_w_inc/transmission_e92d1428-5066-4bc5-b46b-5a2608d2ab6e.png"
  }
};
