/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_johnson_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813337/tapavis_tenant_garage_johnson_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813337/tapavis_tenant_garage_johnson_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813351/tapavis_tenant_garage_johnson_inc/hero_8dac807e-f9ba-462a-94f7-4689308b992d.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813348/tapavis_tenant_garage_johnson_inc/freins_c6adc15a-3d63-4e5f-aec6-37c4cf6e5e66.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813350/tapavis_tenant_garage_johnson_inc/vidange-huile_1ba68f91-b03e-4ebe-b8a6-e80a9d2c04dd.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813351/tapavis_tenant_garage_johnson_inc/mecanique-generale_f258d281-188d-4cd3-a32d-93351d51e169.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813359/tapavis_tenant_garage_johnson_inc/equilibrage-rotation-pneus_60da42e1-68e4-4b42-b22f-1cb3afa1c6e6.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813361/tapavis_tenant_garage_johnson_inc/silencieux_fbaf9523-6fba-4642-acb4-10ec04118e81.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813362/tapavis_tenant_garage_johnson_inc/suspension_bc76ede1-95e0-41b3-bd79-0c3bd2c053de.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813369/tapavis_tenant_garage_johnson_inc/systeme-de-refroidissement_d3b66a9e-d47d-43ff-b046-72a19c04011f.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813373/tapavis_tenant_garage_johnson_inc/mise-au-point_97f9d73d-e554-4946-b48f-9f1c6697ad44.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813375/tapavis_tenant_garage_johnson_inc/climatisation_6dc3d4a2-ec2f-4bbe-86cf-6c73a17ebe2f.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813376/tapavis_tenant_garage_johnson_inc/transmission_0cc7bea7-c107-4f8d-877f-8287dfec5ebd.png"
  }
};
