/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_luc_beliveau_enr).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670722/tapavis_tenant_garage_luc_beliveau_enr/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670722/tapavis_tenant_garage_luc_beliveau_enr/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670733/tapavis_tenant_garage_luc_beliveau_enr/hero_db8643c0-97cd-4f97-b1b7-f0f05d911470.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670733/tapavis_tenant_garage_luc_beliveau_enr/vidange-huile_72d5a379-de76-45a9-b199-7b88d700afee.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670733/tapavis_tenant_garage_luc_beliveau_enr/freins_5fb57c19-1c69-418f-bc00-eed88c619af0.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670735/tapavis_tenant_garage_luc_beliveau_enr/mecanique-generale_30f0c4b8-1d83-482d-a08f-5361c4c183c0.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670744/tapavis_tenant_garage_luc_beliveau_enr/equilibrage-rotation-pneus_c5e73488-577e-4b57-9f94-f4493d7660d1.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670744/tapavis_tenant_garage_luc_beliveau_enr/suspension_c14e9edd-0b55-4e32-bbed-0909e0f7c2bf.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670746/tapavis_tenant_garage_luc_beliveau_enr/systeme-de-refroidissement_0d7e0e70-b882-4d71-bf93-6f8b9f0f421f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670746/tapavis_tenant_garage_luc_beliveau_enr/silencieux_937f8bad-9f75-45fd-ba73-65771525feb0.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670755/tapavis_tenant_garage_luc_beliveau_enr/climatisation_7401c602-704c-479b-8ca6-b2db989958b2.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670755/tapavis_tenant_garage_luc_beliveau_enr/mise-au-point_21e35b4b-06dd-4fd3-b1de-6dff8deb4fe5.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790670759/tapavis_tenant_garage_luc_beliveau_enr/transmission_fae48482-bb44-41f6-8fbe-aa317e6c3e85.png"
  }
};
