/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_vital_hudon_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536271/tapavis_tenant_garage_vital_hudon_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536271/tapavis_tenant_garage_vital_hudon_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536283/tapavis_tenant_garage_vital_hudon_inc/hero_690219e2-d063-4a11-9a5e-849880fc2514.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536283/tapavis_tenant_garage_vital_hudon_inc/vidange-huile_5dfc51c2-af15-4e9f-898f-4b1a3727c91f.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536284/tapavis_tenant_garage_vital_hudon_inc/mecanique-generale_249a733d-2911-4aaa-a046-30acbd75c999.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536286/tapavis_tenant_garage_vital_hudon_inc/freins_10017ef1-ef1f-430c-a76b-f9987bf87327.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536293/tapavis_tenant_garage_vital_hudon_inc/silencieux_51f3939b-b52f-4270-a063-3e30b69b0f0e.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536294/tapavis_tenant_garage_vital_hudon_inc/equilibrage-rotation-pneus_bc7a99cb-8f91-465f-9483-a32a1c49fc00.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536295/tapavis_tenant_garage_vital_hudon_inc/suspension_b6e7cd7f-b103-4127-9cee-b9ba6b410382.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536298/tapavis_tenant_garage_vital_hudon_inc/systeme-de-refroidissement_29360379-cd96-464d-8886-405aea3535d8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536305/tapavis_tenant_garage_vital_hudon_inc/mise-au-point_c440ecd2-6d28-40bc-9c03-b734fc4d6a80.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536306/tapavis_tenant_garage_vital_hudon_inc/transmission_61683f5a-3999-4939-9d8b-652e566a1a94.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790536307/tapavis_tenant_garage_vital_hudon_inc/climatisation_f2f4383a-24d3-4461-aa82-5310993e7d88.png"
  }
};
