/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_rejean_beauregard).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736233/tapavis_tenant_garage_rejean_beauregard/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736233/tapavis_tenant_garage_rejean_beauregard/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736243/tapavis_tenant_garage_rejean_beauregard/hero_ddabbd74-3407-4a28-9e2b-7c352a1423a2.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736245/tapavis_tenant_garage_rejean_beauregard/vidange-huile_5c65603b-79fc-428b-bd78-9f3069af6881.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736245/tapavis_tenant_garage_rejean_beauregard/mecanique-generale_dcd11b2e-81d4-4057-b5c0-46cf1b813ed2.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736246/tapavis_tenant_garage_rejean_beauregard/freins_8a780d85-0a9c-4136-8d39-ed408afc5336.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736254/tapavis_tenant_garage_rejean_beauregard/equilibrage-rotation-pneus_c341eb38-d4a9-4780-af65-982fc18c40eb.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736255/tapavis_tenant_garage_rejean_beauregard/silencieux_48121b16-f205-479a-9b7a-45261a74c113.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736256/tapavis_tenant_garage_rejean_beauregard/suspension_22384058-4dbb-4a44-873a-9fbc00adba98.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736258/tapavis_tenant_garage_rejean_beauregard/systeme-de-refroidissement_7fe27996-5f75-4544-bf40-e9a317a28a6e.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736266/tapavis_tenant_garage_rejean_beauregard/mise-au-point_ddcc0112-3c74-4422-a604-9bfd010591b2.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736267/tapavis_tenant_garage_rejean_beauregard/climatisation_83bb8f40-a062-46ba-aa2e-6bcc689300b8.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790736268/tapavis_tenant_garage_rejean_beauregard/transmission_e8f246f7-3c5e-447b-abe7-acf7907c9159.png"
  }
};
