/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_michel_nadeau).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812991/tapavis_tenant_garage_michel_nadeau/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790812991/tapavis_tenant_garage_michel_nadeau/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814548/tapavis_tenant_garage_michel_nadeau/hero_c4a587e4-cf03-4be2-8c92-a8fa5785b0e6.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813002/tapavis_tenant_garage_michel_nadeau/freins_682a4b59-973f-4fdf-bb39-98bb4251c581.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813002/tapavis_tenant_garage_michel_nadeau/silencieux_6ae0cdc6-71d6-4d1c-b44a-5b5d9f9d1c7b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813004/tapavis_tenant_garage_michel_nadeau/transmission_bd1a298d-c5c6-4690-93e4-125137751568.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813004/tapavis_tenant_garage_michel_nadeau/systeme-de-refroidissement_199227c5-127e-49ee-99f3-46ce1a902568.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814549/tapavis_tenant_garage_michel_nadeau/equilibrage-rotation-pneus_66656f1e-1aea-4859-8905-9e87ec7b7ffb.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814549/tapavis_tenant_garage_michel_nadeau/vidange-huile_54661af1-8534-4438-b81f-f19baf4d11d8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814550/tapavis_tenant_garage_michel_nadeau/mecanique-generale_861702a2-02f2-48c7-8d9a-e6a7a487c120.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814560/tapavis_tenant_garage_michel_nadeau/suspension_e8200fed-36c9-44b9-a764-c666206234a1.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814561/tapavis_tenant_garage_michel_nadeau/mise-au-point_8dc53b18-f500-4562-a59c-1d54ba74b0ac.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814561/tapavis_tenant_garage_michel_nadeau/climatisation_fb2f9db6-9551-4c96-b49e-ea8993857fe9.png"
  }
};
