/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_a_chabot_et_fils).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813272/tapavis_tenant_garage_a_chabot_et_fils/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813272/tapavis_tenant_garage_a_chabot_et_fils/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813291/tapavis_tenant_garage_a_chabot_et_fils/hero_c9a078e6-f3e1-46da-b0a3-96854cf97545.png",
  "services": {
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813291/tapavis_tenant_garage_a_chabot_et_fils/equilibrage-rotation-pneus_5128bd9d-56e0-4235-8982-981af481e4cb.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813295/tapavis_tenant_garage_a_chabot_et_fils/mise-au-point_690f36e3-114c-4102-91cc-6aecac366908.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813297/tapavis_tenant_garage_a_chabot_et_fils/climatisation_e0e2fa7a-07f9-49cb-9b9e-0da28367d10d.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813311/tapavis_tenant_garage_a_chabot_et_fils/transmission_0073ef0b-13b3-46cd-a582-e2b4589197b8.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813328/tapavis_tenant_garage_a_chabot_et_fils/vidange-huile_db12a061-ecb2-48a1-9062-f6be4eeb06e2.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813332/tapavis_tenant_garage_a_chabot_et_fils/mecanique-generale_cbfcd4c4-4310-49a6-8f1c-4716241a2b5d.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813332/tapavis_tenant_garage_a_chabot_et_fils/systeme-electrique_85e357ec-eb81-45df-acc7-77c79b354d64.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813333/tapavis_tenant_garage_a_chabot_et_fils/freins_b07d0c30-9862-496c-8ec3-a69ba4706427.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813340/tapavis_tenant_garage_a_chabot_et_fils/suspension_0aca0d4e-c61f-484c-86c9-493ffcd8155a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813343/tapavis_tenant_garage_a_chabot_et_fils/silencieux_55a29fab-50fc-48a0-9124-5dbfe1d7af36.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813346/tapavis_tenant_garage_a_chabot_et_fils/systeme-de-refroidissement_6ca35cbb-e0ce-459c-b8e0-68f6d8b8cdbf.png"
  }
};
