/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_alma_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534841/tapavis_tenant_garage_alma_auto/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534841/tapavis_tenant_garage_alma_auto/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534856/tapavis_tenant_garage_alma_auto/hero_6b81aad0-dd10-468b-8fef-f18f242982d3.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534851/tapavis_tenant_garage_alma_auto/vidange-huile_6046677f-388b-428d-9ce6-b636a3310996.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534855/tapavis_tenant_garage_alma_auto/freins_22b8625e-c3b3-4686-b946-fb6a8e28f639.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534856/tapavis_tenant_garage_alma_auto/mecanique-generale_59a22cbf-c679-4770-a96e-a0e4d7e954b0.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534863/tapavis_tenant_garage_alma_auto/equilibrage-rotation-pneus_a94630bb-6fea-40e0-b4fc-fd59eb5f96ad.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534867/tapavis_tenant_garage_alma_auto/silencieux_ff2be332-5693-44da-a240-250d6cf39ed3.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534867/tapavis_tenant_garage_alma_auto/suspension_514ac631-a937-4c67-a153-0531317f4a2d.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534869/tapavis_tenant_garage_alma_auto/systeme-de-refroidissement_98c5c2c0-d63c-4a3b-b9fe-b87b2afc63fc.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534875/tapavis_tenant_garage_alma_auto/climatisation_408a89d5-f3f2-4ce8-92e6-857d02506fed.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534881/tapavis_tenant_garage_alma_auto/mise-au-point_23d64f54-fd23-4747-9c01-91255a0582e9.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534881/tapavis_tenant_garage_alma_auto/transmission_e8587ceb-660b-4398-8c09-e890ce6c62a3.png"
  }
};
