/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_midnight_tuning).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813111/tapavis_tenant_midnight_tuning/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813111/tapavis_tenant_midnight_tuning/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814707/tapavis_tenant_midnight_tuning/hero_b44ec823-34a0-4abd-b1ce-61c4380021e5.png",
  "services": {
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813122/tapavis_tenant_midnight_tuning/systeme-de-refroidissement_981831fe-251e-4dd7-b565-6f17cccbc30e.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813122/tapavis_tenant_midnight_tuning/suspension_d04f968b-ef55-4d9c-adb8-81555e376dfd.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813139/tapavis_tenant_midnight_tuning/mise-au-point_2916e9a0-2766-4521-8060-9e49e2f0f542.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814706/tapavis_tenant_midnight_tuning/vidange-huile_139e4c74-1905-41eb-a53e-0da90a293b78.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814707/tapavis_tenant_midnight_tuning/freins_ec0d2c9c-fe94-4456-bd0a-acfb86830d04.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814708/tapavis_tenant_midnight_tuning/mecanique-generale_7f4db830-ee25-45fa-bdca-ccffd571af3b.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814716/tapavis_tenant_midnight_tuning/equilibrage-rotation-pneus_e73dede6-94f9-4ed9-b6b8-0345283687e0.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814718/tapavis_tenant_midnight_tuning/transmission_d2d5311c-8dc2-4c95-bbfb-e6c8556ece6a.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814718/tapavis_tenant_midnight_tuning/climatisation_044c9af0-dcbf-44f7-bedb-e687ba2f68c5.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814718/tapavis_tenant_midnight_tuning/silencieux_230366af-34fa-433a-a178-f5b24c5ed7ca.png"
  }
};
