/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_s_b_auto_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577326/tapavis_tenant_garage_s_b_auto_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577326/tapavis_tenant_garage_s_b_auto_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577339/tapavis_tenant_garage_s_b_auto_inc/hero_97ce887a-fce5-4b6e-8ec7-3043e35d727a.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577337/tapavis_tenant_garage_s_b_auto_inc/freins_64d0a487-aebc-46a1-b6db-4da4725c126e.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577337/tapavis_tenant_garage_s_b_auto_inc/vidange-huile_3049dcf1-8003-4cc8-b84e-bd9dd9b36af2.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577340/tapavis_tenant_garage_s_b_auto_inc/mecanique-generale_c3d41f4c-80a0-43b0-bfc8-63dd1959cad9.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577348/tapavis_tenant_garage_s_b_auto_inc/equilibrage-rotation-pneus_a9367154-ea76-4e99-ab07-eea2c29c5504.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577348/tapavis_tenant_garage_s_b_auto_inc/silencieux_63dbe39b-9df4-46f5-920a-be670b164930.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577349/tapavis_tenant_garage_s_b_auto_inc/suspension_c3ef0d6e-3791-4852-973e-616648020e3f.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577354/tapavis_tenant_garage_s_b_auto_inc/systeme-de-refroidissement_96efe95d-a132-4932-8714-650fb13a1471.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577359/tapavis_tenant_garage_s_b_auto_inc/mise-au-point_0da0c474-ff51-4944-a0e6-143acea27c40.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577361/tapavis_tenant_garage_s_b_auto_inc/transmission_80362794-1756-407c-9ce0-ced46bf24a29.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790577361/tapavis_tenant_garage_s_b_auto_inc/climatisation_1f815297-7797-4eec-a1cf-072edac5e3ad.png"
  }
};
