/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_laframboise).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666631/tapavis_tenant_garage_laframboise/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666631/tapavis_tenant_garage_laframboise/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666641/tapavis_tenant_garage_laframboise/hero_6c8ca469-3e69-499c-acf0-23dd2acad1d9.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666641/tapavis_tenant_garage_laframboise/vidange-huile_ebbb579c-0673-40cb-97d0-4b8c2694c469.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666643/tapavis_tenant_garage_laframboise/systeme-de-refroidissement_ed657a7a-98cf-441f-99a0-77e6416400c4.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666646/tapavis_tenant_garage_laframboise/systeme-electrique_6a705bac-dcc4-4ce8-8f55-1889f7edd3cb.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666652/tapavis_tenant_garage_laframboise/equilibrage-rotation-pneus_637afd0f-f9d5-4547-acff-e15775fa583c.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666654/tapavis_tenant_garage_laframboise/alignement_05dd99c6-d4cf-494b-a731-8d1cb7ff5e0f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666655/tapavis_tenant_garage_laframboise/silencieux_45317cdf-c57a-4820-9fcb-80fd3cb980f4.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666655/tapavis_tenant_garage_laframboise/mise-au-point_f00d0a45-3983-4052-a790-d4f76cc79650.png",
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666664/tapavis_tenant_garage_laframboise/batterie-demarreur-alternateur_6dcec236-401c-4094-be27-537ee7f74ef7.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666664/tapavis_tenant_garage_laframboise/suspension_57eaa2b9-81ba-42c1-8291-ae4448eaa852.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666666/tapavis_tenant_garage_laframboise/entretien-preventif_b95cc48f-8e2e-4530-950b-d2a3427a6a87.png",
    "embrayage": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666668/tapavis_tenant_garage_laframboise/embrayage_aac6759e-d4ca-40ba-84fb-d4e904ae379a.png",
    "inspection-mecanique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790666676/tapavis_tenant_garage_laframboise/inspection-mecanique_bdbf2cf4-3b28-4d85-b9b1-a405e10f0094.png"
  }
};
