/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_centre_mecanique_michel_lanthier).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732723/tapavis_tenant_centre_mecanique_michel_lanthier/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732723/tapavis_tenant_centre_mecanique_michel_lanthier/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732736/tapavis_tenant_centre_mecanique_michel_lanthier/hero_d7720d1c-c5c0-4240-888b-1b00a224df54.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732734/tapavis_tenant_centre_mecanique_michel_lanthier/vidange-huile_025ef908-3548-432c-8753-300250136bd2.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732735/tapavis_tenant_centre_mecanique_michel_lanthier/freins_c1e774b4-ca81-417c-a257-a3b774f63ea2.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732736/tapavis_tenant_centre_mecanique_michel_lanthier/mecanique-generale_d0a11534-f509-43dc-96d2-44975b16a9dd.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732745/tapavis_tenant_centre_mecanique_michel_lanthier/equilibrage-rotation-pneus_82f370ed-6077-4844-aeea-14de3ad82eb6.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732745/tapavis_tenant_centre_mecanique_michel_lanthier/suspension_42f237ff-8f35-40b7-8358-0f5e50381642.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732746/tapavis_tenant_centre_mecanique_michel_lanthier/silencieux_7e2c7840-967e-4593-8567-a8e4fc1bc9dc.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732750/tapavis_tenant_centre_mecanique_michel_lanthier/systeme-de-refroidissement_4037dfad-e4f7-4738-9390-047e18ab33cd.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732756/tapavis_tenant_centre_mecanique_michel_lanthier/mise-au-point_a3f327ba-7846-47dc-9872-ca2176e88fd5.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732757/tapavis_tenant_centre_mecanique_michel_lanthier/climatisation_ee27c594-d061-4697-b977-675d2d71da05.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790732761/tapavis_tenant_centre_mecanique_michel_lanthier/transmission_06b7c766-4a6c-42fa-ba98-d8a85aeb49e7.png"
  }
};
