/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_beauchemin_fils).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791048385/tapavis_tenant_garage_beauchemin_fils/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791048385/tapavis_tenant_garage_beauchemin_fils/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791048399/tapavis_tenant_garage_beauchemin_fils/hero_0e42c56d-0bcc-4f7e-a06b-1d0998ffd793.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1791048400/tapavis_tenant_garage_beauchemin_fils/mecanique-generale_f4471479-a7e5-49f6-ad25-e1be3ee1231b.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791048401/tapavis_tenant_garage_beauchemin_fils/vidange-huile_35235fa5-1548-41f9-b10a-c845935ac09f.webp",
    "freins": "https://media.liasse.tech/upload/v1791048402/tapavis_tenant_garage_beauchemin_fils/freins_70312506-478b-4522-83e8-dacedc5bc1a0.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791048409/tapavis_tenant_garage_beauchemin_fils/equilibrage-rotation-pneus_5763a045-2c5b-48ae-a127-0373e07bb976.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791048409/tapavis_tenant_garage_beauchemin_fils/silencieux_fe80aecb-b1f0-4dc0-803c-adcea43f90eb.webp",
    "suspension": "https://media.liasse.tech/upload/v1791048410/tapavis_tenant_garage_beauchemin_fils/suspension_98547c1e-8be0-454f-b945-6a4d00ed637b.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791048413/tapavis_tenant_garage_beauchemin_fils/systeme-de-refroidissement_4301894d-91c0-4fb5-b15c-a1920846aaeb.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791048419/tapavis_tenant_garage_beauchemin_fils/mise-au-point_29e6e19b-b9ca-49bb-af74-28ec778152c6.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791048420/tapavis_tenant_garage_beauchemin_fils/climatisation_5a6c337d-3422-4722-87f2-6ec30696c5fa.webp",
    "transmission": "https://media.liasse.tech/upload/v1791048420/tapavis_tenant_garage_beauchemin_fils/transmission_760b1415-8afc-4085-a885-47ef6d7cbce1.webp"
  }
};
