/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_j_m).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813239/tapavis_tenant_garage_j_m/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813239/tapavis_tenant_garage_j_m/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814894/tapavis_tenant_garage_j_m/hero_7207fa8d-47eb-47f5-bc14-7abc98cb3d92.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813252/tapavis_tenant_garage_j_m/freins_e6e6179b-2dc3-41e7-b291-c024c6b75c4e.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813255/tapavis_tenant_garage_j_m/climatisation_5b42364c-468f-40b0-9674-54bad569c175.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813272/tapavis_tenant_garage_j_m/transmission_4fde36b1-73f0-4f0e-844b-0f1a4bff3d9c.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814894/tapavis_tenant_garage_j_m/vidange-huile_7b44f686-a2ca-43c3-9475-8c27c4ca7478.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814894/tapavis_tenant_garage_j_m/equilibrage-rotation-pneus_b44e739e-834e-4f2c-b906-ab0ffc2de90c.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814895/tapavis_tenant_garage_j_m/mecanique-generale_f284e0a8-ccf9-4012-8ae8-07d9fbf11b92.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814906/tapavis_tenant_garage_j_m/systeme-de-refroidissement_caa20c84-cf29-4974-b608-cb6b2e8e11db.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814906/tapavis_tenant_garage_j_m/suspension_5bf1dd19-aa4a-413a-bd5e-7e64bd67fdec.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814907/tapavis_tenant_garage_j_m/mise-au-point_563e405e-5203-4533-8fda-ae28d51455ba.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790814919/tapavis_tenant_garage_j_m/silencieux_eb190def-120f-4f63-b13d-865cfbce4fd2.png"
  }
};
