/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_garage_jean_lapierre).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791052527/tapavis_tenant_garage_jean_lapierre/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791052527/tapavis_tenant_garage_jean_lapierre/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791054273/tapavis_tenant_garage_jean_lapierre/hero_b9185f93-511d-4740-8421-18afb6f6c1a7.webp",
  "services": {
    "freins": "https://media.liasse.tech/upload/v1791052541/tapavis_tenant_garage_jean_lapierre/freins_3d9ce40f-c83f-4867-b81d-064a86781232.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791052541/tapavis_tenant_garage_jean_lapierre/vidange-huile_d7fb8122-0db3-4b14-9a98-388991c9f2aa.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791052542/tapavis_tenant_garage_jean_lapierre/mecanique-generale_903149f7-70db-4d82-86cf-f7e0adf718c5.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791052550/tapavis_tenant_garage_jean_lapierre/silencieux_7bd6da60-4bb8-49bb-aa22-ee5efcd8f003.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791052552/tapavis_tenant_garage_jean_lapierre/equilibrage-rotation-pneus_943c10b2-473d-4ff0-a8cf-287655c78dc3.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791052552/tapavis_tenant_garage_jean_lapierre/systeme-de-refroidissement_973daef9-4d54-4ef2-9894-fd9905c30130.webp",
    "suspension": "https://media.liasse.tech/upload/v1791052552/tapavis_tenant_garage_jean_lapierre/suspension_e867feef-f69b-43a1-a041-d2894df15069.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791052560/tapavis_tenant_garage_jean_lapierre/climatisation_0dcd0c35-70fc-478d-8cc4-1b2604ef9049.webp",
    "transmission": "https://media.liasse.tech/upload/v1791052563/tapavis_tenant_garage_jean_lapierre/transmission_71d7d60b-2250-49ce-8845-0b083da0006b.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791052563/tapavis_tenant_garage_jean_lapierre/mise-au-point_3d36b946-1084-4fb6-b925-d30aa043cfec.webp"
  }
};
