/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_skl).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668801/tapavis_tenant_mecanique_skl/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668801/tapavis_tenant_mecanique_skl/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668812/tapavis_tenant_mecanique_skl/hero_e5d91c56-79fd-4599-845d-6a159e99fb5e.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668812/tapavis_tenant_mecanique_skl/freins_790f4092-09ca-4c7e-a0e8-4603067925b1.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668812/tapavis_tenant_mecanique_skl/vidange-huile_98cd812f-5e22-4296-9447-3ee1c1d4a6ce.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668813/tapavis_tenant_mecanique_skl/mecanique-generale_259bf0ef-d88c-4f3a-88e1-61083d196e45.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668822/tapavis_tenant_mecanique_skl/equilibrage-rotation-pneus_06227a5e-2016-400a-a82e-d4be627329cd.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668822/tapavis_tenant_mecanique_skl/silencieux_20919d52-9e83-4ead-ae10-5cb0e8c0b01e.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668823/tapavis_tenant_mecanique_skl/suspension_b46e1270-6aa7-4340-ae39-b4821d64ddce.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668825/tapavis_tenant_mecanique_skl/systeme-de-refroidissement_a4eb8863-aaad-4ace-bd59-0402b5b8e5d1.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668833/tapavis_tenant_mecanique_skl/climatisation_44db7efb-5636-487e-8434-44f60b6b270f.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668833/tapavis_tenant_mecanique_skl/mise-au-point_87cc1f5f-9ccb-47fa-98b4-c1387255e5e1.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668835/tapavis_tenant_mecanique_skl/transmission_422592f5-fe31-41e3-9b96-6ac7664f92d6.png"
  }
};
