/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_mecan_o_pneus).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791052909/tapavis_tenant_mecan_o_pneus/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791052909/tapavis_tenant_mecan_o_pneus/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791052923/tapavis_tenant_mecan_o_pneus/hero_1e485bc4-f7a7-46f1-9da0-b4b0cea9cb63.webp",
  "services": {
    "mecanique-generale": "https://media.liasse.tech/upload/v1791052924/tapavis_tenant_mecan_o_pneus/mecanique-generale_b3ae0058-2221-4139-8d34-e0b149a3597e.webp",
    "pneus": "https://media.liasse.tech/upload/v1791052924/tapavis_tenant_mecan_o_pneus/pneus_e6d63a72-5b56-4c32-aef8-9658192cb5f9.webp",
    "freins": "https://media.liasse.tech/upload/v1791052925/tapavis_tenant_mecan_o_pneus/freins_595240ed-e0c6-4d1e-b163-c030e41551c7.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791052933/tapavis_tenant_mecan_o_pneus/equilibrage-rotation-pneus_0a526ee9-398f-4e7e-b436-2d41477b9336.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791052934/tapavis_tenant_mecan_o_pneus/silencieux_7992a7eb-8a0e-48c3-ad88-9ed99ccacfd6.webp",
    "vidange-huile": "https://media.liasse.tech/upload/v1791052935/tapavis_tenant_mecan_o_pneus/vidange-huile_46fd3bd8-7097-4851-af9b-b3671c46747f.webp",
    "suspension": "https://media.liasse.tech/upload/v1791052936/tapavis_tenant_mecan_o_pneus/suspension_8ea63c8b-4cd6-4488-a4b1-fbcd995f28f9.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791052944/tapavis_tenant_mecan_o_pneus/climatisation_f850337d-a9ac-4b0d-b298-45843727f9cf.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791052944/tapavis_tenant_mecan_o_pneus/systeme-de-refroidissement_e1a4f9fa-1d4f-478f-9269-c9bce692b6dc.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791052945/tapavis_tenant_mecan_o_pneus/mise-au-point_399c763d-85f4-4d32-ae96-001a2e42c696.webp",
    "transmission": "https://media.liasse.tech/upload/v1791052946/tapavis_tenant_mecan_o_pneus/transmission_f3fff1ee-d519-47de-be59-1718162c55c8.webp"
  }
};
