ALTER TABLE dishes ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE dishes ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS review_date TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE hours ADD COLUMN IF NOT EXISTS day_en TEXT;
ALTER TABLE hours ADD COLUMN IF NOT EXISTS closed INTEGER DEFAULT 0;
ALTER TABLE hours ADD COLUMN IF NOT EXISTS image_url TEXT;
