/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_automob).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740505/tapavis_tenant_automob/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740505/tapavis_tenant_automob/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740516/tapavis_tenant_automob/hero_642d2682-4d60-433a-8941-cf945cbee0ba.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740517/tapavis_tenant_automob/freins_f79b31a2-899c-41d3-9a61-a9de2cea17b5.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740517/tapavis_tenant_automob/vidange-huile_7f3e6a1a-88e4-490d-88ac-c6f5ffc6fd59.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740518/tapavis_tenant_automob/mecanique-generale_4b1c4239-43fa-4258-a9e6-815d9784bb06.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740526/tapavis_tenant_automob/equilibrage-rotation-pneus_d9fde64a-894a-46ca-9db4-7984b61fc930.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740528/tapavis_tenant_automob/silencieux_51dad27e-4ab1-479b-a3c0-31f5c4be6439.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740530/tapavis_tenant_automob/systeme-de-refroidissement_40f4f50f-4ebe-4c48-82b7-f5dbec958c2c.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740533/tapavis_tenant_automob/suspension_56f91ffb-ba44-4876-9860-f51b2357ef3f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740539/tapavis_tenant_automob/climatisation_dd84f381-3b8b-4cd1-98bc-9779cf731703.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740539/tapavis_tenant_automob/mise-au-point_14446780-24e2-4fea-9d49-07731a59b4c8.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790740542/tapavis_tenant_automob/transmission_268671bc-a78f-4f20-8b04-c7ec7a89459a.png"
  }
};
