/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_sda_auto_service).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624255/tapavis_tenant_sda_auto_service/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624255/tapavis_tenant_sda_auto_service/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624266/tapavis_tenant_sda_auto_service/hero_348ab764-f252-4594-93dc-9ed56a6ff7a5.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624266/tapavis_tenant_sda_auto_service/vidange-huile_417b1e67-b9c1-4c21-a110-71cdb7082ce4.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624266/tapavis_tenant_sda_auto_service/freins_125c9b68-29db-41b0-bf26-c7df74eb86b8.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624267/tapavis_tenant_sda_auto_service/mecanique-generale_52a653f1-af55-499e-9e71-84256db5027f.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624277/tapavis_tenant_sda_auto_service/equilibrage-rotation-pneus_fa463d65-12b7-49d8-b9b5-23a13c99407b.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624277/tapavis_tenant_sda_auto_service/suspension_f9ae17d6-9306-4337-8eff-97a0f57852ab.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624278/tapavis_tenant_sda_auto_service/silencieux_7ea7a69c-225e-4b82-aca5-7945625829b3.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624280/tapavis_tenant_sda_auto_service/systeme-de-refroidissement_b3c4d5aa-0476-45e0-b905-0da9d37185e8.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624289/tapavis_tenant_sda_auto_service/mise-au-point_0e8743b9-5c0a-4f89-9d94-b14080b839c4.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624289/tapavis_tenant_sda_auto_service/climatisation_e35906e6-19d8-4783-91a6-22a574a688fa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624289/tapavis_tenant_sda_auto_service/transmission_281df50e-8273-4f4b-bea9-d8fff7dd565c.png"
  }
};
