/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_robert_boissonneault_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813308/tapavis_tenant_garage_robert_boissonneault_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813308/tapavis_tenant_garage_robert_boissonneault_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813323/tapavis_tenant_garage_robert_boissonneault_inc/hero_ba1018bf-db6f-4111-883c-ef66ba7a8979.png",
  "services": {
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813326/tapavis_tenant_garage_robert_boissonneault_inc/mecanique-generale_a73a2580-a04b-4b50-8a19-e7dbf3c7c474.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813325/tapavis_tenant_garage_robert_boissonneault_inc/freins_e13092fc-1959-485b-be90-8172c645803d.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813327/tapavis_tenant_garage_robert_boissonneault_inc/vidange-huile_8d7de292-870e-474a-b069-b92fa203f318.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813339/tapavis_tenant_garage_robert_boissonneault_inc/suspension_424d86bb-7a53-4fca-b632-dc37f9e492a8.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813339/tapavis_tenant_garage_robert_boissonneault_inc/equilibrage-rotation-pneus_7dbadbe6-8293-4402-bafc-3840cf5deaa0.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813340/tapavis_tenant_garage_robert_boissonneault_inc/silencieux_2276e644-909a-44c7-88b8-fc511b1008ad.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813340/tapavis_tenant_garage_robert_boissonneault_inc/systeme-de-refroidissement_da01d270-1f92-4847-9b8d-8f0ecae341ab.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813354/tapavis_tenant_garage_robert_boissonneault_inc/mise-au-point_67a4b975-8284-4fdf-a8f7-7f2430c03cfc.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813355/tapavis_tenant_garage_robert_boissonneault_inc/climatisation_624f6352-c03b-4ea0-980b-3c258a20f5ea.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813355/tapavis_tenant_garage_robert_boissonneault_inc/transmission_5fe49b37-3645-4c64-86ba-1cce248b246d.png"
  }
};
