/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_otto_pucher_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791049251/tapavis_tenant_otto_pucher_inc/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791049251/tapavis_tenant_otto_pucher_inc/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791050675/tapavis_tenant_otto_pucher_inc/hero_0592d020-2f86-42dd-933d-a25b1fbd0d19.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791049266/tapavis_tenant_otto_pucher_inc/vidange-huile_66eba107-5c25-4627-9922-8bc7d3f21565.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791049267/tapavis_tenant_otto_pucher_inc/mecanique-generale_0cd7b77b-47af-4973-99d4-5bf45b7a3397.webp",
    "freins": "https://media.liasse.tech/upload/v1791049268/tapavis_tenant_otto_pucher_inc/freins_128c76c2-1878-405b-80ff-727409ca2be8.webp",
    "suspension": "https://media.liasse.tech/upload/v1791049277/tapavis_tenant_otto_pucher_inc/suspension_37a3b7ee-2dec-49fe-9cae-b735a1cfe026.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791049277/tapavis_tenant_otto_pucher_inc/equilibrage-rotation-pneus_b92199f5-70a0-4029-939a-e786b848cb99.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791049278/tapavis_tenant_otto_pucher_inc/silencieux_399fcd9b-52b6-4cec-96cd-b99e108eff83.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791049280/tapavis_tenant_otto_pucher_inc/systeme-de-refroidissement_68f880b8-abcd-41fe-9163-25c2bf5fa75e.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791049288/tapavis_tenant_otto_pucher_inc/climatisation_4301fe63-6bfa-48c7-a84f-85295b0157f3.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791049289/tapavis_tenant_otto_pucher_inc/mise-au-point_d83002e9-5fe6-48a2-a294-94698e874687.webp",
    "transmission": "https://media.liasse.tech/upload/v1791049291/tapavis_tenant_otto_pucher_inc/transmission_5449bb07-5f71-46b4-8eb9-122ec5f99717.webp"
  }
};
