module.exports = async function(db) {
  const settings = [
    ['business_name', 'André Auger Plomberie'],
    ['contact_email', 'andreaugerplomberie@liasse.tech'],
    ['hours_text_fr', 'Lun–Ven: 7h–18h | Sam: 9h–15h | Dim: urgences seulement'],
    ['hours_text_en', 'Mon–Fri: 7am–6pm | Sat: 9am–3pm | Sun: emergencies only'],
    ['about_text_fr', '<p><strong>André Auger Plomberie</strong> est un service de plomberie de confiance, fondé sur trois principes simples: <em>la transparence des prix</em>, <em>la rapidité d\'intervention</em>, et <em>un travail bien fait du premier coup</em>.</p><p>Trop souvent, faire venir un plombier signifie ne pas savoir ce qu\'on va payer avant que la facture arrive. Chez nous, c\'est différent. <strong>Tous nos tarifs sont publiés sur le site</strong>: vous savez exactement à quoi vous attendre avant même de réserver.</p><p>Notre calendrier est synchronisé en temps réel. Choisissez un créneau qui vous convient, et nous serons là. Pour les urgences, nous sommes disponibles 24/7.</p><p>Plombier certifié, assuré, et reconnu par la <strong>CMMTQ</strong>. Travail garanti.</p>'],
    ['about_text_en', '<p><strong>André Auger Plomberie</strong> is a trusted plumbing service, built on three simple principles: <em>transparent pricing</em>, <em>fast response</em>, and <em>doing the job right the first time</em>.</p><p>Too often, calling a plumber means not knowing what you will pay until the bill arrives. We do things differently. <strong>All our rates are published on the website</strong>: you know exactly what to expect before you even book.</p><p>Our schedule is synced in real time. Pick a slot that works for you, and we will be there. For emergencies, we are available 24/7.</p><p>Certified, insured plumber, recognized by the <strong>CMMTQ</strong>. Work is guaranteed.</p>']
  ];
  for (let i=0; i<settings.length; i++) {
    await db.run("INSERT INTO admin_settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING", [settings[i][0], settings[i][1]]);
  }
  await db.run("INSERT INTO admin_settings (key, value, updated_at) VALUES ('_p_hero_image_url', 'https://res.cloudinary.com/duhp69meg/image/upload/v1778695827/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695827179.png', NOW()) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()");
  await db.run("INSERT INTO admin_settings (key, value, updated_at) VALUES ('about_image_url', 'https://res.cloudinary.com/duhp69meg/image/upload/v1778695822/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695822550.png', NOW()) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()");

  const svcs = [
    ['Réparation de fuite','Leak repair','Diagnostic et réparation de fuites sous évier, lavabo, douche, baignoire ou tuyauterie apparente. Inclut le diagnostic initial, le serrage ou remplacement du raccord défectueux, et un test d\'étanchéité avant départ.','Diagnosis and repair of leaks under sinks, lavatories, showers, tubs, or visible piping. Includes initial diagnosis, tightening or replacement of the faulty fitting, and a leak test before leaving.','https://res.cloudinary.com/duhp69meg/image/upload/v1778695832/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695832607.png','Urgence',95,250,'fixe',60,1],
    ['Débouchage de drains','Drain unclogging','Débouchage de drains, lavabos, baignoires et toilettes. Selon le cas, nous utilisons une furet manuel, électrique, ou de l\'hydropression. Diagnostic caméra disponible si nécessaire.','Unclogging of drains, sinks, tubs, and toilets. Depending on the case, we use manual or electric augers, or hydro-jetting. Camera diagnosis available if needed.','https://res.cloudinary.com/duhp69meg/image/upload/v1778695834/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695834786.png','Urgence',120,350,'fixe',90,1],
    ['Installation de chauffe-eau','Water heater installation','Installation complète d\'un chauffe-eau standard (40 ou 60 gallons) ou sans réservoir, incluant le retrait de l\'ancien appareil, la mise aux normes, et la mise en marche.','Complete installation of a standard water heater (40 or 60 gallons) or tankless, including removal of the old unit, code compliance, and startup.','https://res.cloudinary.com/duhp69meg/image/upload/v1778695816/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695816246.png','Installation',350,950,'fixe',180,1],
    ['Rénovation salle de bain','Bathroom renovation','Plomberie complète pour rénovation de salle de bain: déplacement de tuyauterie, installation de bain ou douche, toilette, lavabo, robinetterie. Estimation gratuite sur place.','Full bathroom renovation plumbing: pipe relocation, tub or shower installation, toilet, sink, faucets. Free on-site estimate.','https://res.cloudinary.com/duhp69meg/image/upload/v1778695822/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695822834.png','Installation',800,3500,'sur estimation',480,0],
    ['Inspection caméra de drain','Drain camera inspection','Inspection vidéo de votre tuyauterie pour détecter racines, fissures, affaissements ou obstructions — sans démolition. Vous recevez la vidéo par courriel.','Video inspection of your piping to detect roots, cracks, sagging, or obstructions — without demolition. You receive the video by email.',null,'Diagnostic',150,250,'fixe',60,0],
    ['Entretien préventif annuel','Annual preventive maintenance','Visite annuelle: vérification de pression d\'eau, du chauffe-eau (anode, soupape), des drains, des toilettes (chasse, joints), et des robinets. Petits ajustements et conseils inclus.','Annual visit: water pressure check, water heater (anode, valve), drains, toilets (flush, seals), and faucets. Minor adjustments and advice included.',null,'Entretien',175,null,'fixe',120,0],
    ['Urgence 24/7','Emergency 24/7','Service d\'urgence en tout temps — fuite majeure, dégât d\'eau, refoulement, gel de tuyaux. Tarif horaire; majoration soirs et fins de semaine.','Emergency service anytime — major leak, water damage, backup, frozen pipes. Hourly rate; surcharge evenings and weekends.',null,'Urgence',145,null,'horaire',60,1],
    ['Installation de toilette','Toilet installation','Remplacement complet d\'une toilette: retrait de l\'ancienne, installation du nouveau modèle, scellement à la cire, raccordement et test. Disposition de l\'ancienne incluse.','Complete toilet replacement: removal of old toilet, installation of the new model, wax sealing, connection, and test. Disposal of old unit included.',null,'Installation',275,475,'fixe',90,0]
  ];
  for (let i=0; i<svcs.length; i++) {
    const s = svcs[i];
    await db.run("INSERT INTO services (name, name_en, description, description_en, image_url, category, price_min, price_max, price_unit, duration_min, featured, published) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,1)", s);
  }

  const tests = [
    ['Marie Tremblay','Québec','Service rapide et professionnel. André est arrivé en moins de 2 heures pour une fuite urgente et le prix était exactement comme annoncé sur le site. Très transparent, je recommande!',5],
    ['Jean-François Bouchard','Lévis','Excellent travail pour l\'installation de notre nouveau chauffe-eau. Propre, ponctuel, et tout fonctionne parfaitement depuis 6 mois.',5],
    ['Sophie Lavoie','Sainte-Foy','J\'ai apprécié de pouvoir voir les prix avant même d\'appeler. Pas de surprise sur la facture finale, et le service a été impeccable.',5],
    ['Pierre Gagné','Charlesbourg','Drain bouché un samedi matin, ils sont venus le jour même. Prix raisonnable et conseils utiles pour éviter que ça se reproduise.',5],
    ['Linda Robitaille','Beauport','Rénovation complète de notre salle de bain. Très satisfaite du résultat et du suivi tout au long du projet. Travail de qualité.',5],
    ['Marc-André Côté','Limoilou','La prise de rendez-vous en ligne est super pratique — j\'ai choisi mon créneau en 30 secondes. Service à la clientèle excellent.',5]
  ];
  for (let i=0; i<tests.length; i++) {
    await db.run("INSERT INTO testimonials (author, location, content, rating, published) VALUES ($1,$2,$3,$4,1)", tests[i]);
  }

  const posts = [
    ['Comment éviter les fuites en hiver','How to prevent winter leaks','En hiver, les tuyaux exposés au froid peuvent geler, se dilater et éclater — causant des dégâts d\'eau majeurs. Voici nos meilleurs conseils:\n\n1. Isolez vos tuyaux exposés (sous-sol non chauffé, vide sanitaire, garage). Des manchons en mousse coûtent quelques dollars et durent des années.\n2. Maintenez le chauffage à au moins 13°C même en cas d\'absence prolongée.\n3. Lors d\'un grand froid (-25°C ou moins), laissez un mince filet d\'eau couler des robinets les plus exposés. L\'eau qui coule gèle beaucoup moins facilement.\n4. Repérez la valve de coupure principale et apprenez à la fermer rapidement en cas d\'urgence.\n\nSi un tuyau a déjà gelé sans éclater, ne le réchauffez jamais avec une flamme nue. Appelez-nous!','In winter, exposed pipes can freeze, expand, and burst — causing major water damage. Here are our best tips:\n\n1. Insulate exposed pipes (unheated basement, crawlspace, garage). Foam sleeves cost a few dollars and last for years.\n2. Keep heating at at least 13°C even during extended absences.\n3. During extreme cold (-25°C or lower), let a thin trickle of water run from the most exposed faucets. Running water freezes much less easily.\n4. Locate the main shutoff valve and learn how to close it quickly in case of emergency.\n\nIf a pipe has already frozen without bursting, never warm it with an open flame. Call us!','https://res.cloudinary.com/duhp69meg/image/upload/v1778695829/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695829575.png','Conseils'],
    ['Signes que votre chauffe-eau doit être remplacé','Signs your water heater needs replacing','Un chauffe-eau dure en moyenne 8 à 12 ans. Voici les signes qui indiquent qu\'il est temps de le remplacer:\n\n• Eau brune ou rouille à la sortie du robinet d\'eau chaude (mais pas froide)\n• Sons étranges venant du réservoir (grondements, claquements)\n• Eau tiède ou jamais assez chaude, même au max\n• Fuite à la base de l\'appareil — c\'est presque toujours irréparable\n• Plus de 10-12 ans d\'âge (vérifiez l\'étiquette du fabricant)\n\nUn chauffe-eau qui lâche peut causer des milliers de dollars de dégâts. Mieux vaut prévenir!','A water heater lasts on average 8-12 years. Here are the signs it\'s time to replace it:\n\n• Brown or rusty water from the hot tap (but not cold)\n• Strange sounds from the tank (rumbling, banging)\n• Lukewarm water, never hot enough, even at max\n• Leak at the base of the unit — almost always unrepairable\n• Over 10-12 years old (check manufacturer label)\n\nA failing water heater can cause thousands in damage. Better safe than sorry!','https://res.cloudinary.com/duhp69meg/image/upload/v1778695831/tapavis_tenant_andre-auger-plomberie/build_andre-auger-plomberie_1778695831620.png','Conseils'],
    ['Pourquoi nous publions nos prix','Why we publish our prices','La transparence est au cœur de notre service. Nous croyons fermement que les clients méritent de savoir combien ils vont payer AVANT que le plombier sonne à leur porte.\n\nCela élimine le stress, les négociations gênantes, et les mauvaises surprises sur la facture. Nos prix sont calculés pour être justes pour vous comme pour nous: pas de gonflage, pas de frais cachés.\n\nC\'est aussi pourquoi nous prenons les rendez-vous en ligne — vous choisissez votre créneau, vous voyez le prix, vous réservez. Simple.','Transparency is at the heart of our service. We firmly believe customers deserve to know how much they\'ll pay BEFORE the plumber rings their doorbell.\n\nIt eliminates stress, awkward negotiations, and nasty surprises on the bill. Our prices are calculated to be fair for you and for us: no inflation, no hidden fees.\n\nThat\'s also why we take bookings online — you pick your slot, see the price, and book. Simple.',null,'Nouvelles'],
    ['Urgences plomberie : quand appeler?','Plumbing emergencies: when to call?','Toutes les situations ne sont pas des vraies urgences. Voici comment reconnaître les cas qui justifient un appel immédiat (et donc un tarif d\'urgence):\n\n✓ Fuite active qui ne s\'arrête pas, même en fermant le robinet local\n✓ Refoulement d\'égout dans le sous-sol ou la toilette\n✓ Tuyau gelé qui menace d\'éclater\n✓ Chauffe-eau qui fuit à la base\n\nPour ces cas, fermez immédiatement la valve principale d\'eau de la maison, puis appelez-nous.\n\nCe qui peut attendre le lendemain matin:\n• Robinet qui goutte\n• Toilette qui fait du bruit après chasse\n• Drain qui s\'écoule lentement\n\nDans le doute, appelez — nous vous dirons honnêtement si c\'est une vraie urgence.','Not all situations are real emergencies. Here\'s how to recognize cases that justify an immediate call (and therefore an emergency rate):\n\n✓ Active leak that won\'t stop, even when closing the local valve\n✓ Sewer backup in basement or toilet\n✓ Frozen pipe threatening to burst\n✓ Water heater leaking at the base\n\nFor these cases, immediately close the main water valve, then call us.\n\nWhat can wait until morning:\n• Dripping faucet\n• Toilet that makes noise after flush\n• Slow-draining sink\n\nWhen in doubt, call — we\'ll honestly tell you if it\'s a real emergency.',null,'Conseils']
  ];
  for (let i=0; i<posts.length; i++) {
    await db.run("INSERT INTO posts (title, title_en, content, content_en, image_url, category, published) VALUES ($1,$2,$3,$4,$5,$6,1)", posts[i]);
  }

  const today = new Date();
  for (let i = 1; i <= 21; i++) {
    const d = new Date(today);
    d.setDate(d.getDate() + i);
    const day = d.getDay();
    if (day === 0) continue;
    const dateStr = d.toISOString().slice(0,10);
    const times = (day === 6) ? ['09:00','10:30','12:00','13:30'] : ['08:00','09:30','11:00','13:00','14:30','16:00'];
    for (let j=0; j<times.length; j++) {
      try {
        await db.run("INSERT INTO availability_slots (slot_date, slot_time, duration_min, booked) VALUES ($1,$2,60,0)", [dateStr, times[j]]);
      } catch(e) {}
    }
  }
};
