/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_saint_jacques_le_mineur).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739641/tapavis_tenant_garage_saint_jacques_le_mineur/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739641/tapavis_tenant_garage_saint_jacques_le_mineur/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790742083/tapavis_tenant_garage_saint_jacques_le_mineur/hero_d859e939-a477-4a49-a317-35c64b28d66f.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739651/tapavis_tenant_garage_saint_jacques_le_mineur/freins_cfed74f1-9216-4d71-9326-f9feb3c58c13.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739651/tapavis_tenant_garage_saint_jacques_le_mineur/vidange-huile_b5149cb1-d966-4626-bff6-269230675cbb.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739654/tapavis_tenant_garage_saint_jacques_le_mineur/mecanique-generale_69babced-a017-44c8-8818-74c3dc33475e.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739662/tapavis_tenant_garage_saint_jacques_le_mineur/equilibrage-rotation-pneus_54d6b335-ebe6-4f25-8445-bf3eb3ab7000.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739662/tapavis_tenant_garage_saint_jacques_le_mineur/suspension_e42f6900-5692-4a36-8909-bdcd7b119756.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739662/tapavis_tenant_garage_saint_jacques_le_mineur/silencieux_7075480a-df3e-47ff-8319-0762a5f2bdbf.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739665/tapavis_tenant_garage_saint_jacques_le_mineur/systeme-de-refroidissement_ae4df25c-e27a-4626-8688-6962fa85919d.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739672/tapavis_tenant_garage_saint_jacques_le_mineur/mise-au-point_42b72bc0-6ca2-4c2d-976e-5da379bac714.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739674/tapavis_tenant_garage_saint_jacques_le_mineur/climatisation_2195a03c-ed89-4f36-8d40-af68e6b537b4.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739675/tapavis_tenant_garage_saint_jacques_le_mineur/transmission_e21518bd-2ed5-40c3-a28f-652854cf013b.png"
  }
};
