/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_beauchemin_garage_mecanique_55).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668685/tapavis_tenant_beauchemin_garage_mecanique_55/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668685/tapavis_tenant_beauchemin_garage_mecanique_55/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668696/tapavis_tenant_beauchemin_garage_mecanique_55/hero_f093bf5e-564c-4bec-8d14-884bb03dc56e.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668698/tapavis_tenant_beauchemin_garage_mecanique_55/freins_a0885615-e803-4e7a-a1d8-6418c07215cb.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668699/tapavis_tenant_beauchemin_garage_mecanique_55/vidange-huile_61c2a97b-9817-4e16-b7ea-1b87201fa690.png",
    "diagnostic-electronique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668699/tapavis_tenant_beauchemin_garage_mecanique_55/diagnostic-electronique_a54f35db-9edd-4394-bcea-23f8f5f8e4b8.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668708/tapavis_tenant_beauchemin_garage_mecanique_55/alignement_dd121bf6-fd18-4918-8413-9862532cc306.png",
    "pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668711/tapavis_tenant_beauchemin_garage_mecanique_55/pneus_cb2d8efa-7baa-4b10-89ed-a7802d918c51.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668710/tapavis_tenant_beauchemin_garage_mecanique_55/suspension_ea77e9a5-aa74-4e87-aec0-6aa5f88d4ea6.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668711/tapavis_tenant_beauchemin_garage_mecanique_55/systeme-electrique_8ecd96ac-de59-450b-bbfb-cbb12b6395df.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668722/tapavis_tenant_beauchemin_garage_mecanique_55/silencieux_90941ba0-e150-4b13-83a7-0bd4574cbd29.png"
  }
};
