/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_autos_mecanique_js).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734127/tapavis_tenant_autos_mecanique_js/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734127/tapavis_tenant_autos_mecanique_js/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734138/tapavis_tenant_autos_mecanique_js/hero_a5312220-cb44-40f6-92d9-c038fdbae531.png",
  "services": {
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734139/tapavis_tenant_autos_mecanique_js/mecanique-generale_3c1dace3-dad8-4719-84a5-836c5fa07720.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734140/tapavis_tenant_autos_mecanique_js/vidange-huile_1ba795f0-e6a6-482c-ae7c-1ead1713409d.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734140/tapavis_tenant_autos_mecanique_js/freins_86a37410-7014-477a-9605-45262208e2c7.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734150/tapavis_tenant_autos_mecanique_js/equilibrage-rotation-pneus_c64c1a8c-66ab-4881-b3eb-396d84b3bb3b.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734150/tapavis_tenant_autos_mecanique_js/silencieux_a065fde4-d7be-4d11-b8ac-e4cd01995e12.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734153/tapavis_tenant_autos_mecanique_js/suspension_04f5f826-c155-4e44-a57b-afe54da901a3.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734153/tapavis_tenant_autos_mecanique_js/systeme-de-refroidissement_7f7334f2-7009-45bc-a8f4-d755dd0ebf2d.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734161/tapavis_tenant_autos_mecanique_js/climatisation_fa5d0a6a-14c9-4a44-bc40-ee8ae1074dd6.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734162/tapavis_tenant_autos_mecanique_js/mise-au-point_86426219-1dd5-47d4-a3d4-63500587591b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790734165/tapavis_tenant_autos_mecanique_js/transmission_9a777867-811d-4d54-960c-8d56cb502e7f.png"
  }
};
