/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_enterprises_mecaniques).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625584/tapavis_tenant_enterprises_mecaniques/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625584/tapavis_tenant_enterprises_mecaniques/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625596/tapavis_tenant_enterprises_mecaniques/hero_1373cfe2-8feb-489b-914b-3cf039fdb484.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625594/tapavis_tenant_enterprises_mecaniques/freins_dd71fa90-5c56-48f7-8bec-df3de6014c11.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625594/tapavis_tenant_enterprises_mecaniques/vidange-huile_fc5c44cf-65b5-44bb-8c53-4bc0c194e72d.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625596/tapavis_tenant_enterprises_mecaniques/mecanique-generale_171f829e-23dc-49ae-b20f-5df351a6c24d.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625605/tapavis_tenant_enterprises_mecaniques/equilibrage-rotation-pneus_90a0fb00-5234-4aa0-9551-ae196ec8de2a.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625606/tapavis_tenant_enterprises_mecaniques/silencieux_39c4a25b-ac28-48bf-9270-7e69058c5443.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625606/tapavis_tenant_enterprises_mecaniques/suspension_d41ceefc-cd8d-4050-b8f4-66d97b11e2bb.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625614/tapavis_tenant_enterprises_mecaniques/systeme-de-refroidissement_f1bd45c8-e26e-4c11-bd1d-69947e3542d9.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625616/tapavis_tenant_enterprises_mecaniques/mise-au-point_1b037338-103f-4d0e-b9e7-bb12089035d6.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625617/tapavis_tenant_enterprises_mecaniques/climatisation_3e299546-cecc-4aac-b74d-a3899b23f6b7.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790625619/tapavis_tenant_enterprises_mecaniques/transmission_fc3e8c9d-eaef-4408-be73-294896749c57.png"
  }
};
