/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_micca_auto).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668104/tapavis_tenant_micca_auto/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668104/tapavis_tenant_micca_auto/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668116/tapavis_tenant_micca_auto/hero_ae2771e8-fce3-40b3-be4d-f2af80693a6e.png",
  "services": {
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668116/tapavis_tenant_micca_auto/vidange-huile_e27c7003-6954-4b57-9660-6f3413ecd66e.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668117/tapavis_tenant_micca_auto/mecanique-generale_1231984f-4f94-493c-9509-3b047f93be96.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668117/tapavis_tenant_micca_auto/freins_b7e2555d-9a72-4d8d-9286-ca91eab9a0a3.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668126/tapavis_tenant_micca_auto/equilibrage-rotation-pneus_97f9c93c-f02e-4bd7-848f-035219157634.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668127/tapavis_tenant_micca_auto/silencieux_a5608a01-e3f7-4058-8248-b50e59d06fc9.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668128/tapavis_tenant_micca_auto/suspension_7c87972e-330e-4d55-bb45-3644e0ae0be4.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668129/tapavis_tenant_micca_auto/systeme-de-refroidissement_9b7cbf74-d317-4cc9-8102-b934f3251d74.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668138/tapavis_tenant_micca_auto/mise-au-point_262c6262-1699-45dd-997e-f21303a77d6f.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668139/tapavis_tenant_micca_auto/climatisation_3a630bf8-f799-4715-9c01-a01dea0d3e46.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790668143/tapavis_tenant_micca_auto/transmission_7885f69e-6702-4220-9248-97f7e26efcbf.png"
  }
};
