const S=require('./lib/settings');const T=require('./lib/i18n');const getModules=require('./lib/modules');const A=require('./lib/admin');const B=require('./lib/appointments');const makePayPal=require('./lib/paypal');
module.exports=function(services){const express=require('express');const router=express.Router();const store=S(services),paypal=makePayPal(services);router.use(express.json({limit:'7mb'}));router.use(express.urlencoded({extended:false,limit:'30kb'}));
function fail(req,res,e){const code=e.code==='23P01'?'overlap':e.code==='23505'?'conflict':e.status?e.code:'server_error';const status=e.code==='23P01'||e.code==='23505'?409:e.status||500;const t=res.locals.t||T.fr;if(req.path.startsWith('/api/'))return res.status(status).json({error:(t[code]||t.server_error)+(e.detail?' ('+e.detail+')':''),code});return res.status(status).render('error',{page:'error',errorText:t[code]||t.server_error});}
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res,next);}catch(e){fail(req,res,e);}};
router.use(wrap(async(req,res,next)=>{const q=req.query.lang;let lang=q==='en'||q==='fr'?q:req.path.startsWith('/en')?'en':(req.cookies&&req.cookies.pwa_lang==='en'?'en':'fr');if(q==='en'||q==='fr')res.cookie('pwa_lang',lang,{maxAge:365*86400000,path:req.tenantPath?req.tenantPath('/'):req.baseUrl+'/',sameSite:'lax',secure:true});req.lang=lang;res.locals.lang=lang;res.locals.t={...T[lang]};res.locals.settings={};res.locals.hours=[];res.locals.urls=S.urls(lang);res.locals.page='index';res.locals.user=null;res.locals.tenantRoot=req.tenantPath('/');res.locals.flags={};res.locals.langLinks={fr:'.?lang=fr',en:'en/?lang=en'};res.locals.safeJSON=S.safeJSON;res.locals.money=v=>S.money(v,lang);res.locals.formatDate=v=>S.date(v,lang);res.locals.field=(row,key)=>lang==='en'&&row[key+'_en']?row[key+'_en']:row[key]||'';res.locals.column=(row,key)=>lang==='en'&&row[key+'_en']?key+'_en':key;req.isPreview=!!(services.config.isPreview||services.config.preview||req.query.preview==='1');const raw=await store.load();req.site=raw;res.locals.settings=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,S.localized(v,lang)]));res.locals.t=S.translate(raw,lang);res.locals.flags={contact:S.flag(raw,'contact_verified'),address:S.flag(raw,'address_verified'),hours:S.flag(raw,'hours_verified'),requests:S.flag(raw,'requests_enabled')&&S.flag(raw,'privacy_approved')&&S.both(raw.privacy_notice),privacy:S.flag(raw,'privacy_approved'),operations:S.flag(raw,'live_actions_enabled')};res.locals.phoneHref='tel:'+String(raw.contact_phone||'').replace(/[^+\d]/g,'');res.locals.emailHref='mailto:'+String(raw.contact_email||'').replace(/[\r\n]/g,'');res.locals.directionsHref='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(raw.business_address||'');res.locals.hours=await services.db.all('SELECT * FROM hours ORDER BY weekday');if(req.path.startsWith('/api/')||req.path.startsWith('/admin')||req.path.includes('rendez-vous')||req.path.includes('appointments'))res.set('Cache-Control','private, no-store');next();}));
router.use(wrap(async(req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api')&&!req.path.startsWith('/admin')&&!req.path.includes('.')){try{await services.db.run('INSERT INTO site_visits(path) VALUES($1)',[req.path]);}catch(e){}}next();}));
router.use((req,res,next)=>{if(['POST','PUT','PATCH','DELETE'].includes(req.method)){if(req.get('X-Requested-With')!=='liasse')return res.status(403).json({error:res.locals.t.forbidden});const origin=req.get('origin');if(origin){try{if(new URL(origin).host!==req.get('host'))return res.status(403).json({error:res.locals.t.forbidden});}catch(e){return res.status(403).json({error:res.locals.t.forbidden});}}next();}});
function languageLinks(req,res,key,id){const query=new URLSearchParams();for(const k of ['q','category','page'])if(req.query[k])query.set(k,String(req.query[k]));const links={};for(const lang of ['fr','en']){query.set('lang',lang);const u=S.urls(lang);links[lang]=(key==='payment'?u.payment+id:u[key])+'?'+query.toString();}res.locals.langLinks=links;}
function page(paths,key,view,load){router.get(paths,services.auth.optionalAuth,wrap(async(req,res)=>{res.locals.user=req.user||null;res.locals.page=key;languageLinks(req,res,key,req.params.id);res.render(view,Object.assign({page:key},load?await load(req,res):{}));}));}
page(['/','/en/'],'home','index',async()=>({items:await services.db.all('SELECT * FROM services WHERE published=1 ORDER BY sort_order,id LIMIT 4')}));
page(['/services/','/en/services/'],'services','services',async(req)=>{const q=String(req.query.q||'').slice(0,100),category=['massage','ayurveda','yoga','meditation'].includes(req.query.category)?req.query.category:'';const params=['%'+q+'%',category];const where="published=1 AND (name ILIKE $1 OR name_en ILIKE $1 OR description ILIKE $1 OR description_en ILIKE $1) AND ($2='' OR category=$2)";const total=Number((await services.db.get('SELECT COUNT(*) AS n FROM services WHERE '+where,params)).n),pages=Math.max(1,Math.ceil(total/10)),current=Math.max(1,Math.min(pages,parseInt(req.query.page,10)||1));const items=await services.db.all('SELECT * FROM services WHERE '+where+' ORDER BY sort_order,id LIMIT 10 OFFSET $3',[...params,(current-1)*10]);return {items,q,category,current,pages,total};});
page(['/a-propos/','/en/about/'],'about','about');page(['/contact/','/en/contact/'],'contact','contact');page(['/confidentialite/','/en/privacy/'],'privacy','privacy');
page(['/rendez-vous/','/en/appointments/'],'appointments','appointments',async()=>({items:await services.db.all('SELECT id,name,name_en FROM services WHERE published=1 ORDER BY sort_order,id'),today:S.today()}));
page(['/rendez-vous/paiement/:id','/en/appointments/payment/:id'],'payment','payment',async req=>{if(!/^\d+$/.test(req.params.id))throw S.error('not_found',404);return {bookingId:Number(req.params.id)};});
router.get(['/514-885-4316','/services/514-885-4316','/a-propos/514-885-4316','/contact/514-885-4316'],(req,res)=>res.redirect(301,req.tenantPath('/contact/')));
router.get('/api/appointments',services.auth.requireAuth,wrap(async(req,res)=>{const current=Math.max(1,parseInt(req.query.page,10)||1),total=Number((await services.db.get('SELECT COUNT(*) AS n FROM appointments WHERE user_id=$1',[String(req.user.id)])).n);const rows=await services.db.all('SELECT * FROM appointments WHERE user_id=$1 ORDER BY created_at DESC LIMIT 10 OFFSET $2',[String(req.user.id),(current-1)*10]);res.json({appointments:rows.map(x=>B.publicRow(x,req.lang)),total,page:current,pages:Math.max(1,Math.ceil(total/10))});}));
router.post('/api/appointments',services.auth.requireAuth,wrap(async(req,res)=>{const row=await B.create(services,req,req.site);res.status(201).json({appointment:B.publicRow(row,req.lang),message:res.locals.t.sent});}));
async function own(req){if(!/^\d+$/.test(req.params.id))throw S.error('not_found',404);const b=await services.db.get('SELECT * FROM appointments WHERE id=$1 AND user_id=$2',[Number(req.params.id),String(req.user.id)]);if(!b)throw S.error('not_found',404);return b;}
router.get('/api/appointments/:id',services.auth.requireAuth,wrap(async(req,res)=>{const b=await own(req);res.json({appointment:B.publicRow(b,req.lang),paypal:paypal.publicConfig(b,req.site,req.isPreview)});}));
router.post('/api/appointments/:id/cancel',services.auth.requireAuth,wrap(async(req,res)=>{const b=await own(req);if(!['requested','confirmed'].includes(b.status))throw S.error('conflict',409);if(b.status==='requested'&&!b.order_key)await services.db.run("UPDATE appointments SET status='cancelled',updated_at=NOW() WHERE id=$1 AND status='requested' AND order_key IS NULL",[b.id]);else await services.db.run('UPDATE appointments SET cancel_requested=1,updated_at=NOW() WHERE id=$1',[b.id]);res.json({message:res.locals.t.cancel_sent});}));
router.post('/api/appointments/:id/paypal/order',services.auth.requireAuth,wrap(async(req,res)=>res.json(await paypal.create(await own(req),req.site,req.isPreview,req.body))));
router.post('/api/appointments/:id/paypal/capture',services.auth.requireAuth,wrap(async(req,res)=>res.json({appointment:B.publicRow(await paypal.capture(await own(req),req.site,req.isPreview,req.body),req.lang)})));
router.post('/api/appointments/:id/paypal/sync',services.auth.requireAuth,wrap(async(req,res)=>{if(!paypal.enabled(req.site,req.isPreview))throw S.error('pay_unavailable',503);const b=await own(req);if(b.checked_at&&Date.now()-new Date(b.checked_at).getTime()<8000)throw S.error('rate_limit',429);res.json({appointment:B.publicRow(await paypal.sync(b),req.lang)});}));
function requireAdmin(req,res,next){if(!services.admin.isAdmin(req))return res.status(403).json({error:res.locals.t.forbidden});next();}
router.use('/api/admin',requireAdmin);
router.get('/api/admin/modules',(req,res)=>res.json(getModules(req.lang)));
router.get('/api/admin/stats',wrap(async(req,res)=>res.json(await A.stats(services,getModules(req.lang).modules))));
router.get('/api/admin/submissions',wrap(async(req,res)=>res.json({submissions:await services.db.all('SELECT * FROM appointments ORDER BY created_at DESC')})));
router.get('/api/admin/settings',wrap(async(req,res)=>res.json({settings:await store.load()})));
router.put('/api/admin/settings',wrap(async(req,res)=>{const key=String(req.body.key||''),value=String(req.body.value==null?'':req.body.value);if(!/^[a-zA-Z0-9_:-]{1,100}$/.test(key)||key.startsWith('_seed')||value.length>20000)throw S.error('invalid');if(key.endsWith('_url')&&!A.imageOK(value))throw S.error('invalid');const booleans=getModules(req.lang).settingsFields.map(x=>x.name);if(booleans.includes(key)&&!['0','1'].includes(value))throw S.error('invalid');if(key==='privacy_approved'&&value==='1'&&!S.both(req.site.privacy_notice))throw S.error('required');if(key==='payment_terms_approved'&&value==='1'&&!S.both(req.site.payment_terms))throw S.error('required');if(key==='contact_email'&&value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw S.error('invalid');if(key==='contact_phone'&&value&&!/^[+()\d .-]{7,40}$/.test(value))throw S.error('invalid');await services.db.run('INSERT INTO admin_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()',[key,value]);res.json({success:true});}));
router.post('/api/admin/upload',wrap(async(req,res)=>{if(req.isPreview||!S.flag(req.site,'live_actions_enabled'))throw S.error('operation_disabled',409);const image=String(req.body.image||'');if(!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(image)||image.length>6000000)throw S.error('invalid');if(!services.cloudinary||!services.cloudinary.uploader||typeof services.cloudinary.uploader.upload!=='function')throw S.error('image_error',503);try{const result=await services.cloudinary.uploader.upload(image,{folder:services.config.slug+'/content',resource_type:'image'});res.json({imageUrl:result.secure_url});}catch(e){throw S.error('image_error',502);}}));
router.post('/api/admin/generate-image',wrap(async(req,res)=>{if(req.isPreview||!S.flag(req.site,'live_actions_enabled'))throw S.error('operation_disabled',409);const prompt=String(req.body.prompt||'').trim();if(prompt.length<12||prompt.length>1800)throw S.error('invalid');try{const imageUrl=await services.ai.generateImage(prompt+' No text overlays. Clearly illustrative, not a documentary photograph of this business.',{aspectRatio:['1:1','4:3','16:9','4:5'].includes(req.body.aspectRatio)?req.body.aspectRatio:'4:3'});res.json({imageUrl});}catch(e){throw S.error('image_error',502);}}));
router.post('/api/admin/appointments/:id/reconcile',wrap(async(req,res)=>{if(!paypal.enabled(req.site,req.isPreview))throw S.error('pay_unavailable',503);const b=await services.db.get('SELECT * FROM appointments WHERE id=$1',[Number(req.params.id)]);if(!b)throw S.error('not_found',404);res.json({appointment:await paypal.sync(b)});}));
for(const base of getModules('fr').modules){const key=base.key;router.get('/api/admin/'+key,wrap(async(req,res)=>res.json({[key]:await services.db.all('SELECT * FROM '+key+' ORDER BY id DESC')})));router.post('/api/admin/'+key,wrap(async(req,res)=>{const m=getModules(req.lang).modules.find(x=>x.key===key);const row=key==='appointments'?await B.adminSave(services,m,req.body,null,req.site):await A.save(services.db,m,req.body,null);res.status(201).json({[m.singular]:row});}));router.put('/api/admin/'+key+'/:id',wrap(async(req,res)=>{if(!/^\d+$/.test(req.params.id))throw S.error('invalid');const m=getModules(req.lang).modules.find(x=>x.key===key);const row=key==='appointments'?await B.adminSave(services,m,req.body,Number(req.params.id),req.site):await A.save(services.db,m,req.body,Number(req.params.id));res.json({[m.singular]:row});}));router.delete('/api/admin/'+key+'/:id',wrap(async(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id))throw S.error('invalid');let row;if(key==='appointments'){const b=await services.db.get('SELECT * FROM appointments WHERE id=$1',[id]);if(b&&b.order_key)throw S.error('billing_locked',409);row=await services.db.get('DELETE FROM appointments WHERE id=$1 AND order_key IS NULL RETURNING id',[id]);}else row=await services.db.get('DELETE FROM '+key+' WHERE id=$1 RETURNING id',[id]);if(!row)throw S.error('not_found',404);res.json({success:true});}));}
router.get('/admin',wrap(async(req,res)=>{if(!services.admin.isAdmin(req))return res.redirect(req.tenantPath('/admin/login'));const modules=getModules(req.lang).modules;res.render('admin',{page:'admin',modules,stats:await A.stats(services,modules),recent:await services.db.all('SELECT * FROM appointments ORDER BY created_at DESC LIMIT 6'),emailConfigured:!!services.config.contactEmail,paypalConfigured:paypal.ready(),adminUser:{name:services.config.ownerName||res.locals.t.admin}});}));
router.get('/admin/settings',wrap(async(req,res)=>{if(!services.admin.isAdmin(req))return res.redirect(req.tenantPath('/admin/login'));res.render('admin-settings',{page:'admin',modules:getModules(req.lang).modules,settingsFields:getModules(req.lang).settingsFields,rawSettings:req.site,adminUser:{name:services.config.ownerName||res.locals.t.admin}});}));
for(const m of getModules('fr').modules)router.get('/admin/'+m.key,wrap(async(req,res)=>{if(!services.admin.isAdmin(req))return res.redirect(req.tenantPath('/admin/login'));res.render('admin-'+m.key,{page:'admin',items:await services.db.all('SELECT * FROM '+m.key+' ORDER BY id DESC'),modules:getModules(req.lang).modules,module:getModules(req.lang).modules.find(x=>x.key===m.key),adminUser:{name:services.config.ownerName||res.locals.t.admin}});}));
router.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:res.locals.t.not_found});res.redirect(req.tenantPath('/'));});
router.use((err,req,res,next)=>fail(req,res,err));
// Auto-injected admin page routes for orphaned views
router.get('/admin/appointments', async function(req, res) {
  if (!services.admin.isAdmin(req)) return res.redirect('.');
  var items = await db.all('SELECT * FROM appointments ORDER BY created_at DESC');
  res.render('admin-appointments', { items: items });
});
router.get('/admin/hours', async function(req, res) {
  if (!services.admin.isAdmin(req)) return res.redirect('.');
  var items = await db.all('SELECT * FROM hours ORDER BY created_at DESC');
  res.render('admin-hours', { items: items });
});
router.get('/admin/posts', async function(req, res) {
  if (!services.admin.isAdmin(req)) return res.redirect('.');
  var items = await db.all('SELECT * FROM posts ORDER BY created_at DESC');
  res.render('admin-posts', { items: items });
});
router.get('/admin/services', async function(req, res) {
  if (!services.admin.isAdmin(req)) return res.redirect('.');
  var items = await db.all('SELECT * FROM services ORDER BY created_at DESC');
  res.render('admin-services', { items: items });
});

return router;};