/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mecanique_de_la_montee).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667434/tapavis_tenant_mecanique_de_la_montee/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667434/tapavis_tenant_mecanique_de_la_montee/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667446/tapavis_tenant_mecanique_de_la_montee/hero_252600a5-027a-4c9a-9a40-9b62a8b8481e.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667444/tapavis_tenant_mecanique_de_la_montee/freins_90e679fe-969a-4fea-9948-b78db6ef55c4.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667446/tapavis_tenant_mecanique_de_la_montee/vidange-huile_d355aafa-e221-43ef-ae01-3a612ab38281.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667446/tapavis_tenant_mecanique_de_la_montee/mecanique-generale_697d2503-70c7-49e0-96ad-81f88e3870ac.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667456/tapavis_tenant_mecanique_de_la_montee/equilibrage-rotation-pneus_d44c460a-129e-4b96-b4fe-538ee92dbf7d.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667456/tapavis_tenant_mecanique_de_la_montee/silencieux_7e1a583b-3987-4378-8e22-cda2d7fed638.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667457/tapavis_tenant_mecanique_de_la_montee/suspension_78f4fe3e-2acd-4051-ac7e-412c9291628b.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667461/tapavis_tenant_mecanique_de_la_montee/systeme-de-refroidissement_e9df7af9-c655-4ea1-a400-46ce323cb7d2.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667467/tapavis_tenant_mecanique_de_la_montee/mise-au-point_8203262f-0758-41e3-b671-0b7ba3dcf6ba.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667468/tapavis_tenant_mecanique_de_la_montee/climatisation_364249b6-90c9-45ef-a7da-d5388a7ac2fb.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790667469/tapavis_tenant_mecanique_de_la_montee/transmission_3942cda3-bf69-4cc6-9819-8957145c313b.png"
  }
};
