/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_richa_general_mechanic).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624613/tapavis_tenant_richa_general_mechanic/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624613/tapavis_tenant_richa_general_mechanic/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624624/tapavis_tenant_richa_general_mechanic/hero_0c5366d8-462c-4fc3-ae5c-4613a77f2c4b.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624624/tapavis_tenant_richa_general_mechanic/freins_62a789e6-1cd5-48a1-8d8f-1920ba379c7e.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624624/tapavis_tenant_richa_general_mechanic/mecanique-generale_fc4c8ed7-5fcb-49fd-b8ee-b7c2973c4168.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624624/tapavis_tenant_richa_general_mechanic/vidange-huile_aa5362f4-2692-4541-b569-4aec0de1ddb3.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624634/tapavis_tenant_richa_general_mechanic/suspension_935b3841-86e8-4ebb-8a58-2d457aad81a9.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624634/tapavis_tenant_richa_general_mechanic/silencieux_c0fbf3d2-d7fc-4610-8280-c35f512efd82.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624635/tapavis_tenant_richa_general_mechanic/equilibrage-rotation-pneus_d8f03ccf-8f05-4c13-8de8-6b6d4212c577.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624636/tapavis_tenant_richa_general_mechanic/systeme-de-refroidissement_2072f489-380d-4c64-8a2b-1f079569e5fc.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624645/tapavis_tenant_richa_general_mechanic/climatisation_564e8a7d-6273-472d-b79a-5ee88932a791.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624646/tapavis_tenant_richa_general_mechanic/mise-au-point_00afb37a-d78e-424a-bf67-bf5e6f1d8e2b.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624646/tapavis_tenant_richa_general_mechanic/transmission_7fc32906-4470-43c5-9d55-0d3baf056117.png"
  }
};
