/**
 * Garage Auto Expert — the services its PagesJaunes listing names, in the listing's
 * order (confirmed: 1). Descriptions are general automotive guidance, never
 * claims about this garage's prices, warranties or team.
 */
module.exports = [
  {
    "slug": "entretien-preventif",
    "icon": "oil",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Entretien préventif",
    "name_en": "Preventive maintenance",
    "tagline": "L’entretien prévu par le fabricant, au bon moment.",
    "tagline_en": "The maker’s maintenance schedule, on time.",
    "body": "Le carnet d’entretien du fabricant prévoit des inspections et des remplacements selon le kilométrage et le temps : liquides, filtres, courroies, freins, pneus. Les suivre aide à éviter les pannes et les grosses réparations, et garde un historique utile à la revente.",
    "body_en": "The maker’s maintenance schedule calls for inspections and replacements by mileage and time: fluids, filters, belts, brakes, tires. Keeping to it helps avoid breakdowns and big repairs, and leaves a history that helps at resale.",
    "signs": "[\"Voyant d’entretien allumé\", \"Kilométrage prévu au carnet atteint\", \"Avant un long voyage\", \"Changement de saison\"]",
    "signs_en": "[\"Service light on\", \"Scheduled mileage reached\", \"Before a long trip\", \"Change of season\"]",
    "confirmed": 1
  },
  {
    "slug": "vidange-huile",
    "icon": "oil",
    "duration_min": 30,
    "bookable": 1,
    "featured": 0,
    "name": "Changement d’huile",
    "name_en": "Oil change",
    "tagline": "Huile, filtre et inspection des points essentiels.",
    "tagline_en": "Oil, filter and a check of the essentials.",
    "body": "La vidange est l’entretien le plus simple et le plus important pour la vie du moteur. Elle comprend l’huile appropriée à votre moteur, un filtre neuf et un coup d’œil aux niveaux, aux pneus et aux fuites. Réservez en ligne, déposez la voiture ou attendez sur place.",
    "body_en": "An oil change is the simplest and most important service for engine life. It includes the right oil for your engine, a new filter and a quick look at fluid levels, tires and leaks. Book online, drop the car off or wait on site.",
    "signs": "[\"Le rappel d’entretien s’affiche\",\"Kilométrage atteint depuis la dernière vidange\",\"Huile foncée ou niveau bas\"]",
    "signs_en": "[\"The service reminder appears\",\"Mileage reached since the last change\",\"Dark oil or a low level\"]",
    "confirmed": 1
  },
  {
    "slug": "suspension",
    "icon": "spring",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Suspension et amortisseurs",
    "name_en": "Suspension and shocks",
    "tagline": "Amortisseurs, ressorts, rotules : stabilité et confort.",
    "tagline_en": "Shocks, springs, ball joints: stability and comfort.",
    "body": "Nids-de-poule et routes bosselées usent vite la suspension. Des amortisseurs fatigués allongent les distances de freinage et usent les pneus. L’inspection vérifie amortisseurs, ressorts, rotules, biellettes et bras de suspension.",
    "body_en": "Potholes and rough roads wear a suspension quickly. Tired shocks lengthen braking distances and wear tires. The inspection covers shocks, springs, ball joints, links and control arms.",
    "signs": "[\"Cognements dans les bosses\",\"Le véhicule tire d’un côté\",\"Le nez plonge au freinage\",\"Rebonds après une bosse\"]",
    "signs_en": "[\"Clunks over bumps\",\"The car pulls to one side\",\"The nose dives when braking\",\"Bouncing after a bump\"]",
    "confirmed": 1
  },
  {
    "slug": "systeme-de-refroidissement",
    "icon": "thermo",
    "duration_min": 90,
    "bookable": 1,
    "featured": 0,
    "name": "Radiateur et refroidissement",
    "name_en": "Radiator and cooling",
    "tagline": "Radiateur, pompe à eau, thermostat, antigel.",
    "tagline_en": "Radiator, water pump, thermostat, coolant.",
    "body": "Le système de refroidissement protège le moteur de la surchauffe l’été et du gel l’hiver. Une inspection vérifie le niveau et l’état de l’antigel, l’étanchéité du radiateur et des boyaux, la pompe à eau et le thermostat. Une surchauffe ignorée peut endommager le moteur : mieux vaut agir au premier signe.",
    "body_en": "The cooling system keeps the engine from overheating in summer and freezing in winter. An inspection checks the coolant level and condition, the radiator and hoses for leaks, the water pump and the thermostat. Ignored overheating can damage the engine, so act at the first sign.",
    "signs": "[\"L’aiguille de température monte\",\"Liquide vert, orange ou rose sous le véhicule\",\"Chauffage faible l’hiver\",\"Odeur sucrée dans l’habitacle\"]",
    "signs_en": "[\"The temperature needle climbs\",\"Green, orange or pink fluid under the car\",\"Weak heat in winter\",\"A sweet smell in the cabin\"]",
    "confirmed": 1
  },
  {
    "slug": "electricite-electronique",
    "icon": "spark",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Électricité et électronique",
    "name_en": "Electrical and electronics",
    "tagline": "Démarrage, charge, capteurs, modules.",
    "tagline_en": "Starting, charging, sensors, modules.",
    "body": "Les véhicules récents dépendent de leur électricité et de leurs modules électroniques : démarrage, recharge, éclairage, capteurs et calculateurs. Le diagnostic mesure la batterie et l’alternateur, lit les codes d’erreur et suit le câblage jusqu’à la cause de la panne.",
    "body_en": "Modern vehicles depend on their electrical system and electronic modules: starting, charging, lights, sensors and computers. Diagnosis measures the battery and alternator, reads the fault codes and follows the wiring to the cause of the fault.",
    "signs": "[\"Voyant allumé au tableau de bord\", \"Démarrage lent\", \"Accessoire qui ne fonctionne plus\", \"Batterie qui se décharge\"]",
    "signs_en": "[\"A warning light on the dash\", \"Slow cranking\", \"An accessory that stopped working\", \"A battery that keeps draining\"]",
    "confirmed": 1
  },
  {
    "slug": "batterie-demarreur-alternateur",
    "icon": "spark",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Batterie et alternateur",
    "name_en": "Battery and alternator",
    "tagline": "Le véhicule démarre mal ou pas du tout?",
    "tagline_en": "Slow start or no start?",
    "body": "La batterie fournit l’énergie au démarrage, le démarreur fait tourner le moteur et l’alternateur recharge la batterie en roulant. Un test du système de charge indique lequel est en cause. Nos hivers sont durs pour les batteries : mieux vaut la tester à l’automne.",
    "body_en": "The battery powers the start, the starter turns the engine and the alternator recharges the battery while driving. A charging-system test shows which one is at fault. Our winters are hard on batteries: test yours in the fall.",
    "signs": "[\"Démarrage lent le matin\", \"Clic sans démarrage\", \"Voyant de batterie allumé\", \"Phares qui faiblissent\"]",
    "signs_en": "[\"Slow cranking in the morning\", \"A click but no start\", \"Battery light on\", \"Headlights dimming\"]",
    "confirmed": 1
  },
  {
    "slug": "carburateur",
    "icon": "gear",
    "duration_min": 120,
    "bookable": 1,
    "featured": 0,
    "name": "Réparation de carburateur",
    "name_en": "Carburetor repair",
    "tagline": "Pour les moteurs à carburateur.",
    "tagline_en": "For carbureted engines.",
    "body": "Certains véhicules plus anciens, motos, VTT et petits moteurs fonctionnent encore au carburateur. Un nettoyage, un réglage ou une remise à neuf règlent souvent un ralenti instable, des ratés ou une consommation élevée.",
    "body_en": "Some older vehicles, motorcycles, ATVs and small engines still run on a carburetor. Cleaning, adjusting or rebuilding it often cures an unsteady idle, misfires or high fuel use.",
    "signs": "[\"Ralenti instable\", \"Démarrage difficile\", \"Odeur d’essence\", \"Consommation élevée\"]",
    "signs_en": "[\"Unsteady idle\", \"Hard starting\", \"A fuel smell\", \"High fuel use\"]",
    "confirmed": 1
  },
  {
    "slug": "embrayage",
    "icon": "gear",
    "duration_min": 180,
    "bookable": 1,
    "featured": 0,
    "name": "Réparation d’embrayage",
    "name_en": "Clutch repair",
    "tagline": "Pédale qui patine, passages difficiles.",
    "tagline_en": "Slipping pedal, hard shifts.",
    "body": "Sur une boîte manuelle, l’embrayage relie le moteur à la transmission. Avec l’usure, il patine, broute ou rend les passages de vitesses difficiles. Le remplacement comprend généralement le disque, le plateau de pression et la butée, avec une vérification du volant moteur.",
    "body_en": "On a manual gearbox, the clutch connects the engine to the transmission. As it wears, it slips, judders or makes shifting hard. Replacement usually covers the disc, pressure plate and release bearing, with a check of the flywheel.",
    "signs": "[\"Le régime monte sans que la voiture accélère\", \"Pédale dure ou qui reste enfoncée\", \"Vitesses difficiles à passer\", \"Odeur de brûlé en côte\"]",
    "signs_en": "[\"Revs rise but the car does not speed up\", \"A stiff or sticking pedal\", \"Hard-to-select gears\", \"A burning smell on hills\"]",
    "confirmed": 1
  },
  {
    "slug": "inspection-mecanique",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Inspection avant achat",
    "name_en": "Pre-purchase inspection",
    "tagline": "Avant un achat, un voyage ou pour l’assurance.",
    "tagline_en": "Before buying, a trip, or for insurance.",
    "body": "L’inspection passe en revue les points essentiels du véhicule : freins, pneus, suspension, direction, éclairage, fuites, échappement et état général, avec un rapport des travaux à prévoir. Utile avant d’acheter un véhicule d’occasion, avant un long voyage ou lorsqu’un assureur la demande.",
    "body_en": "An inspection reviews the vehicle’s key points: brakes, tires, suspension, steering, lights, leaks, exhaust and general condition, with a report of the work to plan. Useful before buying a used vehicle, before a long trip, or when an insurer asks for one.",
    "signs": "[\"Achat d’un véhicule d’occasion\", \"Long voyage à venir\", \"Demande de l’assureur\", \"Bruits ou fuites inexpliqués\"]",
    "signs_en": "[\"Buying a used vehicle\", \"A long trip ahead\", \"Insurer request\", \"Unexplained noises or leaks\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-americaines",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures américaines",
    "name_en": "American cars",
    "tagline": "Autos, VUS et camionnettes américains.",
    "tagline_en": "American cars, SUVs and pickups.",
    "body": "Autos, VUS et camionnettes de constructeurs américains : entretien prévu au carnet, freins, suspension, direction et diagnostic. Indiquez le modèle, l’année et le moteur en réservant.",
    "body_en": "Cars, SUVs and pickups from American makers: scheduled maintenance, brakes, suspension, steering and diagnostics. Give the model, year and engine when you book.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant moteur allumé\", \"Bruit sous le véhicule\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"Check-engine light on\", \"A noise under the vehicle\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-asiatiques",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures asiatiques",
    "name_en": "Asian cars",
    "tagline": "Japonaises et coréennes.",
    "tagline_en": "Japanese and Korean cars.",
    "body": "Voitures japonaises et coréennes : entretien prévu au carnet, freins, suspension, courroies et diagnostic. Indiquez la marque, le modèle et l’année en réservant.",
    "body_en": "Japanese and Korean cars: scheduled maintenance, brakes, suspension, belts and diagnostics. Give the make, model and year when you book.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant allumé\", \"Bruit ou vibration\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"A warning light\", \"A noise or vibration\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-europeennes-x",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures européennes",
    "name_en": "European cars",
    "tagline": "Entretien et réparation des voitures européennes.",
    "tagline_en": "Maintenance and repair of European cars.",
    "body": "Les voitures européennes ont leurs propres intervalles d’entretien, leurs huiles et leurs pièces. Au rendez-vous, indiquez la marque, le modèle et l’année (ou le NIV) pour que le garage prévoie les bonnes pièces.",
    "body_en": "European cars have their own service intervals, oils and parts. When you book, give the make, model and year (or the VIN) so the garage can plan the right parts.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant allumé\", \"Bruit ou comportement nouveau\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"A warning light\", \"A new noise or behaviour\"]",
    "confirmed": 1
  },
  {
    "slug": "voitures-luxe",
    "icon": "car",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Voitures de luxe",
    "name_en": "Luxury cars",
    "tagline": "Entretien et réparation des véhicules haut de gamme.",
    "tagline_en": "Maintenance and repair of high-end vehicles.",
    "body": "Les véhicules haut de gamme ont leurs propres intervalles, leurs huiles et leurs systèmes électroniques. Au rendez-vous, indiquez la marque, le modèle et l’année (ou le NIV) pour que le garage prévoie les pièces et le temps nécessaires.",
    "body_en": "High-end vehicles have their own intervals, oils and electronic systems. When you book, give the make, model and year (or the VIN) so the garage can plan the parts and time needed.",
    "signs": "[\"Entretien prévu au carnet\", \"Voyant allumé\", \"Bruit ou comportement nouveau\"]",
    "signs_en": "[\"Scheduled maintenance due\", \"A warning light\", \"A new noise or behaviour\"]",
    "confirmed": 1
  },
  {
    "slug": "entretien-flotte",
    "icon": "wrench",
    "duration_min": 60,
    "bookable": 1,
    "featured": 0,
    "name": "Entretien de flotte",
    "name_en": "Fleet maintenance",
    "tagline": "Les véhicules de votre entreprise, suivis.",
    "tagline_en": "Your company vehicles, kept on schedule.",
    "body": "Pour une entreprise, chaque véhicule immobilisé coûte cher. L’entretien de flotte suit le carnet de chaque véhicule, planifie les vidanges, les inspections et les réparations, et garde un historique par véhicule. Appelez le garage pour organiser le suivi de vos véhicules.",
    "body_en": "For a business, every vehicle off the road costs money. Fleet maintenance follows each vehicle’s schedule, plans oil changes, inspections and repairs, and keeps a history per vehicle. Call the garage to set up follow-up for your vehicles.",
    "signs": "[\"Plusieurs véhicules à entretenir\", \"Besoin d’un historique par véhicule\", \"Véhicules de travail très sollicités\"]",
    "signs_en": "[\"Several vehicles to maintain\", \"A need for per-vehicle history\", \"Hard-working vehicles\"]",
    "confirmed": 1
  },
  {
    "slug": "voiture-courtoisie",
    "icon": "car",
    "duration_min": 0,
    "bookable": 0,
    "featured": 0,
    "option": "courtesy",
    "name": "Voiture de courtoisie",
    "name_en": "Courtesy car",
    "tagline": "Disponible selon la fiche du garage.",
    "tagline_en": "Available according to the garage’s listing.",
    "body": "La fiche du garage indique qu’une voiture de courtoisie est disponible. Demandez-la au moment de réserver ; le garage confirme sa disponibilité.",
    "body_en": "The garage’s listing says a courtesy car is available. Ask for it when you book; the garage confirms availability.",
    "signs": "[\"Réparation de plus d’une journée\", \"Besoin de rester mobile\"]",
    "signs_en": "[\"A repair taking more than a day\", \"Need to stay mobile\"]",
    "confirmed": 1
  }
];
