/**
 * Brand assets on media.liasse.tech (folder tapavis_tenant_radiateur_giffard).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://media.liasse.tech/upload/v1791052413/tapavis_tenant_radiateur_giffard/logo.png",
  "mark": "https://media.liasse.tech/upload/v1791052413/tapavis_tenant_radiateur_giffard/logo.png",
  "hero": "https://media.liasse.tech/upload/v1791052427/tapavis_tenant_radiateur_giffard/hero_b38cb6ed-5a6c-4546-b603-585c837a9af2.webp",
  "services": {
    "vidange-huile": "https://media.liasse.tech/upload/v1791052427/tapavis_tenant_radiateur_giffard/vidange-huile_f8e4935d-54c9-4b5f-921a-013420a611bb.webp",
    "freins": "https://media.liasse.tech/upload/v1791052429/tapavis_tenant_radiateur_giffard/freins_ff7e92ec-58ee-4ab0-ae86-3926cb4309c9.webp",
    "mecanique-generale": "https://media.liasse.tech/upload/v1791052429/tapavis_tenant_radiateur_giffard/mecanique-generale_6a00f85d-0c89-486a-a80f-0646c0111e07.webp",
    "equilibrage-rotation-pneus": "https://media.liasse.tech/upload/v1791052437/tapavis_tenant_radiateur_giffard/equilibrage-rotation-pneus_ca4fab5b-b2cb-49b3-b323-9b613e34b78f.webp",
    "silencieux": "https://media.liasse.tech/upload/v1791052438/tapavis_tenant_radiateur_giffard/silencieux_87beb576-704a-4c1d-983e-8badd4982799.webp",
    "suspension": "https://media.liasse.tech/upload/v1791052438/tapavis_tenant_radiateur_giffard/suspension_fc1f4eec-358a-48a5-9502-b84fe2af7178.webp",
    "systeme-de-refroidissement": "https://media.liasse.tech/upload/v1791052441/tapavis_tenant_radiateur_giffard/systeme-de-refroidissement_fcceb6b6-2665-4451-b353-7fcf2e501ae2.webp",
    "mise-au-point": "https://media.liasse.tech/upload/v1791052447/tapavis_tenant_radiateur_giffard/mise-au-point_5df688c6-6b04-4b63-95d0-d2b1444f4f8e.webp",
    "transmission": "https://media.liasse.tech/upload/v1791052448/tapavis_tenant_radiateur_giffard/transmission_82e4e109-f3a8-4384-b4bd-fb21938a175c.webp",
    "climatisation": "https://media.liasse.tech/upload/v1791052449/tapavis_tenant_radiateur_giffard/climatisation_87f8977e-9b4f-4aba-bca0-d5db8d5e60bf.webp"
  }
};
