/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_mondial_mecanique_automobile).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624574/tapavis_tenant_mondial_mecanique_automobile/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624574/tapavis_tenant_mondial_mecanique_automobile/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624587/tapavis_tenant_mondial_mecanique_automobile/hero_600be349-d0b1-4450-9a5f-d2f329aeca4d.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624585/tapavis_tenant_mondial_mecanique_automobile/freins_d55e463a-4223-4c30-b4be-897e62fca86e.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624586/tapavis_tenant_mondial_mecanique_automobile/vidange-huile_50668c28-e2c1-496d-b3fd-a3c22928f4a9.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624589/tapavis_tenant_mondial_mecanique_automobile/mecanique-generale_09bcadb6-ce0f-48d5-aca5-78688b6ea988.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624597/tapavis_tenant_mondial_mecanique_automobile/silencieux_b18aa64c-9288-4c59-927d-0b009f93cc07.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624597/tapavis_tenant_mondial_mecanique_automobile/equilibrage-rotation-pneus_bd55beb0-ac4a-4dd0-a3f6-00de083d59f7.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624600/tapavis_tenant_mondial_mecanique_automobile/suspension_2d037337-df0d-4d84-9816-e9e00082f065.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624601/tapavis_tenant_mondial_mecanique_automobile/systeme-de-refroidissement_ed87fc6a-27c5-4b45-9b44-283ee78f46a9.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624608/tapavis_tenant_mondial_mecanique_automobile/climatisation_479588a1-3505-4800-a34b-a7e4eaad55e9.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624609/tapavis_tenant_mondial_mecanique_automobile/mise-au-point_cc5648f3-a692-46c6-9bd3-a0ce235af0a4.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790624612/tapavis_tenant_mondial_mecanique_automobile/transmission_3a928e1a-16fe-43c4-9d3c-0f88ce72fc3f.png"
  }
};
