/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_multi_automatique_transmission_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534814/tapavis_tenant_multi_automatique_transmission_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534814/tapavis_tenant_multi_automatique_transmission_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534826/tapavis_tenant_multi_automatique_transmission_inc/hero_764ffdaf-0b60-45fa-9513-6626a6a151dd.png",
  "services": {
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534825/tapavis_tenant_multi_automatique_transmission_inc/freins_dbb586fe-aa49-492a-a264-6b78f0a8f3c7.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534827/tapavis_tenant_multi_automatique_transmission_inc/vidange-huile_d1df790a-8928-4cda-b8c2-44d07d72c862.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534828/tapavis_tenant_multi_automatique_transmission_inc/mecanique-generale_f9617bca-78eb-486c-8368-bee8803dd59a.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534836/tapavis_tenant_multi_automatique_transmission_inc/suspension_93165418-ce97-4871-8b47-9bccb426390f.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534836/tapavis_tenant_multi_automatique_transmission_inc/equilibrage-rotation-pneus_105e7db8-f219-4f2f-a17d-59c01b27dc2f.png",
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534839/tapavis_tenant_multi_automatique_transmission_inc/silencieux_8a85aff8-f0ff-429b-92c1-490f4e85ed4a.png",
    "systeme-de-refroidissement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534840/tapavis_tenant_multi_automatique_transmission_inc/systeme-de-refroidissement_7d539603-4745-4d8a-b961-70a0c83a88cf.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534848/tapavis_tenant_multi_automatique_transmission_inc/mise-au-point_acf720f7-3aa6-498e-be10-24c6c3963029.png",
    "climatisation": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534848/tapavis_tenant_multi_automatique_transmission_inc/climatisation_09acb740-12bc-4a6b-b846-427a455b70aa.png",
    "transmission": "https://res.cloudinary.com/duhp69meg/image/upload/v1790534851/tapavis_tenant_multi_automatique_transmission_inc/transmission_6d7b0ebb-810b-4a2e-88a8-0b62c03e5c25.png"
  }
};
