ALTER TABLE services ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS tagline_fr TEXT;
ALTER TABLE services ADD COLUMN IF NOT EXISTS tagline_en TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_id TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE zones ADD COLUMN IF NOT EXISTS region TEXT;
