CREATE TABLE IF NOT EXISTS admin_settings (key TEXT PRIMARY KEY, value TEXT, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS site_visits (id SERIAL PRIMARY KEY, path TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS posts (id SERIAL PRIMARY KEY, title TEXT NOT NULL, content TEXT, image_url TEXT, category TEXT, published INTEGER DEFAULT 1, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS services (id SERIAL PRIMARY KEY, name_fr TEXT NOT NULL, name_en TEXT, tagline_fr TEXT, tagline_en TEXT, description_fr TEXT, description_en TEXT, duration_min INTEGER DEFAULT 60, price DOUBLE PRECISION DEFAULT 0, image_url TEXT, category TEXT, featured BOOLEAN DEFAULT false, sort_order INTEGER DEFAULT 0, active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS zones (id SERIAL PRIMARY KEY, name TEXT NOT NULL, region TEXT, sort_order INTEGER DEFAULT 0, active BOOLEAN DEFAULT true, image_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS bookings (id SERIAL PRIMARY KEY, service_id INTEGER, service_name TEXT, customer_name TEXT, customer_email TEXT, customer_phone TEXT, customer_address TEXT, city TEXT, booking_date DATE, booking_time TEXT, duration_min INTEGER, price DOUBLE PRECISION, status TEXT DEFAULT 'pending', payment_status TEXT DEFAULT 'unpaid', payment_id TEXT, notes TEXT, user_id INTEGER, image_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS form_submissions (id SERIAL PRIMARY KEY, name TEXT, email TEXT, phone TEXT, message TEXT, image_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS availability_rules (id SERIAL PRIMARY KEY, day_of_week INTEGER NOT NULL, start_time TEXT NOT NULL DEFAULT '09:00', end_time TEXT NOT NULL DEFAULT '19:00', service_id INTEGER, label TEXT, valid_from DATE, valid_to DATE, active BOOLEAN DEFAULT true, sort_order INTEGER DEFAULT 0, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS blackout_dates (id SERIAL PRIMARY KEY, start_date DATE NOT NULL, end_date DATE, reason TEXT, service_id INTEGER, active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
