module.exports = async function(db){
 async function setImg(k,v){await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value, updated_at=NOW()',[k,v]);}
 async function set(k,v){await db.run('INSERT INTO admin_settings (key,value) VALUES ($1,$2) ON CONFLICT (key) DO NOTHING',[k,v]);}
 await set('booking_days','1,2,3,4,5,6');
 await set('booking_start','09:00');
 await set('booking_end','19:00');
 await set('slot_minutes','60');
 await set('max_days_ahead','60');
 await set('min_hours_ahead','24');
 await setImg('_p_hero_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1783701926/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701926182.png');
 await setImg('_p_table_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1783701923/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701923583.png');
 await setImg('_p_about_image_url','https://res.cloudinary.com/duhp69meg/image/upload/v1783701924/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701924540.png');
 var cs=await db.get('SELECT COUNT(*)::int AS n FROM services');
 if(cs.n===0){
  var S=[['Massage suédois','Swedish massage','Détente profonde, de la nuque aux pieds.','Deep relaxation, from neck to toes.','Des manœuvres lentes et enveloppantes pour relâcher les tensions et calmer le système nerveux. Le soin par excellence pour décrocher complètement.','Slow, enveloping strokes that release tension and calm the nervous system. The treatment of choice to fully unwind.',60,120,'https://res.cloudinary.com/duhp69meg/image/upload/v1783701924/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701924792.png','Détente',true,1],['Massage thérapeutique','Therapeutic massage','Soulagement ciblé des douleurs.','Targeted relief for pain.','Un travail en profondeur sur les zones de tension et les douleurs chroniques, adapté à votre condition. Vous repartez plus léger.','Deep work on tension zones and chronic pain, tailored to your condition. You leave lighter.',75,150,'https://res.cloudinary.com/duhp69meg/image/upload/v1783701923/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701923471.png','Thérapeutique',true,2],['Massage duo & couples','Duo & couples massage','À deux, côte à côte, au même moment.','Together, side by side, at the same time.','Deux tables installées côte à côte pour partager un moment de calme. Avec une ou deux massothérapeutes, selon vos préférences.','Two tables set side by side to share a moment of calm. With one or two therapists, as you prefer.',60,260,'https://res.cloudinary.com/duhp69meg/image/upload/v1783701926/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701925625.png','Duo',true,3],['Massage prénatal','Prenatal massage','Douceur et soutien pour la future maman.','Gentle support for the mother-to-be.','Un soin tout en douceur, dans une position confortable et sécuritaire, pour soulager le dos, les jambes et l’esprit.','A gentle treatment in a safe, comfortable position to ease the back, legs and mind.',60,130,'https://res.cloudinary.com/duhp69meg/image/upload/v1783701923/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701923317.png','Spécialisé',false,4],['Massage aux pierres chaudes','Hot stone massage','La chaleur qui dénoue tout.','Warmth that melts it all.','Des pierres de basalte chauffées glissent sur le corps pour une détente enveloppante et une chaleur qui pénètre les muscles.','Heated basalt stones glide over the body for enveloping relaxation and warmth that reaches deep into the muscles.',90,175,'https://res.cloudinary.com/duhp69meg/image/upload/v1783701923/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701923745.png','Détente',false,5]];
  for(var i=0;i<S.length;i++){var s=S[i];await db.run('INSERT INTO services (name_fr,name_en,tagline_fr,tagline_en,description_fr,description_en,duration_min,price,image_url,category,featured,sort_order,active,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,true,NOW(),NOW())',s);}
 }
 var cz=await db.get('SELECT COUNT(*)::int AS n FROM zones');
 if(cz.n===0){
  var Z=['Saint-Sauveur','Sainte-Adèle','Morin-Heights','Piedmont','Prévost','Saint-Jérôme','Sainte-Agathe-des-Monts','Val-David','Val-Morin','Mont-Tremblant','Saint-Hippolyte','Blainville'];
  for(var j=0;j<Z.length;j++){await db.run('INSERT INTO zones (name,region,sort_order,active,created_at,updated_at) VALUES ($1,$2,$3,true,NOW(),NOW())',[Z[j],'Laurentides',j+1]);}
 }
 var car=await db.get('SELECT COUNT(*)::int AS n FROM availability_rules');
 if(car.n===0){
  for(var wd=1;wd<=6;wd++){await db.run('INSERT INTO availability_rules (day_of_week,start_time,end_time,service_id,label,active,sort_order,created_at,updated_at) VALUES ($1,$2,$3,NULL,NULL,true,$4,NOW(),NOW())',[wd,'09:00','19:00',wd]);}
 }
 var cp=await db.get('SELECT COUNT(*)::int AS n FROM posts');
 if(cp.n===0){
  var P=[['Trois minutes de respiration avant de dormir','Avant de fermer les yeux, offrez-vous trois minutes. Inspirez lentement par le nez pendant quatre temps, retenez un instant, puis relâchez pendant six temps.\n\nRépété quelques soirs, ce petit rituel apprend au corps à reconnaître le signal du repos. Le sommeil vient plus doucement.','https://res.cloudinary.com/duhp69meg/image/upload/v1783701924/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701924450.png','Rituels'],['Pourquoi le massage à domicile change tout','Le vrai luxe, ce n’est pas seulement le soin — c’est de ne rien avoir à organiser autour. Pas de trajet, pas de salle d’attente, pas de retour à faire une fois détendu·e.\n\nJe viens à vous avec tout le nécessaire. Vous n’avez qu’à rester là où le calme vous attend déjà : chez vous.','https://res.cloudinary.com/duhp69meg/image/upload/v1783701924/tapavis_tenant_parenthese-detente/build_parenthese-detente_1783701924229.png','À la maison'],['Préparer votre espace pour un massage','Un coin tranquille, un peu de place pour la table, une prise à proximité : c’est tout ce qu’il faut. Je m’occupe du reste, du drap chaud à la lumière tamisée.\n\nUn conseil : prévoyez un grand verre d’eau pour après le soin. Votre corps vous remerciera.',null,'Conseils'],['Le confort d’une grande table','Ma table de massage est le cœur de mon travail. Rembourrage épais, surface chauffante, habillage de lin lavé changé à chaque visite.\n\nC’est ce détail, souvent invisible, qui transforme un bon massage en un vrai moment de lâcher-prise.',null,'Coulisses']];
  for(var k=0;k<P.length;k++){var p=P[k];await db.run('INSERT INTO posts (title,content,image_url,category,published,created_at,updated_at) VALUES ($1,$2,$3,$4,1,NOW() - ($5 || \' days\')::interval,NOW())',[p[0],p[1],p[2],p[3],String(k)]);}
 }
 var cb=await db.get('SELECT COUNT(*)::int AS n FROM bookings');
 if(cb.n===0){
  var d1=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
  var d2=new Date(Date.now()+6*86400000).toISOString().slice(0,10);
  var d0=new Date(Date.now()-4*86400000).toISOString().slice(0,10);
  await db.run('INSERT INTO bookings (service_name,customer_name,customer_email,customer_phone,customer_address,city,booking_date,booking_time,duration_min,price,status,payment_status,notes,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW(),NOW())',['Massage suédois','Claire Bélanger','claire@exemple.com','(450) 555-0142','128 rue des Érables','Saint-Sauveur',d1,'10:00',60,120,'confirmed','paid','Préférence pour une ambiance très calme.']);
  await db.run('INSERT INTO bookings (service_name,customer_name,customer_email,customer_phone,customer_address,city,booking_date,booking_time,duration_min,price,status,payment_status,notes,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW(),NOW())',['Massage thérapeutique','Marc Tremblay','marc@exemple.com','(450) 555-0188','54 chemin du Lac','Sainte-Adèle',d2,'14:00',75,150,'pending','unpaid','Douleur au bas du dos.']);
  await db.run('INSERT INTO bookings (service_name,customer_name,customer_email,customer_phone,customer_address,city,booking_date,booking_time,duration_min,price,status,payment_status,notes,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,NOW(),NOW())',['Massage aux pierres chaudes','Julie Rousseau','julie@exemple.com','(819) 555-0110','9 allée des Pins','Val-David',d0,'16:00',90,175,'completed','paid','']);
 }
};
