/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_garage_levesque_leopold).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738129/tapavis_tenant_garage_levesque_leopold/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738129/tapavis_tenant_garage_levesque_leopold/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738141/tapavis_tenant_garage_levesque_leopold/hero_3fde14f8-575e-4087-aa67-d05419970435.png",
  "services": {
    "silencieux": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738140/tapavis_tenant_garage_levesque_leopold/silencieux_579ab800-b001-4250-99c8-1323689f03eb.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738142/tapavis_tenant_garage_levesque_leopold/suspension_c9cda972-75df-446e-bf76-d141541140a5.png",
    "mecanique-generale": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738142/tapavis_tenant_garage_levesque_leopold/mecanique-generale_e7cd5aa0-d2ec-45f4-8232-46cc406ebecd.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738151/tapavis_tenant_garage_levesque_leopold/mise-au-point_ef321e63-afd0-4b74-a669-6d73e259ac62.png",
    "freins": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738155/tapavis_tenant_garage_levesque_leopold/freins_25be1284-07dc-4c3e-a527-ae149d45e958.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738155/tapavis_tenant_garage_levesque_leopold/vidange-huile_6558fd0e-fabf-48a4-945d-1276b8755f6a.png",
    "pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790738156/tapavis_tenant_garage_levesque_leopold/pneus_ba043c2c-3a2b-4617-a582-ecaf0ae3a8a7.png"
  }
};
