const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const {create,root}=require('./harness.cjs'),M=require(root+'/public/js/campaign-model-v2'),G=require(root+'/public/js/canada-geography-v1'),mail=require(root+'/mailing-service-v5');
const cities={BC:[49.2827,-123.1207],AB:[51.0447,-114.0719],SK:[50.4452,-104.6189],MB:[49.8951,-97.1384],ON:[43.6532,-79.3832],QC:[45.5017,-73.5673],NB:[45.9636,-66.6431],NS:[44.6488,-63.5752],PE:[46.2382,-63.1311],NL:[47.5615,-52.7126],YT:[60.7212,-135.0568],NT:[62.454,-114.3718],NU:[63.7467,-68.5167]};
function addr(p){const [lat,lng]=cities[p];return {numero:'100',rue:'Main Street',ville:p+' city',lat,lng,source:'point'};}
test('all Canadian provinces and territories accepted; US, Alaska and Greenland rejected',()=>{
 for(const p of Object.keys(cities)){const a=addr(p);assert.equal(G.province(a),p);const s=M.sanitize({...a,province:'QC'});assert(s,p);assert.equal(s.province,p,'province derives from geography, not caller');assert.equal(s.country,'CA');assert.match(mail.addressLines(s)[1],new RegExp(p));
 const parsed=M.parse([{type:'node',id:1,lat:a.lat,lon:a.lng,tags:{'addr:housenumber':'100','addr:street':'Main Street'}}],a,a.ville,200);assert.equal(parsed.length,1);assert.equal(parsed[0].province,p);}
 for(const [lat,lng] of [[47.6062,-122.3321],[42.3314,-83.0458],[44.4759,-73.2121],[44.8012,-68.7778],[64.8378,-147.7164],[58.3019,-134.4197],[64.1814,-51.6941]]){assert.equal(G.canada({lat,lng}),false,lat+','+lng);assert.equal(M.sanitize({...addr('ON'),lat,lng,province:'ON',country:'CA'}),null);}
 for(const [lat,lng,p] of [[42.3149,-83.0364,'ON'],[49.0253,-122.8029,'BC'],[48.4267,-123.3656,'BC'],[49.15,-125.9,'BC'],[46.98,-64.05,'PE']])assert.equal(G.province({lat,lng}),p,'Canadian border/coastal location');
 assert.equal(mail.addressLines({numero:'1',rue:'Test',ville:'Old record',postal:'V6B 1A1'})[1],'Old record BC V6B 1A1');
});
test('national draft/save and server export keep per-address provinces without registration numbers',async()=>{
 const h=await create();h.services.externalVars.PAYPAL_MODE='live';try{const b=await h.db.get("INSERT INTO brokers(slug,full_name,email,status,published,access_plan,billing_address,billing_confirmed_at) VALUES('canada-map','Canada Tester','map@example.test','invited',1,'mailing',$1,NOW()) RETURNING *",[JSON.stringify({legal_name:'Canada Realty',line1:'123 Main Street',city:'Toronto',province:'ON',postal_code:'M5V 1A1',country:'CA'})]);const raw=crypto.randomBytes(32).toString('hex');await h.db.run("INSERT INTO broker_sessions(broker_id,token_hash,idle_expires_at,absolute_expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour',NOW()+INTERVAL '1 hour')",[b.id,crypto.createHash('sha256').update(raw).digest('hex')]);const cookie='vv_broker_session='+raw,session=await (await fetch(h.url+'/api/espace/session',{headers:{cookie}})).json(),headers={cookie,'X-VV-Payment-Mode':'live','Content-Type':'application/json','x-vv-csrf':session.csrf};
 let revision=0;
 for(const p of Object.keys(cities)){const a=M.sanitize(addr(p));const data={center:{lat:a.lat,lng:a.lng,libelle:a.ville},city:a.ville,radius:200,target:1,addresses:[a],selected:[a.id],excluded:[]};const res=await fetch(h.url+'/api/espace/campagne/brouillon',{method:'PUT',headers,body:JSON.stringify({revision,data})});assert.equal(res.status,200,p+' '+await res.clone().text());revision=(await res.json()).revision;const draft=await h.db.get('SELECT data FROM broker_campaign_drafts WHERE broker_id=$1',[b.id]);assert.equal(draft.data.addresses[0].province,p);}
 const html=await (await fetch(h.url+'/espace?lang=en',{headers:{cookie}})).text();assert.doesNotMatch(html,/id="csMapWelcome"|data-city=/);assert.match(html,/city in Canada/);assert.match(html,/canada-geography-v1/);
 const quote=await (await fetch(h.url+'/api/espace/campagne/devis',{method:'POST',headers,body:JSON.stringify({count:150,destinationCounts:{ON:150}})})).json();assert.equal(quote.price.taxReady,true);assert.equal(quote.price.total,26951);assert.equal(quote.price.taxLines[0].registration,'');
 const review=await (await fetch(h.url+'/api/espace/campagne/devis',{method:'POST',headers,body:JSON.stringify({count:150,destinationCounts:{BC:150}})})).json();assert.equal(review.price.taxReady,true);assert.equal(review.price.total,26713);
 }finally{await h.close();}
});
