const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const {create,root}=require('./harness.cjs'),auth=require(root+'/broker-auth-v2');
const admin={'x-test-admin':'yes'};
function cookies(r){return r.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');}
test('safe local recovery destinations retain payment context without open redirects',()=>{
 for(const s of ['espace/commandes','espace/commandes/123','espace/campagnes/12/decision','espace/commandes/123?lang=en','espace/commandes?page=2&lang=en','espace/courrier-cible?campaignPage=2&lang=en'])assert.equal(auth.safeNext(s),s);
 assert.equal(auth.safeNext('espace/campagne/retour?mode=live&token=ORDER-12&PayerID=ABCDEF123'),'espace/campagne/retour?token=ORDER-12&mode=live');
 assert.equal(auth.safeNext('espace/campagne/retour?mode=live&token=ORDER-12&annule=1'),'espace/campagne/retour?token=ORDER-12&mode=live&annule=1');
 for(const s of ['https://evil.test','//evil.test','espace/commandes/12/../../admin','espace/campagne/retour?token=x&next=https://evil.test','espace/campagne/retour?token=x&token=y','espace/campagne/retour?token=x%0d%0a','espace/commandes/1#x','espace\\commandes\\1'])assert.equal(auth.safeNext(s),'espace');
});
test('new and existing invitation accounts count only after authenticated email confirmation; sent cohort only',async()=>{const h=await create();try{
 const campaign=await h.db.get("INSERT INTO solicitation_campaigns(name,format,sent_at) VALUES('Sent audit','fr',NOW()) RETURNING *");
 async function invite(letter){return h.db.get("INSERT INTO solicitation_agents(campaign_id,tag,name,agency,phone,address1,address2) VALUES($1,$2,'Marie QA','Agency','5145550100','123 RUE TEST','MONTREAL QC H2X 1Y4') RETURNING *",[campaign.id,'VV-'+letter.repeat(32)]);}
 const a=await invite('a');async function signup(agent){return fetch(h.url+'/api/courtier/demarrer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tag:agent.tag,name:'Marie QA',agency:'Agency',phone:'5145550100',email:'claim@example.test',mailing_terms:true})});}
 assert.equal((await signup(a)).status,201);let stored=await h.db.get('SELECT * FROM solicitation_agents WHERE id=$1',[a.id]);assert.equal(stored.broker_id,null);async function stats(){const r=await fetch(h.url+'/api/admin/operations',{headers:admin});assert.equal(r.status,200,await r.clone().text());return r.json();}let s=await stats();assert.equal(s.summary.started,1);assert.equal(s.summary.claimed,0);
 async function redeemLatest(){const mail=h.emails.at(-1),url=mail.text.match(/https?:\/\/\S+\/acces\/[a-f0-9]{64}\?\S+/)[0],get=await fetch(url),html=await get.text(),challenge=html.match(/name="challenge" value="([^"]+)"/)[1];return fetch(new URL(url).origin+new URL(url).pathname,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json',cookie:cookies(get)},body:JSON.stringify({challenge,next:'espace/commandes/42'})});}
 const signed=await redeemLatest();assert.equal(signed.status,303);assert.equal(signed.headers.get('location'),'/espace/commandes/42');s=await stats();assert.equal(s.summary.claimed,1);assert(s.agents[0].claimed_at);
 const second=await invite('b');await h.db.run("UPDATE mailing_signup_limits SET last_at=NOW()-INTERVAL '3 minutes'");assert.equal((await signup(second)).status,200);assert.equal((await h.db.get('SELECT broker_id FROM solicitation_agents WHERE id=$1',[second.id])).broker_id,null);assert.equal((await redeemLatest()).status,303);assert.equal((await stats()).summary.claimed,2);
 await h.db.run('UPDATE solicitation_campaigns SET sent_at=NULL WHERE id=$1',[campaign.id]);assert.equal((await stats()).summary.claimed,0);assert.equal((await stats()).summary.invited,0);
}finally{await h.close();}});
test('campaign metrics retain activity and analysis outcome attribution; job retry remains admin protected',async()=>{const h=await create();try{
 const b=await h.db.get("INSERT INTO brokers(slug,full_name,email,access_plan,status,published) VALUES('metrics-qa','QA Broker','qa@example.test','mailing','invited',1) RETURNING *"),c=await h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,address_count) VALUES($1,'paid','mailed','paid',10) RETURNING *",[b.id]);
 await h.db.run("INSERT INTO agent_page_activity(token_hash,visitor_hash,kind,broker_id,campaign_id,first_seen_at,last_seen_at,active) VALUES('one','visitor','mailer',$1,$2,NOW(),NOW(),true)",[b.id,c.id]);await h.db.run("INSERT INTO broker_leads(broker_id,campaign_id,name,contacted_at,analysis_delivered_at) VALUES($1,$2,'QA',NOW(),NOW())",[b.id,c.id]);
 const outbox=require(root+'/notification-outbox-v1').create(h.services),j=await outbox.enqueue('qa',{to:'qa@example.test',subject:'QA',text:'QA'});await h.db.run("UPDATE notification_jobs SET status='failed',attempts=12 WHERE id=$1",[j.id]);const r=await fetch(h.url+'/api/admin/operations',{headers:admin}),s=await r.json();assert.equal(r.status,200);assert.equal(s.campaigns[0].requests,1);assert.equal(s.campaigns[0].views,1);assert.equal(s.campaigns[0].delivered,1);assert.equal(s.notifications.failed,1);
 assert.equal((await fetch(h.url+'/api/admin/notifications')).status,403);assert.equal((await fetch(h.url+'/api/admin/notifications/'+j.id+'/retry',{method:'POST',headers:{...admin,'Content-Type':'application/json',origin:'https://evil.test'},body:'{}'})).status,403);assert.equal((await fetch(h.url+'/api/admin/notifications/'+j.id+'/retry',{method:'POST',headers:{...admin,'Content-Type':'application/json'},body:'{}'})).status,200);
}finally{await h.close();}});
test('background jobs register, lease, persist health and run independently of a browser',async()=>{const h=await create();try{const jobs=[];h.services.scheduler={register:(name,interval,fn)=>jobs.push({name,interval,fn})};let checks=0;h.services.vendvitePaymentRecovery={run:async()=>{checks++;return [];}};require(root+'/crons')(h.services);assert.equal(jobs.length,3);for(const job of jobs)await job.fn({db:h.db});assert.equal(checks,1);assert.equal((await h.db.all('SELECT * FROM operations_job_runs WHERE finished_at IS NOT NULL')).length,3);await h.db.run("UPDATE operations_job_runs SET lease_until=NOW()+INTERVAL '10 minutes' WHERE name='vendvite-payments-v1'");await jobs[0].fn({db:h.db});assert.equal(checks,1);assert.equal(h.emails.length,0);}finally{await h.close();}});

test('public operational health wakes the tenant while exposing only readiness and returning 503 for worker or database failures',async()=>{const h=await create();try{let r=await fetch(h.url+'/health/operations');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.deepEqual(await r.json(),{state:'starting'});for(const name of ['vendvite-payments-v1','vendvite-notifications-v1','vendvite-reminders-v1'])await h.db.run('INSERT INTO operations_job_runs(name,finished_at) VALUES($1,NOW())',[name]);r=await fetch(h.url+'/health/operations');assert.deepEqual(await r.json(),{state:'ready'});await h.db.run("UPDATE operations_job_runs SET last_error='private details' WHERE name='vendvite-payments-v1'");r=await fetch(h.url+'/health/operations');assert.equal(r.status,503);assert.deepEqual(await r.json(),{state:'unavailable'});h.db.all=async()=>{throw Error('private database details')};r=await fetch(h.url+'/health/operations');assert.equal(r.status,503);assert.deepEqual(await r.json(),{state:'unavailable'});}finally{await h.close();}});
