const assert=require('node:assert/strict'),crypto=require('crypto'),fs=require('fs');const {create,root}=require('./harness.cjs'),P=require(root+'/production-v1'),M=require(root+'/public/js/campaign-model-v2'),{chromium}=require('/home/liassetech/liasse.tech/node_modules/playwright');
(async()=>{const h=await create();let browser;try{
const broker=await h.db.get("INSERT INTO brokers(slug,full_name,agency,email,status,access_plan,published) VALUES('production-browser','Marie Exemple','Agence Exemple','qa@example.test','invited','mailing',1) RETURNING *"),batch=await h.db.get("INSERT INTO solicitation_campaigns(name,format,batch_number,sent_at) VALUES('Courtiers Québec — lot QA','fr',1,NOW()) RETURNING *"),agent=await h.db.get("INSERT INTO solicitation_agents(campaign_id,broker_id,tag,name,address1,address2) VALUES($1,$2,$3,'Marie Exemple','123 RUE TEST','MONTREAL QC H2X 1Y4') RETURNING *",[batch.id,broker.id,'VV-'+'b'.repeat(32)]);
const addresses=[100,200,300].map(n=>({...M.sanitize({numero:String(n),rue:'Rue des Érables',ville:'Montréal',lat:45.5,lng:-73.6,source:'point'}),analysis:{type:n===200?'apartment':'house',units:n===200?4:null}}));const campaign=await h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,address_count,quantity,addresses,total_cents,centre_label,city,deadline_at) VALUES($1,'paid','confirmed','paid',3,3,$2,548,'Rue des Érables, Montréal','Montréal',NOW()+INTERVAL '3 days') RETURNING *",[broker.id,JSON.stringify(addresses)]);
browser=await chromium.launch({headless:true});const admin=await browser.newContext({viewport:{width:1440,height:1000},extraHTTPHeaders:{'x-test-admin':'yes'}}),page=await admin.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const publicContext=await browser.newContext({userAgent:'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/132.0.0.0 Safari/537.36'});await publicContext.route('https://maps.googleapis.com/**',r=>r.abort());const visitor=await publicContext.newPage();const beat=visitor.waitForResponse(r=>r.url().endsWith('/api/page-activity')&&r.status()===204);await visitor.goto(h.url+'/invitation/'+agent.tag);await beat;
await page.goto(h.url+'/admin');await page.waitForFunction(()=>document.querySelector('#opsRows').textContent.includes('Marie Exemple'));assert.equal(await page.locator('#opsOrders').textContent(),'1');assert.equal(await page.locator('#opsBuyers').textContent(),'1');assert.equal(await page.locator('#opsRows td').nth(1).textContent(),'1');assert.equal(await page.locator('#opsRows td').nth(5).textContent(),'Oui');assert.equal(await page.locator('.admin-nav a').count(),4);assert(!await page.locator('.admin-sidebar').textContent().then(s=>/Témoignages|Journal|Demandes|Test de conversion/.test(s)));
fs.mkdirSync(__dirname+'/tax-preview',{recursive:true});await page.screenshot({path:__dirname+'/tax-preview/operations-dashboard.png'});await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:__dirname+'/tax-preview/operations-dashboard-mobile.png'});await page.locator('#adminBurger').click();assert(await page.locator('#adminSidebar').evaluate(e=>e.classList.contains('open')));await page.setViewportSize({width:1440,height:1000});
await page.goto(h.url+'/admin/campagnes/'+campaign.id+'/preparation');assert.match(await page.locator('main').textContent(),/Immeubles à vérifier/);const download=page.waitForEvent('download');await page.getByText('Télécharger le CSV modèle de cette commande').click();const file=await download;assert.match(file.suggestedFilename(),/codes-postaux.csv/);
const rows=P.original(campaign).flatMap(a=>(a.numero==='200'?['1','2','3']:['']).map(unit=>[P.addressId(a),a.numero,a.rue,unit,a.ville,a.province,'H2X 1Y4']));await page.locator('#postalFile').setInputFiles({name:'postal-return.csv',mimeType:'text/csv',buffer:Buffer.from(P.csv(rows))});await page.locator('#postalImport button').click();await page.locator('#postalApproval').waitFor();assert.equal(await page.locator('#postalSelected').textContent(),'2');assert(await page.locator('#postalApprove').isDisabled());await page.getByRole('radio',{name:'Choisir 2 au 200 Rue des Érables',exact:true}).check();assert.equal(await page.locator('#postalSelected').textContent(),'3');await page.locator('#postalAcknowledge').check();await page.locator('#postalApproval').scrollIntoViewIfNeeded();await page.screenshot({path:__dirname+'/tax-preview/operations-unit-review.png'});await page.setViewportSize({width:390,height:844});await page.locator('#postalAcknowledge').scrollIntoViewIfNeeded();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:__dirname+'/tax-preview/operations-unit-review-mobile.png'});
await page.locator('#postalApprove').click();await page.getByText('Liste validée · 3 lettres à imprimer').waitFor();assert.equal(await page.locator('#postalImport').count(),0);assert.match(await page.locator('main').textContent(),/unité 2/);assert.match(await page.locator('main').textContent(),/Unité 1/);assert.match(await page.locator('main').textContent(),/Unité 3/);
const raw=crypto.randomBytes(32).toString('hex');await h.db.run("INSERT INTO broker_sessions(broker_id,token_hash,idle_expires_at,absolute_expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour',NOW()+INTERVAL '1 hour')",[broker.id,crypto.createHash('sha256').update(raw).digest('hex')]);const owner=await browser.newContext({viewport:{width:390,height:844}});await owner.addCookies([{name:'vv_broker_session',value:raw,url:h.url}]);const report=await owner.newPage();await report.goto(h.url+'/espace/campagnes/'+campaign.id+'/preparation?lang=en');assert.match(await report.locator('main').textContent(),/unit 2/);assert.match(await report.locator('main').textContent(),/Unit 1/);assert(await report.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await report.screenshot({path:__dirname+'/tax-preview/operations-agent-report.png'});assert.deepEqual(errors,[]);assert.equal(h.emails.length,0);
console.log('Human page beacon, dashboard attribution, streamlined navigation, desktop/mobile, CSV download/upload, unit choice, locked approval and private agent report passed.');
}finally{if(browser)await browser.close();await h.close();}})().catch(e=>{console.error(e);process.exitCode=1});
