const assert=require('node:assert/strict'),fs=require('fs');const {create,root}=require('./harness.cjs'),{chromium}=require('/home/liassetech/liasse.tech/node_modules/playwright');
(async()=>{const h=await create();let browser;try{
 const b=await h.db.get("INSERT INTO brokers(slug,full_name,email,access_plan,status,published) VALUES('ops-browser','Marie Exemple','qa@example.test','mailing','invited',1) RETURNING *");
 const lot=await h.db.get("INSERT INTO solicitation_campaigns(name,format,sent_at) VALUES('Envoi exemple','fr',NOW()) RETURNING *");
 const a=await h.db.get("INSERT INTO solicitation_agents(campaign_id,tag,name,broker_id,claimed_at,address1,address2) VALUES($1,$2,'Marie Exemple',$3,NOW(),'123 Rue Exemple','Montreal QC') RETURNING *",[lot.id,'VV-'+'a'.repeat(32),b.id]);
 await h.db.run('INSERT INTO solicitation_claims(agent_id,broker_id,verified_at) VALUES($1,$2,NOW())',[a.id,b.id]);
 const c=await h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,address_count,mailed_at,production) VALUES($1,'paid','mailed','paid',10,NOW(),'{\"preparedCount\":10}') RETURNING *",[b.id]);
 await h.db.run("INSERT INTO agent_page_activity(token_hash,visitor_hash,kind,broker_id,campaign_id,first_seen_at,last_seen_at,active) VALUES('one','visitor','mailer',$1,$2,NOW(),NOW(),true)",[b.id,c.id]);
 await h.db.run("INSERT INTO broker_leads(broker_id,campaign_id,name,contacted_at,analysis_delivered_at) VALUES($1,$2,'QA',NOW(),NOW())",[b.id,c.id]);
 const outbox=require(root+'/notification-outbox-v1').create(h.services),j=await outbox.enqueue('qa',{to:'qa@example.test',subject:'QA',text:'QA'});
 await h.db.run("UPDATE notification_jobs SET status='failed',attempts=12 WHERE id=$1",[j.id]);
 for(const name of ['vendvite-payments-v1','vendvite-notifications-v1','vendvite-reminders-v1'])await h.db.run('INSERT INTO operations_job_runs(name,started_at,finished_at) VALUES($1,NOW(),NOW())',[name]);
 browser=await chromium.launch({headless:true});const context=await browser.newContext({extraHTTPHeaders:{'x-test-admin':'yes'},viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(h.url+'/admin');await page.waitForFunction(()=>document.querySelector('#opsClaimed').textContent==='1 / 1');
 assert.equal(await page.locator('#opsStarted').textContent(),'1');assert.match(await page.locator('#opsRows').textContent(),/Activée/);assert.match(await page.locator('#opsCampaigns').textContent(),/10 \/ 10/);assert.equal(await page.locator('#opsWorkers .ops-error').count(),0);assert.match(await page.locator('#opsNotifications').textContent(),/1 à vérifier/);
 await page.locator('summary').filter({hasText:'Notifications et reprises'}).click();await page.locator('#opsJobs button').click();await page.waitForFunction(()=>document.querySelector('#opsJobs').textContent.includes('En attente'));assert.equal((await h.db.get('SELECT status FROM notification_jobs WHERE id=$1',[j.id])).status,'pending');assert.equal(h.emails.length,0);
 fs.mkdirSync(__dirname+'/tax-preview',{recursive:true});await page.screenshot({path:__dirname+'/tax-preview/operations-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.addStyleTag({content:'*,*::before,*::after{transition:none!important;animation:none!important}'});await page.evaluate(()=>scrollTo(0,0));await page.locator('#adminBurger').click();assert(await page.locator('#adminSidebar').evaluate(e=>e.classList.contains('open')));await page.locator('#adminSidebar a').filter({hasText:'Suivi & conversions'}).click();await page.waitForFunction(()=>document.querySelector('#opsClaimed').textContent==='1 / 1');assert.equal(await page.locator('#adminSidebar').evaluate(e=>Math.round(e.getBoundingClientRect().right)),0);await page.screenshot({path:__dirname+'/tax-preview/operations-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: verified activation, campaign results, worker health, failed notification retry, desktop/mobile dashboard; no real messages.');
}finally{if(browser)await browser.close();await h.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
