const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const {create,root}=require('./harness.cjs'),M=require(root+'/public/js/campaign-model-v2'),H=require(root+'/campaign-history-v3');
const address=n=>M.sanitize({numero:String(n),rue:'Rue du Test',ville:'Montréal',postal:'H2X 1A1',lat:45.5017,lng:-73.5673,source:'point'});
async function fixture(){
 const h=await create();Object.assign(h.services.externalVars,{PAYPAL_MODE:'live',PAYPAL_CLIENT_ID:'live-client',PAYPAL_CLIENT_SECRET:'live-secret',PAYPAL_SANDBOX_CLIENT_ID:'sandbox-client',PAYPAL_SANDBOX_CLIENT_SECRET:'sandbox-secret'});h.services.config.contactEmail='operator@example.test';
 const b=await h.db.get("INSERT INTO brokers(slug,full_name,email,status,published,access_plan,billing_address,billing_confirmed_at) VALUES('sandbox-checkout','Rehearsal Broker','broker@example.test','invited',1,'mailing',$1,NOW()) RETURNING *",[JSON.stringify({legal_name:'Example Realty',line1:'123 Main Street',city:'Montréal',province:'QC',postal_code:'H2X 1A1',country:'CA'})]);
 async function session(broker=b){const raw=crypto.randomBytes(32).toString('hex');await h.db.run("INSERT INTO broker_sessions(broker_id,token_hash,idle_expires_at,absolute_expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour',NOW()+INTERVAL '1 hour')",[broker.id,crypto.createHash('sha256').update(raw).digest('hex')]);const cookie='vv_broker_session='+raw,info=await (await fetch(h.url+'/api/espace/session',{headers:{cookie}})).json();return {cookie,raw,csrf:info.csrf};}
 const s=await session();const orders=new Map(),calls=[];let sequence=0;
 h.services.fetch=async(url,options={})=>{const mode=new URL(url).hostname==='api-m.sandbox.paypal.com'?'sandbox':'live';calls.push({url,mode,options});if(url.endsWith('/v1/oauth2/token')){assert.equal(options.headers.Authorization,'Basic '+Buffer.from(mode+'-client:'+mode+'-secret').toString('base64'));return {ok:true,json:async()=>({access_token:'token-'+mode})};}assert.equal(options.headers.Authorization,'Bearer token-'+mode);
  if(url.endsWith('/v2/checkout/orders')){const payload=JSON.parse(options.body),id='ORDER-'+mode.toUpperCase()+'-'+(++sequence),order={...payload,id,status:'CREATED',links:[{rel:'approve',href:'https://'+(mode==='sandbox'?'www.sandbox.paypal.com':'www.paypal.com')+'/checkoutnow?token='+id}]};orders.set(id,order);return {ok:true,status:201,json:async()=>structuredClone(order)};}
  const id=url.endsWith('/capture')?url.split('/').at(-2):url.split('/').at(-1),order=orders.get(id);assert(order);assert(id.includes(mode.toUpperCase()));if(url.endsWith('/capture')){order.status='COMPLETED';order.purchase_units[0].payments={captures:[{id:'CAPTURE-'+id,status:'COMPLETED',amount:structuredClone(order.purchase_units[0].amount)}]};}return {ok:true,status:200,json:async()=>structuredClone(order)};
 };
 async function request(path,{method='GET',body,mode='live',actor=s,extra={}}={}){const headers={cookie:actor.cookie,'x-vv-csrf':actor.csrf,...extra};if(mode!==null)headers['X-VV-Payment-Mode']=mode;if(body!==undefined)headers['Content-Type']='application/json';return fetch(h.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});}
 async function toggle(enabled,actor=s){const r=await request('/api/espace/sandbox',{method:'POST',body:{enabled},actor});assert.equal(r.status,200,await r.clone().text());actor.cookie=actor.cookie.replace(/; vv_sandbox_mode=[^;]*/,'');if(enabled)actor.cookie+='; '+r.headers.getSetCookie().find(c=>c.startsWith('vv_sandbox_mode=')).split(';')[0];return actor;}
 async function quote(mode='live',actor=s,reprise=0){const r=await request('/api/espace/campagne/devis',{method:'POST',mode,actor,body:{count:1,destinationCounts:{QC:1},reprise}});assert.equal(r.status,200,await r.clone().text());return (await r.json()).price;}
 function draft(n){const a=address(n);return {center:{lat:a.lat,lng:a.lng,libelle:'Test neighborhood'},city:a.ville,radius:800,target:1,addresses:[a],selected:[a.id],excluded:[],notes:'',historyFilter:{mode:'off'},reprise:0};}
 async function checkout(mode='live',actor=s,extra={}){const price=await quote(mode,actor);return request('/api/espace/campagne/commander',{method:'POST',mode,actor,body:{paymentMode:mode,centre:draft(101).center,adresses:[address(101)],quantite:1,expectedTotal:price.total,historyFilter:{mode:'off'},...extra}});}
 return {h,b,s,session,request,toggle,quote,draft,checkout,orders,calls};
}

test('signed account opt-in isolates server drafts and rejects missing/stale mode before saves, quotes, checkout, or proof',async()=>{const f=await fixture();try{
 let r=await f.request('/api/espace/campagne/brouillon',{method:'PUT',body:{revision:0,data:f.draft(101)}});assert.equal(r.status,200,await r.clone().text());assert.equal((await r.json()).revision,1);
 const otherSession=await f.session();await f.toggle(true);assert.equal((await f.request('/api/espace/campagne/brouillon',{mode:'sandbox'})).status,200);
 r=await f.request('/api/espace/campagne/brouillon',{mode:'sandbox'});assert.equal((await r.json()).revision,0);r=await f.request('/api/espace/campagne/brouillon',{mode:'sandbox',method:'PUT',body:{revision:0,data:f.draft(202)}});assert.equal(r.status,200,await r.clone().text());
 for(const [path,method,body] of [['/api/espace/campagne/brouillon','GET'],['/api/espace/campagne/brouillon','PUT',{revision:1,data:f.draft(303)}],['/api/espace/campagne/devis','POST',{count:1,destinationCounts:{QC:1}}],['/api/espace/campagne/commander','POST',{}],['/api/espace/campagne','POST',{}],['/api/espace/billing-address','PUT',{}]])for(const mode of ['live',null]){r=await f.request(path,{method,body,mode});assert.equal(r.status,409,path);assert.equal((await r.json()).code,'PAYMENT_MODE_CHANGED');}
 r=await f.request('/api/espace/publier',{method:'POST',mode:'live',body:{published:false}});assert.equal(r.status,409);assert.equal((await f.h.db.get('SELECT published FROM brokers WHERE id=$1',[f.b.id])).published,1);
 for(const mode of ['sandbox',null])for(const published of [true,false]){r=await f.request('/api/espace/publier',{method:'POST',mode,body:{published}});assert.equal(r.status,409);assert.equal((await r.json()).code,'SANDBOX_PUBLISH_DISABLED');}assert.equal((await f.h.db.get('SELECT published FROM brokers WHERE id=$1',[f.b.id])).published,1);
 assert.equal(f.calls.length,0);assert.equal((await f.h.db.get('SELECT data FROM broker_campaign_drafts WHERE broker_id=$1',[f.b.id])).data.addresses[0].numero,'101');assert.equal((await f.h.db.get('SELECT data FROM broker_sandbox_campaign_drafts WHERE broker_id=$1',[f.b.id])).data.addresses[0].numero,'202');
 r=await f.request('/espace/lettre-proprietaires?proof=1&paymentMode=live',{mode:null});assert.equal(r.status,409);r=await f.request('/espace/lettre-proprietaires?proof=1&paymentMode=sandbox',{mode:null});assert.equal(r.status,200,await r.clone().text());assert.match(await r.text(),/202 Rue du Test/);
 r=await f.request('/api/espace/campagne/brouillon',{actor:otherSession});assert.equal((await r.json()).data.addresses[0].numero,'101','Same account on a different session stays live');
 const forged={...otherSession,cookie:otherSession.cookie+'; vv_sandbox_mode='+f.s.cookie.split('vv_sandbox_mode=')[1]};r=await f.request('/api/espace/campagne/brouillon',{actor:forged,mode:'sandbox'});assert.equal(r.status,409,'A mode cookie cannot move between authenticated sessions');
 assert.equal((await f.h.db.get("SELECT value FROM admin_settings WHERE key='paypal_mode'")),undefined);assert.equal(f.h.services.externalVars.PAYPAL_MODE,'live');await f.toggle(false);r=await f.request('/api/espace/campagne/brouillon');assert.equal((await r.json()).data.addresses[0].numero,'101');assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});

test('sandbox and live identical selections produce separate immutable orders, private test checkout and preview-only paid effects',async()=>{const f=await fixture();try{
 let r=await f.checkout();assert.equal(r.status,200,await r.clone().text());const live=await r.json(),before=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[live.id]);assert.equal(before.is_test,0);assert.equal(before.paypal_mode,'live');
 await f.toggle(true);await f.h.db.run('UPDATE brokers SET published=0 WHERE id=$1',[f.b.id]);r=await f.checkout('sandbox');assert.equal(r.status,200,await r.clone().text());const sandbox=await r.json();assert.notEqual(sandbox.id,live.id);let stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[sandbox.id]);assert.equal(stored.is_test,1);assert.equal(stored.paypal_mode,'sandbox');assert.equal(stored.quota_period,null);assert(stored.production.orderPrintSnapshot);assert.match(stored.paypal_order_id,/SANDBOX/);assert.equal((await f.h.db.get('SELECT published FROM brokers WHERE id=$1',[f.b.id])).published,0);
 const body={paymentMode:'sandbox',centre:f.draft(101).center,adresses:[address(101)],quantite:1,expectedTotal:stored.total_cents,reprend:live.id};r=await f.request('/api/espace/campagne/commander',{method:'POST',mode:'sandbox',body});assert.equal(r.status,409);assert.equal((await r.json()).code,'ORDER_MODE_MISMATCH');r=await f.request('/api/espace/campagne/'+live.id+'/territoire',{mode:'sandbox'});assert.equal(r.status,409);r=await f.request('/api/espace/campagne/brouillon',{method:'PUT',mode:'sandbox',body:{revision:0,data:{...f.draft(101),reprise:live.id}}});assert.equal(r.status,409);assert.deepEqual(await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[live.id]),before);
 // Browser closes after approval; the ordinary scheduled worker recovers only this due attempt.
 f.orders.get(stored.paypal_order_id).status='APPROVED';await f.h.db.run('UPDATE broker_campaigns SET payment_check_after=NOW() WHERE id=$1',[sandbox.id]);const worker=await f.h.services.vendvitePaymentRecovery.run({mode:'sandbox',req:{tenantUrl:p=>'https://vendvite.app'+p,lang:'fr'}});assert.equal(worker[0].state,'paid');stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[sandbox.id]);assert.equal(stored.payment_status,'paid');const invoice=await f.h.db.get('SELECT * FROM broker_invoices WHERE campaign_id=$1',[sandbox.id]);assert(invoice.email_previewed_at);assert.equal(invoice.emailed_at,null);assert.equal(invoice.is_test,1);const jobs=await f.h.db.all('SELECT * FROM notification_jobs WHERE campaign_id=$1',[sandbox.id]);assert(jobs.some(j=>j.kind==='invoice_test'));assert(jobs.some(j=>j.kind==='campaign_operator'));assert(jobs.every(j=>j.delivery_mode==='preview'&&j.is_test===1));assert.equal(f.h.emails.length,0);assert.equal((await f.h.db.get('SELECT payment_status FROM broker_campaigns WHERE id=$1',[live.id])).payment_status,'pending');
 // Stored order mode wins when opening it from a session currently in the other mode.
 await f.toggle(false);r=await f.request('/espace/commandes/'+sandbox.id);assert.equal(r.status,200,await r.clone().text());assert.match(await r.text(),/SANDBOX|Sandbox|sandbox/);r=await f.request('/api/espace/commandes/'+sandbox.id+'/verifier',{method:'POST',body:{}});assert.equal(r.status,200);assert.equal((await r.json()).state,'paid');assert.equal(f.calls.filter(x=>x.url.endsWith('/capture')&&x.mode==='live').length,0);assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});

test('campaign history matches only the same paired mode and supports excluding the current approval',async()=>{const f=await fixture();try{
 const a=address(101),b=address(202);async function campaign(mode,isTest,addresses){return f.h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,is_test,paypal_mode,addresses,city,province,mailed_at) VALUES($1,'paid','mailed','paid',$2,$3,$4::jsonb,'Montréal','QC',NOW()) RETURNING *",[f.b.id,isTest,mode,JSON.stringify(addresses)]);}
 const live=await campaign('live',0,[a]),sandbox=await campaign('sandbox',1,[b]);await campaign('sandbox',0,[a,b]);await campaign('live',1,[a,b]);
 let rows=await H.matches(f.h.db,f.b.id,[a,b],{mode:'all'});assert.deepEqual(rows.map(r=>r.id),[a.id]);assert.equal(rows[0].campaignId,live.id);assert.equal(rows[0].historyKey,H.key(a));rows=await H.matches(f.h.db,f.b.id,[a,b],{mode:'all'},new Date(),'sandbox');assert.deepEqual(rows.map(r=>r.id),[b.id]);assert.equal(rows[0].campaignId,sandbox.id);assert.deepEqual(await H.matches(f.h.db,f.b.id,[a,b],{mode:'all'},new Date(),'sandbox',sandbox.id),[]);
 await f.toggle(true);let r=await f.request('/api/espace/campagne/historique-adresses',{method:'POST',mode:'sandbox',body:{addresses:[a,b],historyFilter:{mode:'all'}}});assert.equal(r.status,200,await r.clone().text());assert.deepEqual((await r.json()).matches.map(r=>r.id),[b.id]);r=await f.request('/api/espace/campagne/brouillon',{method:'PUT',mode:'sandbox',body:{revision:0,data:{...f.draft(101),addresses:[a,b],selected:[a.id,b.id],historyFilter:{mode:'all'}}}});assert.equal(r.status,200,await r.clone().text());assert.deepEqual((await r.json()).selected,[a.id]);
 }finally{await f.h.close();}});


test('sandbox billing copies on write, persists only in test quotes/invoices, and stale forms cannot update real account billing',async()=>{const f=await fixture();try{
 const original=await f.h.db.get('SELECT billing_address,billing_confirmed_at FROM brokers WHERE id=$1',[f.b.id]);await f.toggle(true);let r=await f.request('/espace/courrier-cible',{mode:null});assert.equal(r.status,200,await r.clone().text());let page=await r.text();assert.match(page,/data-payment-mode="sandbox"/);assert.match(page,/public\/js\/billing-address-v2\.js/);assert.match(page,/Example Realty/);
 const testAddress={legal_name:'Sandbox Buyer Only',line1:'999 Test Street',city:'Vancouver',province:'BC',postal_code:'V6B 1A1',country:'CA'};r=await f.request('/api/espace/billing-address',{mode:'sandbox',method:'PUT',body:{confirmed:true,paymentMode:'sandbox',address:testAddress}});assert.equal(r.status,200,await r.clone().text());let b=await f.h.db.get('SELECT * FROM brokers WHERE id=$1',[f.b.id]);assert.deepEqual(b.billing_address,original.billing_address);assert.deepEqual(b.billing_confirmed_at,original.billing_confirmed_at);assert.deepEqual(b.sandbox_billing_address,testAddress);assert(b.sandbox_billing_confirmed_at);
 const price=await f.quote('sandbox');assert.equal(price.taxSnapshot.billing_address.legal_name,'Sandbox Buyer Only');assert.equal(price.taxSnapshot.billing_province,'BC');assert.equal(price.taxSnapshot.allocations[0].province,'QC','Destination tax calculation remains independent of test billing province');r=await f.request('/espace/courrier-cible',{mode:null});page=await r.text();assert.match(page,/Sandbox Buyer Only/);assert.match(page,/value="V6B 1A1"/);
 r=await f.checkout('sandbox');assert.equal(r.status,200,await r.clone().text());const order=await r.json(),c=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[order.id]);assert.equal(c.tax_snapshot.billing_address.legal_name,'Sandbox Buyer Only');f.orders.get(c.paypal_order_id).status='APPROVED';await f.h.db.run('UPDATE broker_campaigns SET payment_check_after=NOW() WHERE id=$1',[c.id]);await f.h.services.vendvitePaymentRecovery.run({mode:'sandbox',req:{tenantUrl:p=>'https://vendvite.app'+p,lang:'fr'}});const invoice=await f.h.db.get('SELECT * FROM broker_invoices WHERE campaign_id=$1',[c.id]);assert.equal(invoice.tax_snapshot.billing_address.legal_name,'Sandbox Buyer Only');assert(invoice.email_previewed_at);assert.equal(invoice.emailed_at,null);
 await f.toggle(false);for(const mode of ['sandbox',null]){r=await f.request('/api/espace/billing-address',{mode,method:'PUT',body:{confirmed:true,address:{...testAddress,legal_name:'Stale form'}}});assert.equal(r.status,409);assert.equal((await r.json()).code,'PAYMENT_MODE_CHANGED');}b=await f.h.db.get('SELECT * FROM brokers WHERE id=$1',[f.b.id]);assert.deepEqual(b.billing_address,original.billing_address);assert.equal(b.sandbox_billing_address.legal_name,'Sandbox Buyer Only');const realPrice=await f.quote();assert.equal(realPrice.taxSnapshot.billing_address.legal_name,'Example Realty');r=await f.request('/espace/courrier-cible',{mode:null});page=await r.text();assert.match(page,/data-payment-mode="live"/);assert.doesNotMatch(page,/value="Sandbox Buyer Only"/);assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});
