'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {create,root}=require('./harness.cjs'),Mode=require(root+'/broker-sandbox-v1'),Auth=require(root+'/broker-auth-v3');
async function owner(h){const nonce=crypto.randomBytes(5).toString('hex'),b=await h.db.get("INSERT INTO brokers(slug,full_name,email,status,access_plan) VALUES($1,'Sandbox Owner',$2,'active','mailing') RETURNING *",[nonce,nonce+'@example.test']),raw=crypto.randomBytes(32).toString('hex');await h.db.run("INSERT INTO broker_sessions(broker_id,token_hash,idle_expires_at,absolute_expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour',NOW()+INTERVAL '1 hour')",[b.id,crypto.createHash('sha256').update(raw).digest('hex')]);return {b,raw,headers:{cookie:'vv_broker_session='+raw,'Content-Type':'application/json','X-VV-CSRF':crypto.createHash('sha256').update('csrf:'+raw).digest('hex')}};}
test('sandbox mode is explicit, CSRF-protected, tied to one authenticated session and never changes global PayPal',async()=>{const h=await create();try{Object.assign(h.services.externalVars,{PAYPAL_MODE:'live',PAYPAL_SANDBOX_CLIENT_ID:'fake-sandbox',PAYPAL_SANDBOX_CLIENT_SECRET:'fake-secret'});const a=await owner(h),b=await owner(h),url=h.url+'/api/espace/sandbox';
 const call=(headers,enabled)=>fetch(url,{method:'POST',headers,body:JSON.stringify({enabled})});
 assert.equal((await call({'Content-Type':'application/json'},true)).status,401);
 assert.equal((await call({...a.headers,'X-VV-CSRF':'bad'},true)).status,403);
 assert.equal((await call({...a.headers,origin:'https://evil.test'},true)).status,403);
 const response=await call(a.headers,true);assert.equal(response.status,200);assert.equal((await response.json()).enabled,true);const cookie=response.headers.getSetCookie().find(x=>x.startsWith('vv_sandbox_mode='));assert(cookie&&cookie.includes('HttpOnly')&&cookie.includes('SameSite=Lax'));const token=cookie.split(';')[0].split('=')[1];
 assert(Mode.enabled({_vvSession:{raw:a.raw,broker_id:a.b.id},cookies:{vv_sandbox_mode:token}}));assert(!Mode.enabled({_vvSession:{raw:b.raw,broker_id:b.b.id},cookies:{vv_sandbox_mode:token}}));assert(!Mode.enabled({cookies:{vv_sandbox_mode:token}}));assert(!Mode.enabled({_vvSession:{raw:a.raw,broker_id:a.b.id},cookies:{vv_sandbox_mode:'é'.repeat(64)}}));
 await h.db.run("UPDATE brokers SET access_plan='legacy',paypal_subscription_id='REAL-SUBSCRIPTION' WHERE id=$1",[a.b.id]);const testHeaders={...a.headers,cookie:a.headers.cookie+'; vv_sandbox_mode='+token};for(const endpoint of ['/api/espace/abonnement','/api/espace/abonnement/annuler']){const blocked=await fetch(h.url+endpoint,{method:'POST',headers:testHeaders,body:'{}'});assert.equal(blocked.status,409);assert.equal((await blocked.json()).code,'SANDBOX_SUBSCRIPTION_DISABLED');}assert.equal((await h.db.get('SELECT status FROM brokers WHERE id=$1',[a.b.id])).status,'active');
 const legacyPostal=await fetch(h.url+'/api/espace/campagne-postale',{method:'POST',headers:testHeaders,body:JSON.stringify({quantity:300,sector:'Test'})});assert.equal(legacyPostal.status,409);assert.equal((await legacyPostal.json()).code,'SANDBOX_LEGACY_REQUEST_DISABLED');
 assert.equal(h.services.externalVars.PAYPAL_MODE,'live');assert.equal(await h.db.get("SELECT value FROM admin_settings WHERE key='paypal_mode'"),undefined);assert.equal(h.emails.length,0);
 const disabled=await call({...a.headers,cookie:a.headers.cookie+'; vv_sandbox_mode='+token},false);assert.equal(disabled.status,200);assert(disabled.headers.getSetCookie().some(x=>/^vv_sandbox_mode=;/.test(x)));
 delete h.services.externalVars.PAYPAL_SANDBOX_CLIENT_SECRET;assert.equal((await call(a.headers,true)).status,409);
 }finally{await h.close();}});
test('reconnection preserves only safe private test destinations',()=>{for(const path of ['espace/tests','espace/tests/notifications?campaign=12&page=2','espace/pistes?mode=test&lang=en','courrier-test/'+'a'.repeat(48)+'/'+'b'.repeat(32)+'?lang=en'])assert.equal(Auth.safeNext(path),path);for(const path of ['https://evil.test','//evil.test','espace/tests?next=https://evil.test','courrier-test/'+'a'.repeat(48)+'/'+'b'.repeat(32)+'?next=evil','espace/pistes?mode=test&mode=live','espace/tests/../../admin','espace/pistes?mode=sandbox'])assert.equal(Auth.safeNext(path),'espace');});
