const {test}=require('node:test'),assert=require('node:assert/strict');
const {create,root}=require('./harness.cjs'),R=require(root+'/payment-recovery-v2');
async function fixture(){
 const h=await create();await h.db.run('ALTER TABLE broker_invoices ADD COLUMN IF NOT EXISTS email_previewed_at TIMESTAMPTZ');
 const broker=await h.db.get("INSERT INTO brokers(slug,full_name,email,status,access_plan,published) VALUES('sandbox-worker','Sandbox Rehearsal','rehearsal@example.test','invited','mailing',1) RETURNING *");
 const configs={live:{mode:'live',base:'https://api-m.paypal.com',clientId:'mock-live-client',secret:'mock-live-secret'},sandbox:{mode:'sandbox',base:'https://api-m.sandbox.paypal.com',clientId:'mock-sandbox-client',secret:'mock-sandbox-secret'}};
 const orders=new Map(),calls=[],tokens=[],effects=[],timeouts=new Map(),effectFailures=new Set();let createFailure=false;
 const services={...h.services,fetch:async(url,opts={})=>{
  const mode=new URL(url).hostname==='api-m.sandbox.paypal.com'?'sandbox':'live';assert.equal(new URL(url).origin,configs[mode].base);assert.equal(opts.headers.Authorization,'Bearer token-'+mode);calls.push({mode,url,method:opts.method||'GET',key:opts.headers['PayPal-Request-Id']});
  if(url.endsWith('/v2/checkout/orders')){if(createFailure)throw Error('Uncertain create response');const payload=JSON.parse(opts.body),id=mode.toUpperCase()+'-ORDER-'+payload.purchase_units[0].custom_id.split(':').at(-1);const order=orders.get(id)||{...payload,id,status:'CREATED',links:[{rel:'approve',href:'https://'+(mode==='sandbox'?'www.sandbox.paypal.com':'www.paypal.com')+'/checkoutnow?token='+id}]};orders.set(id,order);return {ok:true,status:201,json:async()=>structuredClone(order)};}
  const id=url.endsWith('/capture')?url.split('/').at(-2):url.split('/').at(-1),order=orders.get(id);assert(order,'Provider can only read the stored local order');assert.equal(id.split('-')[0].toLowerCase(),mode);
  if(url.endsWith('/capture')){const timeout=timeouts.get(id);if(timeout==='before')throw Error('Capture request interrupted');order.status='COMPLETED';order.purchase_units[0].payments={captures:[{id:id+'-CAPTURE',status:'COMPLETED',amount:structuredClone(order.purchase_units[0].amount)}]};if(timeout==='after')throw Error('Capture response lost');}
  return {ok:true,status:200,json:async()=>structuredClone(order)};
 }};
 const hooks={cfg:async mode=>configs[mode],token:async cfg=>{assert.equal(cfg.clientId,configs[cfg.mode].clientId);assert.equal(cfg.secret,configs[cfg.mode].secret);tokens.push(cfg.mode);return 'token-'+cfg.mode;},deadline:()=>new Date(Date.now()+72*3600000),afterPaid:async(req,b,c)=>{effects.push({id:c.id,mode:c.paypal_mode,isTest:c.is_test});if(effectFailures.has(c.id))return false;const test=c.paypal_mode==='sandbox';await h.db.run("INSERT INTO broker_invoices(broker_id,kind,campaign_id,payment_key,payment_time,subtotal_cents,total_cents,currency,is_test,paypal_mode,emailed_at,email_previewed_at) VALUES($1,'campagne',$2,$3,NOW(),477,549,'CAD',$4,$5,$6,$7) ON CONFLICT(payment_key) DO NOTHING",[b.id,c.id,'rehearsal:'+c.paypal_mode+':'+c.id,test?1:0,c.paypal_mode,test?null:new Date(),test?new Date():null]);return true;}};
 const recovery=R.create(services,hooks);
 async function add(mode='sandbox',{initialized=true,isTest=mode==='sandbox'?1:0,meta=null}={}){const c=await h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,address_count,quantity,total_cents,subtotal_cents,gst_cents,qst_cents,is_test,paypal_mode,tax_snapshot,payment_recovery) VALUES($1,'paid','pending_payment','pending',3,3,549,477,24,48,$2,$3,'{}',$4::jsonb) RETURNING *",[broker.id,isTest,mode,JSON.stringify(meta||{})]);const payload={intent:'CAPTURE',purchase_units:[{custom_id:'camp:'+broker.id+':'+c.id,amount:{currency_code:'CAD',value:'5.49'}}]};if(initialized)await recovery.prepare(c,payload,'rehearsal-create-'+c.id);return c;}
 const due=()=>h.db.run("UPDATE broker_campaigns SET payment_check_after=NOW()");
 return {h,broker,configs,orders,calls,tokens,effects,timeouts,effectFailures,recovery,add,due,set createFailure(v){createFailure=v;}};
}
test('sandbox capture recovers after browser closure and uncertain capture; invoice preview retries never claim email or real settlement',async()=>{const f=await fixture();try{
 const c=await f.add();f.createFailure=true;assert.equal((await f.recovery.run({mode:'sandbox'}))[0].state,'verification');f.createFailure=false;await f.due();let rows=await f.recovery.run({mode:'sandbox'});assert.equal(rows[0].state,'pending');let stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[c.id]);const id=stored.paypal_order_id;f.orders.get(id).status='APPROVED';f.timeouts.set(id,'before');await f.due();rows=await f.recovery.run();assert.deepEqual(rows,[{id:c.id,state:'processing',mode:'sandbox',isTest:true}]);assert.equal((await f.recovery.reconcile(c.id,{cancel:true,capture:false})).code,'CAPTURE_IN_PROGRESS');
 f.timeouts.set(id,'after');f.effectFailures.add(c.id);await f.due();rows=await f.recovery.run();assert.equal(rows[0].state,'paid');stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[c.id]);assert.equal(stored.is_test,1);assert.equal(stored.paypal_mode,'sandbox');assert.equal(stored.payment_status,'paid');assert.equal(stored.payment_recovery.effectsComplete,false);assert.equal(stored.address_count,3);assert.equal(stored.total_cents,549);f.effectFailures.delete(c.id);await f.due();await f.recovery.run();const invoice=await f.h.db.get('SELECT * FROM broker_invoices WHERE campaign_id=$1',[c.id]);assert.equal(invoice.is_test,1);assert.equal(invoice.paypal_mode,'sandbox');assert(invoice.email_previewed_at);assert.equal(invoice.emailed_at,null);const captureCalls=f.calls.filter(x=>x.url.endsWith('/capture'));assert.equal(captureCalls.length,2);assert.equal(new Set(captureCalls.map(x=>x.key)).size,1);assert.equal(f.calls.filter(x=>x.method==='POST'&&x.url.endsWith('/orders'))[0].key,f.calls.filter(x=>x.method==='POST'&&x.url.endsWith('/orders'))[1].key);await f.due();assert.equal((await f.recovery.run()).length,0,'A preview-complete sandbox invoice must not be retried forever');assert.equal(f.h.emails.length,0);assert(f.calls.every(x=>x.mode==='sandbox'));assert(f.tokens.every(x=>x==='sandbox'));
 }finally{await f.h.close();}});
test('dual worker uses strictly isolated credentials, currencies and invoice-completion modes',async()=>{const f=await fixture();try{
 const live=await f.add('live'),sandbox=await f.add('sandbox');let rows=await f.recovery.run({mode:'sandbox'});assert.equal(rows.length,1);assert.equal(rows[0].id,sandbox.id);assert(f.calls.every(c=>c.mode==='sandbox'));await f.due();rows=await f.recovery.run({mode:'live'});assert.equal(rows.length,1);assert.equal(rows[0].id,live.id);for(const order of f.orders.values())order.status='APPROVED';const testOrder=[...f.orders.values()].find(o=>o.id.startsWith('SANDBOX'));testOrder.purchase_units[0].amount.currency_code='USD';await f.due();rows=await f.recovery.run();assert.equal(rows.find(r=>r.id===live.id).state,'paid');assert.equal(rows.find(r=>r.id===sandbox.id).state,'verification');assert.equal(f.calls.filter(c=>c.mode==='sandbox'&&c.url.endsWith('/capture')).length,0);testOrder.purchase_units[0].amount.currency_code='CAD';testOrder.purchase_units[0].custom_id='camp:999:999';assert.equal((await f.recovery.reconcile(sandbox.id)).code,'PAYMENT_MISMATCH');testOrder.purchase_units[0].custom_id='camp:'+f.broker.id+':'+sandbox.id;await f.due();await f.recovery.run();const invoices=await f.h.db.all('SELECT * FROM broker_invoices ORDER BY campaign_id');assert(invoices[0].emailed_at);assert.equal(invoices[0].email_previewed_at,null);assert(invoices[1].email_previewed_at);assert.equal(invoices[1].emailed_at,null);assert.deepEqual(new Set(f.tokens),new Set(['live','sandbox']));
 // A preview cannot satisfy a real invoice, and a sent marker cannot satisfy a test preview.
 await f.h.db.run("UPDATE broker_invoices SET emailed_at=NULL,email_previewed_at=NOW() WHERE campaign_id=$1",[live.id]);await f.due();rows=await f.recovery.run();assert.deepEqual(rows.map(r=>r.id),[live.id]);await f.h.db.run("UPDATE broker_invoices SET emailed_at=NOW(),email_previewed_at=NULL WHERE campaign_id=$1",[sandbox.id]);await f.due();rows=await f.recovery.run({mode:'sandbox'});assert.deepEqual(rows.map(r=>r.id),[sandbox.id]);assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});
test('uninitialized old tests, contradictory flags and cross-host configurations remain excluded',async()=>{const f=await fixture();try{
 const old=await f.add('sandbox',{initialized:false}),oldLive=await f.add('live',{initialized:false}),badTest=await f.add('sandbox',{isTest:0}),badLive=await f.add('live',{isTest:1});assert.equal((await f.recovery.run()).length,0);assert.equal(f.calls.length,0);assert.equal((await f.recovery.reconcile(badTest.id)).code,'MODE_MISMATCH');assert.equal((await f.recovery.reconcile(badLive.id)).code,'MODE_MISMATCH');assert.equal(f.calls.length,0);await f.h.db.run("UPDATE broker_campaigns SET payment_status='paid' WHERE id IN ($1,$2)",[badTest.id,badLive.id]);assert.equal((await f.recovery.reconcile(badTest.id)).code,'MODE_MISMATCH');assert.equal(f.effects.length,0);
 const test=await f.add();f.configs.sandbox.secret='';await f.due();let rows=await f.recovery.run({mode:'sandbox'});assert.equal(rows.length,1);assert.equal(rows[0].state,'verification');assert.equal(f.tokens.length,0);f.configs.sandbox.secret='mock-sandbox-secret';f.configs.sandbox.base='https://api-m.paypal.com';assert.equal((await f.recovery.reconcile(test.id)).code,'MODE_MISMATCH');assert.equal(f.tokens.length,0);f.configs.sandbox.base='https://api-m.sandbox.paypal.com';await assert.rejects(f.recovery.run({mode:'fake'}),e=>e.code==='BAD_MODE');assert.equal((await f.h.db.get('SELECT payment_status FROM broker_campaigns WHERE id=$1',[old.id])).payment_status,'pending');assert.equal((await f.h.db.get('SELECT payment_status FROM broker_campaigns WHERE id=$1',[oldLive.id])).payment_status,'pending');assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});
test('explicitly checked test attempts recover while cancelled approvals stay cancelled',async()=>{const f=await fixture();try{
 const c=await f.add();await f.recovery.reconcile(c.id,{capture:false});let stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[c.id]);f.orders.get(stored.paypal_order_id).status='APPROVED';assert.equal((await f.recovery.reconcile(c.id,{cancel:true,capture:false})).state,'cancelled');await f.due();assert.equal((await f.recovery.run())[0].state,'cancelled');assert.equal(f.calls.filter(c=>c.url.endsWith('/capture')).length,0);
 const checked=await f.add();await f.recovery.reconcile(checked.id,{capture:false});stored=await f.h.db.get('SELECT * FROM broker_campaigns WHERE id=$1',[checked.id]);await f.h.db.run("UPDATE broker_campaigns SET payment_recovery=payment_recovery-'createKey',payment_check_after=NOW() WHERE id=$1",[checked.id]);f.orders.get(stored.paypal_order_id).status='APPROVED';const rows=await f.recovery.run();assert.equal(rows.find(r=>r.id===checked.id).state,'paid');assert.equal(f.h.emails.length,0);
 }finally{await f.h.close();}});
