'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {create,root}=require('./harness.cjs'),Outbox=require(root+'/notification-outbox-v2');
const admin={'x-test-admin':'yes','Content-Type':'application/json'};
async function fixture(h,name){const b=await h.db.get("INSERT INTO brokers(slug,full_name,email,status,access_plan) VALUES($1,$1,$2,'active','mailing') RETURNING *",[name,name+'@example.test']),raw=crypto.randomBytes(32).toString('hex');await h.db.run("INSERT INTO broker_sessions(broker_id,token_hash,idle_expires_at,absolute_expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour',NOW()+INTERVAL '1 hour')",[b.id,crypto.createHash('sha256').update(raw).digest('hex')]);const headers={cookie:'vv_broker_session='+raw,'X-VV-CSRF':crypto.createHash('sha256').update('csrf:'+raw).digest('hex'),'Content-Type':'application/json'},campaign=async(test)=>h.db.get("INSERT INTO broker_campaigns(broker_id,kind,status,payment_status,is_test,paypal_mode) VALUES($1,'paid','confirmed','paid',$2,$3) RETURNING *",[b.id,test?1:0,test?'sandbox':'live']);return {b,headers,c:await campaign(true),live:await campaign(false)};}
async function good(response){assert.equal(response.status,200,await response.clone().text());return response;}
test('test workspace and text-only previews are private, escaped, and immediate generation is scoped without sending live email',async()=>{const h=await create();try{
 Object.assign(h.services.externalVars,{PAYPAL_SANDBOX_CLIENT_ID:'fake',PAYPAL_SANDBOX_CLIENT_SECRET:'fake'});const a=await fixture(h,'test-owner'),b=await fixture(h,'other-owner'),outbox=Outbox.create(h.services),payload={to:'preview@example.test',subject:'Unsafe <script>window.attack=1</script>',text:'Test text <img src=x onerror="window.attack=1">',html:'<script>window.attack=1</script>'};
 const own=await outbox.enqueue('test-owner',payload,{brokerId:a.b.id,campaignId:a.c.id,isTest:true}),foreign=await outbox.enqueue('test-foreign',{...payload,subject:'Foreign private preview'},{brokerId:b.b.id,campaignId:b.c.id,isTest:true}),live=await outbox.enqueue('test-live',{...payload,subject:'Actual live queued email'},{brokerId:a.b.id,campaignId:a.live.id});
 for(const path of ['/espace/tests','/espace/tests/notifications']){const r=await fetch(h.url+path,{redirect:'manual'});assert([302,401].includes(r.status));}
 let r=await good(await fetch(h.url+'/espace/tests',{headers:a.headers})),html=await r.text();assert.match(html,/Répéter tout le parcours/);assert.match(html,/developer.paypal.com\/sandbox-testing\/accounts/);assert.match(r.headers.get('cache-control'),/no-store/);
 assert.equal((await fetch(h.url+'/espace/tests/notifications?campaign='+b.c.id,{headers:a.headers})).status,404);assert.equal((await fetch(h.url+'/espace/tests/notifications?campaign='+a.live.id,{headers:a.headers})).status,404);
 r=await good(await fetch(h.url+'/espace/tests/notifications',{headers:a.headers}));html=await r.text();assert.match(html,/&lt;script&gt;window.attack=1&lt;\/script&gt;/);assert.doesNotMatch(html,/<script>window.attack=1|<img src=x|Foreign private preview|Actual live queued email/);assert.match(html,/Préparer les aperçus maintenant/);
 const run=(path,headers,body={})=>fetch(h.url+path,{method:'POST',headers,body:JSON.stringify(body)});
 assert.equal((await run('/api/espace/tests/notifications/run',{...a.headers,'X-VV-CSRF':'bad'})).status,403);assert.equal((await run('/api/espace/tests/notifications/run',{...a.headers,Origin:'https://evil.test'})).status,403);
 assert.equal((await run('/api/espace/tests/notifications/run?campaign='+b.c.id,a.headers)).status,404);
 assert.equal((await run('/api/admin/tests/notifications/run',a.headers,{brokerId:a.b.id})).status,403);assert.equal((await run('/api/admin/tests/notifications/run',admin)).status,400);assert.equal((await run('/api/admin/tests/notifications/run?campaign='+a.live.id,admin)).status,404);assert.equal((await run('/api/admin/tests/notifications/run',{...admin,Origin:'https://evil.test'},{brokerId:a.b.id})).status,403);
 r=await good(await run('/api/espace/tests/notifications/run',a.headers,{brokerId:b.b.id}));const result=await r.json();assert.equal(result.previewed,1);assert.equal(result.sent,0);assert.equal(h.emails.length,0);assert.equal((await h.db.get('SELECT status FROM notification_jobs WHERE id=$1',[own.id])).status,'sent');for(const id of [foreign.id,live.id])assert.equal((await h.db.get('SELECT status FROM notification_jobs WHERE id=$1',[id])).status,'pending');
 await good(await run('/api/admin/tests/notifications/run?campaign='+b.c.id,admin));assert.equal((await h.db.get('SELECT status FROM notification_jobs WHERE id=$1',[foreign.id])).status,'sent');assert.equal((await h.db.get('SELECT status FROM notification_jobs WHERE id=$1',[live.id])).status,'pending');assert.equal(h.emails.length,0);
 }finally{await h.close();}});
test('admin test inbox supports simulated follow-up and delivery but refuses real leads and unauthorized mutations',async()=>{const h=await create();try{
 const a=await fixture(h,'inbox-owner');const insert=async(c,test,name)=>h.db.get("INSERT INTO broker_leads(broker_id,campaign_id,is_test,name,address,email,status,response_due_at) VALUES($1,$2,$3,$4,'10 Rue Exemple','homeowner@example.test','nouveau',NOW()+INTERVAL '24 hours') RETURNING *",[a.b.id,c.id,test?1:0,name]);const l=await insert(a.c,true,'Test Homeowner'),live=await insert(a.live,false,'Live Hidden Homeowner');
 let r=await good(await fetch(h.url+'/admin/tests/leads?campaign='+a.c.id,{headers:admin})),html=await r.text();assert.match(html,/Test Homeowner/);assert.doesNotMatch(html,/Live Hidden Homeowner|mailto:/);assert.match(html,/Simuler 24 h sans réponse/);assert.match(html,/Enregistrer la remise simulée/);assert.match(html,/admin\/tests\/notifications\?campaign=/);
 assert.equal((await fetch(h.url+'/admin/tests/leads',{headers:a.headers})).status,403);assert.equal((await fetch(h.url+'/admin/tests/leads?campaign='+a.live.id,{headers:admin})).status,404);
 const update=(id,body,headers=admin)=>fetch(h.url+'/api/admin/tests/leads/'+id,{method:'PUT',headers,body:JSON.stringify(body)}),overdue=(id,headers=admin)=>fetch(h.url+'/api/admin/tests/leads/'+id+'/overdue',{method:'POST',headers,body:'{}'});
 assert.equal((await update(l.id,{status:'contacté'},a.headers)).status,403);assert.equal((await update(l.id,{status:'contacté'},{...admin,Origin:'https://evil.test'})).status,403);assert.equal((await update(live.id,{status:'contacté'})).status,404);assert.equal((await overdue(live.id)).status,404);
 const reminder=await (await good(await overdue(l.id))).json();assert.equal(reminder.previewed,true);assert.equal(reminder.status,'sent');assert.equal((await h.db.get("SELECT count(*)::int n FROM notification_jobs WHERE lead_id=$1 AND delivery_mode='preview' AND status='sent'",[l.id])).n,1);
 await good(await update(l.id,{status:'contacté'}));assert.equal((await overdue(l.id)).status,404);assert.equal((await update(l.id,{status:'évalué'})).status,400);await good(await update(l.id,{status:'évalué',deliveryAcknowledged:true,deliveryMethod:'other',deliveryReference:'Simulated hand delivery'}));
 const stored=await h.db.get('SELECT * FROM broker_leads WHERE id=$1',[l.id]);assert(stored.contacted_at&&stored.analysis_delivered_at);assert.equal(stored.is_test,1);assert.equal((await h.db.get('SELECT status FROM broker_leads WHERE id=$1',[live.id])).status,'nouveau');assert.equal(h.emails.length,0);
 }finally{await h.close();}});
