/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_therrien_auto_electrique_enr).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813048/tapavis_tenant_therrien_auto_electrique_enr/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790813048/tapavis_tenant_therrien_auto_electrique_enr/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815824/tapavis_tenant_therrien_auto_electrique_enr/hero_d4a91428-24f8-4471-b3db-aa5a938132ca.png",
  "services": {
    "diagnostic-electronique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815206/tapavis_tenant_therrien_auto_electrique_enr/diagnostic-electronique_852dab2d-9c93-4291-abcf-fbd2e0a7005d.png",
    "injection": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815207/tapavis_tenant_therrien_auto_electrique_enr/injection_339be69b-f55e-4363-8096-6ba89e2d7407.png",
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815207/tapavis_tenant_therrien_auto_electrique_enr/batterie-demarreur-alternateur_df0ff7dc-4c2e-4166-a93d-0b6f0b91c426.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790815208/tapavis_tenant_therrien_auto_electrique_enr/systeme-electrique_c393c93a-4830-4b16-989c-8e1253542d79.png"
  }
};
