ALTER TABLE services ADD COLUMN IF NOT EXISTS featured INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS bill_amount INTEGER;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS bill_paid INTEGER DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS bill_date TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
