/**
 * Brand assets on the platform Cloudinary (folder tapavis_tenant_car_inc).
 *  - logo / mark: the business's own logo as published on its public listing;
 *    shown back to the owner in this proposal (permission confirmed at claim).
 *  - hero + one illustration per service: studio illustrations in the logo's
 *    style — never a photograph presented as this business's shop or team.
 * Generated by scripts/prospect_build/illustrations.js.
 */
module.exports = {
  "logo": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739863/tapavis_tenant_car_inc/logo.png",
  "mark": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739863/tapavis_tenant_car_inc/logo.png",
  "hero": "https://res.cloudinary.com/duhp69meg/image/upload/v1790742117/tapavis_tenant_car_inc/hero_8a32860b-2400-4d16-9583-54d8595820ad.png",
  "services": {
    "batterie-demarreur-alternateur": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739874/tapavis_tenant_car_inc/batterie-demarreur-alternateur_f1f569e0-c7ee-4e65-ad94-98bf8370a06e.png",
    "suspension": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739874/tapavis_tenant_car_inc/suspension_c832d4a0-292b-4210-9105-1651eb7834eb.png",
    "equilibrage-rotation-pneus": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739876/tapavis_tenant_car_inc/equilibrage-rotation-pneus_43a0a61c-3224-4c5e-8974-c648405e28d6.png",
    "entretien-preventif": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739885/tapavis_tenant_car_inc/entretien-preventif_db27025f-13da-4f8b-8cf7-f65985cbaab8.png",
    "vidange-huile": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739885/tapavis_tenant_car_inc/vidange-huile_aef131b4-b718-4e8c-a091-2e6491c2dfa6.png",
    "mise-au-point": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739885/tapavis_tenant_car_inc/mise-au-point_5247c268-fa3b-4d13-ae52-8a4bf579ecc5.png",
    "alignement": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739887/tapavis_tenant_car_inc/alignement_4c7b1c9d-2647-4cb4-b6c1-e5f223c51d5f.png",
    "systeme-electrique": "https://res.cloudinary.com/duhp69meg/image/upload/v1790739897/tapavis_tenant_car_inc/systeme-electrique_e6f65775-d69c-4f00-b35d-77ae4d1e7464.png"
  }
};
